### ISSUE TITLE
server端admin没有添加（删除）好友的接口  

### ISSUE THREAD

**Issue by hlwskgypmb** [wildfirechat/server#10]

**Comment by hlwskgypmb** [comment]
![image](https://user-images.githubusercontent.com/18130329/57995611-a0829780-7af5-11e9-9d40-a59d043f391f.png)

**Comment by heavyrain2012** [comment]
已添加对于的功能，请更新代码，然后依照文档进行验证

**Comment by hlwskgypmb** [comment]
收到，3q
