### ISSUE TITLE
敏感词移除不生效

### ISSUE THREAD

**Issue by davidzhang12138** [wildfirechat/server#110]
复现步骤
1、使用sdk创建敏感词
2、发敏感语言-发送失败
3、使用sdk删除敏感词
4、发言-发送失败
5、重启server
6、发言-成功

**Comment by heavyrain2012** [comment]
最新代码已修改，请更新代码验证

**Comment by heavyrain2012** [comment]
建议给我们点个star，支持一下我们，谢谢
