### ISSUE TITLE
SDK中的ChannelAdmin API是否有误？

### ISSUE THREAD

**Issue by JiaRG** [wildfirechat/server#111]
https://github.com/wildfirechat/server/blob/4fdefca33d95a4f55758b9477a9dcf3a8294436b/sdk/src/main/java/cn/wildfirechat/sdk/ChannelAdmin.java#L8-L27

**Comment by JiaRG** [comment]
https://github.com/wildfirechat/server/blob/4fdefca33d95a4f55758b9477a9dcf3a8294436b/sdk/src/main/java/cn/wildfirechat/sdk/GeneralAdmin.java#L25-L28

**Comment by heavyrain2012** [comment]
请问你们发现了什么问题

**Comment by JiaRG** [comment]
ChannelAdmin为啥跟ChatroomAdmin一样？

**Comment by heavyrain2012** [comment]
这里是一些无用的代码，已经删除该文件，非常感谢您的提醒。

**Comment by JiaRG** [comment]
@heavyrain2012 Channel的API目前我只发现`createChannel`这一个，是否可以添加`订阅`、`取消订阅`、`获取指定Channel的订阅者列表`等接口?
