### ISSUE TITLE
消息id可以放客户端生成吗?会有什么缺陷?

### ISSUE THREAD

**Issue by gccdChen** [wildfirechat/server#112]

**Comment by heavyrain2012** [comment]
放到客户端生成需要确保id的唯一性。如果要确保唯一，id就必须是很长的uuid，因为普通文本消息非常小的，这样会显著增加payload的大小，导致本地存储和服务器存储增加，导致网络带宽增加。

如果你们的业务系统需要自己生成id，可以把id放到消息的extra字段中，这样业务系统就可以处理这个id了。

**Comment by gunC** [comment]
如果用类似其他id策略呢?

**Comment by gunC** [comment]
例如 这个

**Comment by gccdChen** [comment]
仅仅出于技术上的好奇 .. 或者自己的知识点不够.突然想到这个,因为在客户端生产唯一id ,处理去重等比服务器生成要方便..

缺点除了报文偏大外.还有其他原因吗?例如,分布式上的这样子做会有性能问题吗?

如果用其他id策略
例如 , [每 5 个 Bit ，进行一次 32 进制编码，转换为一个字符，字符取值范围是：数字 “2 ~ 9 ”和字母“A ~ B”。其中，已经去掉容易造成肉眼混淆的数字 0 和 1 （余下可用的数字就是8个了），及字母 O 和 I（余下可用的字母就是24个了），那么总可用字符就是32个（刚好可按32进制进行编码）。](http://www.52im.net/thread-2747-1-1.html)

或者类似 snowflake  , 不过机器id要转成用户id , 而且占位更长一点 . 时间会用服务器时间

**Comment by imndx** [comment]
这个id最好是有序的，端上生成id没法保证有序，会出现的现象就是群聊里面，你不知道消息的顺序

**Comment by gccdChen** [comment]
有道理
