### ISSUE TITLE
图片发送不了

### ISSUE THREAD

**Issue by zhangguangkuo** [wildfirechat/server#113]
![image](https://user-images.githubusercontent.com/19705820/69221055-55833300-0bb1-11ea-95f0-04c093b11675.png)

**Comment by heavyrain2012** [comment]
使用的是我们demo，还是自己部署的？请提供更多信息

**Comment by zhangguangkuo** [comment]
自己部署的，也没有报错信息
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "heavyrain.lee"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 上午10:06
收件人: "wildfirechat/server"<server@noreply.github.com&gt;; 
抄送: "阔"<945272565@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wildfirechat/server] 图片发送不了 (#113)




使用的是我们demo，还是自己部署的？请提供更多信息

**Comment by Krosxx** [comment]
看下你的 HttpResponseHelper.java 文件报错没
