### ISSUE TITLE
用nginx的话，http_port 和  local_port 怎么配置

### ISSUE THREAD

**Issue by zhoubenhua** [wildfirechat/server#114]

**Comment by zhoubenhua** [comment]
用nginx的话，http_port 和  local_port 怎么配置

**Comment by heavyrain2012** [comment]
使用nginx很麻烦，很容易出现问题，我们不推荐在IM服务前面加nginx，往往调试排查问题耽误的时间的损失要比使用nginx带来的收益要大。

**Comment by anlei586** [comment]
不介意的话，阿帕奇改掉80端口

**Comment by heavyrain2012** [comment]
由于长时间没有回复，本问题将被关闭，如果有新的信息需要补充，请重新打开或者新提一个，谢谢
