### ISSUE TITLE
 有没有java版长连接

### ISSUE THREAD

**Issue by zhoubenhua** [wildfirechat/server#116]

**Comment by heavyrain2012** [comment]
你好，我们没有java版本的长链接。请问你们是什么场景下需要java版本的长链接？

**Comment by zhoubenhua** [comment]
我们后台需要跟im服务保持长连接 但不知道连接要发什么消息格式

**Comment by heavyrain2012** [comment]
业务后台跟IM后台是可以双向通讯的，使用server api，业务后台可以给任何人发消息。添加机器人，设置机器人接受消息为业务后台，业务后台就能收到该机器人的消息。设置消息转发地址，业务后台能收到所有的消息。

不知道这样是不是能够满足你们的需求

**Comment by heavyrain2012** [comment]
由于长时间没有回复，本问题将被关闭，如果有新的信息需要补充，请重新打开或者新提一个，谢谢
