### ISSUE TITLE
偶尔看到网络状况良好,但是会自己断开重连,这部分是mars的逻辑吗?

### ISSUE THREAD

**Issue by gccdChen** [wildfirechat/server#118]
我用的是android模拟器 , 连的是本机 , 偶尔看到 [ERROR] disconnect...这样的日志..
按理应该是网络状况良好的

**Comment by heavyrain2012** [comment]
没有看到日志，只能猜测一下，是不是mars的短链接释放？功能正常还是不正常？
如果方便的话，请贴一下日志我们分析一下

**Comment by gccdChen** [comment]
功能是正常的,日志没及时保存好.

**Comment by gccdChen** [comment]
短链接也会 ROUTE 和 CONNECT 吗?
不过不影响功能 , 只是有点奇怪在网络良好情况下会重连?

**Comment by heavyrain2012** [comment]
route是短链接的，connect是长连接的，观察一下吧，如果下次遇到了，可以给我们贴日志看看。

**Comment by gccdChen** [comment]
好的,先关了
