### ISSUE TITLE
日志信息记录不完整

### ISSUE THREAD

**Issue by JiaRG** [wildfirechat/server#119]
https://github.com/wildfirechat/server/blob/9aaaa71ce932c88fc3ed4f9652703dd2837aa2f1/broker/src/main/java/cn/wildfirechat/push/PushServer.java#L60
https://github.com/wildfirechat/server/blob/9aaaa71ce932c88fc3ed4f9652703dd2837aa2f1/broker/src/main/java/win/liyufan/im/HttpUtils.java#L55
上述日志都缺少一个占位符

**Comment by heavyrain2012** [comment]
已修改，多谢提醒🙏🙏
