### ISSUE TITLE
common 下的 cn.wildfirechat.pojos 这个包什么情况？

### ISSUE THREAD

**Issue by wwlleo0730** [wildfirechat/server#120]
git clone下来报错，是特意写成这样的？

**Comment by heavyrain2012** [comment]
是一些API数据对象的定义，请问是下载错误？还是编译错误？

**Comment by wwlleo0730** [comment]
cn.wildfirechat.pojos 是包路径 ， 但是源码里面文件夹的名字叫  " cn.wildfirechat.pojos "

直接IDE编译报错，如图

![批注 2019-11-27 112016](https://user-images.githubusercontent.com/6244792/69690811-f15bf400-1107-11ea-9f0d-2e3176b87a64.jpg)

**Comment by heavyrain2012** [comment]
已经修改，请下载最新版本验证，谢谢提醒
