### ISSUE TITLE
当消息线路(line)不为默认线路的时候，删除会话后，卸载重装后会重新显示(2019.8.9号之后版本)

### ISSUE THREAD

**Issue by lewiswon** [wildfirechat/server#126]
### Expected behavior
message.roaming和message.remote_history_message都设置为0的时候，删除的会话不应该再次显示
### Actual behavior
删除后，卸载重新安装会显示线路不为默认线路的会话
### Steps to reproduce
设置消息的线路>0,删除会话，卸载应用，重新安装登录
### OS version (e.g. `uname -a`)
centos 7     服务器版本  0.29  客户端版本(Android)  0.6.3

**Comment by heavyrain2012** [comment]
是单聊会话还是群组会话？

客户端会根据会话的已读状态生成会话列表，如果不需要可以在读取会话列表后过滤没有草稿或最后一条消息的会话

**Comment by lewiswon** [comment]
> 是单聊会话还是群组会话？
> 
> 客户端会根据会话的已读状态生成会话列表，如果不需要可以在读取会话列表后过滤没有草稿或最后一条消息的会话

单聊，我目前是这样处理的。
