### ISSUE TITLE
请求支持推送用户上线，下线 到远程服务器

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/server#127]
### Expected behavior
请求支持推送用户上线，下线 到远程服务器

**Comment by heavyrain2012** [comment]
已添加，请更新到最新代码验证

**Comment by heavyrain2012** [comment]
0.37版本已发布，请验证

**Comment by zuoliang0** [comment]
请问如何测试，能否给出一个使用方法？
0.0.5. 事件回调
用户在线状态回调
群组成员变动回调
好友关系变动回调
用户信息变更回调

**Comment by heavyrain2012** [comment]
这些暂不支持
