### ISSUE TITLE
服务端有办法直接知道消息已读还是未读吗？

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/server#128]
服务端有办法直接知道消息已读还是未读吗？
还是这部分需要自己来进行实现呢？
谢谢！

**Comment by heavyrain2012** [comment]
IM服务不清楚已读未读状态。可以自己来实现，阅读完成功记录一下，可以是发一条自定义消息也可以同步到应用服务

**Comment by dilenzhu** [comment]
> IM服务不清楚已读未读状态。可以自己来实现，阅读完成功记录一下，可以是发一条自定义消息也可以同步到应用服务

好的，明白了，谢谢您！
