### ISSUE TITLE
能否建立多server用于CDN加速

### ISSUE THREAD

**Issue by NBY** [wildfirechat/server#129]
使用场景：
目前有中国大陆用户、日本、香港用户。

问题产生点：
目前server、im、push服务器部署在日本，中国大陆用户反馈发送消息经常失败，经测试中国大陆到日本server之间丢包率在20-50%。

设想架构：
假如我部署多台服务器：
日本服务器，跑server、push、im、db。
中国大陆服务器，跑server、push、im、db。
db为mysql且互为主从。

客户端修改：
启动时检测两台服务器延迟，选择延迟较低服务器连接。

问题：
使用该架构会不会产生问题，比如数据库冲突死锁或者重复push或其他问题？

**Comment by heavyrain2012** [comment]
这样是不行的，不支持多个服务部署，不同服务之间的用户无法互通的，可能还会有一系列的问题。如果你们把服务部署在国内，是不是日本和香港的用户可以能连上？

**Comment by NBY** [comment]
中国大陆服务器到香港/日本之间丢包率太高了，对于网络不太好的用户消息很难发送成功。

**Comment by NBY** [comment]
即便是mysql双向同步 也不能让用户互通吗

**Comment by zuoliang0** [comment]
@NBY 你这种想法，阿里巴巴都没实现，我之前和一个阿里资深架构聊过这种类似的架构，要保证数据一致性，必然性能就很垃圾，无法上线使用
