### ISSUE TITLE
部署了server,但是无法访问接口

### ISSUE THREAD

**Issue by ralax123** [wildfirechat/server#135]
我部署了imserver,浏览器输入http://121.199.39.204/api/version也能成功,但是比如我调用admin/user/create这个api,请求头里面也添加了timestamp和sign等数据,但是就是debug进不到CreateUserAction这个类,可以进到AdminAction类中的preAction方法,求大佬求解??

**Comment by heavyrain2012** [comment]
admin端口是管理端口，端口号默认是18080. 跟客户使用的端口不一样，请检查admin请求的端口号
