### ISSUE TITLE
强烈建议重开Proto

### ISSUE THREAD

**Issue by yzdying** [wildfirechat/server#136]
我们在实际正是app中发现，消息过多proto调用太慢而造成页面卡顿！所以需要对消息过多的会话 做只缓存最多 1024条消息的操作。

**Comment by heavyrain2012** [comment]
我们是商用公司，有我们的商业利益考虑，请见谅这部分代码我们不能开放。

另外过多的消息是无意义的，可以只保留最近1024条消息，即便是使用市场上主流的即时通讯云平台，服务器端保存的消息也是有限的，不可能非常多。再有就是要保证单条消息足够小，太大也会有问题。
