### ISSUE TITLE
创建群时，当异步线程池还没有把该群信息插入到数据库时，这个时候删除群成员会报错

### ISSUE THREAD

**Issue by tanxxtarena** [wildfirechat/server#137]
新创建一个群，如果mScheduler.execute 线程还没插入该群信息到数据库时，此时到群里去操作删除群成员或者解散该群时，会报错，导致群成员接收不到信息，也发送不出信息。很多设计都是使用了异步线程池去插入数据库，当数据库插入较慢时，可能也会存在这类问题，不知道后期是否有更好的处理方案？

**Comment by heavyrain2012** [comment]
最新的提交已经把群的操作全改为同步操作了，同步操作是一个合理的选择，因为群改动的频率并不高，同步操作可以保证数据的一致性。

但不一定能解决你们的问题，mysql写入不应该等太久，否则创建群组会超时失败。要么提高im服务器的配置，增加核心数，要么提高mysql服务的处理速度。另外可以考虑选择专业版，专业版具有更高的性能。
