### ISSUE TITLE
api有问题/admin/user/status

### ISSUE THREAD

**Issue by hlwskgypmb** [wildfirechat/server#14]
![image](https://user-images.githubusercontent.com/18130329/58165974-67941f80-7cbb-11e9-83f1-f56bfbd5acc2.png)

更新用户状态 传入useId 与 status 结果直接数据库删除了该用户。。。。

**Comment by heavyrain2012** [comment]
已解决，请使用0.21版本验证

**Comment by hlwskgypmb** [comment]
好的
