### ISSUE TITLE
本地Server部署成功，但小程序连接失败

### ISSUE THREAD

**Issue by Hipple** [wildfirechat/server#140]
### Expected behavior
![image](https://user-images.githubusercontent.com/13818792/71245063-e125e600-234e-11ea-8510-33e1e9d578a1.png)
连接成功并返回正常的字符串

### Actual behavior
![image](https://user-images.githubusercontent.com/13818792/71245115-ff8be180-234e-11ea-9e81-5d108ed2e760.png)
连接成功但返回值是乱码

### Minimal yet complete reproducer code (or URL to code) or complete log file
小程序连接代码：
`
       let appServer = 'http://192.168.1.163:8888/login'
       let clientId = 'cid123456aaa788'
        wx.request({
            url: appServer,
            data: {
                mobile: "18642830993",
                code: "66666",
                clientId: clientId
            },
            header: {
                'content-type': 'application/json', // 默认值
            },
            method: 'POST',
            success(res) {
                console.log(res.data)
                if (res.statusCode === 200) {
                    let loginResult = res.data;
                    if (loginResult.code === 0) {
                        let userId = loginResult.result.userId;
                        let token = loginResult.result.token;
                        wfc.connect('wx_12345678', 'e7a9ad28474252f306c682ee78b31558cc0eca30', 'http://192.168.1.163', 80, userId, clientId, token);
                    } else {
                        console.log('login failed', loginResult);
                    }
                }
            }
        })
`

### JVM version (e.g. `java -version`)
JDK 1.8

### OS version (e.g. `uname -a`)
Win10

参照wx-chat进行连接，访问/route接口成功，但返回值乱码，server端没有相关的错误日志，
想请教下这种错误的原因？

**Comment by imndx** [comment]
你好，小程序SDK是付费的，没法直接修改连接地址。

**Comment by Hipple** [comment]
> 你好，小程序SDK是付费的，没法直接修改连接地址。

额，好吧。那建议更新下相关文档，写明哪些是付费的
