### ISSUE TITLE
后台接口群相关接口错误，创建机器人也不行

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/server#143]
这个是机器人的请求体

`{"user_id":"robot1","name":"robot1","display_name":"机器人","secret":"123456","callback":"http://127.0.0.1:8883/robot/recvmsg"}`

但是反馈的结果是空的，数据库也没有实际的增加机器人用户数据

这是退出群的请求内容
`{"group_id":"_F_1_1vv","notify_message":{"type":0,"searchableContent":"哈哈","pushContent":"","content":"哈哈","base64edData":"","mediaType":0,"remoteMediaUrl":"","expireDuration":0,"mentionedType":0,"mentionedTarget":null},"operator":"","to_lines":null}`
结果返回空

**Comment by dotcool** [comment]
![image](https://user-images.githubusercontent.com/6111056/71432681-3d558500-2716-11ea-9a97-460409b7767f.png)
我解析了0.34的sdk里面关于机器人的接口是这样的。但是这样提示参数错误。
实际要传入的字段是

	Owner string `json:"owner"`
	Name string `json:"name"`
	DisplayName string `json:"displayame"`

希望可以完善一下文档啊。现在群的相关接口我还是不知道应该调用那些字段

**Comment by heavyrain2012** [comment]
本项目sdk目录下是sdk的源代码，其中有个main类里有测试代码，可以参考测试代码。退群的接口及测试已经加上
