### ISSUE TITLE
好友添加成功后状态刷新延迟

### ISSUE THREAD

**Issue by taany6210** [wildfirechat/server#145]
### Expected behavior
好友刷新后再次获取friendrequest的时候能及时返回状态
### Actual behavior
新的朋友界面，点击接受好友，然后返回上个界面，再进入这个界面，还是显示接受按钮。status是0
### Steps to reproduce
A搜索B添加好友，发送好友申请，B收到以后在新的朋友里面点击接受按钮，返回通讯录，再进入新的朋友界面，接受按钮依然存在，friendrequest.status是0，再次点击接受，返回通讯录，第三次进入新的朋友，正常了。（重新登录能解决）
### Minimal yet complete reproducer code (or URL to code) or complete log file
无
### Moquette MQTT version
未知
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
0.36

**Comment by heavyrain2012** [comment]
是使用demo测试的吗，那个端的？

正常流程应该是进入后调用强制刷新接口，且在界面上监听通知。如果与服务器端内容不一致协议栈更新之后会发送通知，界面如果收到通知再重新从库里获取一遍更新UI就行
