### ISSUE TITLE
请求增加修改好友备注API

### ISSUE THREAD

**Issue by anlei586** [wildfirechat/server#147]
请求增加修改好友备注API

**Comment by heavyrain2012** [comment]
请更新到最新代码进行验证

**Comment by heavyrain2012** [comment]
请使用0.37版本验证，问题我先关了，如果有问题请重新打开或新提一个

**Comment by anlei586** [comment]
用0.37版本验证，
（1）APIPath.Friend_Get_Alias返回{"code":0,"msg":"success","result":{"operator":"admin"}}
（2）APIPath.Friend_Set_Alias返回{"code":253,"msg":"not exist"}

**Comment by anlei586** [comment]
0.37-1验证过了，可以使用。非常方便。
