### ISSUE TITLE
群消息推送

### ISSUE THREAD

**Issue by weibocai** [wildfirechat/server#149]
群消息，单个用户推送过于频繁。每个用户发送消息，都会向所有不在线的用户进行推送。

**Comment by heavyrain2012** [comment]
这个是正常的吧，也可以做归并，一个群里的推送消息一段时间内只推一次，可以在push server做归并

**Comment by weibocai** [comment]
谢谢您，假如说，每条群消息，只调用一次推送接口的话，或许更好。

> 这个是正常的吧，也可以做归并，一个群里的推送消息一段时间内只推一次，可以在push server做归并

**Comment by heavyrain2012** [comment]
内网的话，多次推送影响效率不大，暂不进行修改
