### ISSUE TITLE
用户更新头像后，朋友列表不更新头像

### ISSUE THREAD

**Issue by gentlepen** [wildfirechat/server#150]

**Comment by gentlepen** [comment]
这个应该是移动端缓存了朋友列表数据吧？可不可以在用户更新个人数据的时候，发送通知，根据更新时间判断，更新下朋友列表的数据呢？这样会不会更好点

**Comment by heavyrain2012** [comment]
请参考微信的逻辑，好友头像变更后，联系人列表头像不会自动更新，在进入到会话或者点击用户详情时更新

**Comment by zhanshen1373** [comment]
好友头像变更之后。在进入到会话或者点击用户详情时更新时并没有更新。android代码是12.20更新的
