### ISSUE TITLE
请求增加t_messages_xx增加_target索引

### ISSUE THREAD

**Issue by anlei586** [wildfirechat/server#151]
手动测试有_target索引的情况下mysql性能提高了近2倍

**Comment by heavyrain2012** [comment]
请问是在执行什么操作下需要用到target的索引

**Comment by anlei586** [comment]
SELECT max(id) id, _type, _from from t_messages_12 WHERE _target="xxxxxxUid" GROUP BY (_from) ORDER BY id DESC
开发web后台管理， 超级管理员需要侦听普通管理员的最新聊天记录。

**Comment by heavyrain2012** [comment]
可以从t_user_messages表中查到某个用户的消息id，然后再根据消息id找到消息，这种方法比你们这种方法更好吧
