### ISSUE TITLE
安装服务端后的报错

### ISSUE THREAD

**Issue by rivergao87** [wildfirechat/server#155]
### Actual behavior
[root@ecs-1XM ~]# sh ./bin/wildfirechat.sh
/root
To enable GC log rotation, use -Xloggc:<filename> -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=<num_of_files>
where num_of_file > 0
GC log rotation is turned off
{Heap before GC invocations=0 (full 0):
 garbage-first heap   total 126976K, used 64512K [0x0000000085c00000, 0x0000000085d003e0, 0x0000000100000000)
  region size 1024K, 63 young (64512K), 0 survivors (0K)
 Metaspace       used 3011K, capacity 4554K, committed 4864K, reserved 1056768K
  class space    used 327K, capacity 390K, committed 512K, reserved 1048576K
[GC pause (G1 Evacuation Pause) (young)
Desired survivor size 4194304 bytes, new threshold 15 (max 15)
, 0.0036475 secs]
   [Parallel Time: 1.9 ms, GC Workers: 8]
      [GC Worker Start (ms): Min: 301.2, Avg: 302.1, Max: 302.9, Diff: 1.7]
      [Ext Root Scanning (ms): Min: 0.0, Avg: 0.2, Max: 0.6, Diff: 0.6, Sum: 1.4]
      [Update RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
         [Processed Buffers: Min: 0, Avg: 0.0, Max: 0, Diff: 0, Sum: 0]
      [Scan RS (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.1, Sum: 0.1]
      [Code Root Scanning (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.1, Sum: 0.1]
      [Object Copy (ms): Min: 0.0, Avg: 0.2, Max: 0.7, Diff: 0.7, Sum: 1.6]
      [Termination (ms): Min: 0.0, Avg: 0.4, Max: 0.7, Diff: 0.7, Sum: 3.4]
         [Termination Attempts: Min: 1, Avg: 2.5, Max: 7, Diff: 6, Sum: 20]
      [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.1]
      [GC Worker Total (ms): Min: 0.0, Avg: 0.8, Max: 1.8, Diff: 1.7, Sum: 6.7]
      [GC Worker End (ms): Min: 303.0, Avg: 303.0, Max: 303.0, Diff: 0.0]
   [Code Root Fixup: 0.0 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 0.3 ms]
   [Other: 1.5 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 1.0 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.2 ms]
      [Humongous Register: 0.0 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 0.1 ms]
   [Eden: 63.0M(63.0M)->0.0B(73.0M) Survivors: 0.0B->1024.0K Heap: 63.0M(124.0M)->839.5K(124.0M)]
Heap after GC invocations=1 (full 0):
 garbage-first heap   total 126976K, used 839K [0x0000000085c00000, 0x0000000085d003e0, 0x0000000100000000)
  region size 1024K, 1 young (1024K), 1 survivors (1024K)
 Metaspace       used 3011K, capacity 4554K, committed 4864K, reserved 1056768K
  class space    used 327K, capacity 390K, committed 512K, reserved 1048576K
}
 [Times: user=0.01 sys=0.00, real=0.00 secs] 
Total time for which application threads were stopped: 0.0042103 seconds, Stopping threads took: 0.0000725 seconds
Total time for which application threads were stopped: 0.0001507 seconds, Stopping threads took: 0.0000587 seconds
            _  _      _   __  _                    _             _   
 __      __(_)| |  __| | / _|(_) _ __  ___    ___ | |__    __ _ | |_ 
 \ \ /\ / /| || | / _` || |_ | || '__|/ _ \  / __|| '_ \  / _` || __|
  \ V  V / | || || (_| ||  _|| || |  |  __/ | (__ | | | || (_| || |_ 
   \_/\_/  |_||_| \__,_||_|  |_||_|   \___|  \___||_| |_| \__,_| \__|

Total time for which application threads were stopped: 0.0002190 seconds, Stopping threads took: 0.0000700 seconds
Total time for which application threads were stopped: 0.0001445 seconds, Stopping threads took: 0.0000691 seconds
Total time for which application threads were stopped: 0.0000765 seconds, Stopping threads took: 0.0000321 seconds
Total time for which application threads were stopped: 0.0030964 seconds, Stopping threads took: 0.0029841 seconds
Total time for which application threads were stopped: 0.0002481 seconds, Stopping threads took: 0.0000813 seconds
Total time for which application threads were stopped: 0.0002691 seconds, Stopping threads took: 0.0000765 seconds
Total time for which application threads were stopped: 0.0002466 seconds, Stopping threads took: 0.0001274 seconds
Total time for which application threads were stopped: 0.0001600 seconds, Stopping threads took: 0.0000559 seconds
Total time for which application threads were stopped: 0.0001599 seconds, Stopping threads took: 0.0000664 seconds
Total time for which application threads were stopped: 0.0001886 seconds, Stopping threads took: 0.0000775 seconds
Total time for which application threads were stopped: 0.0001481 seconds, Stopping threads took: 0.0000924 seconds
Total time for which application threads were stopped: 0.0003166 seconds, Stopping threads took: 0.0000589 seconds

**Comment by rivergao87** [comment]
[root@ecs-1XM ~]# java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by imndx** [comment]
这个日志，看起来是正常启动了的。
