### ISSUE TITLE
Add modifyUserInfo api

### ISSUE THREAD

**Issue by jessecoding** [wildfirechat/server#157]
如题

**Comment by heavyrain2012** [comment]
创建和修改用户信息是同一个接口，名字有误，应该是createOrUpdate

**Comment by jessecoding** [comment]
> 创建和修改用户信息是同一个接口，名字有误，应该是createOrUpdate

@heavyrain2012 但是如果userInfo对象某些字段之前有值，但是更新传值为空就好被置空值了。

**Comment by heavyrain2012** [comment]
是的，跟根据您提交的信息进行更新。可以先获取用户信息，更改某个字段后再去修改
