### ISSUE TITLE
同一用户，不同设备登陆

### ISSUE THREAD

**Issue by weibocai** [wildfirechat/server#158]
`
17/01/2020 10:23:14,021 [pool-2-thread-2] ERROR DatabaseStore 37  - Exception: Duplicate entry '1E171CDD-29C7-46D0-BE93-88DCC799D531-0144de441a5511ea805a00163e2' for key 'session_uid_cid_index'
17/01/2020 10:23:14,021 [pool-2-thread-2] ERROR DatabaseStore 38  -
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:115)
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1116)
com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1066)
com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1396)
com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1051)
com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462)
io.moquette.persistence.DatabaseStore.createSession(DatabaseStore.java:1517)
io.moquette.persistence.MemorySessionStore.updateOrCreateUserSession(MemorySessionStore.java:345)
io.moquette.imhandler.GetTokenHandler.action(GetTokenHandler.java:23)
io.moquette.imhandler.GetTokenHandler.action(GetTokenHandler.java:19)
io.moquette.imhandler.IMHandler.lambda$doHandler$0(IMHandler.java:191)
cn.wildfirechat.server.ThreadPoolExecutorWrapper.lambda$execute$0(ThreadPoolExecutorWrapper.java:37)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
17/01/2020 10:23:14,021 [pool-2-thread-2] ERROR IMHandler 37  - Exception: null
17/01/2020 10:23:14,021 [pool-2-thread-2] ERROR IMHandler 38  -
java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
io.moquette.persistence.MemorySessionStore.updateOrCreateUserSession(MemorySessionStore.java:347)
io.moquette.imhandler.GetTokenHandler.action(GetTokenHandler.java:23)
io.moquette.imhandler.GetTokenHandler.action(GetTokenHandler.java:19)
io.moquette.imhandler.IMHandler.lambda$doHandler$0(IMHandler.java:191)
cn.wildfirechat.server.ThreadPoolExecutorWrapper.lambda$execute$0(ThreadPoolExecutorWrapper.java:37)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
`

**Comment by heavyrain2012** [comment]
server的版本是多少，另外问题每次都复现吗，还是在某些特殊场景下才会出现，能告诉我们稳定的复现问题的方法吗
