### ISSUE TITLE
如何修改用户默认头像

### ISSUE THREAD

**Issue by hhahali** [wildfirechat/server#16]

**Comment by heavyrain2012** [comment]
最新IM服务中，当创建用户没有传头像地址时，服务器端没有再生成默认头像。这样有2种方案可以实现修改默认头像：
1. 在创建用户时，传入默认头像的地址。
2. 在创建用户时，传入空的头像地址，然后客户端的头像placeholder换成默认头像

**Comment by hlwskgypmb** [comment]
创建用户后 调创建接用户接口 传入uid 可刷新用户数据
