### ISSUE TITLE
Api文档问题

### ISSUE THREAD

**Issue by Yecgaa1** [wildfirechat/server#166]
由于开发PC程序且不使用Java
请问是否可以完善一下Server API文档中的群聊API和好友请求API

**Comment by heavyrain2012** [comment]
我们提供electron方案的pc解决方案还有C#语言SDK方案，我们只支持这两种方案。

**Comment by Yecgaa1** [comment]
请问不支持post形式的请求吗？

**Comment by Yecgaa1** [comment]
?

**Comment by heavyrain2012** [comment]
您可能混淆了概念，您应该是说的server api的sdk吧。我们暂时只能提供java版本的，文档的更新功能还没有排上日程。建议您找个java的工程师，很容易地就能看明白所有的api
