### ISSUE TITLE
是否有提供flutterSDK版本计划

### ISSUE THREAD

**Issue by huayuxi** [wildfirechat/server#169]
当前Flutter应用越来越多，是否有flutter SDK版本的计划？

**Comment by imndx** [comment]
你好，目前我们还没有推flutter SDK的计划。

但是有小伙伴基于现有的 Android SDK 和 iOS SDK 自行封装了 flutter SDK。

**Comment by heavyrain2012** [comment]
有哪位小伙伴能够贡献出flutter sdk吗

**Comment by netkn001** [comment]
现在如果要使用 flutter 要怎么对接呢？

**Comment by echokk11** [comment]
期待flutter SDK

**Comment by huazaihuola** [comment]
期待flutter SDK，对于开发者来说，开发一套内容是最好的

**Comment by oawang** [comment]
期待flutter SDK

**Comment by heavyrain2012** [comment]
正在开发中

**Comment by heavyrain2012** [comment]
已实现，请检查 https://github.com/wildfirechat/flutter_imclient
