### ISSUE TITLE
如何手动设置消息的发送 发送中这些状态

### ISSUE THREAD

**Issue by hyl87** [wildfirechat/server#171]
我尝试手动设置发送中，消息发送成功后，重启app都会变成发送失败

**Comment by heavyrain2012** [comment]
因为协议栈在启动后会把所有在发送中的消息状态改成发送失败状态。

这么做的原因是，应用有可能crash或者用户杀进程，正在发送的消息在数据库中就是发送中，重启后要改成发送失败。

**Comment by hyl87** [comment]
@heavyrain2012  那怎么手动更新消息状态呢，我看没有直接使用的方法

**Comment by heavyrain2012** [comment]
最新代码添加了 - (bool)updateMessage:(long)messageId status:(WFCCMessageStatus)status; 方法，请检查

**Comment by heavyrain2012** [comment]
android也有对应方法
