### ISSUE TITLE
可以支持阅后即焚和消息已读回执的计划吗

### ISSUE THREAD

**Issue by xuezhongde** [wildfirechat/server#179]

**Comment by heavyrain2012** [comment]
没有计划，请自己二次开发

**Comment by xuezhongde** [comment]
> 没有计划，请自己二次开发
协议proto/imtopic 是编译生成的，包括移动端提供的也是编译后的.so. 
请问针对社区版的源码开发程序，支持的了这个issue的二次开发吗？

**Comment by xuezhongde** [comment]
> 没有计划，请自己二次开发

社区版的IM通讯协议是.proto生成的代码，以及移动客户端是编译后的.so
请问针对社区版的源码开放程度，能满足这个issue的二次开发吗？

**Comment by heavyrain2012** [comment]
可以做到的，请在外围进行开发，不需要改动过IM服务和协议
