### ISSUE TITLE
app server 中application.properties文件里面设置了sms.super_code=66666不起作用啊，登录测试填写6666仍然失败

### ISSUE THREAD

**Issue by allenlei2010** [wildfirechat/server#180]
### Actual behavior
application.properties文件里面设置了sms.super_code=66666不起作用啊，登录测试填写6666仍然失败，获取验证码的话就真的发短信了收到短信验证是通过的。
以下是 application.properties文件 内容： spring.message.encoding=UTF-8 server.port=8888

sms.verdor=1

sms.super_code=66666

**Comment by heavyrain2012** [comment]
与appserver项目的issue重复
