### ISSUE TITLE
野火IM应用之对讲机

### ISSUE THREAD

**Issue by xCingular** [wildfirechat/server#184]
### http://docs.wildfirechat.cn/blogs/%E9%87%8E%E7%81%ABIM%E5%BA%94%E7%94%A8%E4%B9%8B%E5%AF%B9%E8%AE%B2%E6%9C%BA.html

请问这个页面里的“4. 4. 终结版”方案能否在现有野火IM基础上二开做到？

**Comment by heavyrain2012** [comment]
终结版核心技术是音视频技术，基本上跟IM没有太大关系了
