### ISSUE TITLE
 Unsupported Content-Coding: utf-8

### ISSUE THREAD

**Issue by CxycStudio** [wildfirechat/server#185]
你好，我在调用sdk时，AdminHttpUtils.java第71行HttpResponse response = httpClient.execute(post);报错。Caused by: org.apache.http.HttpException: Unsupported Content-Coding: utf-8
	at org.apache.http.client.protocol.ResponseContentEncoding.process(ResponseContentEncoding.java:98)。请问如何解决？谢谢。

**Comment by heavyrain2012** [comment]
是不是请求的内容中有非utf8的内容？
