### ISSUE TITLE
求问登陆之后的系统管理员名称显示错误是什么问题

### ISSUE THREAD

**Issue by AmosWong1998** [wildfirechat/server#187]
登录之后，系统管理员会有一条欢迎的语句：欢迎xxxx
但是现在的情况是显示的管理员的名称是631089

**Comment by heavyrain2012** [comment]
管理员是一个默认的用户，更新这个用户的displayname就可以了

**Comment by AmosWong1998** [comment]
> 管理员是一个默认的用户，更新这个用户的displayname就可以了

请问 这个用户是在哪个表中？userid是不是admin？我在t_user表中没有找到管理员这个账户

**Comment by heavyrain2012** [comment]
appserver发送欢迎消息时会指定一个发送人，默认的用户id是“admin”，这个用户在IM数据库的t_user表中，可以通过api修改此用户的信息，或者更改表中的信息（更改数据库需要重启服务，因为有缓存）

**Comment by AmosWong1998** [comment]
> appserver发送欢迎消息时会指定一个发送人，默认的用户id是“admin”，这个用户在IM数据库的t_user表中，可以通过api修改此用户的信息，或者更改表中的信息（更改数据库需要重启服务，因为有缓存）

我的表里面怎么没这个用户，我是不是也可以在表中创建一个用户id为admin的用户 然后他会作为管理员发送消息？
