### ISSUE TITLE
server启动时JDBC 抛出 serverTimeZone问题 设置时区为GMT%2B8后还是报错

### ISSUE THREAD

**Issue by AmosWong1998** [wildfirechat/server#188]
修改c3p0-config.xml这个文件的url后数据库还是报出时区错误（实际上c3p0的默认配置文件就是GMT%2B8）
我的MySQL的版本是8.0

![image](https://user-images.githubusercontent.com/41744494/79222634-7d3da500-7e8a-11ea-959b-cbf3d477c147.png)

**Comment by heavyrain2012** [comment]
请用最新的0.40版本验证

**Comment by AmosWong1998** [comment]
好的 感谢
