### ISSUE TITLE
请问下IM服务域名连接不上什么原因

### ISSUE THREAD

**Issue by bilining** [wildfirechat/server#190]
现在我们用IP连接IM服务是没有任何问题的，解析成域名的话就会发布了消息，国外的服务，80端口也有telnet通。请问下是因为有什么特殊的配置嘛  还是做了什么限制

**Comment by bilining** [comment]
急急急

**Comment by heavyrain2012** [comment]
请提供客户端配置文件，客户端协议栈日志，im服务器配置文件，im服务日志文件，发送到support@wildfirechat.cn

**Comment by 258538429** [comment]
我也遇到同样的问题

**Comment by heavyrain2012** [comment]
如果有问题，可以把客户端协议栈日志，im服务器配置文件，im服务日志文件，发送到support@wildfirechat.cn
