### ISSUE TITLE
随着用户增多，用户的聊天信息并没有实时写入到mysql数据库当中去。

### ISSUE THREAD

**Issue by anlei586** [wildfirechat/server#191]
### OS version (e.g. `uname -a`)

1.请问一下，这种情况正常吗？
2.如何让它能实时写入到mysql数据库当中去？

**Comment by t1mek1ller** [comment]
MYSQL是异步写的，broker宕机可能都会丢消息

```
void persistMessage(final WFCMessage.Message message, boolean update) {
        if(message.getContent().getPersistFlag() == Transparent) {
            return;
        }

        mScheduler.execute(()-> {...)
}
```

**Comment by heavyrain2012** [comment]
现在消息的写入是异步的，如果服务器压力比较大，或者mysql服务器性能比较差，可能会出现写入数据库不及时，请确认延时有多久，短时间内是可以接受的。

采用异步的原因是为了提高系统的吞吐能力，如果采用同步的方式，性能会特别特别的差。

**Comment by anlei586** [comment]
> 现在消息的写入是异步的，如果服务器压力比较大，或者mysql服务器性能比较差，可能会出现写入数据库不及时，请确认延时有多久，短时间内是可以接受的。
> 
> 采用异步的原因是为了提高系统的吞吐能力，如果采用同步的方式，性能会特别特别的差。

最高延时2个小时。

**Comment by heavyrain2012** [comment]
发生严重延时时，系统的消息分发量是多大（分发量是消息数*目标人数，目标人数包括自己，如果一个群1000个人，发一条就是1000次分发），还有服务器的硬件配置信息，还有数据库是否单独部署，是否是SSD？请提供这些信息

**Comment by anlei586** [comment]
> 发生严重延时时，系统的消息分发量是多大（分发量是消息数*目标人数，目标人数包括自己，如果一个群1000个人，发一条就是1000次分发），还有服务器的硬件配置信息，还有数据库是否单独部署，是否是SSD？请提供这些信息

群不多，8个，每个群有800左右的人。
我时时统计一分钟内在线人数是168人。非在线人数5000+ 左右。
独立的服务器（MySql和野火服务端Java程序在同服运行），硬件16核32G，非SSD。

**Comment by anlei586** [comment]
> 发生严重延时时，系统的消息分发量是多大（分发量是消息数*目标人数，目标人数包括自己，如果一个群1000个人，发一条就是1000次分发），还有服务器的硬件配置信息，还有数据库是否单独部署，是否是SSD？请提供这些信息

消息分发量是相当大，几乎白天都有人在聊天。我把服务器上传限制在2MB了。也做了CDN。但问题依然存在。我怀疑是视频和图片写入数据库时太大，这点很困惑，为什么缩图和视频要写入数据库呢？
我有点怀疑是视频和图片写入量大的原因。

**Comment by heavyrain2012** [comment]
这里面有个明显的短板就是mysql服务器，使用机械硬盘会是一个严重的瓶颈，可以查一下服务器io的监控指标，可以考虑另外单独部署一台mysql服务器，配置不用太高但要使用ssd硬盘，优化一下mysql的配置，比如修改默认缓存大小等，可以显著提高性能。

另外就是文件存储服务要使用七牛，这样就能把文件上传下载的压力从IM服务器剥离开来。

**Comment by anlei586** [comment]
> 这里面有个明显的短板就是mysql服务器，使用机械硬盘会是一个严重的瓶颈，可以查一下服务器io的监控指标，可以考虑另外单独部署一台mysql服务器，配置不用太高但要使用ssd硬盘，优化一下mysql的配置，比如修改默认缓存大小等，可以显著提高性能。
> 
> 另外就是文件存储服务要使用七牛，这样就能把文件上传下载的压力从IM服务器剥离开来。

好的，一般来说延时多久算正常？

**Comment by heavyrain2012** [comment]
时间延迟一般10秒以内吧，另外你们也可以考虑一下专业版，专业版的性能更高一些，承压能力也更好一些

**Comment by anlei586** [comment]
经研究，并不是数据库瓶颈原因。 在高峰期时（就是发现野火延时）使用navicat工具对野火数据库进行操作，例如增删改操作则是实时完成的。
