### ISSUE TITLE
admin/user/onlinestatus 返回为空

### ISSUE THREAD

**Issue by 258538429** [wildfirechat/server#192]
![image](https://user-images.githubusercontent.com/54980148/79934494-41f03700-8485-11ea-8b3c-12e0b272685e.png)
调用onlinestatus 返回结果为空是什么问题

**Comment by anlei586** [comment]
好像服务端配置文件里修改一下。

**Comment by 258538429** [comment]
> 好像服务端配置文件里修改一下。

用户在线状态事件回调地址 开启吗？这个我开了，还是不行

**Comment by anlei586** [comment]
> > 好像服务端配置文件里修改一下。
> 
> 用户在线状态事件回调地址 开启吗？这个我开了，还是不行

那就不懂了，这个问题我之前也有提过呢。
我用个取巧的方案，客户每1分钟向服务端发一次请求来记录状态。

**Comment by heavyrain2012** [comment]
只有用户曾经登录过才会返回来数据，请确认用户在服务器启动后是否登录过？如果还有问题，请更新到最新的版本，然后使用最新版本SDK的测试代码进行测试
