### ISSUE TITLE
有人配置成功吗？服务端的部署对服务器的内存有要求吗？

### ISSUE THREAD

**Issue by tuantuanyu** [wildfirechat/server#194]
我是按照下面的编译进行的：
在命令行中执行mvn clean compile package，生成的目标文件在./distribution/target/distribution-xxxx-bundle-tar.tar.gz。然后放到linux解压后，修改/config/wildfirechat.conf文件，修改server.ip为服务器ip地址。运行wildfirechat.sh时，直接报./bin/wildfirechat.sh: line 2: : command not found。

如果是用编译好的安装包，直接启动不起来

**Comment by Vivian-debug** [comment]
请教一下后来是怎么解决的呀？ 也遇见同样的问题
