### ISSUE TITLE
删除群成员, 返回code=0, 但是成员没有真正删除

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/server#196]
### Expected behavior

能删除群成员

### Actual behavior

没有真正删除

### Steps to reproduce

我正在尝试将Server SDK移植到.NET Core上, 在移植`GroupAdmin`中发现了这个问题.
我为移植的`GroupAdmin`编写了单元测试代码, 覆盖创建群, 修改群信息, 获取群成员等用例, 其它测试都能正常通过, 但是在删除群成员时发生了该问题.

测试的代码截图如下:
![image](https://user-images.githubusercontent.com/3471718/81521196-0d331980-9379-11ea-80e5-ad17eb93bcf1.png)

服务端是试用的专业版, 返回的code为0, LOG截图如下:
![image](https://user-images.githubusercontent.com/3471718/81521334-7155dd80-9379-11ea-99cd-311e4759ac51.png)

因为刚接触野火, 从LOG中看不出有什么问题, 所以提issue请求帮助.

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

### OS version (e.g. `uname -a`)

Linux wildfire-server-f54bd8ff4-7smq2 4.14.105-19-0008 #1 SMP Sat Oct 12 11:12:05 CST 2019 x86_64 GNU/Linux

**Comment by heavyrain2012** [comment]
请提供一下服务器版本的git节点号，用api/version看就行，我们查一下

**Comment by wakuflair** [comment]
![image](https://user-images.githubusercontent.com/3471718/81521853-16bd8100-937b-11ea-87a7-d1fb114a0b04.png)

**Comment by heavyrain2012** [comment]
问题查出来了，是因为获取群成员时没有过滤已经删除的群成员，最新版本已经改了，请给我们发邮件要求更新版本，或者在这里加一下对member的类型判断，当type为4时表示已经删除群成员

**Comment by wakuflair** [comment]
更新后没问题了, 谢谢.
