### ISSUE TITLE
IM server 可以配置成非80端口吗？

### ISSUE THREAD

**Issue by chinesechina** [wildfirechat/server#198]
IM server 可以配置成非80端口吗？
以前版本可以，新版本可否放开下了，谢谢！

**Comment by heavyrain2012** [comment]
强制80有以下几方面原因：
1，在国内使用80是必须备案的，这样就能减少或避免一些非法或者灰色的使用，我们期望客户都是在备案下运行，确保不会有人使用我们的开源对社会造成危害
2，80端口是网络中最畅通的端口，使用80能够提高网络的访问体验
3，使用非80端口跟我们的一些商业策略有冲突，我们要求必须使用80端口才行

目前我们只针对国企和事业单位会开启非80端口，如果不是这种情况请进行备案并使用80端口，谢谢理解
