### ISSUE TITLE
为什么新请求加好友getuserinfo 接口拿不到信息 

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/server#20]
![image](https://user-images.githubusercontent.com/7382234/59151196-6ad02f00-8a61-11e9-9b61-2ce8d166f293.png)

**Comment by yuzhongrong** [comment]
是否存在过期说法

**Comment by heavyrain2012** [comment]
因为本地没有该好友信息，在第一次获取用户信息时，同步返回空，然后会去服务器拉取，当拉取成功后，会有通知用户信息更新。
最佳做法应该是获取用户信息时同时注册用户信息更新监听。
