### ISSUE TITLE
AES解密 bug

### ISSUE THREAD

**Issue by xuezhongde** [wildfirechat/server#201]
环境：服务端（基于 commuit 1bd060936cb38d39f14a3a13cb32ac9cfbb25fea）
#37 与此issue是同样的问题。
期待解决

**Comment by heavyrain2012** [comment]
有一种可能是缩略图太大导致的，协议栈不支持发送超过15K的消息，把缩略图控制在15K以内试试

**Comment by xuezhongde** [comment]
> 有一种可能是缩略图太大导致的，协议栈不支持发送超过15K的消息，把缩略图控制在15K以内试试

调试发现，服务端接收到PUB的消息，AES解密异常，可能是加密的数据不完整了。协议栈限制15K，客户端难道截断后发送了？

**Comment by heavyrain2012** [comment]
可能发送缓冲区的限制或者别的什么限制，消息应该是轻量才行，如果消息体过大会影响消息发送和接收的体验，请把消息体限制在15K以下
