### ISSUE TITLE
想要对数据库新增字段，发现一个“无法修改”的MFCMessage文件。请问可否提供wfcmessage_community.proto文件呢

### ISSUE THREAD

**Issue by Idolphint** [wildfirechat/server#203]
##原因描述：##
想要在原有数据库的基础上增加我们想要的字段。但是查看源文件发现，访问数据库经过了一个名为WFCMessage.java的文件。但是没有它的源文件wfcmessage_community.proto 虽然没太搞明白它真正的作用。
但似乎前端的请求都会送入该文件。而后端对数据库的访问也经过了这个文件。

##期望结果：##
一个可以替代的修改数据库字段的方法
或者wfcmessage_community.proto文件

不胜感激！

**Comment by heavyrain2012** [comment]
你好，协议部分属于公司机密，不能提供。另外建议不要修改im服务器的代码，可以在IM外围进行开发，我们文档上有一些使用的建议，请参考。

**Comment by mydogger** [comment]
没有开源呀。。。

**Comment by heavyrain2012** [comment]
协议栈部分是闭源的，其它都是开源的

**Comment by czom** [comment]
就是不给你，哈哈哈
