### ISSUE TITLE
发送文件名中含有"&"符号的文件, 对方接收异常

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/server#206]
使用的是内置文件存储服务, 当发送文件名中含有"&"的文件时, 消息可以正常发送.
但是接收方不能正常接收文件.

原因可能是服务器对文件名未做Encode处理, 导致文件URL不合法:
比如我发送了一个名为`car&.jpg`的图片, 
服务器返回的文件URL为:`http://blablabla.com/fs/1/2020/06/01/11/jiyh-1-1591010640-P1kAlMiG_car&.jpg`

**Comment by heavyrain2012** [comment]
客户端的问题，生成的url没有做urlencode，重新给您发新版本了，请用新版本验证

**Comment by wakuflair** [comment]
更新后返回的URL还是没有被Encode. 下图是我修改了DEMO, 使用`UploadMedia`上传的一个名为`timg&.jpg`文件, 返回的URL截图:
![image](https://user-images.githubusercontent.com/3471718/83828790-0ac3a580-a714-11ea-8155-3aa1c2e992f2.png)

**Comment by heavyrain2012** [comment]
问题查出来了，是server的问题，路径中是可以有&等符号的，im服务中内置的文件存储服务有bug导致。请更新IM服务验证这个问题。

另外内置文件存储服务是个测试级别的服务，不建议在商用环境中使用。商用时建议使用七牛或者专业版带的minio

**Comment by wakuflair** [comment]
更新后问题解决.
