### ISSUE TITLE
野火的消息转发能否带上messageUid、mid

### ISSUE THREAD

**Issue by anlei586** [wildfirechat/server#207]
希望消息转发功能有messageUid、mid

**Comment by heavyrain2012** [comment]
不明白您的意思，转发是在UI层实现的，如果您想修改可以直接修改，另外消息内容带有extra信息，可以把您要定制的内容放到extra中去，注意使用json保持extra的可继续扩展性

**Comment by anlei586** [comment]
> 不明白您的意思，转发是在UI层实现的，如果您想修改可以直接修改，另外消息内容带有extra信息，可以把您要定制的内容放到extra中去，注意使用json保持extra的可继续扩展性

不是UI前端哦，是服務端的
wildfirechat.conf
文件里的
message.forward.url

**Comment by heavyrain2012** [comment]
明白了，确实是没有带上消息ID，我们会尽快加上，请耐心等待

**Comment by anlei586** [comment]
> 明白了，确实是没有带上消息ID，我们会尽快加上，请耐心等待

感谢，我会耐心等待的~

**Comment by heavyrain2012** [comment]
已添加，添加了messageId和timestamp字段，其中messageId对应客户端的messageUid，请更新代码验证
