### ISSUE TITLE
随着用户增多，用户的聊天信息并没有实时写入到mysql数据库当中去。 #191

### ISSUE THREAD

**Issue by anlei586** [wildfirechat/server#209]
https://github.com/wildfirechat/server/issues/191

经研究，并不是数据库瓶颈原因。 在高峰期时（就是发现野火延时）使用navicat工具对野火数据库进行操作，例如增删改操作则是实时完成的。

**Comment by heavyrain2012** [comment]
数据库的线程默认是cpu数的2倍，如果消息分发量非常大，每秒要写入的数据量太大，是有可能排队的，这时候需要提高数据库写入的速度或者试用专业版。
