### ISSUE TITLE
加好友请求 一晚上没有处理 第二天再去同意 直接提示操作失败

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/server#21]
![image](https://user-images.githubusercontent.com/7382234/59151673-d0c0b480-8a69-11e9-9f14-932f149cc999.png)

**Comment by heavyrain2012** [comment]
http://docs.wildfirechat.cn/faq/general.html 第3个问题
如果行为跟文档不符合，请查看一下错误码
