### ISSUE TITLE
陌生人聊天功能关了但是还是能够聊天（专业版），已重启多次

### ISSUE THREAD

**Issue by mrcitier** [wildfirechat/server#210]
- 希望关闭陌生人聊天后只能加了好友才可以聊天

- 已经关闭了陌生人聊天的配置，但不生效，或者偶尔生效一下

- A删除好友B后，B在聊天记录里再找到A还能发信息，服务器已经配置了不能陌生人聊天（奇怪的是偶尔不能聊，感觉这个配置生效有点随机）

**Comment by heavyrain2012** [comment]
如果是专业版，需要在每个节点上都要配置关掉陌生人聊天。另外有些特殊情况，如果对话双方有至少一方是管理员或者机器人，是可以突破限制的，请检查是否是上述两种情况

**Comment by mrcitier** [comment]
> 如果是专业版，需要在每个节点上都要配置关掉陌生人聊天。另外有些特殊情况，如果对话双方有至少一方是管理员或者机器人，是可以突破限制的，请检查是否是上述两种情况

两个普通用户之间的逻辑，每个节点的配置都更新也都重启了，你们测试看下吧

**Comment by heavyrain2012** [comment]
我们测试过，功能是正常的。请确认一下信息并**截图回复**给我们
1. IM配置信息中，关闭陌生人聊天的配置
2. A用户和B用户在数据库t_user表中的信息
3. A用户和B用户在数据库t_friend表中互相之间的关系

**Comment by mrcitier** [comment]
在t_friend 表中，查看到双方关系 数据状态 都是1

**Comment by mrcitier** [comment]
双方是好友的情况下，进行聊天，然后再删除对方好友，库里中的字段状态是 1 
 对方但是还是通过之前的会话框 发送消息。。。 （删除好友一方的，删除好友后会话框已经被清除，被删掉好友方的对话框未删除）

**Comment by mrcitier** [comment]
@heavyrain2012
