### ISSUE TITLE
聊天消息是怎么选择放在数据库中哪个表的

### ISSUE THREAD

**Issue by 258538429** [wildfirechat/server#211]
聊天的消息记录在 t_messages_*表中，那么我怎么知道某个用户在消息在哪个具体的表中，目前测试的感觉是根据用户userId来分配的

**Comment by imndx** [comment]
可参考```MessageShardingUtil```

**Comment by imndx** [comment]
可参考[常见问题](https://docs.wildfirechat.cn/faq/server.html)第3个问题
