### ISSUE TITLE
通过服务端SDK添加成员到群组时，如何屏蔽掉客户端的提示信息？

### ISSUE THREAD

**Issue by JiaRG** [wildfirechat/server#214]
**SDK Version: ** 0.38

![image](https://user-images.githubusercontent.com/31472350/84236085-a6488200-ab29-11ea-923b-e9785d09685c.png)

**Comment by heavyrain2012** [comment]
如果此类消息都不想显示，可以修改客户端消息的存储属性，改成不存储即可。如果只想屏蔽掉服务器发的，客户端操作触发的还继续起作用，就比较麻烦了，可以在客户端展示消息前检查如果是管理员发的就过滤掉

**Comment by JiaRG** [comment]
好的，谢谢
