### ISSUE TITLE
多人视频不稳定，有时候可以连通，有时候连通以后，有的设备会自动断开连接

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#218]
发起9个人的视频，连接不稳定，有时候可以连通，有时候连通以后，会有设备自动断开连接

**Comment by heavyrain2012** [comment]
由于多人音视频采用的是mesh方案，要每个人与其他人p2p直连，9名成员时，就需要每位成员与其他8人直连，共输出8路音视频，输入8路音视频。这样对手机客户端的压力非常大，很难稳定支持这么多路。mesh方案的优点就是不需要服务器参与，实现简单，价格便宜，缺点就是对客户端压力大，支持路数不高。

**Comment by heavyrain2012** [comment]
Duplicate of #217
