### ISSUE TITLE
发起多人视频时，被邀请人，看到的通话成员列表不对

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#219]
1人对另外3人发起多人视频，3个接受方在等待接听的页面中，看到的成员列表不对，每个人只看到2个成员（应该是包括了发起方在内的3个人）

**Comment by heavyrain2012** [comment]
这个是产品设计的问题，请看下面的截图，这是用户“星星”打给用户”小云“等三人的，一共是4名成员，在用户”小云“的来电界面上，上面显示发起者是用户”星星“，下面显示的是除了发起者之外的被邀请成员。这是正常的，如果您有自己特殊的产品设计需要，可以自己进行修改，这个界面是开放的，所有的信息都有。

![来电截图](https://cdn.wildfirechat.cn/voip_invite.png)
