### ISSUE TITLE
撤回消息有问题，当聊天时，对方撤回消息，自己这边并没有看到消息被撤回

### ISSUE THREAD

**Issue by anlei586** [wildfirechat/server#221]
当聊天时，对方撤回消息，自己这边并没有看到消息被撤回。

返回会话列表可以看到有xxx撤回一条消息的提示，再进去聊天界面。则是有正常撤回掉。

经查：安卓端 IOnReceiveMessageListener。onTransact(int code...

撤回消息的code=1 与发送消息相同。

IOS同样的问题，

服务端version 0.41

估计服务端问题。

**Comment by heavyrain2012** [comment]
客户端协议栈引入的问题，已经解决，请更新到最新协议栈

**Comment by anlei586** [comment]
> 客户端协议栈引入的问题，已经解决，请更新到最新协议栈

更新了安卓端测试了1个多小时，貌似还是不行。IOS则可以。

**Comment by heavyrain2012** [comment]
不好意思，这个问题我们没有彻底解决。现在已经解决了，请更新android代码到最新验证
