### ISSUE TITLE
debian 系统部署出现问题

### ISSUE THREAD

**Issue by huazaihuola** [wildfirechat/server#222]
debian 操作系统

root@li:/usr/local/im_server# sh ./bin/wildfirechat.sh 
: not foundirechat.sh: 2: ./bin/wildfirechat.sh: 
./bin/wildfirechat.sh: 3: cd: can't cd to ./bin
: not foundirechat.sh: 4: ./bin/wildfirechat.sh: 
: not foundirechat.sh: 7: ./bin/wildfirechat.sh: 
./bin/wildfirechat.sh: 88: ./bin/wildfirechat.sh: Syntax error: end of file unexpected (expecting "then")

启动失败了，windows 能启动，帮看一下原因谢谢~

**Comment by heavyrain2012** [comment]
应该是脚本在windows平台上修改过，导致格式为windows格式。文件常见问题里有个如何转换为unix格式的方法

**Comment by huazaihuola** [comment]
@heavyrain2012
好的 我试一下

**Comment by huazaihuola** [comment]
问题已解决，我在windows上复制了一下，然后vim 保存，启动成功！
