### ISSUE TITLE
中文系统下，双方添加好友成功后，在聊天页面显示了英文的提示语

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#223]

**Comment by heavyrain2012** [comment]
IM服务器下的config目录有语言文件，可以把英文的都改成中文的。这个地方先临时这么改一下，我们后面会重构这个提醒的处理

**Comment by heavyrain2012** [comment]
在最新版本的IM服务的配置文件中有个friend.new_welcome_message开关，打开后添加好友成功，会发送type为92/93的两条消息，客户端会本地化显示“您已经是好友了”和“以上是好友请求信息”的内容。打开开关需要确保所有的客户端已经升级到了适配的版本
