### ISSUE TITLE
在大量发送消息的时候，发现会出现对方收不到消息或图片的现象，可能是什么原因，望解答,服务器（因为是开发环境）配置是（1核16G）

### ISSUE THREAD

**Issue by Aronle** [wildfirechat/server#224]

**Comment by heavyrain2012** [comment]
服务器版本是多少

**Comment by Aronle** [comment]
![image](https://user-images.githubusercontent.com/8521273/86105389-dca66b00-baf1-11ea-9682-76681f3ff95e.png)
![image](https://user-images.githubusercontent.com/8521273/86105493-fd6ec080-baf1-11ea-868d-38e4939954ed.png)

**Comment by Aronle** [comment]
@heavyrain2012 
![image](https://user-images.githubusercontent.com/8521273/86105540-0c557300-baf2-11ea-964a-87068b330edb.png)

**Comment by Aronle** [comment]
@heavyrain2012 
CentOS Linux release 7.6.1810 (Core)

**Comment by heavyrain2012** [comment]
我想问的是IM服务的版本，之前应该是有过bug，可以升级到最新的0.42看看，然后把客户端的版本也都更新到最新试试。

另外大量发送消息的频率有多高

**Comment by Aronle** [comment]
@heavyrain2012 0.41的

**Comment by Aronle** [comment]
@heavyrain2012 是0.37的

**Comment by heavyrain2012** [comment]
升级到最新试试，另外发送消息的频率有多高，服务器load值到了多少
