### ISSUE TITLE
版本0.42不能连接mysql吗？

### ISSUE THREAD

**Issue by 2822680699** [wildfirechat/server#225]
Total time for which application threads were stopped: 0.0001060 seconds, Stopping threads took: 0.0000250 seconds
Total time for which application threads were stopped: 0.0001386 seconds, Stopping threads took: 0.0000703 seconds
{Heap before GC invocations=1 (full 0):
 garbage-first heap   total 120832K, used 71324K [0x000000008a000000, 0x000000008a1003b0, 0x0000000100000000)
  region size 1024K, 70 young (71680K), 1 survivors (1024K)
 Metaspace       used 5429K, capacity 5474K, committed 5632K, reserved 1056768K
  class space    used 627K, capacity 657K, committed 768K, reserved 1048576K
[GC pause (G1 Evacuation Pause) (young)
Desired survivor size 4718592 bytes, new threshold 15 (max 15)
- age   1:     498144 bytes,     498144 total
, 0.0034368 secs]
   [Parallel Time: 2.4 ms, GC Workers: 4]
      [GC Worker Start (ms): Min: 206.0, Avg: 206.2, Max: 206.4, Diff: 0.5]
      [Ext Root Scanning (ms): Min: 0.2, Avg: 0.7, Max: 1.1, Diff: 0.8, Sum: 2.6]
      [Update RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
         [Processed Buffers: Min: 0, Avg: 0.0, Max: 0, Diff: 0, Sum: 0]
      [Scan RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.1]
      [Code Root Scanning (ms): Min: 0.0, Avg: 0.7, Max: 1.5, Diff: 1.5, Sum: 2.9]
      [Object Copy (ms): Min: 0.1, Avg: 0.6, Max: 1.1, Diff: 1.0, Sum: 2.4]
      [Termination (ms): Min: 0.0, Avg: 0.1, Max: 0.2, Diff: 0.2, Sum: 0.5]
         [Termination Attempts: Min: 1, Avg: 1.0, Max: 1, Diff: 0, Sum: 4]
      [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
      [GC Worker Total (ms): Min: 1.9, Avg: 2.1, Max: 2.3, Diff: 0.5, Sum: 8.6]
      [GC Worker End (ms): Min: 208.3, Avg: 208.3, Max: 208.3, Diff: 0.0]
   [Code Root Fixup: 0.0 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 0.1 ms]
   [Other: 1.0 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 0.7 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.1 ms]
      [Humongous Register: 0.0 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 0.0 ms]
   [Eden: 69.0M(69.0M)->0.0B(67.0M) Survivors: 1024.0K->3072.0K Heap: 69.7M(118.0M)->2547.2K(118.0M)]
Heap after GC invocations=2 (full 0):
 garbage-first heap   total 120832K, used 2547K [0x000000008a000000, 0x000000008a1003b0, 0x0000000100000000)
  region size 1024K, 3 young (3072K), 3 survivors (3072K)
 Metaspace       used 5429K, capacity 5474K, committed 5632K, reserved 1056768K
  class space    used 627K, capacity 657K, committed 768K, reserved 1048576K
}
 [Times: user=0.02 sys=0.00, real=0.00 secs] 
Total time for which application threads were stopped: 0.0037231 seconds, Stopping threads took: 0.0000532 seconds
Total time for which application threads were stopped: 0.0000934 seconds, Stopping threads took: 0.0000245 seconds
Total time for which application threads were stopped: 0.0001623 seconds, Stopping threads took: 0.0000329 seconds
Total time for which application threads were stopped: 0.0002595 seconds, Stopping threads took: 0.0000230 seconds
{Heap before GC invocations=2 (full 0):
 garbage-first heap   total 120832K, used 71155K [0x000000008a000000, 0x000000008a1003b0, 0x0000000100000000)
  region size 1024K, 70 young (71680K), 3 survivors (3072K)
 Metaspace       used 14820K, capacity 15046K, committed 15360K, reserved 1062912K
  class space    used 1680K, capacity 1753K, committed 1792K, reserved 1048576K
[GC pause (G1 Evacuation Pause) (young)
Desired survivor size 4718592 bytes, new threshold 15 (max 15)
- age   1:    1000176 bytes,    1000176 total
- age   2:     400040 bytes,    1400216 total
, 0.0073048 secs]
   [Parallel Time: 5.1 ms, GC Workers: 4]
      [GC Worker Start (ms): Min: 735.8, Avg: 735.9, Max: 736.1, Diff: 0.3]
      [Ext Root Scanning (ms): Min: 0.3, Avg: 0.6, Max: 0.9, Diff: 0.6, Sum: 2.3]
      [Update RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
         [Processed Buffers: Min: 0, Avg: 0.0, Max: 0, Diff: 0, Sum: 0]
      [Scan RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
      [Code Root Scanning (ms): Min: 0.1, Avg: 0.2, Max: 0.5, Diff: 0.4, Sum: 1.0]
      [Object Copy (ms): Min: 3.8, Avg: 4.1, Max: 4.4, Diff: 0.6, Sum: 16.5]
      [Termination (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
         [Termination Attempts: Min: 1, Avg: 17.5, Max: 33, Diff: 32, Sum: 70]
      [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
      [GC Worker Total (ms): Min: 4.8, Avg: 5.0, Max: 5.1, Diff: 0.3, Sum: 19.9]
      [GC Worker End (ms): Min: 740.9, Avg: 740.9, Max: 740.9, Diff: 0.0]
   [Code Root Fixup: 0.0 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 0.1 ms]
   [Other: 2.1 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 1.8 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.1 ms]
      [Humongous Register: 0.0 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 0.1 ms]
   [Eden: 67.0M(67.0M)->0.0B(61.0M) Survivors: 3072.0K->9216.0K Heap: 69.5M(118.0M)->11.7M(118.0M)]
Heap after GC invocations=3 (full 0):
 garbage-first heap   total 120832K, used 11945K [0x000000008a000000, 0x000000008a1003b0, 0x0000000100000000)
  region size 1024K, 9 young (9216K), 9 survivors (9216K)
 Metaspace       used 14820K, capacity 15046K, committed 15360K, reserved 1062912K
  class space    used 1680K, capacity 1753K, committed 1792K, reserved 1048576K
}
 [Times: user=0.02 sys=0.00, real=0.00 secs] 
Total time for which application threads were stopped: 0.0076122 seconds, Stopping threads took: 0.0000301 seconds
Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration version 22
-> Applied to database : 0
-> Resolved locally    : 1511335132
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:101)
	at io.moquette.server.Server.startServer(Server.java:227)
	at io.moquette.server.Server.startServer(Server.java:219)
	at io.moquette.server.Server.startServer(Server.java:203)
	at io.moquette.server.Server.start(Server.java:113)
	at cn.wildfirechat.server.Server.main(Server.java:15)
Heap
 garbage-first heap   total 120832K, used 66081K [0x000000008a000000, 0x000000008a1003b0, 0x0000000100000000)
  region size 1024K, 62 young (63488K), 9 survivors (9216K)
 Metaspace       used 15009K, capacity 15206K, committed 15360K, reserved 1062912K
  class space    used 1694K, capacity 1785K, committed 1792K, reserved 1048576K

**Comment by heavyrain2012** [comment]
flyway会校验脚本的完整性，如果自己修改过sql语句就会导致这个问题，可以参考 
https://blog.csdn.net/yxl0011/article/details/79965894

解决办法请从网上查一下吧
