### ISSUE TITLE
关于账号删除的问题

### ISSUE THREAD

**Issue by edwardZhang** [wildfirechat/server#226]
用户反馈账号被盗，希望可以删除账号，防止聊天记录和好友被利用。 
我尝试删除了
t_user,t_user_session,t_friend这几个表里相关用户的数据后。 发现该账号在不主动退出登录的情况下，重新打开APP，连接。 依然可以使用，包括查看聊天记录，和好友聊天等。 
请问如何解决， 使用的是专业版。

**Comment by heavyrain2012** [comment]
1, 可以用封禁功能，封禁用户后，当用户连上IM后应该退出登录。
2. 可以使用多端互踢功能，在IM服务器中关掉多端登录，然后换个客户端登录，之前的客户端应该自动跳出登录界面。

由于这两个功能需要UI层做对应处理，另外以前的版本功能也不够完善，可以先进行测试，根据测试结果确定采用那种方案。
