### ISSUE TITLE
执行/im或则/route出现没有登录

### ISSUE THREAD

**Issue by 2822680699** [wildfirechat/server#227]
id：null
super：null
id：null
super：null
id：null
super：null
id：null
super：null
id：null
super：null

id：null
super：null
id：null
super：null
id：null
super：null
id：null
super：null

**Comment by heavyrain2012** [comment]
你们如果修改过IM服务，我们无法进行支持

**Comment by 2822680699** [comment]
没有修改过



---原始邮件---
发件人: "heavyrain.lee"<notifications@github.com&gt;
发送时间: 2020年7月5日(周日) 上午8:00
收件人: "wildfirechat/server"<server@noreply.github.com&gt;;
抄送: "2822680699"<2822680699@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wildfirechat/server] 执行/im或则/route出现没有登录 (#227)




 
你们如果修改过IM服务，我们无法进行支持

**Comment by heavyrain2012** [comment]
已经邮件支持，issue先关了
