### ISSUE TITLE
禁止陌生人聊天，导致机器人也无法发送消息

### ISSUE THREAD

**Issue by 258538429** [wildfirechat/server#228]
##是否禁止陌生人聊天
message.disable_stranger_chat true
服务端禁止陌生人聊天，导致机器人也无法发给新的用户

我看源码好像有个BUG，不知道是不是我这边理解错误

        if (mDisableStrangerChat) {
            //在禁止私聊时，允许机器人，物联网设备及管理员进行私聊。
            IMap<String, WFCMessage.User> mUserMap = hzInstance.getMap(USERS);
            WFCMessage.User target = mUserMap.get(targetUser);
            if (target != null && target.getType() != ProtoConstants.UserType.UserType_Normal) {
                return ErrorCode.ERROR_CODE_SUCCESS;
            }
            target = mUserMap.get(fromUser);
            if (target != null && target.getType() != ProtoConstants.UserType.UserType_Normal) {
                return ErrorCode.ERROR_CODE_SUCCESS;
            }
            //admin的usertype为3，所以不需要hardcode为admin添加例外
//            if (targetUser.equals("admin") || fromUser.equals("admin")) {
//                return ErrorCode.ERROR_CODE_SUCCESS;
//            }
            return ErrorCode.ERROR_CODE_NOT_RIGHT;
        }

**Comment by heavyrain2012** [comment]
没看出什么问题，请明示

**Comment by 258538429** [comment]
> 没看出什么问题，请明示

目前情况是，服务端，禁止陌生人聊天，新创建的机器人是无法给用户发消息，返回ERROR_CODE_NOT_RIGHT错误码。关掉禁止陌生人聊天，就可以正常发消息过去。
对于机器人来说，是不是也受禁止陌生人聊天影响？
fromUser 是指 owner吗？

**Comment by heavyrain2012** [comment]
fromUser是机器人自己。确认一下，机器人是怎么发送消息的？调用的什么接口，参数是什么
