### ISSUE TITLE
消息免打扰功能

### ISSUE THREAD

**Issue by liwyan** [wildfirechat/server#229]
Server API 里面未提供设置消息免打扰的功能。

**Comment by heavyrain2012** [comment]
请详细描述一下消息免打扰功能

**Comment by liwyan** [comment]
现在我们有一个业务是想某些群可以在建群之后就给你设置免打扰（也就是没有消息提醒，但是退出聊天页面，还是可以收消息的，这点和聊天室不一样），但是server API里面并没有设置群免打扰的地方，也没有可以操作会话的地方。客户端里面提供的是有设置免打扰的功能，但是我们想把这些业务放到服务器来做，所以想让咱们Server API这边提供一下，个人对群组（会话）设置免打扰的功能，或者是直接设置某个群组（会话）对整个群里的人都免打扰的功能。https://dev.yunxin.163.com/docs/product/IM即时通讯/服务端API文档/群组功能（高级群）?#修改消息提醒开关

**Comment by heavyrain2012** [comment]
现在社区版和专业版上都没有这个功能，可以通过二次开发来达到这个目的

1. 创建群时填写extra，表明是个静音群。
2. 客户进入群会话时检查extra，如果是静音群就设置静音。
3. 客户端收到消息要弹通知时，检查群extra。
4. 推送服务要推送时检查群信息。

以上基本就能达到目的。如果您是专业版用户，可以联系对接人要求增加此功能
