### ISSUE TITLE
服务端采用SDK删除用户后，客户端会显示用户的uid

### ISSUE THREAD

**Issue by JiaRG** [wildfirechat/server#230]
客户端上会显示删除用户的uid，期望删除用户后会清除该用户的数据，但是历史的tips上需要显示正常的用户名称

**Comment by heavyrain2012** [comment]
理论上调用删除用户接口后，客户端获取到的用户信息状态是deleted状态，请确认获取到的用户状态是不是deleted状态的

```
public class UserInfo {
    ....
    //0 normal; 1 deleted;
    public int deleted;
}
```

**Comment by JiaRG** [comment]
`UserAdmin.destroyUser(userId)`直接物理删除了，我看数据库里面也没了

**Comment by JiaRG** [comment]
@heavyrain2012 客户端反馈说是群组里没有deleted=1的数据

**Comment by JiaRG** [comment]
目前服务端的解决方式是不在使用`UserAdmin.destroyUser(userId)`，而采用更新用户名的方式，但是这有会引入另外的问题：删除用户的数据还存在并且这个用户也能被找到

**Comment by heavyrain2012** [comment]
这个功能服务器端实现不完整，我们这周会把这个问题处理好，请耐心等待一下。

**Comment by heavyrain2012** [comment]
服务器端逻辑没有问题，需要客户端根据deleted状态去显示用户信息，请检查android-chat工程最新的提交

**Comment by JiaRG** [comment]
👌
