### ISSUE TITLE
sdk_readme.txt 中的 依赖应该添加到哪里？

### ISSUE THREAD

**Issue by zzwooc** [wildfirechat/server#231]
如下图所示，在 server_sdk/ 中的 sdk_readme.txt 文件中，说要把 common 和 sdk 添加到依赖，请问是添加到哪里？

![image](https://user-images.githubusercontent.com/19815528/87388878-3883f000-c5d8-11ea-9845-67879c3d5508.png)

**Comment by tang1007** [comment]
maven管理的项目，粘贴即可

**Comment by zzwooc** [comment]
Idea打开server项目，是往哪一个上面添加依赖

![image](https://user-images.githubusercontent.com/19815528/87400272-29f30400-c5eb-11ea-92bd-f47449185e30.png)


> maven管理的项目，粘贴即可

**Comment by zzwooc** [comment]
我想我知道了，这个是指拿到其他项目里用，不是这个项目，比如admin要用，我要拿到admin里去

**Comment by heavyrain2012** [comment]
对的
