### ISSUE TITLE
音视频带宽疑问。“中转时视频每路带宽消耗140KBps”  是否和 视频码率正比关系（近似值）

### ISSUE THREAD

**Issue by xuezhongde** [wildfirechat/server#234]
请教下，10路 流量公式里面 乘以0.5  怎么理解呢
![a](https://user-images.githubusercontent.com/194413/87621139-b1a75280-c752-11ea-91b5-a865071f1f2e.jpg)

**Comment by heavyrain2012** [comment]
预计有一半的通话能够打洞成功，这样只计算打洞失败的就可以。

云服务器一般都有流量计费的服务，可以用流量计费的方式，带宽足够大，也比较省钱
