### ISSUE TITLE
Server Api ClientID 问题

### ISSUE THREAD

**Issue by zzwooc** [wildfirechat/server#235]
关于Server api 的 ClientID，应该如何获取，比如我现在要开发一个新的客户端，我应该如何获取这个客户端的 ClientID？

![image](https://user-images.githubusercontent.com/19815528/87622173-1cf22400-c755-11ea-8be6-50e01aca1f09.png)

**Comment by imndx** [comment]
Android、iOS、Web、PC、小程序等端，都提供了```getClientId```方法
