### ISSUE TITLE
推送消息这块没有单方推送的吗？比如说只推送从A用户到B用户，而不用推送从B用户到A用户的消息

### ISSUE THREAD

**Issue by CalvinXCui** [wildfirechat/server#238]
推送消息这块没有单方推送的吗？比如说只推送从A用户到B用户，而不用推送从B用户到A用户的消息
是通过Conversation conversation = new Conversation();conversation.etLine();控制的吗？推送消息类型是以那种半透明的推送，就类似于添加好友成功后的那种推送，但希望是单方推送的。这种怎么实现？
              Conversation conversation = new Conversation();
                conversation.setTarget("user1");
                conversation.setType(ProtoConstants.ConversationType.ConversationType_Private);
                conversation.setLine(0);
MessagePayload payload = new MessagePayload();
                payload.setType(90);
MessageAdmin.sendMessage(user.getUid(), conversation, payload);
是这么实现的吗？发现不对

**Comment by heavyrain2012** [comment]
不是太明白你的意思，大概猜测一下，是不是想某种消息只在一方显示，另外一方不显示？
如果是这种情况，用自定义消息就好了，在不显示的一方收到消息就删除掉，显示前先过滤一遍

**Comment by CalvinXCui** [comment]
就是类似于微信删除完好友后，被删除的好友再想给删除者发送消息，服务就会推送一条消息给被删除者，告诉其被删除了，而且这种推送的样式不是正常发送消息的那种，而是类似添加完好友同时推送给双方的那种消息样式

**Comment by heavyrain2012** [comment]
这种是本地插入的吧，用户A给用户B发消息，发送失败，根据失败原因判断，如果是不是好友的原因，就插入一条自定义消息“你们不是好友，无法发送”
