### ISSUE TITLE
服务器端没有监听8888端口

### ISSUE THREAD

**Issue by Warren-Z** [wildfirechat/server#24]
参考http://docs.wildfirechat.cn/quick_start/server.html 第2.0.1和2.0.2部署了IM服务器；
参考http://docs.wildfirechat.cn/quick_start/android.html编译了安卓客户端；现在客户端上使用superCode 66666不能连接到服务器，请问是什么原因？服务器上并没有监听8888端口

**Comment by heavyrain2012** [comment]
需要同时部署***野火IM服务器*** 和***Demo应用服务器***。两者需要配合使用，其中Demo应用服务器监听了8888端口

**Comment by Warren-Z** [comment]
> 需要同时部署_**野火IM服务器**_ 和_**Demo应用服务器**_。两者需要配合使用，其中Demo应用服务器监听了8888端口

好的，谢谢，能测试Demol
