### ISSUE TITLE
启动im服务报错：main" java.io.FileNotFoundException:  config\hazelcast.xml (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by CalvinXCui** [wildfirechat/server#241]
启动im服务报错：main" java.io.FileNotFoundException:  config\hazelcast.xml (系统找不到指定的路径。)但是这个文件是确实存在的，而且路径什么的完全没有问题，都正常着了。不知道是哪里导致的，莫名间就报这个错

**Comment by heavyrain2012** [comment]
是怎么启动的，如果是命令行启动，需要在bin的同级目录下启动，不能在bin内启动，文档中有描述

**Comment by CalvinXCui** [comment]
就是在bin的同目录下启动的，而且用idea也是报这个错

**Comment by heavyrain2012** [comment]
Idea启动方式在文档中有说明

**Comment by CalvinXCui** [comment]
就是照着那个来的。现在是两个都报上面的错

**Comment by imndx** [comment]
可能是工作目录设置错误

Working directory选择到"broker"目录，Classpath of module选择"moquette-broker"。

**Comment by CalvinXCui** [comment]
嗯嗯，这个设置了，之前启动没问题，我就把maven仓库中的依赖包删除了一下，然后重新下载了一下，然后就报这个错了。重新下载后我看了，依赖的jar包下载全了
