### ISSUE TITLE
有没有撤回时间限制的相关配置

### ISSUE THREAD

**Issue by CalvinXCui** [wildfirechat/server#243]
有没有撤回时间限制的相关配置

**Comment by heavyrain2012** [comment]
客户端决定的，可以自己来修改

**Comment by heavyrain2012** [comment]
客户端代码决定撤回菜单的显示，默认是1分钟。服务器已经加上了撤回的配置，默认是5分钟。这两个配置都可以修改，只要客户端的时间小于服务器的配置。
