### ISSUE TITLE
试用专业版0.39 使用频道的时候不是频道所有者发送的消息能被所有人接收

### ISSUE THREAD

**Issue by zengxiang1** [wildfirechat/server#246]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象 
A 、B、C同时收听D创建的一个频道 ， A发送消息给频道   B在频道能看到A发送的消息 ， C不能看到， 

#### 预期结果
A发送消息应该 应该只有D能看到 而B应该不能看到 C也不能看到

#### 补充条件
目前基本上都能发现， 大概有五千用户，版本 0.39

**Comment by heavyrain2012** [comment]
没有看明白问题，请按照issue的小提示，描述操作步骤，现象，和预期正确结果

**Comment by zengxiang1** [comment]
> 没有看明白问题，请按照issue的小提示，描述操作步骤，现象，和预期正确结果

## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明


#### 表现现象 
A 、B、C同时收听D创建的一个频道 ， A发送消息给频道   B在频道能看到A发送的消息 ， C不能看到， 

#### 预期结果
A发送消息应该 应该只有D能看到 而B应该不能看到 C也不能看到

#### 补充条件
目前基本上都能发现， 大概有五千用户，版本 0.39

**Comment by heavyrain2012** [comment]
请 api version 看一下git commit id和编译日期
