### ISSUE TITLE
admin接口有修改群组成员上限的接口吗？

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/server#249]
admin接口创建群组有没有设定群成员上限以及有没有修改已有群组成员上限的接口吗？

**Comment by heavyrain2012** [comment]
数据库t_setting表有默认群组上限的配置，可以直接修改，修改后不用重启。

**Comment by xhun2015** [comment]
这个应该是修改全局默认设置把，已创建群组如果直接操作数据库字段 是否会引起异常

**Comment by heavyrain2012** [comment]
社区版直接修改就可以了。专业版的话看一下专业版上的readme
