### ISSUE TITLE
并发测试出错

### ISSUE THREAD

**Issue by laowangnj** [wildfirechat/server#25]
### Expected behavior
3万并发测试，连接成功。
### Actual behavior
Thread Name: Thread Group 1-22745
Sample Start: 2019-06-17 14:42:01 CST
Load time: 2
Connect Time: 0
Latency: 0
Size in bytes: 7
Sent bytes:0
Headers size in bytes: 0
Body size in bytes: 0
Sample Count: 1
Error Count: 1
Data type ("text"|"bin"|""): 
Response code: 500
Response message: Connection null connected failed.

Response headers:

SampleResult fields:
ContentType: 
DataEncoding: null

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

### OS version (e.g. `uname -a`)
Linux localhost.localdomain 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by heavyrain2012** [comment]
请根据[链接](http://docs.wildfirechat.cn/server/benchmark.html)  进行测试，特别是要注意到
***部署IM服务和应用服务，部署到同一台服务器上，注意使用默认的key和默认的端口。***

另外要使用客户端验证服务器部署成功。

如果还是出现无法连接问题，请点击jmeter右上角黄色三角感叹号，copy出日志贴过来供我们分析

**Comment by laowangnj** [comment]
并发测试不需要应用服务？
小规模并发是成功的。

**Comment by heavyrain2012** [comment]
最高并发量能到多少？
另外测试是不是使用linux？最大打开文件数改成了多少？
最后把jmeter和im server的日志贴给我们吧
