### ISSUE TITLE
服务的80端口可以改成其他端口吗？

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/server#250]
服务器上有nginx运行有其他应用，IM完全没必要使用80端口啊

**Comment by heavyrain2012** [comment]
使用80端口能提高网络的连通性，另外还有非技术原因，我们希望用户都能够备案使用，确保在法律监管下运行，防止用在非法和危害社会的地方

**Comment by xhun2015** [comment]
经测试 服务器端修改端口后，客户端也修改端口 能够连通，不知道是否会存在问题，我觉得备案与不备案 非法与不非法 这些通过80端口是不可能限制的，真正要想干坏事的人 你是限制不住的 就像卖刀一样。如果客户就是为了简单集成一个im,也没多少人使用，但就是需要有这个功能，他的第一选择肯定是在现有应用服务器同时搭建im服务 结果必须用80端口，那就必须的重新买台服务器才能用了

**Comment by heavyrain2012** [comment]
会有问题。

**Comment by veryrich** [comment]
强制使用80端口确实不太合理

**Comment by zuoliang0** [comment]
为此我们单独申请了一台物理机，耗费半个多月，唉

**Comment by heavyrain2012** [comment]
安全无小事，希望大家能够理解

**Comment by bookc-man** [comment]
通过nginx 转发的话，服务端可以绕靠80端口的
