### ISSUE TITLE
IM服务器部署到亚马逊出现移动端连接不稳定

### ISSUE THREAD

**Issue by tanxxtarena** [wildfirechat/server#252]
当IM服务器部署到国外做测试时，移动网络（中国移动卡），会出现连接不稳定，或者连接不上的问题，造成消息会重复推送，不实时，乱序等问题，不知道是否有解决方案？

**Comment by heavyrain2012** [comment]
微信搜索公众号 野火IM ，关注后察看历史消息，有篇文章 “移动移不动” 有说明。

**Comment by heavyrain2012** [comment]
可以看看这个帖子 http://www.txrjy.com/thread-1104371-1-3.html

**Comment by tanxxtarena** [comment]
好的，感谢！
