### ISSUE TITLE
提供一个思路

### ISSUE THREAD

**Issue by bxl0608** [wildfirechat/server#253]
您好，我想问一下。有这样一个需求:需要两个聊天列表，一个是已经添加过好友的。一个是私密聊天，想要在超过24小时就不再显示的，可以在私密聊天列表中满足一定条件可以添加到好友列表。这样两种列表该怎么实现呢。能给一个思路吗

**Comment by imndx** [comment]
可以使用不同的会话线路，然后获取会话列表时，只获取对应线路的会话列表。

比如好友聊天等，使用会话线路0；私密聊天，使用会话线路1。

```Conversation.line```
