### ISSUE TITLE
推送问题

### ISSUE THREAD

**Issue by CalvinXCui** [wildfirechat/server#254]
推送可以推送图片和文字相结合的内容吗,以及推送的图片的大小怎么设置~还有就是用户推送和群推送可以参考那个方法

**Comment by heavyrain2012** [comment]
如果是自定义消息，消息encode时填写pushContent，IM服务需要推送时会把pushConent推送到推送服务，在推送服务您可以按照自己的需求来推送。如果是预制消息，也可以修改消息定义，encode时填写pushContent
