### ISSUE TITLE
windows 下 80端口是被系统占用的，一直启动报错说地址已经被占用

### ISSUE THREAD

**Issue by xiaodouyaer** [wildfirechat/server#255]
必须用80端口吗？可以改成其他端口吗？windows下80端口一直被系统占用导致无法启动。我在Centos下部署刚开始也是这个问题，我查了下占用80端口的应用，把它干掉后就启动起来了，但是windows 这个System我干不掉。

**Comment by heavyrain2012** [comment]
不能更换端口，只能用80

**Comment by xiaodouyaer** [comment]
查了一下，把http服务关了之后80端口被释放了
