### ISSUE TITLE
建议：用户在线状态回调希望回调所在包名称或当前登录的包唯一标识

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/server#257]
回调在线状态这个需求也是我提出的，我们现在使用的是融云服务，计划在年底迁移到野火，目前正在做前期对接，后台对接时发现回调状态不包含当前所登录的包信息，希望能拿到这些信息。我们有多个app，用户可以在多个app之间登录。

**Comment by zuoliang0** [comment]
还有一个问题，因为我们现在是逐步迁移，所以涉及到老用户和新用户的过度。我们在测试时发现，获取token的接口就算没有调用过注册也能获取到token，但是无法获取到资料，这样算不算bug？能否提供获取token如果没有注册就先临时注册一个或者获取token返回一个错误码，让应用这边调用一次注册？

**Comment by zuoliang0** [comment]
还有就是缺乏接口安全校验机制，回调过来的消息可能不可信，可能伪造

**Comment by heavyrain2012** [comment]
> 回调在线状态这个需求也是我提出的，我们现在使用的是融云服务，计划在年底迁移到野火，目前正在做前期对接，后台对接时发现回调状态不包含当前所登录的包信息，希望能拿到这些信息。我们有多个app，用户可以在多个app之间登录。

是个很普遍的需求，我们会给加上用户的包名的，请稍等

**Comment by heavyrain2012** [comment]
> 还有一个问题，因为我们现在是逐步迁移，所以涉及到老用户和新用户的过度。我们在测试时发现，获取token的接口就算没有调用过注册也能获取到token，但是无法获取到资料，这样算不算bug？能否提供获取token如果没有注册就先临时注册一个或者获取token返回一个错误码，让应用这边调用一次注册？

野火IM的用户关系是可选内容，整个系统运行不依赖用户关系，只需要用户ID就可以聊天。如果您想确保总是存在用户，可以先检查用户存在与否，如果不存在则去创建一个。

**Comment by heavyrain2012** [comment]
> 还有就是缺乏接口安全校验机制，回调过来的消息可能不可信，可能伪造

我们不是公有部署，可以把所有服务部署到同一个内网，不对外开放，或者对指定服务开放访问权限，可以避免安全问题

**Comment by zuoliang0** [comment]
查看接口文档 没有发现检查是否注册的接口，是否是我遗漏？

**Comment by heavyrain2012** [comment]
> 查看接口文档 没有发现检查是否注册的接口，是否是我遗漏？

获取用户信息接口，如果返回不存在的错误码就是不存在

**Comment by zuoliang0** [comment]
好的，感谢。
请问能否新增一个获取token返回错误码的接口？因为我们除了依赖聊天之外，还需要在线状态同步，这个应该是要求注册的用户才会有回调对吧？
这就让业务这边必须注册，但是新旧系统迁移的时候为了不动数据库表，所以希望能再获取token阶段完成这个步骤。我感觉虽然可以通过获取用户信息接口来判断，但是这样会有2次调用，感觉不是特别好，如果直接能获取到token，没有注册则返回一个错误码，这样再去注册，感觉更合理。
谢谢

**Comment by zuoliang0** [comment]
对了，还有就是我们现在用的融云同步在线状态是可以一次性同步多个用户的状态，估计是有一点点缓冲，然后一次性同步，这样可以减少相互调用的消耗，望采纳。

**Comment by heavyrain2012** [comment]
> 好的，感谢。
> 请问能否新增一个获取token返回错误码的接口？因为我们除了依赖聊天之外，还需要在线状态同步，这个应该是要求注册的用户才会有回调对吧？
> 这就让业务这边必须注册，但是新旧系统迁移的时候为了不动数据库表，所以希望能再获取token阶段完成这个步骤。我感觉虽然可以通过获取用户信息接口来判断，但是这样会有2次调用，感觉不是特别好，如果直接能获取到token，没有注册则返回一个错误码，这样再去注册，感觉更合理。
> 谢谢

我们系统设计的是不依赖用户就能运行，所以这个需求只需要获取token前先查一下用户信息就能解决了，服务器部署在同一个内网，调用一次的代价非常低。

**Comment by heavyrain2012** [comment]
> 对了，还有就是我们现在用的融云同步在线状态是可以一次性同步多个用户的状态，估计是有一点点缓冲，然后一次性同步，这样可以减少相互调用的消耗，望采纳。

容云他们是公有云，跟客户直接可能不在一个网络，调用一次的代价比较大，咱们这个是可以部署在同一个内网的，而且使用http复用，分开调用的代价也是比较低的，改成缓冲并一起发送的意义不大

**Comment by heavyrain2012** [comment]
在线状态通知中已添加包名，请下载最新代码验证

**Comment by zuoliang0** [comment]
> 在线状态通知中已添加包名，请下载最新代码验证

好像还没有更新文档？，我们期待试用稳定版本

**Comment by heavyrain2012** [comment]
文档已经更新，请检查
