### ISSUE TITLE
野火没办法使用阿里云RDS,因为它不支持MYISAM引擎

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/server#259]
阿里云RDS 会将建表语句中的MYISAM自动转换为InnoDB,导致报如下错误
Message    : Specified key was too long; max key length is 767 bytes
Location   : ./migrate/mysql/V22__add_user_session_token_index.sql (/www/im_server/./migrate/mysql/V22__add_user_session_token_index.sql)
Line       : 1
Statement  : alter table `t_user_session` ADD INDEX `session_token_index` ( `_token` )

**Comment by heavyrain2012** [comment]
请百度一下  Specified key was too long; max key length is 767 bytes
