### ISSUE TITLE
服务器数据库配置修改c3p0-config.xml没效果

### ISSUE THREAD

**Issue by usr80** [wildfirechat/server#26]
distribution-0.22-bundle版本启用mysql出错，没有读取配置文件

**Comment by heavyrain2012** [comment]
请详细阅读文档。
提示：运行分为编译打包后的release包运行，还有使用idea运行。打包后的release运行，要接呀tar.gz包，然后在对应目录执行./bin/wildfirechat.sh 或 bin\wildfirechat.bat。注意一定要在解压的当前目录执行。使用ieda运行faq里有详细说明

**Comment by usr80** [comment]
[服务器数据库配置](http://docs.wildfirechat.cn/server/server_port.html)修改配置不行

**Comment by usr80** [comment]
http://docs.wildfirechat.cn/server/server_config.html

**Comment by usr80** [comment]
[服务器数据库配置1.5.2](http://docs.wildfirechat.cn/server/db_config.html)修改配置不行

**Comment by vnique** [comment]
@usr80 遇到同样的问题，您是证明解决的呢
IDE运行错误如下：
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
