### ISSUE TITLE
您好，请问你们这个IM协议是开源的吗？文档上说移动客户端SDK和demo使用MIT协议开源，以上是开源吗？我们如果需要改协议能够修改吗？

### ISSUE THREAD

**Issue by hfz336** [wildfirechat/server#260]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是毕现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
协议栈是闭源的，SDK层和demo层是开源的。协议是不能修改的，理论上我们预留的接口可以做大部分的二次开发，如果有缺失需要协议修改的需求，可以给我们提由我们修改
