### ISSUE TITLE
移动端创建群，群成员类型全部是普通成员，没有群主BUG

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/server#261]
for (WFCMessage.GroupMember member : memberList) {
            if (member.getMemberId().equals(groupInfo.getOwner())) {
                member = member.toBuilder().setUpdateDt(dt).setCreateDt(dt).setType(ProtoConstants.GroupMemberType.GroupMemberType_Owner).build();
            } else {
                member = member.toBuilder().setUpdateDt(dt).setCreateDt(dt).build();
            }
            groupMembers.put(groupId, member);
            updatedMemberList.add(member);
            dt++;
        }

groupInfo.getOwner() 这个会为空，改后代码
String owner=StringUtil.isNullOrEmpty(groupInfo.getOwner()) ? fromUser : groupInfo.getOwner();
        for (WFCMessage.GroupMember member : memberList) {
            if (member.getMemberId().equals(owner)) {
                member = member.toBuilder().setUpdateDt(dt).setCreateDt(dt).setType(ProtoConstants.GroupMemberType.GroupMemberType_Owner).build();
            } else {
                member = member.toBuilder().setUpdateDt(dt).setCreateDt(dt).build();
            }
            groupMembers.put(groupId, member);
            updatedMemberList.add(member);
            dt++;
        }

**Comment by heavyrain2012** [comment]
确实是个问题，非常感谢您提供的信息，我们已经修改，请参考我们的修改
