### ISSUE TITLE
撤回消息加急问题

### ISSUE THREAD

**Issue by h3846668** [wildfirechat/server#263]
![image](https://user-images.githubusercontent.com/50538079/91956932-f0f82580-ed37-11ea-9972-fd068670d603.png)

**Comment by h3846668** [comment]
JSONObject json = new JSONObject();
            json.put("s", message.getFromUser());
            json.put("ts", message.getServerTimestamp());
            json.put("t", message.getContent().getType());
            json.put("sc", message.getContent().getSearchableContent());
            json.put("c", message.getContent().getContent());
            json.put("e", message.getContent().getExtra());
            String recalledContent = json.toJSONString();

            message = message.toBuilder().setContent(message.getContent().toBuilder().setContent(operatorId).setType(80).clearSearchableContent().setData(ByteString.copyFrom(String.valueOf(messageUid).getBytes())).setExtra(recalledContent).build()).build();
            messageBundle.setMessage(message);
            messageBundle.setFromClientId(clientId);

            databaseStore.deleteMessage(messageUid);

            mIMap.put(messageUid, messageBundle, 7, TimeUnit.DAYS);

为什么数据删除了，当我执行完这一段代码之后数据又添加了一条新的

**Comment by heavyrain2012** [comment]
我们不建议客户自己修改，如果有需求可以给我们提需求，我们无法提供代码的讲解。

**Comment by h3846668** [comment]
@heavyrain2012 能不能增加一个在群聊天跟个人聊天的时候一键撤回的操作，就是一下把自己的消息全部撤回，而不是一条一条的撤回

**Comment by heavyrain2012** [comment]
我们不能在demo上加这个功能，因为这个功能不是常用功能，需要您自己来进行定制，可以在UI上触发撤回，然后查找被撤回用户的消息，逐个的进行撤回。需要注意撤回只能是一条一条的进行，如果撤回内容太多，可能会导致请求超频等问题，建议一次不要撤回太多
