### ISSUE TITLE
互加好友，会导致双方好友请求记录消失

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#264]
操作说明
用户A和用户B，先后通过搜索账号给对方发送好友请求，但不点击同意

操作与现象
1、用户A与用户B不是好友，A搜索B并发送好友请求
2、用户B收到了A的好友请求，但不点同意
3、用户B搜索用户A并发送好友请求
4、此时用户A和用户B都去刷新自己的好友请求列表，A的账号中没有B的请求记录；B的账号中也没有A的请求记录

预期结果
双方都能看到对方的请求，先点击同意的一方提示添加好友成功。之后对方刷新请求列表时，请求状态可以被服务器同步为“已添加”，或者手动点击同意后，更新为已添加。

demo对比结果（demo版本：iOS 1.1.1）
1、用户A与用户B不是好友，A搜索B并发送好友请求。
2、用户B收到了A的好友请求，但不点同意。
3、用户B搜索用户A并发送好友请求。
4、此时用户A和用户B都去刷新自己的好友请求列表，A的账号**有**B的请求记录；B的账号中刚才收到的那条请求记录**消失了**。

**Comment by heavyrain2012** [comment]
问题已经修正，请更新IM服务和客户的SDK进行验证
