### ISSUE TITLE
拉取与好友通话记录，显示通话的状态不对

### ISSUE THREAD

**Issue by amumuku** [wildfirechat/server#266]
## 提issue小提示

换账户/手机登录后，拉取与好友音视频的通话记录，

#### 表现现象
消息页拉取的通话状态错误，ios只显示为【通话时长】， 
#### 预期结果
预期通话状态应该是对方已取消，对方已拒绝等
#### 补充条件
毕现的，anriod也有这样的问题

**Comment by heavyrain2012** [comment]
通话记录是通话时根据当时的状态来更改的状态，从历史消息拉取的消息，无法还原当时的状态，只能知道发生过通话请求
