### ISSUE TITLE
社区版扩展禁言功能疑问

### ISSUE THREAD

**Issue by amumuku** [wildfirechat/server#267]
场景：我们想扩展一个禁言的功能，
问题表现：遇到这个问题看应用的消息文件里面里面有这样一段注释 
/ Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wfcmessage_community.proto
求解：wfcmessage_community.proto 这个文件是怎么生成的，哪里可以可以看到？

**Comment by heavyrain2012** [comment]
协议是闭源的，无法修改，我们也不建议修改IM服务，因为一旦修改了就跟我们的分支分裂了。关于所有的定制和二次开发都可以在应用服务和客户端应用层进行，比如禁言状态保存到应用服务，然后发言前检查允许发言状态等方法来实现，也可以购买专业版，专业版支持。
