### ISSUE TITLE
SDK更新,好友删除功能无法使用

### ISSUE THREAD

**Issue by qq306993208** [wildfirechat/server#268]
场景：使用api 去做好友删除功能
问题：更新最新的专业版SDK和server以后，调用好友设置有问题，无法删除好友
调用函数：RelationAdmin.setUserFriend(String userId, String targetId, boolean isFriend, String extra)
参数： userId, targetId, false, null 
返回结果：{“code”:"23","msg":"already friends"}

注释：接口在我们更新server 服务之前，是可以的，更新以后，添加好友功能没有问题，主要在删除，一直显示已经是好友了

**Comment by heavyrain2012** [comment]
server的问题，已经修改，如果是专业版请发邮件给我们要一下专业版版本
