### ISSUE TITLE
在server 配置为不拉取历史消息时，希望当重装APP后，控制不同步时限之外的会话列表

### ISSUE THREAD

**Issue by lbyjwwyqt** [wildfirechat/server#271]
当 server 配置了不拉取历史消息时  配置如下：
message.roaming 0
message.compensate_time_limit 300000
message.remote_history_message 0
message.remote_history_message_time_limit -1

希望能够增加控制同步会话列表开关，当重装APP第一次登录后，不同步时限之外的会话列表。

**Comment by heavyrain2012** [comment]
已解决
