### ISSUE TITLE
社区版，使用安卓手机发送mp4文件,有些文件无法发出

### ISSUE THREAD

**Issue by qulijun** [wildfirechat/server#273]
后台确认,视频文件已上传到服务器,只是聊天界面出现红色叹号
错误截图http://182.92.179.133/fs/1/2020/09/22/09/1206498111073472513-1-1600736898-chpDAGK3_146Screenshot_2020-09-22-09-07-04-392_com.guanyun.nfw.yunxin_v2.jpg

上传的视频地址http://182.92.179.133/fs/3/2020/09/22/09/1206498111073472513-3-1600736456-oL6Ncjv5_wx_camera_1598180183927.mp4

查看日志，上传视频分三步
1.execute handler for topic GMUT， GetMediaUploadTokenHandler,成功
2.com.xiaoleilu.loServer.action.UploadFileAction,上传文件,能够成功
3.io.moquette.imhandler.SendMessageHandler,execute handler for topic MS,发不出去消息

通过比较发送成功和失败的情况,发现第3步有差别
失败时,不发消息

成功时发送的消息体
conversation {
  type: 0
  target: "1280688436075180034"
  line: 0
}
from_user: "1206498111073472513"
content {
  type: 6
  searchable_content: "[\350\247\206\351\242\221]"
  data: ""省略
  mediaType: 3
  remoteMediaUrl: "http://182.92.179.133/fs/3/2020/09/22/11/1206498111073472513-3-1600743958-YxJ0Wadl_1600650972389.mp4"
  persist_flag: 3
}

**Comment by imndx** [comment]
可能是缩略图太大了，请提供Android端日志看下。
