### ISSUE TITLE
社区版集成阿里云OSS的问题

### ISSUE THREAD

**Issue by dongfangweiyu** [wildfirechat/server#274]
社区版的IM Server只支持内置存储和七牛存储。
由于不能去修改IM Server的代码，现在又需要使用阿里云OSS去发送图片和语音视频消息。
请问一下APP该如何实现？

我说下我的思路帮我看看对不对。

APP直接调用OSS上传获得URL，然后在发送的时候把URL带上。接收方读取URL显示。

在当前提供的android sdk和ios sdk中能有办法实现吗？

**Comment by dongfangweiyu** [comment]
看到代码里面有个byteContent字段，发送图片的时候是把图片转成byte，然后存入数据库了吗？

**Comment by heavyrain2012** [comment]
1，可以考虑专业版，专业版支持阿里云和私有对象存储服务。
2，也可以在app层做，先上传，然后把url放到消息的remoteUrl中，直接发送就好了。

byteContent这个一般是用来缩略图的，直接存放到数据库中，大小不能超过7K

**Comment by dongfangweiyu** [comment]
非常感谢您的解答。@heavyrain2012
