### ISSUE TITLE
群成员分别查看各自的群消息,莫名多出一个消息记录,时间也不同

### ISSUE THREAD

**Issue by qulijun** [wildfirechat/server#275]
群成员分别查看各自的群消息,莫名多出来一个消息,时间也不同
截图http://182.92.179.133/fs/1/2020/09/22/17/1206498111073472513-1-1600768298-blIa4xLf_mmexport1600768272411.png

**Comment by heavyrain2012** [comment]
图中1，3和最后一台手机多收到一条群名片消息，时间还都是不同的，而其它手机没有收到这条消息。可能是使用了群定向消息，可以在群里发送消息填写定向接受人，这样在群里只有目标用户会收到，其他人收不到，请确认发送消息时，toUser是否填写了
