### ISSUE TITLE
集成推送时候的问题，安卓端收不到推送。

### ISSUE THREAD

**Issue by dongfangweiyu** [wildfirechat/server#276]
android给ios端发送消息时没有问题：
![0](https://user-images.githubusercontent.com/43637779/93868366-edcfd400-fcfc-11ea-8aa3-33a515c8fc56.png)

但是ios给android端发消息时提示device token不存在
![1](https://user-images.githubusercontent.com/43637779/93868163-a8130b80-fcfc-11ea-8f52-dc349e3a38d5.png)
然后看了数据库t_user_session表发现_token和_viop_token两个字段没有值。
![2](https://user-images.githubusercontent.com/43637779/93868541-28397100-fcfd-11ea-9307-f06c24b37084.png)

**Comment by dongfangweiyu** [comment]
android和ios端互发消息又是没有任何问题的。
但是杀进程测试推送的时候又出现这个问题，这是怎么回事？应该怎么解决？

**Comment by heavyrain2012** [comment]
token是客户端上传的，检查一下客户端setDeviceToken的方法是不是没有被调用
