### ISSUE TITLE
社区版,聊天上传视频,上传图片,是如何生成缩略图的

### ISSUE THREAD

**Issue by qulijun** [wildfirechat/server#277]
社区版
1.上传视频和图片时,缩略图是在哪里(手机端还是服务器)生成的?
2.如何发送给对方?在消息数据的data中吗?
3.生成的缩略图尺寸是否可以修改?

**Comment by heavyrain2012** [comment]
缩略图是客户端生成的。客户端图片消息的encode/decode有数据转换处理，缩略图是存放到binaryData字段的。客户端可以修改缩略图大小，但大小不能超过7K，超过久无法发送。

如果觉得缩略图不清楚，可以使用这种策略，在wifi下自动下载大图，等下载完成后显示大图。
