### ISSUE TITLE
[建议] 可不可以在server中的sendMessage接口中加一个中间层，以便控制用户是否可以发送消息

### ISSUE THREAD

**Issue by jeryfer** [wildfirechat/server#279]
理论上目前如果开启陌生人聊天模式，通过逆向APP，加hook，可以向所有用户发送消息

**Comment by heavyrain2012** [comment]
服务器端有配置，是否允许陌生人聊天，如果禁止陌生人聊天的话陌生人就不能聊天了。一般情况下需要确保用户ID不能被穷举，这样危害就小很多了，另外就是要做监管，发现及时处理。

**Comment by jeryfer** [comment]
当需求就是允许陌生人聊天，用户ID被暴力穷举也没办法啊，而且目前用户ID的位数比较短，我的建议是可以加个接口层，控制发消息

**Comment by heavyrain2012** [comment]
我们综合考虑了一下，觉得加这个不合适，如果您有这方面的需求可以看看有没有什么曲线的办法可以解决，如果没有就需要您自己来添加了。谢谢您提的建议！
