### ISSUE TITLE
新增群成员GroupAdmin接口

### ISSUE THREAD

**Issue by wenbin1990** [wildfirechat/server#28]
请求参数有一项是群成员id的list集合，为什么不直接传群成员对象集合。server端目前处理时是遍历群成员id的list集合，然后不断新增群成员对象，不做其他特殊处理，这个操作可以由应用服务器或客户端来处理

**Comment by heavyrain2012** [comment]
为了保持跟端上一只，新增成员都是普通成员，请先新增，再进行角色分配
