### ISSUE TITLE
社区版,发视频文件,大于100m发送失败,如何解决

### ISSUE THREAD

**Issue by qulijun** [wildfirechat/server#283]
社区版,发视频文件,大于100m发送失败,如何解决
发送大于100m的视频文件,发送失败,调试显示 上传请求地址是/bad-request
发送小于100m的视频文件,发送成功,调试显示 上传请求地址是/fs

**Comment by heavyrain2012** [comment]
请检查 https://mp.weixin.qq.com/s/Qqv1IIk3hDj7lc8rMzyRAQ
