### ISSUE TITLE
群主设置群成员昵称功能

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#284]
建议野火增加群主可以设置其他群成员的群昵称的功能。
群主或者群管理员可在群组的“...”中，给每一个群成员设置在当前群的群昵称，群成员自己可以并且只可以修改自己的群昵称；
如果群主或者管理员或者成员自己都修改群昵称，则可按照修改的时间顺序，新的群昵称覆盖老的群昵称即可。

**Comment by heavyrain2012** [comment]
功能已添加，请更新IM服务和客户端，客户端中增加了 modifyGroupMemberAlias 接口，使用这个接口群主修改群成员昵称。注意需要同时升级服务器和客户端。
