### ISSUE TITLE
社区版,安卓系统上传文件,文件名含空格被截断,导致上传的文件后缀名丢失

### ISSUE THREAD

**Issue by qulijun** [wildfirechat/server#285]
安卓系统上传的文件含有空格,上传到服务器的文件名在空格前被截断,文件后缀丢失,被指定为默认的.octetstream类型的文件
例如:
原始安卓手机上文件名:this is a picture.jpg
上传到服务器后文件名:this.octetstream

**Comment by heavyrain2012** [comment]
SDK用的是最新的吗？还有对象存储服务用的是七牛吗，内置的对象存储服务功能不完善仅仅建议用在开发测试环境

**Comment by qulijun** [comment]
SDK不是最新,未用对象存储服务,用的内置对象存储
