### ISSUE TITLE
拉取历史消息bug

### ISSUE THREAD

**Issue by haitun521** [wildfirechat/server#288]
![image](https://user-images.githubusercontent.com/9667904/96217662-a8c65700-0fb5-11eb-8639-dba45255500e.png)
假如 2 个人私聊，在 8 月份聊了 100 条消息，10 月份聊了 100 条消息，中间 9 月份没有 产生任何消息，现在拉取历史消息的时候，就会出现无法拉取 8 月份的消息

**Comment by heavyrain2012** [comment]
已更新，请检查

**Comment by haitun521** [comment]
确实解决了，不过提个优化的点，假如已经获取到最早的消息了，再去拉取会多空跑 24 次 SQL

**Comment by haitun521** [comment]
![image](https://user-images.githubusercontent.com/9667904/96949610-da41a400-151a-11eb-9cc0-fd5a3c905754.png)
nextTable的值没有变，会一直重复

**Comment by haitun521** [comment]
![image](https://user-images.githubusercontent.com/9667904/96949717-2a206b00-151b-11eb-8045-3ef9d7c1d86a.png)
nextTablede 的值没有变，一直在重复

**Comment by heavyrain2012** [comment]
不好意思，确实是我们的失误，已经更新，请更新验证。

另外如果读取24次db也是没有办法的时间，可能两个用户之前从来没有聊过，也可以他们2年前聊过，需要遍历每个月的数据
