### ISSUE TITLE
离线消息丢失

### ISSUE THREAD

**Issue by nineveh** [wildfirechat/server#289]
## 提issue小提示
离线消息设置成1024 当离线消息超过1024导致其它会话消息丢失
#### 操作说明
长时间不上线消息堆积超过1024
#### 表现现象
最早的一条消息丢失
#### 预期结果
按照会话，进行离线消息存储，不会因为某个会话，过多消息而导致其它会话消息丢失
#### 补充条件
是必现，当消息超过最大离线消息数量最早的丢失
#### demo对比结果
丢失

**Comment by heavyrain2012** [comment]
是的，这个问题是存在的，因为服务器不可能无限多，总会有个度的。这个值可以适当调大，但会占用更多内存，专业版表现会更好一些。

**Comment by nineveh** [comment]
可以按照用户会话存储吗

**Comment by heavyrain2012** [comment]
不支持
