### ISSUE TITLE
t_message_xxx表_mid重复

### ISSUE THREAD

**Issue by nineveh** [wildfirechat/server#292]
#### 操作说明
同一个_mid有两个消息，导致没有进入该群的用户收到了群里的一条消息

![image](https://user-images.githubusercontent.com/5669553/97286453-7999ca80-187e-11eb-8216-363f6de10733.png)

**Comment by heavyrain2012** [comment]
服务器有没有更新到最新版本

**Comment by nineveh** [comment]
版本4.6~

**Comment by heavyrain2012** [comment]
这个问题我们复现出来了，引入的原因是跟专业版同步代码时同步丢了，已经解决了，请更新的0.47版本验证，感谢您提供的信息！

**Comment by nineveh** [comment]
我更新下
