### ISSUE TITLE
新设备同步会话列表求教

### ISSUE THREAD

**Issue by youqbTn** [wildfirechat/server#293]
请教一下在“不接收历史消息”和“不开启拉取远程历史消息”的情况下。
新设备登录（或清缓存和数据后重新登录）客户端可以重建部分会话列表，如：Android端通过 mClient.getConversationList(intypes, inlines)获取会话列表。
请问一下社区版本Server是否支持自己控制客户端getConversationList逻辑，如果可以是否可以告知一下Server端修改逻辑。非常感谢!

**Comment by heavyrain2012** [comment]
这部分社区版和专业版逻辑是一致的，需要靠IM服务配置文件的对应开关来控制。

**Comment by youqbTn** [comment]
好的,开关逻辑是很清晰的，但逻辑上在“不接收历史消息”和“不开启拉取远程历史消息”的情况下，移动端只能通过mClient.getConversationList(intypes, inlines)来重建部分会话列表， 但个人在Server端未找到mClient.getConversationList(intypes, inlines)相关处理逻辑。能否告知一下Server端处理mClient.getConversationList(intypes, inlines)的处理类或处理逻辑呢？感谢！
