### ISSUE TITLE
加入群聊审核及对应开关

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#294]
是否可以增加入群审核该功能开关的功能：
支持入群申请需要群主或管理员审核通过，以及不需要审核直接入群的功能（需要支持审核与不审核开关），具体包括：
1、审核开关
2、入群方式为邀请入群和自主扫描群二维码加群的两种类型的审核提醒消息，提示群主或管理员入群方式、邀请人、申请人；
3、群主和管理员进入审核页面进行入群确认。
4、审核开关关闭时，邀请和扫码入群直接加入群聊，不需要审核提醒，不需要审核。

**Comment by heavyrain2012** [comment]
请参考 https://docs.wildfirechat.cn/blogs/加群验证功能.html
