### ISSUE TITLE
安卓登录成功后不久主页面循环提示"连接失败",后台日志显示客户端一直在请求route接口

### ISSUE THREAD

**Issue by 80sAzhong** [wildfirechat/server#295]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
登录成功后，进入主页面在拉取好友信息和消息列表时主页面空白上方一直闪烁"连接失败"
#### 表现现象
拉取不到好友列表和消息记录，个人信息也只是显示用户ID，没有头像。主页面上方一直闪烁"连接失败"。后台日志显示一直在调用/route这个路径

#### 预期结果
登录成功，拉取好友列表，个人信息，消息列表

#### 补充条件
不是最新版

#### demo对比结果
请用demo对比测试，demo上是连接成功后拉取消息列表和好友列表以及个人信息

**Comment by imndx** [comment]
请参考[Android抓取日志](https://docs.wildfirechat.cn/faq/android/q3.html)，给我们提供一下日志。

**Comment by heavyrain2012** [comment]
文档常见问题，有个连接不上的说明，请先按照那个排除问题
