### ISSUE TITLE
群聊系统消息，部分成员可见（例如：定向群管理员可见）

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#298]
入群审核开启，入群申请发送时，系统需要向群管理员角色的用户单独发送一条消息。

这个需求功能点希望野火能够尽快发布

**Comment by heavyrain2012** [comment]
server api发送消息时可以加上目标用户的参数，这个参数在MessageAdmin中的接口中没有，现在已经加上了，请更新社区版到最新编译，用其中的SDK库就可以了

**Comment by heavyrain2012** [comment]
请参考提交 https://github.com/wildfirechat/server/commit/9c57a620c9fffe54508979974ee0034eeffa6f92 和 https://github.com/wildfirechat/server/commit/7f6b2d93df5fb7aa797652959f1caa38d7225793
