### ISSUE TITLE
/admin/message/send 发送信息接口问题

### ISSUE THREAD

**Issue by zdmisif** [wildfirechat/server#3]
2019-04-26 10:47:29
[INFO]-[Thread: main]-[HttpUtils.httpJsonPost()]: http request content: {"sender":"z_zazaaa","conv":{"type":2,"target":"chatroom1"},"payload":{"type":1,"content":"你好"}}

2019-04-26 10:47:29
[INFO]-[Thread: main]-[HttpUtils.httpJsonPost()]: http request response content: 

返回的数据为空，而且发送信息，在对应的前端聊天室没有显示，感觉是发送不成功

**Comment by heavyrain2012** [comment]
最新版本已经解决，请验证

**Comment by zdmisif** [comment]
可以了~
