### ISSUE TITLE
mqtt 协议版本的区别

### ISSUE THREAD

**Issue by oawang** [wildfirechat/server#300]
请问下，mqtt 协议版本的区别，MQTT_3_1_1，Wildfire_1，Wildfire_2

**Comment by oawang** [comment]
ProtocolProcessor  - The connection has been configured CId=1a1bcbcf2a4c09c01605075760809, keepAlive=300, cleanSession=true, idleTime=450, cleanSession设置为true，会不会导致断连消息丢失

**Comment by heavyrain2012** [comment]
野火协议是基于MQTT协议修改的，改动比较大，已经无法兼容标准的MQTT协议了
