### ISSUE TITLE
在登录时，发现离线消息特别多时，非常卡

### ISSUE THREAD

**Issue by XavierZeng** [wildfirechat/server#301]
现在系统不管是首次登录，还是在线获取消息都通过接口MP到服务器获取的。

能不能首次登录与在线获取消息分开（或者加标记区分，登录同步还是在线获取消息），首次登录时，只拿个人消息，不取群消息。而在线收消息就拿所有的

**Comment by heavyrain2012** [comment]
现在的实现机制无法做到。可以想办法来优化收取消息的体验，目前收消息是批量收取的，可以等全部收完了统一刷新一次，不能每条消息都去刷新UI。可以用我们demo对比一下

**Comment by XavierZeng** [comment]
那怎么判断已经收完了呢？ proto提供的方法，getMessages 只拿到了消息的列表，没有办法判断是否已经收完了

**Comment by heavyrain2012** [comment]
可以看连接状态，只有全部收完后才会变成connected，在状态为receiving时可以不刷新

**Comment by oawang** [comment]
mark
