### ISSUE TITLE
隔一段时间未登录，离线消息比较多时（如2000条)，同步数据时连接登录多次

### ISSUE THREAD

**Issue by XavierZeng** [wildfirechat/server#302]
隔一段时间未登录，离线消息比较多时（如2000条)，登录成功后，进入同步数据，数据多时间一慢，就出现重复连接登录多次？前几次正在同步数据被中断，导致这部分数据本地没有入库

**Comment by heavyrain2012** [comment]
那个端？用demo对比了吗？

**Comment by XavierZeng** [comment]
现在发现是android

**Comment by XavierZeng** [comment]
现在比对的app, proto版本，获取消息，渲染界都是一样的，还有那些地方对比吗？

**Comment by imndx** [comment]
> 现在比对的app, proto版本，获取消息，渲染界都是一样的，还有那些地方对比吗？

意思是对比下我们的demo有无这个现象

**Comment by XavierZeng** [comment]
1.你信的demo 偶尔也会
2.同时也发现另外一个问题：当离线消息（比例：500条），一连接成功，立刻收到了一个最新消息通过，获取了最新的消息，旧的消息不会拿了

**Comment by heavyrain2012** [comment]
不明白您说的现象，请按照issue模版提供信息，如有必要可以补充录像和日志，谢谢
