### ISSUE TITLE
demo测试，如果几百人群在同时发消息，大家都收不到消息了，停下来后，消息一并出来

### ISSUE THREAD

**Issue by XavierZeng** [wildfirechat/server#304]
demo测试，模拟几百人群在同时发消息，大家都收不到消息了，停下来后，消息一并出来

**Comment by heavyrain2012** [comment]
您好，请明确测试条件，在什么样的机器配置下，群的人数是多少，每秒钟向群中发送的消息数是多少？猜测是机器性能不够，可以提高机器性能或者更换专业版

**Comment by XavierZeng** [comment]
资源是够，只有一个群，5个人，就是用一个for 循环，只要消息间隔很短，就会出现这个问题

**Comment by XavierZeng** [comment]
只是for循环，没有并发呢，如果中间加上消息发出的间隔100毫秒，就能正常了

**Comment by heavyrain2012** [comment]
可能是工作线程被占用了，无法刷新出来。
