### ISSUE TITLE
在会话详情设置显示群成员昵称，返回后未生效

### ISSUE THREAD

**Issue by wl532882877** [wildfirechat/server#306]
## 提issue小提示
在会话详情设置显示群成员昵称，返回后未生效***

#### 操作说明
在首页的消息界面，选择一个群聊，进去之后，选择右上角的头像进入会话详情，滑动列表至最底部，选中或取消 显示群成员昵称，再返回

#### 表现现象
回到聊天界面，群成员的昵称没有显示或关闭

#### 预期结果
群成员的昵称会根据选择显示和隐藏

#### 补充条件
是毕现的 新版

#### demo对比结果
用demo 也是一样的

**Comment by imndx** [comment]
已解决，请参考android-chat。
