### ISSUE TITLE
部分群聊实际人数和t_group表中统计人数不一致，还出现负数

### ISSUE THREAD

**Issue by dannie652107** [wildfirechat/server#309]
部分群聊实际人数和t_group表中统计人数不一致，还出现负数
入群走的是自己写的接口，接口中调用的是AdminHttpUtils

**Comment by heavyrain2012** [comment]
是不是服务器版本太旧，请更新到最新测试

**Comment by dannie652107** [comment]
我这边代码是10月底拉的，
我觉得应该和版本没关系，因为出问题的只是部分群聊，大多数还是正常的

**Comment by heavyrain2012** [comment]
你能想办法帮我们找一下复现路径吗，我们这边没有遇到这个问题，查看代码也没有发现异常，要是能找到复现的方法就好解决了

**Comment by dannie652107** [comment]
复现的话，确实比较困难，我在本地也没有遇到这种情况，我把我们关于群聊的操作描述一下
入群方式：之前拓展了群成员上限限制，入群都是走的接口，然后调用/admin/group/member/add
到期解散：调用的是 GroupAdmin.dismissGroup（）
创建群聊：调用/admin/group/create
客户端的退出和解散没有修改

**Comment by heavyrain2012** [comment]
已经修改了群成员计数的方式，现在改为群关系变动后，在数据库中重新计数成员数，可以避免出现群成员计数问题。请使用0.53版本或以后版本验证
