### ISSUE TITLE
人员头像修改时，T_USER表会新建一条记录

### ISSUE THREAD

**Issue by 14780001553** [wildfirechat/server#310]
人员头像修改时，T_USER表会新建一条记录。原用户信息未被修改。

**Comment by heavyrain2012** [comment]
因为创建和修改是同一个接口，所以修改时一定要把信息带全，特别是userId，name，mobile这三项，一般建议获取用户信息更新某个字段再调用创建/更新接口

**Comment by 14780001553** [comment]
我们是调用的SDK中的更新API接口，APP端的。

**Comment by 14780001553** [comment]
我们现在购买过一套正式的，没有问题，只是我们测试得用社区版的，正式版的给客户做的，不让用。

**Comment by heavyrain2012** [comment]
购买商业版都会额外给测试环境的，问一下负责联系采购的同事吧，如果没有找我们要就可以了。
另外对你说的问题有点儿疑惑，是客户端还是server api调用的，调用的接口是那个，参数是什么

**Comment by 14780001553** [comment]
安卓客户端调用userViewModel.updateUserPortrait(path)

**Comment by heavyrain2012** [comment]
你们是不是改过服务器数据库，请服务器同事在数据库中看一下t_user表的约束。可以命令行进去，use wfchat    后 show create table t_user , 把结果贴给我们

**Comment by 14780001553** [comment]
user_display_name_index	_display_name	NORMAL	0	A	35			0	
user_mobile_index	_mobile	NORMAL	0	A	33			0	
user_email_index	_email	NORMAL	0	A	29			0

**Comment by heavyrain2012** [comment]
已解决
