### ISSUE TITLE
退群通知设置只有管理员和群主可见

### ISSUE THREAD

**Issue by Zyhant** [wildfirechat/server#311]
希望能在服务端可以设置退群通知只有管理员和群主可见

**Comment by heavyrain2012** [comment]
请参考 https://mp.weixin.qq.com/s?__biz=Mzg4MDE3ODEwOA==&mid=2247483925&idx=1&sn=fbc67fa2ca29f2854a4ec97263ff0985&chksm=cf7864c6f80fedd0aef4ea7e4780942499d61bc7fd9e5363c554dc34ac3219506543c620aafa&token=2108136137&lang=zh_CN#rd
