### ISSUE TITLE
请问一下自动加群的逻辑如何做

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#312]
比方说 有人满足了一定的条件，可以自己加入一个隐私的群。  只有管理员才能拉人进去的群怎么处理呢？
   我看Server API接口 有 --添加群组成员--   的接口
是一定要 验证管理员登录了以后才可以拉人进群吗？

我想不经过管理员同意，只要满足一定条件就可以进群怎么操作呢？比方说我冲了300块钱，就直接进群

**Comment by mankind-evolve** [comment]
只有管理员才能拉人进去的群

**Comment by heavyrain2012** [comment]
你需要有个业务服务，在这个服务上做出选择，当决定要加人时，调用server api加群就可以了，可以参考 https://docs.wildfirechat.cn/blogs/加群验证功能.html

**Comment by mankind-evolve** [comment]
我不太明白的是 文档里面说的 appserver  是不是Server API接口

**Comment by heavyrain2012** [comment]
appserver是你们的业务服务，用来做出加群操作的，它会调用server api进行加群。

**Comment by mankind-evolve** [comment]
是不是用appserver请求server api获取群创建者的token，然后拿到token再去请求server api去拉人呢？
还是能直接跳过拿token的过程，直接去请求server api  --添加群组成员-- 的接口 去加人？

**Comment by heavyrain2012** [comment]
server api有接口可以直接加群，server api拥有最高权限，可以无条件加，需要在应用服务（或其它任何业务服务）来做好逻辑判断，比如用户充值了300元，调用serverapi把用户加入到群中，没有所谓的token
