### ISSUE TITLE
服务端发送消息接口能否给指定用户的指定端发送消息？

### ISSUE THREAD

**Issue by TaroFang** [wildfirechat/server#313]
应用后台调用发送消息接口 MessageAdmin.sendMessage 
目前只能向指定用户所有端推送自定义消息

能否新增向用户的指定客户端（andorid/ios/mac/win）推送自定义消息

**Comment by heavyrain2012** [comment]
请问是什么场景下需要这个功能

**Comment by TaroFang** [comment]
目前已在前端处理
