### ISSUE TITLE
发起好友请求添加一个扩展字段

### ISSUE THREAD

**Issue by dannie652107** [wildfirechat/server#314]
好友申请表，以及相应的SDK等地方能否添加一个扩展字段，方便业务拓展

**Comment by heavyrain2012** [comment]
能简单讲一下做什么用吗

**Comment by dannie652107** [comment]
完成一个添加好友时的回复功能，区分是发起方或者接受方
1.实现发起方申请列表能看到回复内容
2.同意/拒绝只能由接受方操作
3.假设删除好友后又不影响两者重新添加好友申请

**Comment by heavyrain2012** [comment]
> 完成一个添加好友时的回复功能，区分是发起方或者接受方
> 1.实现发起方申请列表能看到回复内容
> 2.同意/拒绝只能由接受方操作
> 3.假设删除好友后又不影响两者重新添加好友申请

2，3都没有问题，现在本来就是这样的。1的话需要参考 https://docs.wildfirechat.cn/faq/general.html 问题32来实现

**Comment by heavyrain2012** [comment]
好友请求添加了extra字段，请更新最新代码验证
