### ISSUE TITLE
异常卡顿，无法连接服务器

### ISSUE THREAD

**Issue by bxl0608** [wildfirechat/server#315]
一段时间内异常卡顿
机器配置:
centos7.6
12C 24G 500GB SSD 
server和mysql在同一台服务器
 IO写次数暴增
已拉出日志。
[日志.txt](https://github.com/wildfirechat/server/files/5695699/default.txt)

**Comment by bxl0608** [comment]
平均在线人数在2000

**Comment by heavyrain2012** [comment]
有几点可以优化的点，第一个启动脚本里有没有设置最大内存，如果没有设置会使用非常少的内存，导致患存数据太少会频繁读取数据库。第二个数据库有没有做优化，需要做一些调优，调大缓存大小，优化其它选项。注意调整内存大小时不能超过最大物理内存限制需要给操作系统保留内存。

**Comment by heavyrain2012** [comment]
如果这两点都没有作用，可以加微信 wildfirechat 咱们一起查一下

**Comment by bxl0608** [comment]
> 有几点可以优化的点，第一个启动脚本里有没有设置最大内存，如果没有设置会使用非常少的内存，导致患存数据太少会频繁读取数据库。第二个数据库有没有做优化，需要做一些调优，调大缓存大小，优化其它选项。注意调整内存大小时不能超过最大物理内存限制需要给操作系统保留内存。

启动脚本设置 xms xmx 都为6G。 数据库方面没有进行过多的调整，设置了事务log写回的次数为1000
