### ISSUE TITLE
会话的免打扰设置，缓存userConvSlientMap设计问题

### ISSUE THREAD

**Issue by sage-47** [wildfirechat/server#316]
#### 表现现象
代码中该map用于缓存用户在会话维度的免打扰设置：ConcurrentHashMap<String, Boolean>；
但在3024行以及getUserConversationSilent()方法中可以看到，查询和操作的key并不相同；
操作时key = userId， 查询时key = userId|conversation.getType()|conversation.getTarget()|conversation.getLine();

#### 预期结果
建议优化map结构，使用ConcurrentHashMap<String, Set<String>> (考虑到一个userId不太会存在高频并发操作，set应该足够，或者牺牲性能保证并发安全)，或者直接去掉无用的缓存；

**Comment by heavyrain2012** [comment]
确实是有问题，这个缓存实际上没有生效。已经修正，请检查 https://github.com/wildfirechat/server/commit/c63cc740280123b789985564713fade365996d61 。实际上这个缓存意义不大，因为设置本身也在缓存中，不过已经这样了，还是修改好吧。谢谢您提供的信息
