### ISSUE TITLE
如何在IMServer双向删除聊天记录

### ISSUE THREAD

**Issue by DuJieJerry** [wildfirechat/server#317]
在IM Server服务中，如果要实现把用户好友双方的聊天记录删除，该如何实现？
目前野火IM是否有实现该功能？或者之后的迭代中是否有计划实现该功能？

**Comment by heavyrain2012** [comment]
目前还没有删除消息的功能，预计春节之后我们会评估是否开发删除功能

**Comment by 0230826** [comment]
我也正想在此基础上开发阅后即焚的功能，聊天记录销毁时间由运营方自己设置。

**Comment by heavyrain2012** [comment]
专业版是有server api来双向删除的
