### ISSUE TITLE
希望能在专业版上提供消息会话置顶功能相应的server api

### ISSUE THREAD

**Issue by lbyjwwyqt147** [wildfirechat/server#321]
#### 预期结果
目前有2个端 app端和web端，某些特定的消息会话需要在2个端同步置顶，现在情况是如果APP端本地置顶了不能同步到web端，所以希望能够通过服务器端server api来设置消息会话置顶和取消置顶功能

**Comment by heavyrain2012** [comment]
已经添加，请联系我们更新服务
