### ISSUE TITLE
服务端能否控制断开指定客户端长连接？

### ISSUE THREAD

**Issue by TaroFang** [wildfirechat/server#324]
## 使用场景
服务端调用 SDK中的 API，传入登录时签发的 token， 断开指定客户端的长连接

**Comment by heavyrain2012** [comment]
应用的场景是什么，方便描述一下业务需求吗

**Comment by TaroFang** [comment]
IM 的 token 签发时间超过一定阀值时，自动踢下线，强制用户重新登录，IM 服务则需将其要踢下线。

**Comment by heavyrain2012** [comment]
已经添加请更新最新服务器
