### ISSUE TITLE
通过Server api的addGroupMembers接口拉人进群 被拉取人在聊天界面偶尔不显示群会话

### ISSUE THREAD

**Issue by charlesbabyxu** [wildfirechat/server#327]
通过Server api的addGroupMembers接口拉人进群 被拉取人在聊天界面偶尔不显示群会话
app日志观测到的现象：
1、105提示信息收到
2、拉取会话列表信息少一条
3、被拉进群的人聊天菜单不显示群会话

server 端日志：
MP topic显示拉取一条消息

**Comment by heavyrain2012** [comment]
我们测试了一下，在收到消息时，立即获取会话列表，新会话是存在的。请确认是不是你们对会话列表有过滤，是不是没有群组信息就过滤掉了？如果不是这个原因，请把服务更新到最新测试看看，另外Server api的addGroupMembers方法notifyContent是空吗
