### ISSUE TITLE
websocket 8083 端口未启动

### ISSUE THREAD

**Issue by yuedefeng** [wildfirechat/server#328]
/opt/im-server # netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:44565        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      10/java
tcp        0      0 0.0.0.0:18080           0.0.0.0:*               LISTEN      10/java
tcp        0      0 0.0.0.0:5701            0.0.0.0:*               LISTEN      10/java
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      10/java

**Comment by yuedefeng** [comment]
pc-chat 扫描后登录不成功，返回 connection status changed -6， 是否因为 8083 接口未启动的原因？

**Comment by heavyrain2012** [comment]
pc-chat的sdk是需要收费的，需要购买或者试用才可以使用，请根据 https://docs.wildfirechat.cn/trial/ 申请试用

**Comment by yuedefeng** [comment]
手机扫码后：

connection status changed 0
proto.min.js?026b:70 connection status changed -4
proto.min.js?026b:70 connection status changed -6
proto.min.js?026b:70 connection status changed -4
proto.min.js?026b:70 connection status changed 0
proto.min.js?026b:70 connection status changed -4
LoginPage.vue?c9c6:137 ---------- login {code: 8, message: "会话不存在或已过期", result: null}
LoginPage.v

**Comment by yuedefeng** [comment]
@heavyrain2012 您好，pc-chat的sdk 是 server项目中的代码，还是 vue-pc-chat 项目里的 js 脚本？ 价格从哪里看？

**Comment by imndx** [comment]
> @heavyrain2012 您好，pc-chat的sdk 是 server项目中的代码，还是 vue-pc-chat 项目里的 js 脚本？ 价格从哪里看？

不是的，PC SDK 是```vue-pc-chat```项目下， ```proto_addon ```目录的那几个文件

**Comment by heavyrain2012** [comment]
https://docs.wildfirechat.cn 第六章有pc sdk的价格， pc sdk跟服务器没有关系，是c++写的二进制文件，可以用在vue-pc-chat 或react-pc-chat 中，请按照前面回复中的说明申请试用

**Comment by yuedefeng** [comment]
请问以下问题（确保我的本地打包没问题）：
1、 没有pc sdk, vue-pc-chat 扫描后是登录不上的吗？
2、社区版的 server,  是不启动websocket (8083, 8084) 的吗？

**Comment by heavyrain2012** [comment]
请问以下问题（确保我的本地打包没问题）：
1、 没有pc sdk, vue-pc-chat 扫描后是登录不上的吗？
    是的，pc sdk是收费的，必须由我们提供绑定你们服务器地址的sdk
2、社区版的 server, 是不启动websocket (8083, 8084) 的吗？
    是的，pc sdk是使用的80/1883端口，协议栈基本跟移动端一致，不需要使用websocket端口，可以跟社区版im一起使用

**Comment by yuedefeng** [comment]
1、使用pc sdk需要准备域名，我如果是局域网用服务器的IP（没有域名）可以吗？
2、请问websocket (8083, 8084) 是给哪一端提供服务的？

**Comment by heavyrain2012** [comment]
IP也可以的，ws是给web版本用的，社区版不支持web版本所以没有监听这两个端口
