### ISSUE TITLE
判断两个用户是否是好友，只能通过接口这个吗？能不能提供一个接口可以直接查询的，提高效率。 String Friend_Get_List = "/admin/friend/list";

### ISSUE THREAD

**Issue by huazaihuola** [wildfirechat/server#329]
一个建议：
判断两个用户是否是好友，只能通过接口这个吗？能不能提供一个接口可以直接查询的，提高效率。

 String Friend_Get_List = "/admin/friend/list";
先取出好友列表，再判断当前用户在不在这个列表里面？或者有什么更好的方式我没发现，求指导谢谢！

**Comment by heavyrain2012** [comment]
已添加，https://github.com/wildfirechat/server/commit/9fa13702199f9a738ccb0c2243da303ddce87086  请更新代码验证

**Comment by huazaihuola** [comment]
@heavyrain2012 牛逼兄弟，等我们挣钱了，给你们投资！

**Comment by heavyrain2012** [comment]
你们能够使用得好就是对我们最大的支持啦，祝愿您生意兴隆、财源滚滚～～
