### ISSUE TITLE
当连接增加，app端关于conversation刷新时机问题

### ISSUE THREAD

**Issue by charlesbabyxu** [wildfirechat/server#331]
邀请别人加群时，返回app端邀请成功，由于邀请动作和发送提示信息是解耦异步的，当处理的信息量增加时，被邀请人能否刷新出对话窗口就是看被邀请人收到提示信息是在刷新对话列表的前后了。

又比如退群时，app端sdk收到退群成功开始刷新对话列表，然后移除失效对话框，若因为后端返回对话列表慢于移除失效对话，即先成功移除了失效对话，后刷新列表成功，则导致失效对话列表被重新刷新出来。

以上处理时序问题，根据现在sdk和server设计的处理模式 是会常常出现的，建议探讨优化

**Comment by heavyrain2012** [comment]
会话列表在服务器端是没有对应数据的，会话列表是客户端根据消息来生成的。
