### ISSUE TITLE
什么时候能支持服务端清空聊天记录？

### ISSUE THREAD

**Issue by DuJieJerry** [wildfirechat/server#332]
目前知道客户端可以清空聊天记录，想问下什么时候能支持服务端清空聊天记录？

**Comment by heavyrain2012** [comment]
目前架构设计有难度，因为每个消息都只存一份，会话内的所有人都使用同一份消息，如果某个用户删除消息，比较难处理。我们已经在考虑重新设计方案，但没有时间表，可能时间比较长久。
