### ISSUE TITLE
发布朋友圈提醒谁看的功能未实现

### ISSUE THREAD

**Issue by DuJieJerry** [wildfirechat/server#333]
在接入最新版的朋友圈的时候，发现朋友圈的Demo中有提醒谁看的功能。
在发布朋友圈的时候也有带上对应的参数，但是在获取朋友圈列表的时候对应的参数具体数值却丢失了。
所以朋友圈提醒谁看的功能何时能实现?

**Comment by heavyrain2012** [comment]
该功能暂时无法加上，因为跟现在接口设计有点儿问题，可能需要到第二或者第三季度我们会加上

**Comment by heavyrain2012** [comment]
已经添加
