### ISSUE TITLE
通过Server API群发接口群发消息，发送方登录后没有对话窗口产生

### ISSUE THREAD

**Issue by charlesbabyxu** [wildfirechat/server#335]
通过Server API群发接口群发消息，发送方登录后，在群发对象没有回复的情况下，无对话窗口产生。

假定开启陌生人聊天时，想继续发消息时，无法快速找到对话窗口

**Comment by heavyrain2012** [comment]
群发和广播就是这样的，发送方不为每个对象创建一个会话。如果需要为每个对象创建一个会话，请遍历目标对象，为每个对象发送一条单聊消息。

**Comment by charlesbabyxu** [comment]
若是在群发后  我这边操作数据库 向数据库中插入user_setting  是否可以创建对话框   若可行 参数该如何设置

**Comment by charlesbabyxu** [comment]
若是在群发后  我这边操作数据库 向数据库中插入user_setting  是否可以创建对话框   若可行 参数该如何设置

**Comment by heavyrain2012** [comment]
不可以的，请参考我上面的回复，一个一个用户地去发送就好了
