### ISSUE TITLE
咨询：野火是否有统计用户的在线时长，如果有是否有方法能够获取

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/server#337]
我们准备购买专业版，目前试用一切ok。我们原来业务通过websoket ping pong心跳形式统计了用户的在线时长。
现在想全面切换到野火，请问野火是否有统计用户的在线时长？如果有请问可有方法可以获取。
主要是获取这个用户当日或指定某一天的在线时长。

谢谢

**Comment by heavyrain2012** [comment]
野火没有统计用户在线时长的功能，因为统计在线时长是不准确的，比如android进入到后台后可能比较长时间还不掉线，甚至能一直在线，iOS进入到后台很快会掉线。这个功能一般都是需要自己来在客户端埋点进行统计的，统计用户打开应用、切换到后台，使用时长，甚至在每个页面停留时间的。统计的数据以每天一次或其它频率上传，你们可以自己来加。

**Comment by zuoliang0** [comment]
好的，谢谢。
