### ISSUE TITLE
访问server 的/route接口返回乱码怎么处理？

### ISSUE THREAD

**Issue by Berton520** [wildfirechat/server#338]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
小程序login后自动访问的im服务器route接口，使用的环境是（linux）

#### 表现现象
接口返回乱码

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
问题必现

#### demo对比结果
github上下载的原包，未做改动

**Comment by heavyrain2012** [comment]
小程序和web都是收费的且需要搭配专业版IM服务才可以使用，价格请参考 https://docs.wildfirechat.net/#费用 。可以先试用后购买，试用说明 https://docs.wildfirechat.net/trial/
