### ISSUE TITLE
ajax请求服务器api跨域问题   response.setHeader("Access-Control-Allow-Origin","*");在哪个文件的哪个位置添加

### ISSUE THREAD

**Issue by jvvd2020** [wildfirechat/server#339]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是毕现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
ajax是不是web客户端用的？在客户端是不能直接请求server api的，因为很容易被破解从而拿到服务的密钥，这样就没有任何安全性了。一般客户端都是先请求自己的应用服务，应用服务再请求server api。

**Comment by jvvd2020** [comment]
不是我是在另外一个网站调用服务器

**Comment by jvvd2020** [comment]
不是客户端

**Comment by jvvd2020** [comment]
其实是一个跨域问题,我试了用反向代理,但是还是报错,然后我想能不能在IM服务器那边直接添加Access-Control-Allow-Origin","*",这样就可以解决跨域了

**Comment by heavyrain2012** [comment]
需要由后端的接口来调用，后端调用就没有跨域问题了。你们需要写一个后端服务，需要的时候调用这个后端服务，这个后端服务再调用server api
