### ISSUE TITLE
怎么解析消息内容呢

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#341]
我这边自己需要使用php开发一个IM 的管理后台
因为admin_api提供的功能有限,在有些功能需要直接读取IM的数据库
其中在做消息管理这块
_data字段都是二进制数据,如果直接转化10进制,里面有很多pb的分隔符,有时候还有乱码,
想请教下,如果才能解析出消息表的_data信息,反序列化成MessagePayload呢

**Comment by heavyrain2012** [comment]
_data内容是经过protobuf序列化过的数据，而pb协议内容不开源所以无法由php来解析，如果是java语言的话可以用sdk包中的WFCMessage.java来进行解析。另外我们也提供由自己的管理后台，springboot+vue写的，如果你们有条件的话可以购买源码后来二次开发，也可以根据前面我提到的那个文件来解析内容

**Comment by pslxx** [comment]
那很尴尬`
