### ISSUE TITLE
已经发出的消息，如何变更内部数据状态呢

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#342]
举个最简单的例子，
A 给B 发红包。。后台api 执行 让A 给B 发红包消息，消息负载是红包的数据id和状态等信息

接下来有几中情况，
1、红包被领取了，
2、红包过期了
新的通知消息都好处理，但是需要在A和B的conversionList里更新 第一次发红包消息的状态，让第一个红包消息变成已领取的状态
类似于消息送达的逻辑，或者消息已读落

**Comment by pslxx** [comment]
还有就是前端的SDK或者服务端会不会缓存消息列表啊，如果直接从数据库删除消息或者修改消息，SDK再次请求会话，会更新吗？

**Comment by heavyrain2012** [comment]
客户端有接口可以更新本地消息内容，当有状态变化时，可以更新本地内容。另外可以在消息显示时去业务服务器更新业务状态，并搭配上领取通知消息触发更新
