### ISSUE TITLE
API接口创建群组报错

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#343]
![image](https://user-images.githubusercontent.com/8417207/111062542-5f3a5380-84e4-11eb-9354-d1443df4e52f.png)

实际上,我看数据库群组已经创建了,群组成员也加进去了,但是 服务端接口返回server error,

**Comment by heavyrain2012** [comment]
服务器版本号是多少

**Comment by pslxx** [comment]
不怪服务器,是我这边问题,我这边用户ID 用的是int...在传入群主的时候,被截取了,,,所有导致找不到群主用户,通知失败`

**Comment by pslxx** [comment]
谢谢.我自己debug看了下,传入的参数,群主ID 不对
