### ISSUE TITLE
如何評估一台im的聊天訊息承受能力

### ISSUE THREAD

**Issue by gctcxu** [wildfirechat/server#344]
#### 操作说明
1. 附檔中有提供jmx腳本但是我這邊都無法打開, 想請問是不是闕漏什麼?
2. 另外像是這類的聊天服務, 如果我們要模擬真實的壓力測試, 應該要怎麼做呢? 我們想要測試單台的能力, 進而評估當業務需求近來時候, 可以準確預測機器的規格要開多少

#### 表现现象
1. 前幾天我們有嘗試建立 用幾台電腦開啟1000個分頁 進入一個1000人的群, 模擬一個1000個成員的群, 然後選其中N個分頁(假裝是N個人), 不斷地發送訊息往這個群裡面丟(頻率1s丟 2~5則), 持續1000則, 不知道這樣的測試方式是否正確, 有無更好的評估方式

**Comment by heavyrain2012** [comment]
您好，测试脚本是需要配合我们专有工具进行测试的，目前这个工具还有各种各样的问题，无法公开这个工具。我们目前测试单台服务是可以支持10W用户在线的，更多用户没有进行测试，由于使用的是netty理论上可以支持更多的用户。在发送消息方面，大概单核cpu能够支持300左右的分法量。当然跟数据库也有很大关系，还有日志是否开启异步读写等。因为IM服务的使用场景比较复杂，所以无法准确评估出具体性能，但至少目前来看，专业版用户还没有遇到性能障碍。关于你们测试的问题，可以加微信 wildfirechat 我们来沟通一下

**Comment by gctcxu** [comment]
1. 問一下有沒有 java connection pool, 或是 sql server的調整方式呢? 前幾次壓測下來 覺得系統還沒到滿載 但是訊息就已經都送不太出去了

測試環境:
24

**Comment by heavyrain2012** [comment]
如果遇到性能问题，可以尝试试试我们专业版，专业版具有更高的性能，专业版可以申请试用，试用方式 https://docs.wildfirechat.net/trial/
