### ISSUE TITLE
能不能通过API 更改历史消息内容

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#345]
还是发红包相关的问题,
虽然客户端可以用SDK来更新,但是需要另外一个消息,来触发这个事件,
如果用户很久没登录,.没有收到这个二次更新的消息,或者这个消息只保存很短的时间,
那么用户看到的第一次发送的原始消息,状态就不会更新了.

我觉得可以在后台API能实现个更新消息内容的接口,然后SDK 有个消息更新的统一事件接口..不知道逻辑可正确`

**Comment by heavyrain2012** [comment]
无法在IM服务中实现这个消息，有个办法是在业务服务中记录状态，消息只是个通知，展示消息时去业务服务中更新状态
