### ISSUE TITLE
注册的用户，客户端查询不到用户信息，服务器提示这个错误

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/server#347]
17/03/2021 16:58:51,557 [epollEventLoopGroup-3-3] ERROR ProtocolProcessor 214  - The MQTT login failure. Username=870035
17/03/2021 17:03:00,566 [epollEventLoopGroup-3-1] ERROR ProtocolProcessor 335  - Password decrypt failed of client b02849e20a057b851615892600893
17/03/2021 17:03:00,567 [epollEventLoopGroup-3-1] ERROR ProtocolProcessor 214  - The MQTT login failure. Username=870035
17/03/2021 17:18:07,373 [epollEventLoopGroup-3-3] ERROR ProtocolProcessor 360  - Client didn't supply any credentials and MQTT anonymous mode is disabled. CId=CENSYS
17/03/2021 17:18:07,374 [epollEventLoopGroup-3-3] ERROR ProtocolProcessor 214  - The MQTT login failure. Username=null

**Comment by heavyrain2012** [comment]
这个错误跟查不到用户信息无关
