### ISSUE TITLE
使用同一部android手机登录不同的账号，会出现这样的错误，导致用户无法获取到用户信息

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/server#348]
17/03/2021 19:22:55,226 [epollEventLoopGroup-3-4] ERROR MemorySessionStore 297  - Can't find the session for client <b02849e20a057b851615971925587>
17/03/2021 19:22:55,876 [epollEventLoopGroup-3-2] ERROR MemorySessionStore 297  - Can't find the session for client <b02849e20a057b851615971925587>
17/03/2021 19:22:56,237 [epollEventLoopGroup-3-2] ERROR MemorySessionStore 297  - Can't find the session for client <b02849e20a057b851615971925587>

**Comment by heavyrain2012** [comment]
把服务器升级一下，升级到最新版本试试

**Comment by dotcool** [comment]
已经是最新的了哦

**Comment by heavyrain2012** [comment]
客户端退出重新登录一下呢

**Comment by dotcool** [comment]
还是不行哦

**Comment by charlesbabyxu520** [comment]
这个日志打着玩的  后续会加载session的 最好先getToken route 是数据库session状态改变

**Comment by heavyrain2012** [comment]
长时间没有更新状态，先关闭吧，如果有更新请再打开，谢谢
