### ISSUE TITLE
我看到server sdk中有演示管理聊天室的功能,请问server api没有相应的功能吗?

### ISSUE THREAD

**Issue by w0fv1** [wildfirechat/server#349]
我想保持im服务器独立,是文档未更新吗?
另外我想将将野火im的token与我原先项目的token融合起来，请问这可能吗，是否有api？两个token实在不优雅~

**Comment by w0fv1** [comment]
我找到了
![image](https://user-images.githubusercontent.com/45745544/111868865-65827100-89b7-11eb-8465-d49e735b3a0b.png)
非常感谢野火im，如果我们的项目有起色一定入专业版。谢谢你们~~

**Comment by heavyrain2012** [comment]
好的，祝愿你们事业成功，期待着你们使用我们收费产品～～
