### ISSUE TITLE
当业务中存在删除用户时，野火name属性无法重复导致业务无法闭环，需要野火提供删除账户功能（标记删除即可）

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/server#350]
#### 操作说明
我们现在的业务场景是这样的，我们注册的时候会同步注册野火，野火的用户id是我们的用户id加上一个前缀，野火的name属性是我们系统邮箱字段。

然后我们业务可以删除账号，删除时将我们库中的email加一个前缀做标记删除。但是用户可以用同样的邮箱再次注册，再次注册后去注册野火提示账户（name）不能重复。

可能需要野火提供删除接口或者更新用户名的接口（我们业务在删除的时候调用更新用户名为删除的前缀）这样注册新的账户就不会有问题了。

#### 表现现象
{"code":4,"msg":"用户名不能重复，必须唯一！！！"}
#### 预期结果
预期希望可以更新用户名 或提供删除用户接口

#### 补充条件
主要是和业务冲突了

**Comment by heavyrain2012** [comment]
可以更改用户名，请参考应用服务，应用服务有个接口是给客户端更改名字用的，用的是IM服务的创建接口。

**Comment by zuoliang0** [comment]
> 可以更改用户名，请参考应用服务，应用服务有个接口是给客户端更改名字用的，用的是IM服务的创建接口。

请问这个对于野火是否有版本限制，我这边使用的0.48版本无法通过userId修改到用户名

**Comment by heavyrain2012** [comment]
没有限制，可以参考应用服务的实现，如果出错检查是不是跟已有的用户冲突
