### ISSUE TITLE
能不能给消息定义不入库,不存储?

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#352]
能不能设置消息,不入数据库?

使用场景:
只使用IM的的聊天室功能,做弹幕或者业务消息的转发,
消息的不是很重要,对于送达率也要求没有那么高

能不能设置消息不如数据库.只做转发

**Comment by heavyrain2012** [comment]
聊天室比较特殊，还没有想到好办法做这种直推的消息，因为考虑到聊天室是海量的消息，需要客户端来拉取，不能来一条普通消息就直接推送。有个办法就是客户端做归并，比如30秒的点赞归并为一条，这样别的端收到后播放这30秒内的点赞情况。
