### ISSUE TITLE
如何升级的问题

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#355]
我的版本是0.49

如何升级到最新的版本

是把文件更新上去就可以吗？ 数据库呢？

我没看到升级的程序呢？

**Comment by heavyrain2012** [comment]
旧的程序停掉，备份数据库（表结构和数据），解压新版本，修改新版本配置，启动新版本，等启动成功后验证是否正常，如果正常就升级成功，如果不正常，恢复数据库回退版本

**Comment by mankind-evolve** [comment]
0.49 到  0.60 数据库没有变动吗？ 这样我就容易搞了！

**Comment by heavyrain2012** [comment]
有变动，服务器会自动处理数据库的变动

**Comment by mankind-evolve** [comment]
赞一个。周到！
