### ISSUE TITLE
如果需要支持websocket是不是需要购买专业版的的同时,还需要购买WEB的sdk?

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#356]
如果需要支持websocket是不是需要购买专业版的的同时,还需要购买WEB的sdk?

同时web还需要绑定域名只能使用一个域名

**Comment by heavyrain2012** [comment]
web sdk是依赖专业版的，如果需要web那就需要购买专业版IM和web sdk。会绑定域名，一般都是给一个生成一个测试两个环境
