### ISSUE TITLE
超级用户 未登陆期间接收信息超信箱长度时 再次登陆稍早的会话未读数显示1

### ISSUE THREAD

**Issue by charlesbabyxu520** [wildfirechat/server#357]
超级用户，未登陆期间接收信息超信箱长度时，app端再次登陆聚合会话时，因为接收到的信息数超信箱1024长度，而被逐出缓存，当sdk聚合会话时有的会话因为信箱缓存信息已经逐出，无法正确统计未读数，未读数显示1，即拖过LRM获取的最后一条信息。

希望信箱可以增加更多的细则，对于超级用户和普通用户来说，对信箱的使用程度是不同的，希望可以控制时间维度，如tail尾部消息和头部消息时间相差少于14天允许缓存，这个缓存数量可以是正常1024长度的所少倍

**Comment by heavyrain2012** [comment]
1024这个长度是可以配置的，可以简单配置更大，但这样会更消耗内存，你们可以衡量一下。一般情况下超过一千条消息就已经很多了，特殊角色如果会收到大量消息建议服务处理，比如直接读取消息数据库，或者把消息转到服务去

**Comment by charlesbabyxu520** [comment]
对于可配置是了解的  感谢关注
1、撸库和撸缓存 效率是不一样的 
2、1024的信箱是多数用户用不到，但活跃用户又是不够的，单独为了活跃用户加大缓存又是极大浪费缓存的，但活跃用户对产品的带动性也是不可或缺的，所有希望这个配置能更加灵活，可以插件调整上下限

**Comment by heavyrain2012** [comment]
这个在社区版上没有办法区别对待的
