### ISSUE TITLE
A往群1发送不展示的消息a（No_Persist），B此时会话列表不存在群1会话，而收到消息a后会话列表没有生成群1会话

### ISSUE THREAD

**Issue by wu4321** [wildfirechat/server#359]
A往群1发送不展示的消息a（No_Persist），B此时会话列表不存在群1会话，而收到消息a后会话列表没有生成群1会话，请问是什么原因呢，如果非要生成群1会话如何操作？

**Comment by heavyrain2012** [comment]
会话只有存储的消息才会生成，发送不存储消息到群里是不会触发创建群会话的。如果需要创建群会话，可以在群里发一条存储的消息，也可以在客户端收到不存储消息时，检查会话不存储创建会话（调用设置会话时间那个方法）

**Comment by wu4321** [comment]
![image](https://user-images.githubusercontent.com/11186470/114851287-417a4a00-9e14-11eb-9816-f710a2f50de2.png)
在这里接收判断会话是否存在以及消息是否是不存储消息吗

**Comment by heavyrain2012** [comment]
可以

**Comment by wu4321** [comment]
好的  谢谢
