### ISSUE TITLE
机器人参数的密钥是用在什么地方的,还有多个机器人设置相同的回调地址,在回调程序里如何区分属于哪个机器人的会话

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#360]
机器人参数的密钥是用在什么地方的,回调请求的request和header均没有密钥相关的参数带过来
还有多个机器人设置相同的回调地址,在回调程序里如何区分属于哪个机器人的会话.

**Comment by heavyrain2012** [comment]
机器人API签名需要密钥，请检查 https://docs.wildfirechat.cn/server/robot_api/ 签名规则。
机器人回调是没有签名信息的，理论上是可以被伪造的，可以设置https地址就基本能够避免被抓包然后伪造
机器人回调是每个机器人一个的，可以为每个机器人设置不同的回调地址，比如路径中或者参数中带上机器人id，就能区分是那个机器人了
