### ISSUE TITLE
好友请求数据错乱

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#367]
新部署的最新版本的社区版,会莫名其妙出来多余的好友请求,并且这个target也是不对的,时间也是为0,
如图所示,有4个好友请求,但是实际上只有2个是正确的,
并且我查看了数据库.数据库里是对的,但是通过SDK获取的返回数据是不对的
![image](https://user-images.githubusercontent.com/8417207/117522800-de7d6c80-afe7-11eb-9d81-0e711e96a43a.png)

![image](https://user-images.githubusercontent.com/8417207/117522870-31572400-afe8-11eb-884b-519319fd3ffa.png)

**Comment by heavyrain2012** [comment]
你们是不是有通过API操作好友请求，是不是通过api操作好友请求时，用户id带有\n\r

**Comment by pslxx** [comment]
> 你们是不是有通过API操作好友请求，是不是通过api操作好友请求时，用户id带有\n\r

对,,为什么有\n\r呢,,需要做兼容处理吗?
