### ISSUE TITLE
如何在好友关系之间和群组成员里,能保留来源方式?

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#368]
比如好友之间可以看到 对方通过搜索添加/名片添加/二维码添加好友等
群组里 成员可以看到XX邀请加入群聊/扫描二维码加入群聊等

**Comment by heavyrain2012** [comment]
好友请求和群成员信息都添加了extra信息，可以把来源方式以json的格式存储在extra中。其中好友请求extra中带上来源，然后在接受好友请求的函数中的extra带上这个来源，这样好友请求的extra就有来源了，请更新最新服务器代码和客户端代码验证

**Comment by pslxx** [comment]
厉害了,感谢大佬
