### ISSUE TITLE
希望开源版可配置本地文件生成的url

### ISSUE THREAD

**Issue by bumblebee1024** [wildfirechat/server#369]
开源版的im-server中，
类 io.moquette.imhandler.GetMediaUploadTokenHandler 里面

当用默认的server本地存储文件时，生成的url有点问题。

```java
                resultBuilder.setDomain("http://" + MediaServerConfig.SERVER_IP + ":" + MediaServerConfig.HTTP_SERVER_PORT)
                    .setServer(MediaServerConfig.SERVER_IP);
```

上面这句是拼接上传的文件生成的url。
因为我有用https下载，当我使用nginx代理文件路径的时候，就会有点问题了。

因为开源版，可修改文件存放的路径
在类com.xiaoleilu.loServer.action.UploadFileAction中

```java
datePath = "fs/" + bucket[0] + "/" + datePath; //add bucket
```

上面这句是把上传的文件放在fs文件夹下面。

我希望前端可以直接访问文件，就用nginx代理了这个文件夹。
另外路径“fs”和server当中的接口重合，nginx代理会冲突
所以我改成了
```java
                //   这里的目录，文件夹名fs和接口的path重合，不方便使用nginx，所以需要换
                //datePath = "fs/" + bucket[0] + "/" + datePath; //add bucket
                datePath = "fsroot/" + bucket[0] + "/" + datePath; //add bucket

```

希望当我使用server本地存储文件时，可以用配置的方式定制文件的存放根目录“fs”可以配置成其它文件夹名字
然后生成的url可以使用配置判断是否生成https的

总结一下，大概意思就是
不改代码生成的文件url是

**http://ip:port/fs/5/2021/03/27/08/7J7T7Tqq-5-1616806160-3Q7HxLJJ_.jpg**

当我使用nginx代理文件目录的时候，可以通过配置的方式定制url生成如下

**https://domain/fsroot/5/2021/03/27/08/7J7T7Tqq-5-1616806160-3Q7HxLJJ_.jpg**

**Comment by heavyrain2012** [comment]
添加了配置项，可以配置远程媒体服务地址，请参考提交 https://github.com/wildfirechat/server/commit/43b325d2d583e87c3ebb0bfd7346f41ecef6c59e

**Comment by heavyrain2012** [comment]
尽管内置文件存储可以使用，但是还是建议使用专业级别的对象存储，社区版支持七牛，专业版支持野火私有对象存储

**Comment by bumblebee1024** [comment]
更新后的配置已经实测过了，社区版。
在消息发送视频消息的时候，有些短一些的视频可以点开播放，一些大一些的视频文件就直接报错或者播放不了。
于是用同一个文件分开来验证，使用社区版新的配置用nginx代理im server 80端口的fs路径，仅能解决文件下载，而不能解决视频在线播放。

nginx直接代理一个文件目录的情况是直接可以在H5或者IM上播放视频的。
而野火的80端口的fs路径的文件访问是用netty实现的http，并没有完美支持视频文件的在线播放。

总结一下就是
https://im.domain.com/media/fs/3/2021/05/25/09/SRSmSm33-3-1621904566-lFj21O2z_VklEXzIwMjAwOTI1XzE4MDIzNDU4.mp4
这种方式仅下载没问题，视频播放不能完美支持。

https://nginx.domain.com/static/SRSmSm33-3-1621904566-lFj21O2z_VklEXzIwMjAwOTI1XzE4MDIzNDU4.mp4
这种nginx直接代理文件目录的才能很好支持视频文件的https在线播放

所以目前的配置还是不能很好的解决我的这个问题点

**Comment by heavyrain2012** [comment]
可以nginx代理fs这个目录，通过nginx来访问fs目录下的所有文件

**Comment by bumblebee1024** [comment]
好的
