### ISSUE TITLE
AES解密 bug

### ISSUE THREAD

**Issue by hlwskgypmb** [wildfirechat/server#37]
app聊天发送视频时 部分视频会发送不成功，服务器显示
![image](https://user-images.githubusercontent.com/18130329/60503469-66123a00-9cf2-11e9-82c4-a04f80d0e08a.png)

**Comment by hlwskgypmb** [comment]
0.23最新代码，未修改过源码

**Comment by heavyrain2012** [comment]
服务内置文件服务器仅仅用于开发和测试，请使用七牛文件存储试试

**Comment by hlwskgypmb** [comment]
经过排查 并不是文件上传的bug 实际是上传后返回报文加解密报错
![image](https://user-images.githubusercontent.com/18130329/60561941-0cf4e580-9d88-11e9-96d9-1f7f2bbf132c.png)

**Comment by hlwskgypmb** [comment]
![image](https://user-images.githubusercontent.com/18130329/60561989-3877d000-9d88-11e9-8cd9-1beda4064d14.png)

**Comment by hlwskgypmb** [comment]
用内置的文件上传，然后我录了2个视频，打断点是全部上传成功了。然后服务器也可以找的到文件。但是部分文件（a视频）的发送视频消息会导致解密失败，重发也是解密失败。重复发送这2个视频也是b成功a失败
定位就是在解密出现了异常
[ab.zip](https://github.com/wildfirechat/server/files/3357553/ab.zip)
这里是对应的a,b视频文件

**Comment by hlwskgypmb** [comment]
[ab.zip](https://github.com/wildfirechat/server/files/3357553/ab.zip)
这里是对应的a,b视频文件

**Comment by heavyrain2012** [comment]
无法验证
