### ISSUE TITLE
关于群头像的定制问题

### ISSUE THREAD

**Issue by bumblebee1024** [wildfirechat/server#370]
目前的群头像的生成规则，是按照群成员的加入和踢出来变化成默认的宫格形式的群头像。

有一种逻辑是这样的，当群的管理员或者群成员手动设置了群头像之后，后续这个群增加人或者修改人，都不要再改变群头像了。

就是手动设置的群头像的优先级需要大于默认生成群头像的权重。

**Comment by heavyrain2012** [comment]
群组头像的生成和更新属于非IM核心业务，它是在UI层实现的，你们可以自己来处理。我们有几种可以参考：
第一种创建群组时不生成头像，所有人拿到群组信息都是头像为空，当发现头像为空时，客户端进行拼接头像，并使之联系起来，注意更新比如检查拼接头像的成员是否有变化等，如果管理员手动设置了群头像，客户端则直接使用不再拼接。

第二种方法是客户端操作者处理，当操作群组变动时，重新拼接头像并重新设置群头像，需要注意几点一个是屏蔽掉修改头像通知（把修改头像通知消息改为不存储的状态），另外一个是如果有server api操作，也需要注意头像变动，最后一个是如何区分是自动拼接还是手动设置的，可以修改群extra记住是那种状态。

应该还有别的方法，不要被我们的建议所束缚，如果有更好的方法可以告知我们。
