### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/server#371]
#### 操作说明
https://docs.wildfirechat.cn/server/event_callback.html
消息回调的消息唯一id 不是messageUid 而是messageId 请求订正

**Comment by heavyrain2012** [comment]
已经修改文档，返回来的参数是messageId。其实这里我们有些混乱，比如发送消息返回来的是messageUid，而这里返回的是messageId。为了保持接口兼容，就把文档给改了吧。谢谢提醒

**Comment by zuoliang0** [comment]
谢谢啦
