### ISSUE TITLE
可以提供修改历史消息的功能吗

### ISSUE THREAD

**Issue by udoless** [wildfirechat/server#372]
比如 需要支持消息点赞，或红包的状态更新(已领取，已过期等)
需要对一个历史消息进行更新，如更新点赞人数

**Comment by heavyrain2012** [comment]
没有这样的接口，消息只是一个通知，如果有业务数据，可以在显示消息时再去业务服务器去更新

**Comment by udoless** [comment]
> 没有这样的接口，消息只是一个通知，如果有业务数据，可以在显示消息时再去业务服务器去更新

但是现在没法知道 `有没有业务数据`，如果历史消息支持设置一个flag也可以。融云、sendbird提供的有类似的消息扩展字段且支持修改的功能，不知道这边是否考虑支持。

**Comment by heavyrain2012** [comment]
已经添加设置消息本地扩展信息接口，清检测客户端最新的代码提交

**Comment by udoless** [comment]
好的，谢谢
