### ISSUE TITLE
创建群组拉人进去,然后重复加人 踢人,安卓app直接挂掉了

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#374]
创建群组拉人进去,然后重复加人 踢人,安卓app直接挂掉了

**Comment by pslxx** [comment]
![image](https://user-images.githubusercontent.com/8417207/118913881-e250ad80-b95c-11eb-9848-ef9e3bcfc019.png)
反复操作之后,还剩3个人的群聊,竟然显示4个成员,而且第一个成员的ID 是群聊的ID

数据里都是OK 的

**Comment by heavyrain2012** [comment]
感觉不太可能吧，你加上日志，每次请求的数据都打出来，然后复现问题

**Comment by heavyrain2012** [comment]
问题是出现在转换吗，还是出现在IM服务和协议栈，你看看IM服务数据库里有几个成员，然后客户端杀掉重启看看还有没有，再试试卸载重装看看还有没有

**Comment by heavyrain2012** [comment]
近期引入的bug，bug在0.62和0.63版本上存在，请更新到0.64版本或之后，或者回退到0.61版本
