### ISSUE TITLE
默认的长链接1883端口可以修改吗？

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/server#375]
#### 操作说明
server端0.55版本，因为服务器上1883端口已经被集团其他应用占用了，我们IM可以调整为其他端口吗？
服务必须通过集团域名+端口映射到虚拟机的某个端口方式来访问。
虚拟机的端口都可控，随便设置，但是域名后面的端口不能自定义。
这种情况只能调整服务端的端口。

#### 表现现象
在server端修改成其他端口以后，客户端连接不上了。

#### 预期结果
希望1883和8083端口都可调整，只要客户端和服务端能连接上就行。

#### 补充条件
[#354](https://github.com/wildfirechat/server/issues/354)和 [#250](https://github.com/wildfirechat/server/issues/250)两个issue，好在我们申请的域名，能提供80端口，映射到虚拟机的80端口了。
但是域名之后不能申请1883和8083，以及18080等端口了。

#### 
还请不吝赐教

**Comment by heavyrain2012** [comment]
18080端口为server api接口，不需要也不建议对外开放，这个在你们内网中由其它服务调用就行了。社区版用不到8083端口，只有专业版需要用到，因此只需要处理1883端口就行。1883端口是MQTT协议（tcp协议），非HTTP协议，因此映射时必须是4层的映射。

服务会读取配置文件中的端口配置，绑定指定端口，并把端口传给客户端（客户端通过80端口来获取的），因此需要配置文件中修改为其它端口而且映射到外网的端口也必须是相同端口。

综上有可能有2种原因：
1. 映射没有使用4层映射，使用了7层映射。
2. 外网映射端口与配置文件端口不一致。

请检查上述两种可能性

**Comment by qdhaiqiang** [comment]
感谢细心的解答。
[文档](https://docs.wildfirechat.cn/faq/server.html?h=test)上说“域名只能是im/imtest的二级域名，比如您拥有域名example.com，那么可以给你的IM服务器分配域名im.example.com或imtest.example.co”，如果没法申请到这样的二级域名，有什么替代方案吗？

im-khaos.cosmoplat.com这样的域名可以吗？

**Comment by qdhaiqiang** [comment]
外网域名映射关系如下：
域名:20030  ->   虚拟机ip:20030
域名:80          ->  虚拟机ip:80端口

server里的wildfirechat.conf，配置如下：

```
server.ip mkhaos-im.test.cosmoplat.com

##原生客户端长链接端口
port 20030

##客户端短链接端口
http_port 8018

#管理端口
http.admin.port 18080

##节点ID，当集群部署时，一定不能有重复。
node_id 1

##绑定IP，保持不变即可
host 0.0.0.0

##本地绑定端口
local_port 8018
```

现在[http://mkhaos-im.test.cosmoplat.com/api/version](http://mkhaos-im.test.cosmoplat.com/api/version)是能返回json的。

麻烦检查下这样的配置有问题吗？

**Comment by heavyrain2012** [comment]
> 感谢细心的解答。
> [文档](https://docs.wildfirechat.cn/faq/server.html?h=test)上说“域名只能是im/imtest的二级域名，比如您拥有域名example.com，那么可以给你的IM服务器分配域名im.example.com或imtest.example.co”，如果没法申请到这样的二级域名，有什么替代方案吗？
> 
> im-khaos.cosmoplat.com这样的域名可以吗？

只能用我们指定的域名或者ip，你们这个子域名不可以的。如果是 im.cosmoplat.com /imtest.cosmoplat.com/imdev.cosmoplat.com 这几个是可以的，也可以直接用ip地址

**Comment by heavyrain2012** [comment]
> 外网域名映射关系如下：
> 域名:20030 -> 虚拟机ip:20030
> 域名:80 -> 虚拟机ip:80端口
> 
> server里的wildfirechat.conf，配置如下：
> 
> ```
> server.ip mkhaos-im.test.cosmoplat.com
> 
> ##原生客户端长链接端口
> port 20030
> 
> ##客户端短链接端口
> http_port 8018
> 
> #管理端口
> http.admin.port 18080
> 
> ##节点ID，当集群部署时，一定不能有重复。
> node_id 1
> 
> ##绑定IP，保持不变即可
> host 0.0.0.0
> 
> ##本地绑定端口
> local_port 8018
> ```
> 
> 现在http://mkhaos-im.test.cosmoplat.com/api/version是能返回json的。
> 
> 麻烦检查下这样的配置有问题吗？

##客户端短链接端口
http_port 8018

这个端口要改为80
