### ISSUE TITLE
运行一段时间后登录不上，server侧报超时 & 死锁

### ISSUE THREAD

**Issue by KingDragon08** [wildfirechat/server#376]
日志如下：
25/05/2021 11:03:15,640 [pool-3-thread-2] ERROR RequestInfo 38  - Request timeout. fromUser 6JTJ6JJJ, cliendId 0454CCDB-0C07-4AC3-9963-F164C59BF3D5, requestId 5, request UPUI
25/05/2021 11:03:30,359 [C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-AdminTaskTimer] WARN  ThreadPoolAsynchronousRunner 220  - com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@6376dd02 -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!
25/05/2021 11:03:30,361 [C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-AdminTaskTimer] WARN  ThreadPoolAsynchronousRunner 220  - com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@6376dd02 -- APPARENT DEADLOCK!!! Complete Status:
	Managed Threads: 3
	Active Threads: 3
	Active Tasks:
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@180742b4
			on thread: C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-HelperThread-#1
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@57f345b8
			on thread: C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-HelperThread-#0
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@211fa69d
			on thread: C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-HelperThread-#2
	Pending Tasks:
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@59758a85
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@7bc561fd
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@36d635b8
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@6a2146b1
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@1f75c8d2
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@4fef8848
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@48930ff8
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@28e7dc95
		com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask@1965b203
Pool thread stack traces:
	Thread[C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-HelperThread-#0,5,main]
		org.h2.engine.Engine.openSession(Engine.java:172)
		org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
		org.h2.engine.Engine.createSession(Engine.java:140)
		org.h2.engine.Engine.createSession(Engine.java:28)
		org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
		org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
		org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
		org.h2.Driver.connect(Driver.java:69)
		com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
		com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
	Thread[C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-HelperThread-#2,5,main]
		org.h2.engine.Engine.openSession(Engine.java:172)
		org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
		org.h2.engine.Engine.createSession(Engine.java:140)
		org.h2.engine.Engine.createSession(Engine.java:28)
		org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
		org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
		org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
		org.h2.Driver.connect(Driver.java:69)
		com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
		com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
	Thread[C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-HelperThread-#1,5,main]
		org.h2.engine.Engine.openSession(Engine.java:172)
		org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
		org.h2.engine.Engine.createSession(Engine.java:140)
		org.h2.engine.Engine.createSession(Engine.java:28)
		org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
		org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
		org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
		org.h2.Driver.connect(Driver.java:69)
		com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
		com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

25/05/2021 11:04:30,362 [C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-AdminTaskTimer] WARN  ThreadPoolAsynchronousRunner 220  - Task com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@57f345b8 (in deadlocked PoolThread) failed to complete in maximum time 60000ms. Trying interrupt().
25/05/2021 11:04:30,362 [C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-AdminTaskTimer] WARN  ThreadPoolAsynchronousRunner 220  - Task com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@211fa69d (in deadlocked PoolThread) failed to complete in maximum time 60000ms. Trying interrupt().
25/05/2021 11:04:30,362 [C3P0PooledConnectionPoolManager[identityToken->1br73e3ah18ss9gh3y9cx7|27abe2cd]-AdminTaskTimer] WARN  ThreadPoolAsynchronousRunner 220  - Task com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@180742b4 (in deadlocked PoolThread) failed to complete in maximum time 60000ms. Trying interrupt().
25/05/2021 11:04:48,882 [nioEventLoopGroup-5-18] ERROR MemorySessionStore 259  - Can't find the session for client <94CBCFB8-21E9-437D-AB7E-65614DA29DC9>
25/05/2021 11:04:48,885 [nioEventLoopGroup-5-21] ERROR MemorySessionStore 259  - Can't find the session for client <94CBCFB8-21E9-437D-AB7E-65614DA29DC9>
25/05/2021 11:04:48,893 [nioEventLoopGroup-5-20] ERROR MemorySessionStore 259  - Can't find the session for client <94CBCFB8-21E9-437D-AB7E-65614DA29DC9>
25/05/2021 11:04:48,896 [nioEventLoopGroup-5-22] ERROR MemorySessionStore 259  - Can't find the session for client <94CBCFB8-21E9-437D-AB7E-65614DA29DC9>
25/05/2021 11:04:50,941 [nioEventLoopGroup-5-27] ERROR MemorySessionStore 259  - Can't find the session for client <94CBCFB8-21E9-437D-AB7E-65614DA29DC9>

**Comment by heavyrain2012** [comment]
使用了h2db，且数据库超大（接近100GB），导致响应慢，被c3p0认为死锁，请更新为mysql
