### ISSUE TITLE
请求 Server API 注册更新用户接口，在用户名称带有特殊字符时，连接会被自动砍断，无法正确响应。

### ISSUE THREAD

**Issue by branchzero** [wildfirechat/server#378]
#### 操作说明
http://domain:18080/admin/user/create
displayName带如下任意一个用户设置的名称参数时
```
&&&
~%?…;# *’☆&℃$︿★?
。(。～。($%………。(&
#@$%&*～
```

#### 表现现象

请求无法正常返回（直接被closed）

其中，`&&&`在urlencode之后能够正常响应，其他在urlencode后仍然会被砍请求，无法正常回应

#### 预期结果

在带特殊字符时（毕竟用户设置了什么昵称，我们没办法干涉吧），能够正常返回请求结果。

#### 补充条件

必现

**Comment by heavyrain2012** [comment]
您好，我们使用sdk中的测试代码验证是没有问题的，你们可以看一下 /sdk/src/main/java/cn/wildfirechat/sdk/Main.java 测试，然后测试代码如下：

        InputOutputUserInfo userInfo = new InputOutputUserInfo();
        userInfo.setUserId("userId1");
        userInfo.setName("user1");
        userInfo.setMobile("13900000000");
        userInfo.setDisplayName("&&& ~%?…;# *’☆&℃$︿★? 。(。～。($%………。(& #@$%&*～");

        IMResult<OutputCreateUser> resultCreateUser = UserAdmin.createUser(userInfo);
        if (resultCreateUser != null && resultCreateUser.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
            System.out.println("Create user " + resultCreateUser.getResult().getName() + " success");
        } else {
            System.out.println("Create user failure");
            System.exit(-1);
        }

        IMResult<InputOutputUserInfo> resultGetUserInfo1 = UserAdmin.getUserByName(userInfo.getName());
        if (resultGetUserInfo1 != null && resultGetUserInfo1.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
            if (userInfo.getUserId().equals(resultGetUserInfo1.getResult().getUserId())
                && userInfo.getName().equals(resultGetUserInfo1.getResult().getName())
                && userInfo.getMobile().equals(resultGetUserInfo1.getResult().getMobile())
                && userInfo.getDisplayName().equals(resultGetUserInfo1.getResult().getDisplayName())) {
                System.out.println("get user info success");
            } else {
                System.out.println("get user info by name failure");
                System.exit(-1);
            }
        } else {
            System.out.println("get user info by name failure");
            System.exit(-1);
        }
