### ISSUE TITLE
有时候删除好友后去同步数据源，发现好友还在，删除不成功

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/server#38]
![image](https://user-images.githubusercontent.com/7382234/60515703-cc0cba80-9d0e-11e9-84b1-4cad3c9cda93.png)
看 删除好友后我去更新数据眼，发现走了三次加载通讯录 ，并且删除的那个好友又同步下来了

**Comment by yuzhongrong** [comment]
应该是删除成功了 但是刷新数据时候有时候有有时候 没有  多刷几次又没有

**Comment by heavyrain2012** [comment]
已经解决了，请下载最新的客户端和服务端代码进行验证
