### ISSUE TITLE
体验版：im服务端消息转发到自己服务器丢失问题

### ISSUE THREAD

**Issue by anglamei** [wildfirechat/server#380]
#### 操作说明
web端连续发送多个图片或者文件消息，图片连着发，就只会回调一次，中间隔着发一条文字消息就正常了

#### 预期结果
客户端不管发什么消息，都正常消息转发

#### 补充条件
必现

**Comment by heavyrain2012** [comment]
理论上发送图片文件和普通文本消息都是一样的，在服务器都是messagepayload，会不会是你那边处理有什么不同，可以试试收到转发什么都不做只打印一个日志看看
