### ISSUE TITLE
friend.disable_friend_request false 这个参数直接把后台的send_request也禁止了

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#382]
需求:是禁止通过SDK发送好友请求,需要发送好友请使用业务的API,业务层调用IM 的 admin api 发送请求
但是这个参数如果设置为true,导致admin api的/admin/friend/send_request 也发送不了,直接返回 no right to operate

**Comment by pslxx** [comment]
因为想做了添加好友的隐私权限,比如号码搜索,二维码添加等方式处理
并且需要给每个用户设置短时间内添加多个好友的次数,,所以需要使用后台的 发送请求接口吗,并且关闭前台的该功能

**Comment by heavyrain2012** [comment]
已解决，请更新最新版本验证

**Comment by pslxx** [comment]
真是神速`
