### ISSUE TITLE
社区版能否通过修改部分代码达到多开简单的分布式

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/server#383]
#### 操作说明
我们希望在社区版的基础上进行一些定制和开发，现在在做技术调研，需要确认一下社区版通过源码修改（或不修改）能否直接运行多个实例。我们现在使用的社区安装版运行，主要是没办法启动2个导致无法很好的高可用，所以希望通过修改源码的形式来支撑，当然我们也愿意购买一套商业版，只是商业版闭源不方便定制。
#### 表现现象
这只是一个咨询类问题，不是问实际要改哪些内容

**Comment by heavyrain2012** [comment]
理论上没有什么是不可能的，但建议没有必要，因为要投入大量人力物力和时间，直接购买我们专业版就可以了。专业版对定制性没有影响的，我们社区版也是不建议修改的，而且客户端协议栈是没有开源的，所以也不能大改，社区版开源主要是给大家看一下我们的代码，使用专业版有完善的server api还有自定义消息机制，比常见的即时通讯云平台的定制能力强多了，基本能满足普通需求，如果有特殊需求，可以给我们提需求

**Comment by zuoliang0** [comment]
好的，你好能否提供一个比较快捷的沟通方式，我们让商务对接一下？

**Comment by heavyrain2012** [comment]
请加微信 wildfirechat
