### ISSUE TITLE
SDK缺失消息相关接口，如获取全部历史消息，通过用户获取跟此用户相关的所有聊天记录等。

### ISSUE THREAD

**Issue by xx0508** [wildfirechat/server#384]
#### 操作说明
SDK缺失消息相关接口

#### 表现现象
目前SDK中没有关于获取消息的接口，如获取全部历史消息，通过用户获取跟此用户相关的所有聊天记录等。

#### 预期结果
提供跟消息相关的接口，如获取全部历史消息，通过用户获取跟用户相关的所有聊天记录等

#### 补充条件
如果自行实现，能否提供实现思路？

#### demo对比结果
demo无消息相关接口

**Comment by heavyrain2012** [comment]
直接从数据库里读取消息就好了

**Comment by xx0508** [comment]
我看数据库做了分表，要怎么直接从数据库读取？

**Comment by heavyrain2012** [comment]
对的，是按照月份分表的，分表规则文档上有说明
