### ISSUE TITLE
请问管理 管理端api 接口/admin/message/send是否能发送文件消息呢？

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/server#385]
请问管理 管理端api 接口/admin/message/send是否能发送文件消息呢？
目前试过发送都是未知消息5

**Comment by dilenzhu** [comment]
发送消息体内容：{"sender":"admin","conv": {"type":0,"target":"123456"},"payload":{"type":5,"searchableContent":"测试","mediaType":4,"remoteMediaUrl":"http://10.10.123.1/2021/06/10/123.doc","pushContent":""}}

**Comment by heavyrain2012** [comment]
您好，server和协议栈传输的内容都是[Payload](https://docs.wildfirechat.cn/base_knowledge/message_payload.html)，客户端上层会把这个Payload转成[MessageContent](https://docs.wildfirechat.cn/base_knowledge/message_content.html)。如果通过server api发送消息，需要直接发送payload，需要客户端把对应类型消息的payload格式告诉给server端，最简单的办法就是看一下客户端发送消息时，encode成的payload是什么格式

**Comment by heavyrain2012** [comment]
这个问题就是你们需要检查一下，客户端的文件消息转成的payload是什么样，有两点需要注意
1，发送文件需要有文件链接（客户端协议栈会自动上传），如果没有文件链接需要先上传，然后再发送文件消息。
2，server api发送消息时，payload的binaryContent需要base64编码，如果需要用到这个字段，注意base64编码

**Comment by dilenzhu** [comment]
> 这个问题就是你们需要检查一下，客户端的文件消息转成的payload是什么样，有两点需要注意
> 1，发送文件需要有文件链接（客户端协议栈会自动上传），如果没有文件链接需要先上传，然后再发送文件消息。
> 2，server api发送消息时，payload的binaryContent需要base64编码，如果需要用到这个字段，注意base64编码

我们用的是server api的模式，不是客户端。但是因为接口文档上面没有具体写明payload里面怎么传递文件的方式，比如文件地址的参数名称是什么？谢谢！

**Comment by dilenzhu** [comment]
> > 这个问题就是你们需要检查一下，客户端的文件消息转成的payload是什么样，有两点需要注意
> > 1，发送文件需要有文件链接（客户端协议栈会自动上传），如果没有文件链接需要先上传，然后再发送文件消息。
> > 2，server api发送消息时，payload的binaryContent需要base64编码，如果需要用到这个字段，注意base64编码
> 
> 我们用的是server api的模式，不是客户端。但是因为接口文档上面没有具体写明payload里面怎么传递文件的方式，比如文件地址的参数名称是什么？谢谢！

是remoteMediaUrl  传的是文件地址吗？还是需要文件流呢？

**Comment by dilenzhu** [comment]
> > > 这个问题就是你们需要检查一下，客户端的文件消息转成的payload是什么样，有两点需要注意
> > > 1，发送文件需要有文件链接（客户端协议栈会自动上传），如果没有文件链接需要先上传，然后再发送文件消息。
> > > 2，server api发送消息时，payload的binaryContent需要base64编码，如果需要用到这个字段，注意base64编码
> > 
> > 
> > 我们用的是server api的模式，不是客户端。但是因为接口文档上面没有具体写明payload里面怎么传递文件的方式，比如文件地址的参数名称是什么？谢谢！
> 
> 是remoteMediaUrl 传的是文件地址吗？还是需要文件流呢？

看到vue端用的是remoteUrl，但是使用这些参数服务端都不能准确识别出来，都是提示未知消息类型。

**Comment by heavyrain2012** [comment]
> 您好，server和协议栈传输的内容都是[Payload](https://docs.wildfirechat.cn/base_knowledge/message_payload.html)，客户端上层会把这个Payload转成[MessageContent](https://docs.wildfirechat.cn/base_knowledge/message_content.html)。如果通过server api发送消息，需要直接发送payload，需要客户端把对应类型消息的payload格式告诉给server端，最简单的办法就是看一下客户端发送消息时，encode成的payload是什么格式

服务器和协议栈只有payload这一种格式，具体的消息内容需要看客户端的定义，客户端有消息内容与payload互转的规则。如果使用server api发送某种消息类型，需要跟客户端一样按照这种规则转成payload才行，你需要跟客户端确认一下文件消息转成payload是什么样的

**Comment by dilenzhu** [comment]
> > 您好，server和协议栈传输的内容都是[Payload](https://docs.wildfirechat.cn/base_knowledge/message_payload.html)，客户端上层会把这个Payload转成[MessageContent](https://docs.wildfirechat.cn/base_knowledge/message_content.html)。如果通过server api发送消息，需要直接发送payload，需要客户端把对应类型消息的payload格式告诉给server端，最简单的办法就是看一下客户端发送消息时，encode成的payload是什么格式
> 
> 服务器和协议栈只有payload这一种格式，具体的消息内容需要看客户端的定义，客户端有消息内容与payload互转的规则。如果使用server api发送某种消息类型，需要跟客户端一样按照这种规则转成payload才行，你需要跟客户端确认一下文件消息转成payload是什么样的

好的。谢谢，因为客户端的是默认的，没有修改过github的代码。

**Comment by heavyrain2012** [comment]
> > > 您好，server和协议栈传输的内容都是[Payload](https://docs.wildfirechat.cn/base_knowledge/message_payload.html)，客户端上层会把这个Payload转成[MessageContent](https://docs.wildfirechat.cn/base_knowledge/message_content.html)。如果通过server api发送消息，需要直接发送payload，需要客户端把对应类型消息的payload格式告诉给server端，最简单的办法就是看一下客户端发送消息时，encode成的payload是什么格式
> > 
> > 
> > 服务器和协议栈只有payload这一种格式，具体的消息内容需要看客户端的定义，客户端有消息内容与payload互转的规则。如果使用server api发送某种消息类型，需要跟客户端一样按照这种规则转成payload才行，你需要跟客户端确认一下文件消息转成payload是什么样的
> 
> 好的。谢谢，因为客户端的是默认的，没有修改过github的代码。

好的，让你们客户端检查一下，收到的payload跟客户端发的payload有什么不同
