### ISSUE TITLE
能够登陆服务器，但无法发送任何数据，以及显示连接失败

### ISSUE THREAD

**Issue by geffff** [wildfirechat/server#386]
我刚下了社区开源版的程序。自己搭建了服务器，能够显示OK页面。手机也更具要求改了端口。手机和服务器都是更具文档做了最小改动，现在android客户端能够登陆，并且获得用户ID和token。但始终无法发送任何数据给小机器人，每条数据都显示发送失败，并且主页面会显示连接失败。现在能够登陆，并且能改用户名，所以我就很纳闷为什么不能发送数据。我觉得应该是哪个小地方没设置好。我现在用的是小米手机。请路过的大神指点一下，万分感谢

**Comment by heavyrain2012** [comment]
文档上有无法链接的排除说明，请检查一下文档

**Comment by geffff** [comment]
> 文档上有无法链接的排除说明，请检查一下文档

翻阅了所有文档，并没有找到排除说明，能否发一下具体url

**Comment by heavyrain2012** [comment]
请参考 https://docs.wildfirechat.cn/faq/server.html 问题2
