### ISSUE TITLE
能不能给消息定义不入库,不存储?

### ISSUE THREAD

**Issue by HeyAlaia** [wildfirechat/server#387]
#### 操作说明
一对一聊天，使用专业版删除远程消息以及本地消息后，删除方式为：安卓客户端调用，clearRemoteConversationMessage

#### 表现现象
数据库中消息没有被删除

#### 预期结果
一对一聊天，使用专业版希望能够做到消息不在数据库中存储，仅传输，我已查看数据库的使用文档，发现有一个配置：mongodb.data_expire_days，这个值可以设置成0吗，我希望做到无法在数据库中查询到聊天数据，或者是聊天数据做加密存储

#### 补充条件
目前使用删除远程api无法做到删除数据库中的保留数据（mongodb以及mysql中）
#### demo对比结果
demo中也会出现这个问题

**Comment by heavyrain2012** [comment]
服务器端关于消息的数据分为2部分，一部分是消息数据，是原始数据，存储的t_message_x表中，以月分表存放。另外一部分是用户消息表t_user_message_x，存放的是用户对于的消息id，以用户id hash值分为128个表。客户端调用clearRemoteConversationMessage会删除第二张表的记录，但不会删除第一张表的记录。

如果想要删除消息表里的信息，如果只使用关系型数据库，可以另外写一个程序遍历删除5分钟之前的上面两类表的记录。如果使用了mongodb，可以把超时时间改为5分钟。这样就能确保消息只能在数据库中保留5分钟。

另外作为社交软件的运营方，有义务和责任对软件内的信息进行监管，如果不存储消息将无法进行监管，可能会有一定的风险，建议重新考虑一下这个需求。

**Comment by HeyAlaia** [comment]
明白了，那麻烦问一下 怎么把mongodb超时时间改为5分钟。是对mongodb.data_expire_days做设置吗 还是怎么操作 麻烦您能详细说一下

**Comment by heavyrain2012** [comment]
这个值 mongodb.data_expire_days 是第一次连上mongodb时，为两类消息表设置超时用的，如果已经连上过，那就不会再设置了，需要你们手动改一下表的超时时间

**Comment by HeyAlaia** [comment]
好的明白了，麻烦了
