### ISSUE TITLE
服务器跨域问题

### ISSUE THREAD

**Issue by yangjiejie12308** [wildfirechat/server#389]
我在本地测试服务器和web代码，会报错跨域问题，，这个跨域在何处设置？
![image](https://user-images.githubusercontent.com/38904385/124856236-b9ec4380-dfdc-11eb-8818-27f42521bc93.png)

**Comment by imndx** [comment]
你好，这个问题可能是你把```APP_SERVER```配置错了，配置成```IM SERVER```了，```APP_SERVER```的默认端口是```8888```

```
    // APP SERVER的地址，不能省略http(s)前缀。
    // 默认的app server使用端口是8888，注意端口号别忘记了。
    // 上线建议使用https，使用https更安全。
    //static APP_SERVER = 'http://app.wildfirechat.net:8888';
    static APP_SERVER = 'https://app.wildfirechat.net';
  
```

**Comment by yangjiejie12308** [comment]
好的
