### ISSUE TITLE
服务器缓存跟数据库数据不同步！

### ISSUE THREAD

**Issue by nineveh** [wildfirechat/server#39]
1.获取好友列表功能，数据库里面存在很多还有，通过客户端sdk获取好友列表，获取的列表跟数据库的不一致！2.设置朋友alisa 报找不到用户，数据库中存在该用户。
2.设置朋友alisa 报找不到用户，数据库中存在该用户。

**Comment by heavyrain2012** [comment]
已经解决了，请使用最新客户端和服务器的代码验证
