### ISSUE TITLE
文件存储暂不支持腾讯云存储，希望提供支持，谢谢

### ISSUE THREAD

**Issue by shuiji2018** [wildfirechat/server#391]
文件存储暂不支持腾讯云存储，希望提供支持，谢谢

**Comment by heavyrain2012** [comment]
专业版支持阿里云和[野火私有对象存储服务](https://github.com/wildfirechat/WF-minio)，是不是使用这两个也可以。腾讯云之前考虑过，在对接协议栈时有些困难，短时间难以实现
