### ISSUE TITLE
服务端API能都提供未读消息功能？？

### ISSUE THREAD

**Issue by WayneLee5991** [wildfirechat/server#392]
我们使用你们提供的web端代码来实现的聊天功能，我们的系统携带token参数跳转到你们提供的聊天界面。在你们的界面用户可以收到新消息，但是我们希望在我们系统界面也可以收到新消息提醒。这样用户不用跳转也知道自己有新消息了。

**Comment by heavyrain2012** [comment]
看一下web端的源代码，有设置接收消息回调，在回调里发送收到新消息的通知，你们也在你们自己界面监听这个消息就行了。
看一下wfcEvent.js文件，里面有ReceiveMessage事件
