### ISSUE TITLE
#@消息的快速回复功能实现思路。

### ISSUE THREAD

**Issue by zyojea** [wildfirechat/server#398]
如何实现向钉钉一样在@消息中快速回复的实现思路？

![image](https://user-images.githubusercontent.com/5368993/130177491-4bad3039-ef82-47f5-bb4f-04584a7d394a.png)
类似这样的效果

**Comment by heavyrain2012** [comment]
回复很简单，就是引用和@，在用户点击回复后，自动引用这个消息，然后@发送人就OK了。

收到看着就比较复杂一些，收到显示在消息上了，这个目前我们还有没有看出来如何实现的，我们建议简单处理，点收到时自动引用，然后回复表情收到，再发出去

**Comment by zyojea** [comment]
回复功能，按您说的使用引用实现了，现在还有个问题，就是如何实现回复条数的记录呢，在该条消息下，实现回复消息的统计，类似于已读/未读。

**Comment by heavyrain2012** [comment]
一种办法是在当前会话中记录，显示这条消息时统计它之后的回复情况，这样做可能会有消息被删除的问题。另外一种方法是在应用服务进行存储，每个回复都提交到应用服务存储，然后@消息显示时去应用服务拉取回复状态
