### ISSUE TITLE
client模块怎么运行起来

### ISSUE THREAD

**Issue by quert999** [wildfirechat/server#4]
没有doc介绍不会填啊。。
IMClient client = new IMClient("pqpxpxee","vnVczJAke+2SLT0XguQAjw7p1EXhIZ8t7nCxfr40W2PSF1eRS75BxP61jOMPx/fDQxVP2LjvrmjVzw0JaDnlaC1e/AFQrrOCGeprF63IeEB07cq/c/ivpsZWYdsrXCKRVPMIrReXX3ZJ50u/KdGwdGmS4dyxPYeJN+Xe+wZ2M5Y\u003d", "1234", "127.0.0.1", 1883);
当前这样填写但是运行之后只有一个报错
org.apache.http.NoHttpResponseException: 127.0.0.1:1883 failed to respond

**Comment by imndx** [comment]
用80端口试下。

**Comment by quert999** [comment]
控制台只输出这个
Http response error {500}

**Comment by heavyrain2012** [comment]
http://docs.wildfirechat.cn/java/

**Comment by heavyrain2012** [comment]
看这个文档
