### ISSUE TITLE
调用/admin/user/get_token接口时报以下错误

### ISSUE THREAD

**Issue by llwujunyu** [wildfirechat/server#400]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
INFO  Qos1PublishHandler 150  - imHandler fromUser=yehuo_7_userName, topic=GETTOKEN
19/08/2021 17:04:24,722 [pool-2-thread-3] INFO  IMHandler 154  - imHandler fromUser=yehuo_7_userName, clientId=A218A7E3-0FA8-4194-A103-34FA545396F7, topic=GETTOKEN
19/08/2021 17:04:24,724 [pool-2-thread-3] INFO  DatabaseStore 1597  - Database create session yehuo_7_userName,A218A7E3-0FA8-4194-A103-34FA545396F7
19/08/2021 17:04:24,725 [pool-2-thread-3] ERROR IMHandler 64  - Exception: null
19/08/2021 17:04:24,725 [pool-2-thread-3] ERROR IMHandler 65  -
java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:254)
java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:239)
io.moquette.persistence.MemorySessionStore$Session.<init>(MemorySessionStore.java:174)
io.moquette.persistence.DatabaseStore.createSession(DatabaseStore.java:1606)
io.moquette.persistence.MemorySessionStore.updateOrCreateUserSession(MemorySessionStore.java:361)
io.moquette.imhandler.GetTokenHandler.action(GetTokenHandler.java:23)
io.moquette.imhandler.GetTokenHandler.action(GetTokenHandler.java:19)
io.moquette.imhandler.IMHandler.lambda$doHandler$0(IMHandler.java:189)
cn.wildfirechat.server.ThreadPoolExecutorWrapper.lambda$execute$0(ThreadPoolExecutorWrapper.java:37)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

#### 表现现象
您好,帮忙看看,在调用/admin/user/get_token接口时报以上错误,
![image](https://user-images.githubusercontent.com/33085243/130238195-287f8e58-ea70-4c01-b9eb-65a4a76df9d6.png)
![image](https://user-images.githubusercontent.com/33085243/130238329-5d92b16b-96cf-4aed-8a55-49e9064936e1.png)
调用注册接口成功注册，然后获取token失败，然后查看日志报以上错误
#### 预期结果
返回正确的结果集

#### 补充条件
该现象必现

**Comment by heavyrain2012** [comment]
配置文件中有如下配置，请确认是否存在
message.max_queue 1024

**Comment by llwujunyu** [comment]
我刚看了下，有这个配置，我改成了0





------------------ 原始邮件 ------------------
发件人: heavyrain.lee ***@***.***&gt;
发送时间: 2021年8月21日 07:59
收件人: wildfirechat/server ***@***.***&gt;
抄送: llwujunyu ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[wildfirechat/server] 调用/admin/user/get_token接口时报以下错误 (#400)





 
配置文件中有如下配置，请确认是否存在
 message.max_queue 1024
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
