### ISSUE TITLE
数据量过大,想清理历史聊天记录

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/server#402]
数据量过大,想清理历史聊天记录
需要怎么操作,
是不是直接清理消息表,或者其他什么表

**Comment by heavyrain2012** [comment]
从0.52版本开始，IM服务会自动清理数据库消息，清理超过3年的数据。如果不需要保存3年的消息，可以手动清理数据库。关于消息的数据库有2类，一类是t_message_xxx 这类表存储的是消息内容，每月存一张表，月份与表的对应关系请参考文档常见问题。另一类是 t_user_message_xxx 这类表存储的是用户和消息的对应关系，是按照用户id hash值对128取模得到表，需要对每张表清除历史记录。
