### ISSUE TITLE
【聊天列表】需要分组，显示更多的用户

### ISSUE THREAD

**Issue by daligitim** [wildfirechat/server#403]
![a98a9ed48febcb6e9def9dc1b3481d0](https://user-images.githubusercontent.com/89564484/130898699-6aab4600-1cb3-4e85-b20e-1cc4c9f0c59f.png)

聊天列表】不仅显示这个人的名字还有别的信息，比如多大了，是我们的什么级别的客户，是哪个公司的，什么职位

消息的用户发起聊天来源于ERP，在前端放到ERP的消息下面，另一个消息来源官网，需要放到官网下面，还有一个消息来源于客户，需要放到客户下面

拉取消息不能通过后台拉取只能通过客户端来拉取吗

**Comment by heavyrain2012** [comment]
第一个需求是需要额外显示一些用户信息，这个你们需要维护好数据，UI代码都是开源的，可以修改UI代码，当UI显示时获取这些数据并展示。数据可以你们自己保存，或者导入到野火的用户信息中，野火用户信息中有多个未使用字段，比如公司，地址，社交信息，还有extra都可以使用。

第二个需要是需要对会话分类，我们会话中有个属性line，这个可以用来区分业务线，比如erp使用默认的line 0，官网用line 100，客户用101，每个线路的用户用自己的line处理业务，图上的app可以根据line来过滤不同业务线的会话

**Comment by daligitim** [comment]
好的，如果一个用户的消息，昨天发送的line是1（还不是我们的客户），今天发送的line是2（今天成为我们的客户了）这样的的话会这么区分呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月26日(星期四) 下午2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/server] 【聊天列表】需要分组，显示更多的用户 (#403)





 
第一个需求是需要额外显示一些用户信息，这个你们需要维护好数据，UI代码都是开源的，可以修改UI代码，当UI显示时获取这些数据并展示。数据可以你们自己保存，或者导入到野火的用户信息中，野火用户信息中有多个未使用字段，比如公司，地址，社交信息，还有extra都可以使用。
 
第二个需要是需要对会话分类，我们会话中有个属性line，这个可以用来区分业务线，比如erp使用默认的line 0，官网用line 100，客户用101，每个线路的用户用自己的line处理业务，图上的app可以根据line来过滤不同业务线的会话
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavyrain2012** [comment]
如果想要延续会话上下文，就不能用不同的line了，只能通过用户信息里加上标志位，比如是不是客户，是不是vip客户等，会话列表读取出来会话后再根据用户信息筛选

**Comment by daligitim** [comment]
这里的话也会还有一个问题；有点像boss的聊天会话，不同的人会有不同的状态







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月26日(星期四) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/server] 【聊天列表】需要分组，显示更多的用户 (#403)





 
如果想要延续会话上下文，就不能用不同的line了，只能通过用户信息里加上标志位，比如是不是客户，是不是vip客户等，会话列表读取出来会话后再根据用户信息筛选
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavyrain2012** [comment]
不了解boss的情况，你可以把你们的产品需求详细描述一下，
