### ISSUE TITLE
会议中，同一账号在不同端加入会议时，会踢掉之前设备上的会议，需要对此场景有相应的逻辑，可用来判断，并提示用户，当前会议再其他设备进入

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/server#404]

**Comment by heavyrain2012** [comment]
同一个账户的不同端加入会议时，服务器会踢掉该用户已经在会议的端。从被踢掉的那个端来看，就是会议断开了，没有办法判断时服务问题，还是被踢掉。所以可以把提示修改得更“中性”一点儿，比如“会议已断开”，“会议已中断”等。
