### ISSUE TITLE
聊天室訂閱成員進入與離開的通知

### ISSUE THREAD

**Issue by gctcxu** [wildfirechat/server#406]
您好! 請問可以在新增一個 wfcEvent, 讓前端可以訂閱有人進出聊天的通知嗎

**Comment by heavyrain2012** [comment]
现在服务已经具有聊天室进入/退出事件的服务回调，可以在IM服务的配置文件中搜索```chatroom.chatroom_member_update_callback```配置

如果需要在客户端用户得到进出信息，可以修改客户端更改加入聊天室的欢迎语和离开会议再见语，带上你们需要的信息

**Comment by gctcxu** [comment]
比如說是web端, 那我就是利用 joinChatroom以及quitChatroom的success callback來發送所需要的訊息對吧

**Comment by heavyrain2012** [comment]
对的
