### ISSUE TITLE
聊天室消息问题

### ISSUE THREAD

**Issue by anglamei** [wildfirechat/server#408]
#### 操作说明
web对web端或者web端对移动端聊天室的情况，A和B都在一个聊天室，A在30分钟轮询时间间隔之内一直发消息，B可以一直收到消息，但当B发消息时，A会收不到消息，或者A要等很久一轱辘的收到几条消息

#### 预期结果
A也正常接收消息

#### 补充条件
服务端聊天室默认15分钟超时退出以及永不退出，这个情况都必现

**Comment by anglamei** [comment]
另一个情况是
1.手机端进入聊天室退出后重新进入，但是接收不到消息
2.偶现web端发送聊天室消息，手机端接收不到消息

**Comment by heavyrain2012** [comment]
服务的版本是多少，api/version可以看到。还有当时是什么状态，有多少人在聊天室内，服务器什么配置

**Comment by heavyrain2012** [comment]
你们用的是专业版吗，可以微信联系我们沟通一下情况
