### ISSUE TITLE
部署IM服务器0.23的时候报了下面的错,因为不是专业做后台的,所以对这个比较陌生,麻烦帮忙看一下

### ISSUE THREAD

**Issue by clbDream** [wildfirechat/server#41]
04/07/2019 17:30:25,020 [nioEventLoopGroup-3-2] ERROR NettyMQTTHandler 113  - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=754a87ccd8ce4adb1562230239593, cause=null, errorMessage=Connection reset by peer

**Comment by heavyrain2012** [comment]
这个错误时客户端主动断开链接，不一定是问题。
请严格按照我们的文档进行部署测试（修改ip地址，不要改端口）
