### ISSUE TITLE
怎么查看Server的版本

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/server#411]
已经部署到服务器的Server，怎么查看Server的版本

**Comment by heavyrain2012** [comment]
在浏览器输入 http://{服务器ip}/api/version 会返回一个json信息，里面有git信息

**Comment by jpguo520** [comment]
"commitUserName":"imhao183",
	"commitUserEmail":"wildfirechat86@gmail.com",
	"commitMessageFull":"修正撤回消息时异常信息问题\n",
	"commitMessageShort":"修正撤回消息时异常信息问题",
	"commitTime":"20200716150237",

这是其中的一段信息，我看内容应该是0.42的是不~~我要是想升级的话有什么说明文档或者注意点吗？
![image](https://user-images.githubusercontent.com/26107242/134901079-ac235c95-cb29-4354-ac43-aa77522ff49d.png)

**Comment by heavyrain2012** [comment]
这么久没有更新了，直接更新风险比较大，建议建立测试环境，把线上的数据库拷贝一份到测试环境，然后在测试环境升级验证。

升级时注意野火[Release](https://github.com/wildfirechat/server/releases/tag/0.71)的升级说明。建议先 ”请执行update flyway_schema_history set checksum = 0 where script = 'V17__add_default_sensitive_word.sql' “，然后启动新版本，第一次启动会等待较长时间不要中断（升级成功后，以后再启动就很快了），等启动成功后再验证各种功能。
