### ISSUE TITLE
idea运行server服务后,访问/api/version,返回的json全部为空

### ISSUE THREAD

**Issue by zhangxiucai12** [wildfirechat/server#412]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1.ide:idea
2.jdk:jdk1.8.0_281
3.server版本:server-71

#### 表现现象
已经配置mysql,已经修改broker模块下config包的conf配置的server.ip及embed.db
启动之后:
mysql的表已经全部建立,logs日志文件夹的日志正常,
浏览器访问http://192.168.50.234/api/version,返回的json全部为空
![image](https://user-images.githubusercontent.com/43491996/135118182-651e264d-cd08-43b1-9fdf-47d59fb66b59.png)
![image](https://user-images.githubusercontent.com/43491996/135118220-d8538fee-6fd8-4c42-b8ce-02ab681b38c1.png)

**Comment by heavyrain2012** [comment]
这个不影响的，当编译出来软件包放到服务器上就会有数据的

**Comment by zhangxiucai12** [comment]
> 这个不影响的，当编译出来软件包放到服务器上就会有数据的

谢谢
