### ISSUE TITLE
JMeter Sampler 为何移除了？

### ISSUE THREAD

**Issue by gang83211** [wildfirechat/server#413]
#### 问题说明
于 commit [5ed45ef4](https://github.com/wildfirechat/server/tree/5ed45ef414a824ebb73f2127484660d049810a61/wildfire_jmeter) 前还有JMeter的扩充Sampler，为何后面就移除了呢？

因野火采用私有协议，没有新的sampler，我们无法做压力测试，所以才在此提问，谢谢。

**Comment by heavyrain2012** [comment]
因为问题很多，另外也难以模拟客户端情况，我们维护困难，所以就不再维护了。如果想要压力测试，可以用server api来发送消息。
