### ISSUE TITLE
 加好友时，双方互扫码，一方同意了两人加为好友，另一人的接受按钮还是会显示

### ISSUE THREAD

**Issue by littlewang** [wildfirechat/server#414]
#### 操作说明
A、B两个人互扫码加好友,b点接受按钮
#### 表现现象
两人成为好友 A的新的好友列表里 还是有一条来自B的 加好友 请求，而且这条信息会一直存在点不掉

#### 预期结果
加好友成功后，A的好友申请列表里没有来自B的好友申请

#### 补充条件
t_friend_request 这个表里产生了两条 数据只更新了一条，应该更新两条的

**Comment by heavyrain2012** [comment]
已经解决，请更新最新版本验证
