### ISSUE TITLE
云服务器配置选择？假设10W在线用户一般宽带选择多少

### ISSUE THREAD

**Issue by fushilu06** [wildfirechat/server#42]
如题
![image](https://user-images.githubusercontent.com/52439659/60663583-37cb6080-9e92-11e9-87c0-c9432e6e3d34.png)

**Comment by heavyrain2012** [comment]
请参考 [文档 ](http://docs.wildfirechat.cn/server/hardware_requirement.html)

**Comment by fushilu06** [comment]
好的
