### ISSUE TITLE
华为安装运行提示危险应用 无法正常安装

### ISSUE THREAD

**Issue by APPX-Studio** [wildfirechat/server#421]
如题 鸿蒙手机也不行。
![编组](https://user-images.githubusercontent.com/49307767/139166429-7c638035-ba72-4454-8086-d08166366dec.jpg)

**Comment by heavyrain2012** [comment]
这个问题，可能是有人什么也没改，直接拿开源代码去做了非法的事情导致的。

可以这样尝试：

改一下包名(applicationId)
换成自己的签名。
