### ISSUE TITLE
聊天室功能

### ISSUE THREAD

**Issue by gctcxu** [wildfirechat/server#423]
1. 撤回
這邊整體的想法是聊天室也可以有管理組, 分為管理者, 一般用戶
管理者可以撤回其他人的訊息, 一般使用者不行
2. 標記(mention)
依樣支援 conversationInfo裡面的hasMentioned為true, 我一進聊天室就可以知道我曾被標記過, 而不是要自行往上翻訊息才知道

**Comment by heavyrain2012** [comment]
1. 撤回
在聊天室内用户撤回自己的消息UI有点儿问题，今天已经解决了，请更新最新iOS和Android代码，检查用户是否可以在聊天室内撤回自己的消息。客户端是没有办法在聊天室内撤回别人的消息，可以通过server api来撤回消息，你们可以自己来维护管理员的列表，然后管理员撤回聊天室消息时调用应用服务，应用服务再调用server api来撤回消息。

**Comment by heavyrain2012** [comment]
2. 標記(mention)
这个功能在聊天室里无法完整实现，因为聊天室数据不是全量同步的，只能在加入聊天室时拉取指定数目的历史消息，而且是不存储在本地数据库的，协议栈没有维护聊天室会话的未读和mention状态，因此聊天室无法做到群组一样的功能。你们可以在UI层自己记录，收到消息后检查是不是mention的消息，如果是记录下来提示给用户，还要记录mention消息的已读/未读的状态等
