### ISSUE TITLE
聊天列表问题及聊天室历史消息问题

### ISSUE THREAD

**Issue by Neroliuxx** [wildfirechat/server#425]
一个账号在一台设备上已经和其他账号进行聊天有3段聊天记录，每段聊天内有内容若干，当用该账号登录至另一台设备时，显示的消息数量以及消息内的内容数量不全。请问是什么原因导致？如何可以正常将聊天记录转移至其他设备上？同样，官方DEMO是可以做到这些功能的实现的。

另外，官方DEMO中聊天室是可以看到历史消息的，但IOS和Android接入野火后聊天室的历史消息无法看到了，进入聊天室第一条是欢迎XXX加入聊天室，请问是有什么配置需要更改吗？

**Comment by heavyrain2012** [comment]
一个账号在一台设备上已经和其他账号进行聊天有3段聊天记录，每段聊天内有内容若干，当用该账号登录至另一台设备时，显示的消息数量以及消息内的内容数量不全。请问是什么原因导致？如何可以正常将聊天记录转移至其他设备上？同样，官方DEMO是可以做到这些功能的实现的。
IM服务配置中有个漫游消息条数的配置，默认社区版IM服务是1024条，如果不够可以适当调大，但调大会增大内存占用。专业版可以支持更高的漫游条数。另外也可以开启拉取远程消息的功能，开启后当客户端本地没有消息时可以从服务器加载。

另外，官方DEMO中聊天室是可以看到历史消息的，但IOS和Android接入野火后聊天室的历史消息无法看到了，进入聊天室第一条是欢迎XXX加入聊天室，请问是有什么配置需要更改吗？
可能是拉取远程消息的功能没有开启，开启就可以拉取了。
