### ISSUE TITLE
WFCMessage.java

### ISSUE THREAD

**Issue by wenxiongluo** [wildfirechat/server#426]
你好，我想在这个WFCMessage.java类里面的Message对象里加一个字段，但是没找到WFCMessage.proto文件，如果没这个源文件的话应该怎么添加字段

**Comment by heavyrain2012** [comment]
您好，为了便于控制版本我们没有开源协议，消息内容中有extra字段，可以用extra字段来扩展消息，也可以自定义消息发送任何你们想要的内容。如果无法满足你们二次开发需要，可以描述具体场景供我们分析解决办法

**Comment by wenxiongluo** [comment]
你好，我在这个在这个WFCMessage.java类里面的Message对象中未找到extra字段，我想加一个消息状态的字段

**Comment by heavyrain2012** [comment]
WFCMessage中没有extra字段，但在客户端可以为消息设置localExtra，这个只能存储在本地不能多端同步，是不是可以把扩展信息放到这里。
另外还是没有弄明白您的具体业务情况，“加一个消息状态的字段”的目的是什么，请详细描述一下业务情况和使用这个字段的目的

**Comment by wenxiongluo** [comment]
就是消息已读未读这种状态，我想加个这样的字段。

**Comment by heavyrain2012** [comment]
做消息已读/未读应该不需要在message中添加字段的。消息同步到客户端后，阅读之后，修改message这个字段再发回去是吗？有人是用自定义消息来实现的，感觉不需要添加字段

**Comment by wenxiongluo** [comment]
如果是状态修改同步可以自定义信息，但是应该要保存这个状态吧，所以我想message&nbsp;中应该有个字段来保存消息的状态




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/server] WFCMessage.java (Issue #426)





 
做消息已读/未读应该不需要在message中添加字段的。消息同步到客户端后，阅读之后，修改message这个字段再发回去是吗？有人是用自定义消息来实现的，感觉不需要添加字段
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavyrain2012** [comment]
消息在客户端有个localExtra字段可以保存在本地的扩展信息

**Comment by wenxiongluo** [comment]
服务器不需要保存这个状态吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 晚上6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/server] WFCMessage.java (Issue #426)





 
消息在客户端有个localExtra字段可以保存在本地的扩展信息
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavyrain2012** [comment]
不需要，另外即使Message加了属性也是没有办法同步到服务器的吧
