### ISSUE TITLE
各位 common 和sdk这两个没有开源的把？

### ISSUE THREAD

**Issue by 3thinkthendoit** [wildfirechat/server#428]
common 和sdk这两个没有开源的把

**Comment by heavyrain2012** [comment]
请检查

https://github.com/wildfirechat/server/tree/wildfirechat/common
https://github.com/wildfirechat/server/tree/wildfirechat/sdk

**Comment by 3thinkthendoit** [comment]
> 

tks

**Comment by 3thinkthendoit** [comment]
tks!
