### ISSUE TITLE
如何更改自带的系统管理员这个用户的 用户头像(_portrait)和用户名称(_display_name)这两个属性

### ISSUE THREAD

**Issue by KingOfHui** [wildfirechat/server#429]
#### 操作说明
更改了数据库中的t_user表中的admin用户管理员的 用户头像(_portrait)和用户名称(_display_name) 不起作用
![image](https://user-images.githubusercontent.com/30006239/143512090-83a18311-f62b-4d61-a52c-b7ae7b5822aa.png)

#### 表现现象
客户端那边获取的头像portrait为空，displayName为系统管理员
![image](https://user-images.githubusercontent.com/30006239/143512147-87ec2637-0b0d-47cf-b002-00de8d0b2833.png)

#### 预期结果
希望客户端能够得到数据库中正确的 displayName和portrait

#### 补充条件
必现

**Comment by heavyrain2012** [comment]
IM服务中有内存缓存，如果修改数据库时缓存中已经有这个数据了，客户端同步到的将还是旧数据。需要通过server api来修改用户信息。如果是直接改数据库，需要把用户的_dt字段增加1（用来同步的），然后再重启服务
