### ISSUE TITLE
ByteBuf 可读字节为0

### ISSUE THREAD

**Issue by wenxiongluo** [wildfirechat/server#431]
你好，你们在ActionHandler 类 channelRead0 方法 里有个
![image](https://user-images.githubusercontent.com/33018137/144209651-ae1dc41d-a123-40ad-872a-d82ed0e520bf.png) 
操作，这个操作会让BetyBuf 的可读字节为0 ，导致后面代码逻辑错误。我看新版本你们也没改啥不知道你们有没有遇到这个问题

**Comment by heavyrain2012** [comment]
我们测试服务功能都正常啊，你们是不是做了什么改动？
