### ISSUE TITLE
robot 接收消息，从而自动回复

### ISSUE THREAD

**Issue by huazaihuola** [wildfirechat/server#434]
创建一个user 为我们项目的小秘书，类似公众号（只有一个），
问题是，我想要实时的接收这个小秘书被人发送的消息，我通过用户发送给小秘书的数据，来自动回复，
不知道现在有没有这样的方法来接收用户发给特定用户的消息，或者叫订阅，我找了很久没发现，求指导。

**Comment by imndx** [comment]
支持robot类型的user的，可以通过[server api](https://docs.wildfirechat.cn/server/admin_api/user_api.html)创建机器人，创建的时候，需要配置一个***机器人消息回掉地址***，之后用户发送给该机器人的消息，都会通过***机器人消息回调地址***回调，之后，可以通过[robot api](https://docs.wildfirechat.cn/server/robot_api/)发送消息等。

机器人服务，可以参考[robot server](https://github.com/wildfirechat/robot_server)

**Comment by huazaihuola** [comment]
辛苦了，我回去试一下！
