### ISSUE TITLE
[bug] 不正确的群组id也能获取到群组信息，添加群成员，发送消息... (MySQL 查询问题)

### ISSUE THREAD

**Issue by shenjingfs** [wildfirechat/server#435]
#### 操作说明
Flutter的APP做了个搜索并加入群组的功能：
1. 调用 getGroupInfo('aabbCCDD ', refresh: true) 获取群组信息     （带的参数aabbCCDD后面有一个空格）
2. 如果有结果，显示结果的群组信息
3. 点击“加入群组”，调用addGroupMembers把自己加入群组

数据库：MySQL 5.7 
server版本：0.76

#### 表现现象
数据库t_group里_gid为 'AABBCCDD'
getGroupInfo返回值不为null，返回的groupInfo里的target(即groupId) 为 'aabbCCDD '，其他信息与 'AABBCCDD' 群组一致。
而且用户能成功把自己加入了群组，这时会有一条加入群组的通知，但是这个通知消息的target是不正确的  'aabbCCDD '，这时会话列表会有两个除conversationId不一样其他信息都一样的群组会话，而且其他用户都能在这两个会话发送消息。

#### 预期结果
对于不正确的groupId，客服端调用接口
1. getGroupInfo应该返回null
2. addGroupMembers应该失败
3. sendMessage应该失败

#### 补充
不是服务端开发，下面的补充可能不是太准确。
后面搜索了下 MySQL查询 空格敏感及部分字段大小写敏感问题
创建MySQL 的时候 COLLATE 为 utf8mb4_unicode_ci
utf8mb4_unicode_ci 大小写不敏感，后面手动把数据库里_gid的COLLATE 改为 utf8mb4_bin 暂时解决，搜索'aabbccdd'会正确返回null
https://github.com/wildfirechat/server/blob/ace743572627a98d23680ef9fd230b7498ef0551/broker/src/main/java/win/liyufan/im/DBUtil.java#L101

后面还有一个问题是，由于APP旧版本没有对用户输入的空格做处理，MySQL后置空格又不敏感，导致搜索 'AABBCCDD ' 能获取到 _gid为 'AABBCCDD' 的群组信息
https://github.com/wildfirechat/server/blob/ace743572627a98d23680ef9fd230b7498ef0551/broker/src/main/java/io/moquette/persistence/DatabaseStore.java#L1863-L1900
server里的getPersistGroupInfo，没有查询_gid，返回的groupId就是参数带入的groupId，如果返回的groupId是数据库的数据，这样app端也可以根据搜索的groupId和返回的groupId做比较，不一致的话做些处理

网上说是MySQL查询加上BINARY可以严格区分大小写和空格，不过server好像还有使用另一种数据库，可能这样更好：查询语句加上_gid，然后先检查返回数据库的_gid和参数的groupId 是否一致，不一致直接返回null

可能还有其他一些地方用到了里的查询结果，可能也要做些处理：addGroupMembers, canSendMessageInGroup...

**Comment by heavyrain2012** [comment]
非常感谢，确实我们的非常业余的错误，我们尽快修正

**Comment by heavyrain2012** [comment]
已经更新版本了，新版本sql会把所有key都改为大小写敏感，其他一些字段还是大小写不敏感，还有野火生成id的方法也做了修改，改成生成9位小写字母和数字组成的id（原来是8位大小写字母和数字）。这样数据库的key值就可以避免了。

另外空格的问题，前后的字符串都应该trim掉，我们稍后会在客户端和服务器都加上检查，移除前后无效的空格tab字符等
