### ISSUE TITLE
包含敏感词汇的链接会分享给好友会失败

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#436]
在聊天中分享的链接包含敏感词汇试，链接分享失败。
比如下面格式的链接：

https://xxx.com/IT3KPHSb

后面字符串随机生成，碰巧包含了敏感词汇。导致链接无法分享

**Comment by heavyrain2012** [comment]
最新版本已经解决，如果链接里有敏感词是不会被过滤的
