### ISSUE TITLE
频道回调问题，无论automatic改成什么，结果都是过了一点时间就不回掉，以及automatic=1的bug

### ISSUE THREAD

**Issue by MriceZxu** [wildfirechat/server#437]
1、频道回调问题，IM服务重启会回调，但是过一段时间就不会在回调，咨询过，说automatic=0会影响回调，改成1结果还是一样
2、只有当automatic=1时，但这会导致频道的拥有者会无缘无故看到自己在频道一条发送的消息

**Comment by heavyrain2012** [comment]
已经解决，请验证
