### ISSUE TITLE
需求：WFCMessage文件可以自己生成或者messageId改为字符串形式

### ISSUE THREAD

**Issue by xiefangzhenz** [wildfirechat/server#44]
理由：
       字符串形式扩展性更好
       （1）根据业务需求，添加对Id添加字母下划线等特殊符号
       （2）表名的计算方式更加灵活
       （3）无规则数字不利于后期统计

**Comment by heavyrain2012** [comment]
数字型id已经与系统深度绑定，无法改成字符串id。
当时选型时考虑到了消息体的大小，数字型id只占用8个字节，可以保证用于不会重复，而且还带有时间和节点信息。使用字符型id所需要的空间就大多了，而且无法携带信息。

**Comment by xiefangzhenz** [comment]
@heavyrain2012 明白了，感谢
