### ISSUE TITLE
客户端A显示消息发送失败，其实已经发送成功了的问题

### ISSUE THREAD

**Issue by haitun521** [wildfirechat/server#443]
客户端A发送消息给客户端B，由于网络原因没有收到服务器的ack响应，客户端A界面上会显示发送失败， 但这个时候客户端B已经收到消息了，并回复了这条消息，客户端A拉取最新消息，并没有拉取到A发送失败的消息，依旧会显示发送失败，其实是已经成功了
![image](https://user-images.githubusercontent.com/9667904/147556328-5690d238-9b3f-4814-820a-32e4c99b355e.png)

**Comment by heavyrain2012** [comment]
这是个难以选择的问题，如果去掉这个地方也不好。可以想办法优化网络，网络好了产生问题的几率就小了

**Comment by haitun521** [comment]
还有其他方式解决嘛？

**Comment by heavyrain2012** [comment]
没有其他更好的办法了。你们用户和服务之间是跨国网络吗，可以购买阿里云亚马逊全球加速服务来提高网络质量

**Comment by haitun521** [comment]
不是，就是在国内使用
