### ISSUE TITLE
希望针对撤回讯息新增权限显示撤回与否

### ISSUE THREAD

**Issue by EF03** [wildfirechat/server#444]
現在只要撤回消息就会有一条提示，xxx撤回了一条消息
希望有管理权限 有可控开关 不要显示这条消息

**Comment by imndx** [comment]
有两种种方案
1. 当需要撤回但是不显示撤回消息时，别直接调用撤回api，而是通过 server api 调用删除。
2. 在显示的地方控制，判断是撤回消息的人是否有 撤回但不显示消息 的权限，如果有的会，将对应的消息 UI 的高度置为 0

**Comment by imndx** [comment]
> 

调用 server api，不能直接调用，通过你们的 app server 去调用。

**Comment by EF03** [comment]
It's work, thx.
