### ISSUE TITLE
希望新增搜索功能能有个开关能搜索得到群组

### ISSUE THREAD

**Issue by EF03** [wildfirechat/server#446]
在群管理中有查找方式
希望是可以当开关启动时
可以依照查找方式设定搜索得到开放的公开群组

**Comment by heavyrain2012** [comment]
我们调查过搜索群组的需求，我们没有办法做成比较通用的模式，因此需要你们自己来做二次开发。可以放到一个服务中去，比如应用服务，可以直接读取IM的数据库，也可以在这个服务中保存一份数据
