### ISSUE TITLE
双网环境，网络自动切换时，希望各端 SDK 提供中提供回调或查询方法

### ISSUE THREAD

**Issue by TaroFang** [wildfirechat/server#448]
#### 使用场景
IM 服务在ip授权模式下，使用内网 + 公网， IM 中进行内外网切换的时候， 希望能给一个回调，通知业务侧， 当前正在使用的是公网呢？还是内网？

如果SDK 提供回调 或者 查询方法   那么业务侧接入也会方便得多。

**Comment by heavyrain2012** [comment]
此功能在客户端SDK已经添加，请联系我们更新版本
