### ISSUE TITLE
如果不想在服务端存储聊天记录，该怎么做

### ISSUE THREAD

**Issue by wblzu** [wildfirechat/server#45]
由于一些业务需求，发出某条消息后，对方选择同意或者拒绝。此时，想更新服务器中这条信息的选择状态，该怎么做。 当然，手机终端app可以更新这条消息的选择状态，但是服务器端无法更新，，这样的话就会带来一些问题。比如，删除手机app之后，再请求会话和消息数据，这条业务消息仍然不是期望的状态，而是原始状态。

**Comment by heavyrain2012** [comment]
业务应该和IM来分开，不能把业务状态放到消息体中，可以使用消息作为通知。对于你这个需求，应该把状态存储到应用服务器，展示消息时去应用服务获取状态
