### ISSUE TITLE
我有个图片违规了，被下架了。 到处找找不到   ./media里面也找了。没有， 有没有可能在数据库存着，野火那些地方还可以储存图片？

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#450]
没有经过特别的其他设置

我看配置文件里面有个 ./meida  里面没东西。

有个图片出问题了。现在找不到在哪里呢

**Comment by heavyrain2012** [comment]
这个是im服务程序所在的目录，你看一下跟bin，config同级目录有没有一个media的目录
