### ISSUE TITLE
接收端消息重复接收问题

### ISSUE THREAD

**Issue by blueoa** [wildfirechat/server#452]
#### 操作说明
APP在弱网环境发送消息，发送端显示发送失败，但是接端已经接收到消息。此时发送端点击重新发送，接收端会再接收到一条相同的消息

#### 表现现象
因为服务端发送給客户端消息为QOS-0所以不会进行重试，可能导致客户端丢失SendMessage的ACK
同时messageId为服务端生成，服务端无法进行去重，导致消息出现重复入库并发送

#### 预期结果
希望messageId由客户端进行生产并保证唯一，达到接收端仅收到一条消息

#### 补充条件
只有在弱网环境偶现，所有平台都会出现相同问题

#### demo对比结果
demo也会出现同样问题

**Comment by heavyrain2012** [comment]
请检查链接的问题25 https://docs.wildfirechat.cn/faq/general.html#消息什么情况下会重复？
