### ISSUE TITLE
demo里视频比较卡，有没有解决方案

### ISSUE THREAD

**Issue by 337077418** [wildfirechat/server#455]

**Comment by heavyrain2012** [comment]
您说的视频是视频电话，还是播放视频消息？如果方便的话请提供个录像

**Comment by 337077418** [comment]
视频通话，我们公司计划购买一个IM二开，今天下载了贵公司的demo测试了一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/server] demo里视频比较卡，有没有解决方案 (Issue #455)





 
您说的视频是视频电话，还是播放视频消息？如果方便的话请提供个录像
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavyrain2012** [comment]
是下载我们源码编译安装后测试的，还是下载我们编译好的demo测试的？是android平台还是ios平台？你们在国内还是在国外？
