### ISSUE TITLE
客户端如何获取@消息中的mentionType和mentionTargets？

### ISSUE THREAD

**Issue by sage-47** [wildfirechat/server#456]
## 需求
希望对@消息中的@部分进行高亮展示，类似钉钉。

#### 问题
1. 对于@消息，客户端接收时mentionType和mentionTargets已经为空，不知是否是因为sdk自动处理成msgStatus = 3 or msgStatus = 4，并不会将mention字段信息存储到客户端。
2. 目前我们仅通过字符串正则匹配进行高亮，但这样会将一些非真实的@消息也高亮。
3. 如果我们希望端上能够拿到mention信息，用于判断是否需要高亮展示消息内容，是否需能够提供该功能支持？或者有什么方案建议？

**Comment by heavyrain2012** [comment]
对于@消息，客户端接收时mentionType和mentionTargets已经为空，不知是否是因为sdk自动处理成msgStatus = 3 or msgStatus = 4，并不会将mention字段信息存储到客户端。
是的，客户端收到消息后，如果mentionType是2，那么msgStatus就是4；如果mentionType为1且mentionTargets包含当前用户，那么msgStatus就是3。

如果我们希望端上能够拿到mention信息，用于判断是否需要高亮展示消息内容，是否需能够提供该功能支持？或者有什么方案建议？
你可以看一下ui层的源码，当用户点击发送后，会处理mentinInfo，判断是@所有人还是@某些人，然后填写messageContent的mentionType和mentionTargets。这两个信息不足于还原@到的用户和位置信息，如果想要做成钉钉一样，就需要把mentinInfo整体打包进messagecontent内。可以把mentinInfo序列化到messageContent的extra中，当需要mentionInfo时反序列化这个extra就好了。

**Comment by heavyrain2012** [comment]
题外话一下，做成钉钉那样好像也没有多大好处，像微信这样保持简单也挺好的

**Comment by sage-47** [comment]
> 



> 对于@消息，客户端接收时mentionType和mentionTargets已经为空，不知是否是因为sdk自动处理成msgStatus = 3 or msgStatus = 4，并不会将mention字段信息存储到客户端。 是的，客户端收到消息后，如果mentionType是2，那么msgStatus就是4；如果mentionType为1且mentionTargets包含当前用户，那么msgStatus就是3。
> 
> 如果我们希望端上能够拿到mention信息，用于判断是否需要高亮展示消息内容，是否需能够提供该功能支持？或者有什么方案建议？ 你可以看一下ui层的源码，当用户点击发送后，会处理mentinInfo，判断是@所有人还是@某些人，然后填写messageContent的mentionType和mentionTargets。这两个信息不足于还原@到的用户和位置信息，如果想要做成钉钉一样，就需要把mentinInfo整体打包进messagecontent内。可以把mentinInfo序列化到messageContent的extra中，当需要mentionInfo时反序列化这个extra就好了。
----------------
目前产品是这样设计的😂
我们有想过将mentioninfo放到extra中，但由于msgStatus随时会变更，已读之后，就不知道文本消息中哪一条是普通消息，哪条是包含@信息的消息，貌似就需要每一条消息都尝试反序列化extra了。
还是你们建议对@消息使用特殊消息类型？

**Comment by heavyrain2012** [comment]
> 

是需要对extra做反序列化，可以在文本消息中加个关于mention的字段，然后在消息的encode和decode时处理这个字段和extra，encode时把mention信息序列化道extra中，decode时反序列化extra为mention信息
