### ISSUE TITLE
调用ChannelServiceApi发送消息的方法，设置了targets多值，不在targets里的人也会看到信息

### ISSUE THREAD

**Issue by MriceZxu** [wildfirechat/server#457]
调用ChannelServiceApi发送消息的方法
sendMessage(int line, List<String> targets, MessagePayload payload)
设置了targets多值，不在targets里的人也会看到信息

**Comment by heavyrain2012** [comment]
怎么看见的消息？是不在targets目录的用户能收到消息，还是说收不到，但是可以看到历史消息？

**Comment by heavyrain2012** [comment]
还有提供一下IM服务的版本信息

**Comment by MriceZxu** [comment]
> 还有提供一下IM服务的版本信息

20220125221236

**Comment by MriceZxu** [comment]
> 怎么看见的消息？是不在targets目录的用户能收到消息，还是说收不到，但是可以看到历史消息？

调用方法发送后，有关注频道的人，但是没在targets列表，会收到信息

**Comment by heavyrain2012** [comment]
频道的属性是什么，属性的说明在这里https://docs.wildfirechat.cn/base_knowledge/channel.html

**Comment by MriceZxu** [comment]
> 频道的属性是什么，属性的说明在这里https://docs.wildfirechat.cn/base_knowledge/channel.html

15

**Comment by MriceZxu** [comment]
> 怎么看见的消息？是不在targets目录的用户能收到消息，还是说收不到，但是可以看到历史消息？
发多人的时候会出现这种情况，历史消息会比较严重

**Comment by MriceZxu** [comment]
> 怎么看见的消息？是不在targets目录的用户能收到消息，还是说收不到，但是可以看到历史消息？

发多人的时候会出现这种情况，历史消息会比较严重

**Comment by MriceZxu** [comment]
出现看到非自己的信息，大概有一下三种情况：
1、发送消息targets是多人时，不是很频繁出现
2、未清理前，会看历史消息，如果是刷新也会出现这个问题
2、清理缓存，重新登陆，重新拉去历史消息，会比较严重

**Comment by heavyrain2012** [comment]
我们仔细地测试了这个问题，没有发现你说的问题。请提供更详细的复现的方法和视频录像等

**Comment by heavyrain2012** [comment]
我们的测试方法如下，测试时注意把```AdminUrl```,  ```AdminSecret```,  ```IMUrl```替换成你们IM服务实际的地址。然后测试时在发送消息之前断点停住，然后找用户关注频道，再执行频道发送消息，检查用户是否收到消息错误。如果能够复现，请录像给我们看。
```
static void testChannel() throws Exception {
        //1. 先使用admin api创建频道
        AdminConfig.initAdmin(AdminUrl, AdminSecret);
        String channelId = "testChannel";
        InputCreateChannel inputCreateChannel = new InputCreateChannel();
        inputCreateChannel.setName("testChannel");
        inputCreateChannel.setOwner("userId10");
        String secret = "channelsecret";
        inputCreateChannel.setTargetId(channelId);
        inputCreateChannel.setSecret(secret);
        inputCreateChannel.setState(15);
        IMResult<OutputCreateChannel> resultCreateChannel = GeneralAdmin.createChannel(inputCreateChannel);
        if (resultCreateChannel != null && resultCreateChannel.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
            System.out.println("create channel success");
        } else {
            System.out.println("create channel failure");
            System.exit(-1);
        }


        //2. 初始化api，注意端口是80，不是18080
        ChannelServiceApi channelServiceApi = new ChannelServiceApi(IMUrl, channelId, secret);


        //3. 断点停住这行，多个用户关注此公众号，包括用户 userId2 和 userId3
        System.out.println("关注之后发送消息");
        
        //4. 发送测试消息，分别给用户2和用户3
        MessagePayload payload = new MessagePayload();
        payload.setType(1);


        for (int i = 0; i < 10; i++) {
            int n = i%2 + 2;
            payload.setSearchableContent("hello world " + i + " to user " + n);
            List<String> targets = new ArrayList<>();
            targets.add("userId" + n);
            IMResult<SendMessageResult> resultSendMessage = channelServiceApi.sendMessage(0, targets,payload);
            if (resultSendMessage != null && resultSendMessage.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
                System.out.println("send message to all the subscriber success");
            } else {
                System.out.println("send message to all the subscriber  failure");
                System.exit(-1);
            }
        }
    }
```

**Comment by MriceZxu** [comment]
> 我们的测试方法如下，测试时注意把`AdminUrl`, `AdminSecret`, `IMUrl`替换成你们IM服务实际的地址。然后测试时在发送消息之前断点停住，然后找用户关注频道，再执行频道发送消息，检查用户是否收到消息错误。如果能够复现，请录像给我们看。
> 
> ```
> static void testChannel() throws Exception {
>         //1. 先使用admin api创建频道
>         AdminConfig.initAdmin(AdminUrl, AdminSecret);
>         String channelId = "testChannel";
>         InputCreateChannel inputCreateChannel = new InputCreateChannel();
>         inputCreateChannel.setName("testChannel");
>         inputCreateChannel.setOwner("userId10");
>         String secret = "channelsecret";
>         inputCreateChannel.setTargetId(channelId);
>         inputCreateChannel.setSecret(secret);
>         inputCreateChannel.setState(15);
>         IMResult<OutputCreateChannel> resultCreateChannel = GeneralAdmin.createChannel(inputCreateChannel);
>         if (resultCreateChannel != null && resultCreateChannel.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
>             System.out.println("create channel success");
>         } else {
>             System.out.println("create channel failure");
>             System.exit(-1);
>         }
> 
> 
>         //2. 初始化api，注意端口是80，不是18080
>         ChannelServiceApi channelServiceApi = new ChannelServiceApi(IMUrl, channelId, secret);
> 
> 
>         //3. 断点停住这行，多个用户关注此公众号，包括用户 userId2 和 userId3
>         System.out.println("关注之后发送消息");
>         
>         //4. 发送测试消息，分别给用户2和用户3
>         MessagePayload payload = new MessagePayload();
>         payload.setType(1);
> 
> 
>         for (int i = 0; i < 10; i++) {
>             int n = i%2 + 2;
>             payload.setSearchableContent("hello world " + i + " to user " + n);
>             List<String> targets = new ArrayList<>();
>             targets.add("userId" + n);
>             IMResult<SendMessageResult> resultSendMessage = channelServiceApi.sendMessage(0, targets,payload);
>             if (resultSendMessage != null && resultSendMessage.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
>                 System.out.println("send message to all the subscriber success");
>             } else {
>                 System.out.println("send message to all the subscriber  failure");
>                 System.exit(-1);
>             }
>         }
>     }
> ```

[](url)

> 我们仔细地测试了这个问题，没有发现你说的问题。请提供更详细的复现的方法和视频录像等


https://user-images.githubusercontent.com/16078866/153154560-e1c6de99-d0f3-4718-a258-8fc15de16f18.mp4

**Comment by MriceZxu** [comment]
> 我们的测试方法如下，测试时注意把`AdminUrl`, `AdminSecret`, `IMUrl`替换成你们IM服务实际的地址。然后测试时在发送消息之前断点停住，然后找用户关注频道，再执行频道发送消息，检查用户是否收到消息错误。如果能够复现，请录像给我们看。
> 
> ```
> static void testChannel() throws Exception {
>         //1. 先使用admin api创建频道
>         AdminConfig.initAdmin(AdminUrl, AdminSecret);
>         String channelId = "testChannel";
>         InputCreateChannel inputCreateChannel = new InputCreateChannel();
>         inputCreateChannel.setName("testChannel");
>         inputCreateChannel.setOwner("userId10");
>         String secret = "channelsecret";
>         inputCreateChannel.setTargetId(channelId);
>         inputCreateChannel.setSecret(secret);
>         inputCreateChannel.setState(15);
>         IMResult<OutputCreateChannel> resultCreateChannel = GeneralAdmin.createChannel(inputCreateChannel);
>         if (resultCreateChannel != null && resultCreateChannel.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
>             System.out.println("create channel success");
>         } else {
>             System.out.println("create channel failure");
>             System.exit(-1);
>         }
> 
> 
>         //2. 初始化api，注意端口是80，不是18080
>         ChannelServiceApi channelServiceApi = new ChannelServiceApi(IMUrl, channelId, secret);
> 
> 
>         //3. 断点停住这行，多个用户关注此公众号，包括用户 userId2 和 userId3
>         System.out.println("关注之后发送消息");
>         
>         //4. 发送测试消息，分别给用户2和用户3
>         MessagePayload payload = new MessagePayload();
>         payload.setType(1);
> 
> 
>         for (int i = 0; i < 10; i++) {
>             int n = i%2 + 2;
>             payload.setSearchableContent("hello world " + i + " to user " + n);
>             List<String> targets = new ArrayList<>();
>             targets.add("userId" + n);
>             IMResult<SendMessageResult> resultSendMessage = channelServiceApi.sendMessage(0, targets,payload);
>             if (resultSendMessage != null && resultSendMessage.getErrorCode() == ErrorCode.ERROR_CODE_SUCCESS) {
>                 System.out.println("send message to all the subscriber success");
>             } else {
>                 System.out.println("send message to all the subscriber  failure");
>                 System.exit(-1);
>             }
>         }
>     }
> ```

已经把录屏发到微信群里了，确实存在问题

**Comment by heavyrain2012** [comment]
我们复现问题了，当targets为多人时处理有错误，请联系我们更新IM服务版本。

**Comment by heavyrain2012** [comment]
targets为多人时的处理还不是特别完美，现在时多人时保存消息只保存了第一个人，这样如果清空历史消息再拉取，第二个人及以后可能就拉取不到，如果是重要消息，请每次只发一个人
