### ISSUE TITLE
接口访问频次问题

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/server#458]
## 访问频次问题
服务器超过访问频次会警告，什么样的请求会被记录为累计次数。
```
    ##API接口限频设置，时间是10秒内允许的请求次数。
    ##管理api频率限制，默认是10秒10000次。
    http.admin.rate_limit 10000
    ##机器人api频率限制，默认是10秒1000次，按照机器人ID区分。
    http.robot.rate_limit 1000
    ##频道api频率限制，默认是10秒1000次，按照频道ID区分。
    http.channel.rate_limit 1000

    ##客户端请求频率限制，默认是10秒100次。通常情况下不要修改这个值。
    client.request_rate_limit 100
```

**Comment by heavyrain2012** [comment]
客户端的请求频率限制是每10秒中100次，所有的请求都会被计算在内，包括信息同步，消息发送等。你们提供的日志我看了，同一时间有太多的请求发过来，几秒钟就超过了100次，这是不正常的现象，不应该有这么多请求。我看请求的方法大多数是获取群组信息和获取群组成员信息。这个方法是当获取群组或群组成员信息时refresh参数为true时，就会有一次服务器同步操作。请避免refresh参数使用true，仅当进入到群组会话时第一次调用使用true

**Comment by jpguo520** [comment]
1. 发送消息和信息同步(refresh参数为true)，这两种接口都会被当做访问服务器的接口，这个明确了，wfc.getConversationDelivery() 和 wfc.getConversationRead(),下面这两个接口是服务器请求吗？
1. 超过10秒100次的限制后服务器在抛出警告后，客户端会收到什么样的提示。
1. 在会话窗口多选消息（30条左右），逐条转发给9个会话，这270条消息发送出去，瞬间就超过10秒100次的限制，此时剩下的170条消息状态会返回什么状态。

**Comment by heavyrain2012** [comment]
> * 发送消息和信息同步(refresh参数为true)，这两种接口都会被当做访问服务器的接口，这个明确了，wfc.getConversationDelivery() 和 wfc.getConversationRead(),下面这两个接口是服务器请求吗？
这两个不会
> * 超过10秒100次的限制后服务器在抛出警告后，客户端会收到什么样的提示。
客户端有些请求会失败，另外过多的请求还会对服务器造成巨大的压力，所以一定要处理好
> * 在会话窗口多选消息（30条左右），逐条转发给9个会话，这270条消息发送出去，瞬间就超过10秒100次的限制，此时剩下的170条消息状态会返回什么状态。
会发送失败，但协议栈有重试机制，失败的再尝试一次，可能还会有部分重试成功，有部分失败。

**Comment by jpguo520** [comment]
1. 那就是需要控制尽量不要触发这个警告。像转发270条消息也不应该发送出去是这个概念不？
