### ISSUE TITLE
消息显示处理，只在目标用户显示，发送用户不显示

### ISSUE THREAD

**Issue by MriceZxu** [wildfirechat/server#460]
什么方式可以实现消息只有接收用户的信息列表显示，发送用户的信息列表不显示

**Comment by heavyrain2012** [comment]
可以在获取消息时过滤消息，把不需要显示的都删掉，还有会话也需要处理，如果是最后一条是这种也要删掉（删掉后重新获取一下会话就更新最后一条了），还有监听收到消息，如果不需要的也删掉，还有发送消息，发送成功后删掉消息。
