### ISSUE TITLE
mvn package 抛错

### ISSUE THREAD

**Issue by q764297954** [wildfirechat/server#461]
INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Wildfire Chat 0.57 ................................. SUCCESS [  3.494 s]
[INFO] common ............................................. SUCCESS [02:54 min]
[INFO] Moquette - broker .................................. FAILURE [09:44 min]
[INFO] sdk ................................................ SKIPPED
[INFO] Moquette - distribution 0.57 ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:42 min
[INFO] Finished at: 2022-02-17T17:48:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision (default) on project moquette-broker: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision failed: Unable to find commits until some tag: Walk failure. Missing commit 49c32d7fa104e8f0e578e14be70b5699057df1df -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :moquette-broker

**Comment by heavyrain2012** [comment]
由于使用了一个git的maven插件，如果本地没有git信息就会编译出错，请使用git clone的方法下载代码，或者下载压缩包解压后在根目录创建.git的空目录。建议用git clone的方式下载代码。
