### ISSUE TITLE
T_User_message表中_uid和_target存在一致的情况，与表设计相悖

### ISSUE THREAD

**Issue by charlesbabyxu** [wildfirechat/server#462]
新版中T_User_message 增加conversation info，
但是按照代码中写法，当用户是私聊的接收方是，_uid 和 _target一致，这无法起到标志会话的左右，还会在运行过程中产生错误数据，后期修复耗时费力；
directing字段意义不明，我的理解中该字段应该是消息发送接收属性，用来在T_user_message中标志消息是发送还是接收；
消息广播和群发时sender和conversation.target是一直的，在UserMessage中也是需要考虑点

**Comment by sjhgithub** [comment]
似乎Single类型的会话,target不同于其它类型,会单独处理,目前不知道该字段的意义
[接收方]接收到的该消息,sender(from)      等于conversation.target;
[发送方]接收到的该消息,sender(from)[不]等于conversation.target
不明白该conversation.target的意义所在,望指教
