### ISSUE TITLE
IM server Professional Version - configuration changes related to friend request is not reflected

### ISSUE THREAD

**Issue by gopi-bathala** [wildfirechat/server#463]
## Issue Description

We are currently using IM server professional version and tried to change below configuration related to friend request settings  in **wildfirechat.conf** file and restarted the IM server. But, the new changes did not work as expected. 

Can you please check and advise on this issue? 

Below are the new parameter details provided for your swift response. Thanks in advance

**wildfirechat.conf**

##好友请求重复发送的间隔，单位是毫秒，默认是7天，**0为不限制**
friend.repeat_request_duration 0

##好友请求被拒绝后再次发送的间隔，单位是毫秒，默认是30天，**0为不限制**
friend.reject_request_duration 0

**Comment by BillWangFirePhoenix** [comment]
参数设置成0以后 发送的间隔依然没有调整 请问这个configuration是有效的吗 还是没有提供？

**Comment by heavyrain2012** [comment]
the new changes did not work as expected.

描述一下你们的期望是什么？现在是什么表现？

**Comment by BillWangFirePhoenix** [comment]
> the new changes did not work as expected.
> 
> 描述一下你们的期望是什么？现在是什么表现？

现在是第一次加好友正常 第二次加好友显示发送失败（拒绝前）
拒绝后再次添加好友依然失败
我们的期望就是你们写的comment啊 单位是毫秒，默认是7天，0为不限制
我现在设置为0，应该不限制啊，为什么依然在重复发送好友申请时显示发送失败

**Comment by heavyrain2012** [comment]
我们刚确认过，这个注释是有问题的，0是无限长期限，如果您想不限制，可以设置一个很小的数，比如1是一毫秒。
我们修改的注释请参考提交 https://github.com/wildfirechat/server/commit/b7a30e1d14b7a5015a540b33fc13aae4a9484bb2 ，社区版和专业版这个注释是一样的
