### ISSUE TITLE
如何记录音视频的通话时间以及通话中的用户信息和人数

### ISSUE THREAD

**Issue by bumblebee1024** [wildfirechat/server#464]
自己的业务需求中，需要记录IM中打电话的人数、用户信息、还有通话时长等类似log的数据。
包括高级音视频，中途加入会议或者退出会议等等记录。
请问有什么方案，或者有什么回调接口可以支持，谢谢。

**Comment by heavyrain2012** [comment]
会议有事件回调功能，请参考 https://docs.wildfirechat.cn/server/event_callback.html
其中包括加入会议回调/离开会议回调，这是用户进入/离开的会议的回调
发布回调/取消回调，这是发布视频流和取消视频流的回调
有了这些信息应该就能满足你们记录的需要
