### ISSUE TITLE
安卓版本上传文件超过差不多1M以后，就会报413错误，请问下社区版本是否能修改文件上传的大小限制

### ISSUE THREAD

**Issue by zhoukuikui** [wildfirechat/server#466]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是毕现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
请提供更多的信息，比如你们用的是社区版还是专业版？对象存储用的是什么？有没有用NG？还有没有其它特殊的地方？

**Comment by zhoukuikui** [comment]
我用的社区版本。对象存储这块社区版应该是用hazelcast做缓存，持久化是MySQL。app后端有用Nginx做负载，不过那是http请求的，消息发送我理解走的是netty的长连接，不经过Nginx吧。目前app是通过公网上注册的域名访问的。

**Comment by imndx** [comment]
请参考[如何抓取日志](https://docs.wildfirechat.cn/faq/android/q3.html) 附上日志。

**Comment by heavyrain2012** [comment]
感觉还是NG引起的问题，请根据 https://docs.wildfirechat.cn/server/oss.html 配置好七牛云试试，或者去掉NG试试

**Comment by zhoukuikui** [comment]
多谢，是Nginx那块的问题。我理解错了，以为文件传输不会通过Nginx，而是走1883的netty长连接端口。
