### ISSUE TITLE
发送图片消息发送失败

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/server#467]
背景：
1、server部署在腾讯云上面
2、文件存储服务（MinIO）部署在公司内部（外网可以访问，但部署了Web防御）
现象：
Ios端选择图片，发送图片(文件，视频)都显示发送失败。提示errorcode：54
<img width="889" alt="edbad1252389c4fe6c66e4adf899f35" src="https://user-images.githubusercontent.com/26107242/159604832-95ed3cf2-0d39-410b-9d23-02785f419939.png">
由于其公司内部有Web防御安全部署，提示一下错误被拦截。
![image](https://user-images.githubusercontent.com/26107242/159605068-2aa4bc75-13fb-4530-a166-0cd775361e0b.png)

咨询一下移动端发送图片等带附件消息的附件上传机制，以及解决策略。

**Comment by heavyrain2012** [comment]
https://github.com/wildfirechat/wf-minio readme有说明，大概就是协议栈用的是普通的http上传，你们这个防御需要放行上传，检查一下sdk是不是有个设置http header的方法，可以设置一个特殊的header然后防御放行

**Comment by jpguo520** [comment]
实在不行可以放行上传动作，需要一个放行策略。
关于SDK中设置特殊Header的方法能提供一下吗？
>https://github.com/wildfirechat/wf-minio readme有说明，大概就是协议栈用的是普通的http上传，你们这个防御需要放行上传，检查一下sdk是不是有个设置http header的方法，可以设置一个特殊的header然后防御放行

**Comment by imndx** [comment]
> 实在不行可以放行上传动作，需要一个放行策略。 关于SDK中设置特殊Header的方法能提供一下吗？
> 
> > https://github.com/wildfirechat/wf-minio readme有说明，大概就是协议栈用的是普通的http上传，你们这个防御需要放行上传，检查一下sdk是不是有个设置http header的方法，可以设置一个特殊的header然后防御放行

Android 端只这个```addHttpHeader```，iOS 应当有个类似的方法

**Comment by jpguo520** [comment]
addHttpHeader 方法看到了，这个方法是在什么时间点设置，需要在每次发送媒体消息之前设置吗？还是在某个时点设置一次就行。

**Comment by jpguo520** [comment]
关于minio服务有一个疑问，也看看可以吗？
https://github.com/wildfirechat/WF-minio/issues/1

**Comment by heavyrain2012** [comment]
> addHttpHeader 方法看到了，这个方法是在什么时间点设置，需要在每次发送媒体消息之前设置吗？还是在某个时点设置一次就行。

在connect之前调用就行，只调用一次
