### ISSUE TITLE
Group type is getting modified as restricted

### ISSUE THREAD

**Issue by Sadakhatali** [wildfirechat/server#469]
Dear Team,
    As part of our project requirement we wanted to understand below points, related to group creation.
    
    1. What are the possible ways to changing the group type.
    2. Where do we have a logic to change the group type I mean group type logic has been implemented at front end or backed.

**P.S:** While group creation from front end always we are passing the group type as 0 (GroupType_Normal) but some times group is getting created as type 2 (GroupType_Restricted), we required your help to understand from where the type is getting changed, we are unable to trace in the code.

**Comment by heavyrain2012** [comment]
我们查过代码，type只有在创建group的时候确定下来，代码中没有任何修改的地方。这是第一次听说群组的type会变，之前几年从来没有接到过这种问题报告。感觉不太可能是IM服务代码逻辑有问题。

1，请检查你们所有能创建群组的代码，包括客户端和server api，确认创建的代码中使用的type是0.
2，测试复现问题，把所有可能用到的场景进行测试，找一下复现规律。
3，专业版IM服务代码和社区版IM服务代码关于群组的逻辑基本一致，如果想要查看源代码可以查看社区版的源代码。

**Comment by heavyrain2012** [comment]
另外查询一下数据库，把所有type是2的群信息导出到一个文件中发给support@wildfirechat.cn，我们看一下数据

**Comment by Sadakhatali** [comment]
@heavyrain2012 
Thanks for the quick reply. 

how can we make sure always our group type to create as type 0 (GroupType_Normal).

**Comment by heavyrain2012** [comment]
需要你们找到创建群组的代码，检查一下创建群组的参数，把群组类型改成0 (GroupType_Normal).
