### ISSUE TITLE
音视频高级版的两个问题

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/server#471]
1.推流过程中修改推流分辨率参数；
2. 推流（720p 30帧，1080p 30帧），观看端的流量显示 200~300KB，感觉区别不大，是正常现象还是流推不上去，我们有些场景对清晰度要求非常高，还有多人会议多画面需要考虑移动端带宽问题，所以对流量的评估也要相当准确。

**Comment by imndx** [comment]
1. pc/web 已支持动态修改码率，方法是```CallSession#setVideoMaxBitrate```
2. ```Local Storage```中添加一项```enable_voip_debug=1```，就可以子啊控制台输出当前码率。
