### ISSUE TITLE
Remote message not deleting at receiver end

### ISSUE THREAD

**Issue by Sadakhatali** [wildfirechat/server#472]
Dear Team,
    Kindly help us to understand for the resolution of below issue.

In sender and receiver communication, when sender deleted the message by selecting the option called "**Remote Message Delete**", it is not getting deleting from the receiver side. Please anyone help us with the root cause.

**Comment by heavyrain2012** [comment]
在客户端，如果删除远端消息，只能删除自己侧的消息，不能删除对方的。如果想要双方都删除，只能调用server api来删除

**Comment by Sadakhatali** [comment]
@heavyrain2012 Thanks for the reply. 

As you mentioned above using server API we are unable to delete the message at receiver end.

Below API we have used to delete the receiver end messages
http://domain:18080/admin/message/delete

Kindly confirm is above API is correct or do we need to use some other API.

**Comment by heavyrain2012** [comment]
我们说的“server api”就是http://domain:18080/admin/这类接口。你上面提到的api是对的

**Comment by Sadakhatali** [comment]
@heavyrain2012 Thanks for the assistance, we have resolved the issue.
