### ISSUE TITLE
公众号广播的接口sendMessage，当targets只有1个人时可以正常发送消息，为多人时显示发送成功，但是接收不到

### ISSUE THREAD

**Issue by zhuyunhong** [wildfirechat/server#473]
#### 表现现象
公众号广播时调用ChannelServiceApi中的sendMessage，当targets只有1个人时可以正常发送消息，为多人时显示发送成功，但是接收不到

**Comment by heavyrain2012** [comment]
SDK问题，更新server sdk到最新就没有问题了
