### ISSUE TITLE
Not able to upload more than 100MB file into aliyuncs storage

### ISSUE THREAD

**Issue by Sadakhatali** [wildfirechat/server#474]
Dear Team,
     As part of our project requirement we are using the aliyuncs storage to store the file, but we are facing one small issue like if the file size is less than 100MB we able to upload the file successfully, but more than 100MB file size we are not able to upload, even we are not able to find any configurations to change the allowed file size. 

Kindly assist us to upload the file size which is more than 100MB.

**Comment by heavyrain2012** [comment]
100MB是个界限，100MB一下是通过协议栈上传，发送文件消息时，协议栈自动进行上传并发送消息；100MB以上是无法通过协议栈上传的，需要先调用getMediaUploadUrl，得到所需要的上传信息，然后再在UI层进行上传，上传成功后把链接写入到消息体中再发送。

这个问题，请用我们的demo跑一下完整的流程，然后再对照你们的应用是走到那里失败的，并把失败的日志和截图和失败的错误码贴到这里

**Comment by imndx** [comment]
你好，你们调用 ```wfc. getUploadMediaUrl```时，少了一个参数```contentType```

具体请参考：https://github.com/wildfirechat/vue-pc-chat/issues/194
