### ISSUE TITLE
有技术路线图吗？

### ISSUE THREAD

**Issue by yuantongkang** [wildfirechat/server#475]

**Comment by heavyrain2012** [comment]
目前IM的完成度很高了，音视频基本需求也都能满足。由于我们是面向开发者的，所以我们的技术演进方向是根据客户的需求来的。如果您有需求，可以跟我们提。一般情况下我们只能做普适性的关于IM和实时音视频的功能，如果我们评估后是需要客户自己进行二开的或者是我们不能做的，我们也会给出适当的建议

**Comment by yuantongkang** [comment]
目前有个需求就是 pc 的 sdk 可以提供 wasi 版本吗

**Comment by imndx** [comment]
> 目前有个需求就是 pc 的 sdk 可以提供 wasi 版本吗

你好，现在pc sdk没法提供 wasm 版。
