### ISSUE TITLE
Server API 可不可以增加了个接口  根据聊天信息的id获取信息的详细内容

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#477]
目前遇到这个问题，用户有时候会发送一些违规的信息，可不可以根据信息的id获取信息的详细内容

如果用户自主上传聊天内容也是可以，但是可能会不安全。

**Comment by heavyrain2012** [comment]
可以直接读取IM服务数据库

**Comment by mankind-evolve** [comment]
因为现在使用都是通过serverapi交互
如果直接操作im数据库的话可能会造成一些混乱。
