### ISSUE TITLE
数据库加密的消息要怎么解密获取

### ISSUE THREAD

**Issue by BarryYang1** [wildfirechat/server#482]
message.encrypt_message_content设置为true，即消息加密存储数据库_data字段，那要怎么取出这个字段并解密
我使用sdk里面的WFCMessage.Message.parseFrom(data)并不行，报错：Protocol message contained an invalid tag (zero)，请问是不是我的方法用错了

**Comment by heavyrain2012** [comment]
这是因为数据经过了加密。加密的原因就是防止有人通过数据库读取聊天内容。如果你们想要读取内容，这个开关应该设置为关

**Comment by BarryYang1** [comment]
> 这是因为数据经过了加密。加密的原因就是防止有人通过数据库读取聊天内容。如果你们想要读取内容，这个开关应该设置为关

那要是关闭加密，怎么读取并解析_data字段

**Comment by heavyrain2012** [comment]
关掉开关后，再发送的消息就没有经过加密了，WFCMessage.Message.parseFrom(data) 这个方法来解析字段

**Comment by BarryYang1** [comment]
> 关掉开关后，再发送的消息就没有经过加密了，WFCMessage.Message.parseFrom(data) 这个方法来解析字段

是这个吧 WFCMessage.MessageContent.parseFrom
