### ISSUE TITLE
什么时候开发uniapp客户端

### ISSUE THREAD

**Issue by zhang-ykun** [wildfirechat/server#483]
什么时候开发uniapp客户端

**Comment by imndx** [comment]
Android 端，请看[野火IM 原生插件](https://ext.dcloud.net.cn/plugin?id=7895)
iOS 端，正在开发中

**Comment by heavyrain2012** [comment]
完整的uniapp插件已经开发完成，支持android和iOS，地址在：https://github.com/wildfirechat/uni-wfc-client
