### ISSUE TITLE
Server端追加删除用户及相关记录的接口

### ISSUE THREAD

**Issue by Antony-Jia** [wildfirechat/server#484]
从6月30日开始iOS要求能够删除用户及相关信息，希望能够在Server端、客户端补足相关功能

**Comment by heavyrain2012** [comment]
没有明白什么问题，这是个政策要求是吗？能不能提供来源信息或更多信息给我们？

**Comment by Antony-Jia** [comment]
https://zhuanlan.zhihu.com/p/519829524

很多啦，你去官方文档也能找到

**Comment by heavyrain2012** [comment]
IM服务有个删除用户接口，可以通过这个接口来删除关于此用户的所有数据。应用服务提供了删除用户接口给客户端用，iOS客户端实现了删除账户功能。其它客户端暂时没有需求添加此功能。

请更新应用服务和iOS客户端验证删除账户功能
