### ISSUE TITLE
APP退回桌面未登出，重新进入后离线消息丢失

### ISSUE THREAD

**Issue by wuyumin1988** [wildfirechat/server#486]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
app未进行登出操作。只是单纯退出到桌面。后续，重新打开app，收不到退出期间的消息。离线消息丢失
#### 预期结果
收到离线消息

#### 补充条件
偶发

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
丢的消息是单聊消息还是群聊消息，后台这段时间有什么事件发生吗，比如群组成员变动、服务重启等
