### ISSUE TITLE
寻求非法信息的一个解决方案

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#489]
原因：有些用户发一些乱七八糟的信息和非法的以及骚扰信息

需求方案：需要一个举报的功能，传给服务器一个信息id,根据信息id拿到对应的信息内容。

困难： 打开数据库一看有这么多表，完全懵逼，不知道从哪里下手！ 我从客户端可以拿到信息的 messageid 和 messageuid  

困惑：是不是可以提供一个serverapi接口去拿信息内容    数据库信息有加密，要怎么寻找对应的信息？ 怎么判断某条数据具体在哪个库里面呢？

**Comment by mankind-evolve** [comment]
请问  数据库中 t_message_** 中    _data字段和_searchable_key有什么用？   

后来测试_searchable_key是我发的信息明码，  那_data这个是干啥的？ 是记录图片和文字信息的吗？

 记录中存在大量_data不为空_searchable_key为空的记录 

 后来发图片的时候，_searchable_key字段会记录[图片]   那那些大量_data不为空_searchable_key为空的记录是做什么的讷？

**Comment by heavyrain2012** [comment]
请检查文档 https://docs.wildfirechat.cn/faq/server.html#Q__消息存储在数据库的那张表里，如果获取消息内容？ 问题36

**Comment by mankind-evolve** [comment]
我看 _searchable_key字段是用户的聊天记录明文，可以直接用这个字段吗？ 

安卓客户端可以拿到 messageuid的这个值我对比了一下，与 _mid是一致的。

所以我可以直接用 t_messages_x 做用户的信息审核工作吗?

**Comment by heavyrain2012** [comment]
_searchable_key 某些消息会用到这个字段，比如文本，不会是全部的消息，你们需要确认一下是否只检查这个字段是否够用。
可以直接用t_messages_x做信息审核工作

**Comment by mankind-evolve** [comment]
收到。 感谢感谢

**Comment by mankind-evolve** [comment]
刚刚在测试用 t_messages_x 的时候发现一个问题，就是我今天发送的信息这个表里面查不到（发送的信息在客户端能正常接收）， 最早能找到 昨天 2022-07-06 16:59:15的信息， 是不是有什么特别的设定？

**Comment by heavyrain2012** [comment]
可以按照消息id逆序查看一下最新的，理论上会立即存入数据库的，看一下是不是看错了？另外会不会保存失败，你看看有没有sql报错？

**Comment by mankind-evolve** [comment]
的确是。 我刚排查了一下，数据库连接错误，已解决。感谢感谢
