### ISSUE TITLE
java client接收消息不能获取发件人id

### ISSUE THREAD

**Issue by zzl221000** [wildfirechat/server#49]
fromUser是自己

**Comment by heavyrain2012** [comment]
![屏幕快照 2019-07-16 22 10 04](https://user-images.githubusercontent.com/34463389/61301497-95f32e80-a816-11e9-9784-5b39e9f5f24a.png)
我今天测试了，如果是别人发的，fromUser就会是发送人不是自己，请确实是不是多端的情况存在，如果确认不是，请给我们抓个这样的截图

**Comment by zzl221000** [comment]
找到问题了，Admin发送数据会导致fromUser是收件人
