### ISSUE TITLE
前段调用getUserInfo() extra字段未实时刷新

### ISSUE THREAD

**Issue by xushuai21** [wildfirechat/server#490]
###需求
用户聊天界面，当日过生日的人的头像上展示生日帽

#### 操作说明
后端在getUserInfo topic 中 查询用户表生日，算出当日是否是其生日，然后把结果放到extra字段返回给前端

#### 表现现象
客户端聊天框调用getUserInfo()获取用户信息，extra拓展字段未实时刷新，必须切换其他账号再返回原来账号（或卸载重装）登陆才会刷新

#### 预期结果
客户端调用getUserInfo() 获取的extra字段为最新字段

**Comment by heavyrain2012** [comment]
尽量不要修改IM服务，因为你们修改了IM服务后，就跟我们代码不一致了，我们就没有办法做技术支撑了，最好是通过api来调用IM服务。

客户端同步用户信息的机制是：当客户端本地没有时，UI层调用获取用户信息，协议栈会返回空，然后再去IM服务同步，同步下来之后保存再发送一个通知UI更新；如果本地已经有了，refresh为false就只返回本地的缓存数据，当refresh为true时会返回本地用户数据之后再去服务器端更新，更新会判断用户信息的更新时间来确认是否有变更，只有更新时间不同才会同步下来用户信息。

生日这个问题，可以在创建用户时，把生日放到extra中，客户端读取extra就能算出来生日。现在的同步机制没有用户信息实时更新机制，所以不能实时修改用户信息。

**Comment by xushuai21** [comment]
好的，谢谢，我改下逻辑

**Comment by xushuai21** [comment]
现在这个客户信息数据已经有了的话，，那怎么让这个生日显示出来？本地有了的话，他不是就不去IM服务同步了吗，只取本地缓存

**Comment by heavyrain2012** [comment]
正常情况下是不会去服务器同步的，只有在调用获取用户信息refresh参数为true才会去服务器同步，注意这个只能在某些界面调用一次，方式过多调用对服务器产生压力
