### ISSUE TITLE
IMCallback为什么回调两次？

### ISSUE THREAD

**Issue by wuqinduo** [wildfirechat/server#491]
IMCallback 我看服务端代码IMCallback 总是被回调两次。比如preAction触发了限流，在preAction里回调一次。返回respone被回调一次 ，为什么这样做啊

**Comment by heavyrain2012** [comment]
您好，我们检查了，确实是多回调了一次，最新代码已经修改，请检查今天的提交，感谢您的提醒

**Comment by heavyrain2012** [comment]
您好，我们检查了，确实是多回调了一次，最新代码已经修改，请检查今天的提交，感谢您的提醒
