### ISSUE TITLE
希望能新增一个接口，查询消息的状态

### ISSUE THREAD

**Issue by liumingjf** [wildfirechat/server#493]
希望能新增一个接口，查询消息的状态： 

例如：

* Sending 0，正在发送中。
* Sent 1，已发送。
* Send_Failure 2，发送失败。
* Mentioned 3，提醒。
* AllMentioned 4，提醒所有人。
* Unread 5，未读。
* Readed 6，已读。
* Played 7，已播放。

**Comment by heavyrain2012** [comment]
消息状态是在客户端本地维护，没有同步到IM服务，无法通过server api来获取消息状态。

请问您要做什么需求？看看是不是有别的办法实现需求？

**Comment by liumingjf** [comment]
> 

就是想知道一个消息是否已经被对方收到或者读取，如果未读，就把消息撤回

**Comment by heavyrain2012** [comment]
只有专业版才支持，看这个提交 https://github.com/wildfirechat/im-server/commit/dece1d7a1c69610ea35dce8c82d181033a779c2d 把sdk更新到最新，然后再更新专业版im服务。这个提交能够获取用户同步的消息记录和用户会话的阅读记录
