### ISSUE TITLE
请求接口异常java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#496]
请求注册、获取token、发消息接口均会出现偶发性的Connection reset异常
客户端异常信息参考，如图：
![image](https://user-images.githubusercontent.com/20660920/180390492-54fb9f75-8ec2-43b9-9f5e-78e5ea1124aa.png)

**Comment by heavyrain2012** [comment]
sdk有没有初始化，初始化的IM server api地址是不是正确的（默认是18080端口），secret是不是正确

**Comment by 615203360** [comment]
> Contributor
> ### [<img alt="@heavyrain2012" width="20" height="20" src="https://avatars.githubusercontent.com/u/34463389?s=60&amp;v=4">](/heavyrain2012) ** [heavyrain2012](/heavyrain2012) ** commented [前天](#issuecomment-1193022473)

以上的配置肯定是正确的，不正确接口是不能请求成功的，我说了出现Connection reset的问题是偶发的，不是必现的异常，但出现的频率也不算低，所以才亟待解决

**Comment by heavyrain2012** [comment]
sdk和im服务都是什么时候的？

**Comment by heavyrain2012** [comment]
sdk请求im服务是直接请求吗，中间有没有反向代理之类的东西

**Comment by 615203360** [comment]
> 
sdk用的是0.80版本；
以下是im服务器启动信息
	"tags":"null",
	"branch":"8aa72ec1819e8d02fa09c88c087730af90b54f79",
	"dirty":"null",
	"remoteOriginUrl":"git@github.com:heavyrain2012/server_commercial.git",
	"commitId":"8aa72ec1819e8d02fa09c88c087730af90b54f79",
	"commitIdAbbrev":"8aa72ec",
	"describe":"moli-397-g8aa72ec-dirty",
	"describeShort":"null",
	"commitUserName":"heavyrain2012",
	"commitUserEmail":"heavyrain.lee@gmail.com",
	"commitMessageFull":"add protobuf 2.5.0 bin\n",
	"commitMessageShort":"add protobuf 2.5.0 bin",
	"commitTime":"20220307113811",
	"nodeIds":"1 ",
	"closestTagName":"null",
	"closestTagCommitCount":"null",
	"buildUserName":"Unknown",
	"buildUserEmail":"Unknown",
	"buildTime":"20220308155351",
	"buildHost":"null",
	"buildVersion":"null",
	"verified":true,
	"currentNode":1,
	"runTime":233530

**Comment by 615203360** [comment]
> sdk请求im服务是直接请求吗，中间有没有反向代理之类的东西

是直接请求的，没有用到其他代理

**Comment by heavyrain2012** [comment]
把im服务的日志发给我们看一下，邮箱support@wildfirechat.cn 还有调用服务错误日志一起发过来

**Comment by 615203360** [comment]
> 把im服务的日志发给我们看一下，邮箱[support@wildfirechat.cn](mailto:support@wildfirechat.cn) 还有调用服务错误日志一起发过来

im服务端没有异常，只有客户端有异常，客户端异常的图就是我提问里面的那张

**Comment by heavyrain2012** [comment]
我们自己没有遇到这个问题，也没有客户报告有这个问题，还是需要你们提供一下日志我们分析一下。另外也可以在你们代码中加上重试机制，如果有异常就重试一次看看是否保证业务能够顺利进行

**Comment by 615203360** [comment]
> 我们自己没有遇到这个问题，也没有客户报告有这个问题，还是需要你们提供一下日志我们分析一下。另外也可以在你们代码中加上重试机制，如果有异常就重试一次看看是否保证业务能够顺利进行

想问下sdk中用的CloseableHttpClient，有做过优化吗，目前还是有很多Connection reset的错误出现

**Comment by heavyrain2012** [comment]
CloseableHttpClient做过优化

**Comment by 615203360** [comment]
> CloseableHttpClient做过优化

![image](https://user-images.githubusercontent.com/20660920/185576787-599d4d98-62b4-4f6c-a14f-c3a26b5e754c.png)
能指明下优化的代码是在哪里吗，上图是我再sdk里截的图，只能到初始化了个默认的httpClient

**Comment by heavyrain2012** [comment]
对就是这里

**Comment by heavyrain2012** [comment]
你加我微信 wildfirechat 我问下详细情况吧
