### ISSUE TITLE
怎么自定义限制用户发送消息条数

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#497]
怎么自定义限制用户发送消息条数，比如陌生人之间只让发3条消息，超过3条系统返回限制提示

**Comment by imndx** [comment]
可以在客户端做下限制，客户端发送消息时，判断下：
1. 是否是单聊会话
2. 是否是好友
3. 如果是非好友的话，判断下已经发送了几条消息

**Comment by 615203360** [comment]
> 可以在客户端做下限制，客户端发送消息时，判断下：
> 
> 1. 是否是单聊会话
> 2. 是否是好友
> 3. 如果是非好友的话，判断下已经发送了几条消息

可能是我之前问题没有描述清楚，您上面回答也没错。我现在补充下我的问题，我现在的场景是能否让陌生人发消息，能发几条，这些配置信息是配置在我们业务系统中的，客户端虽然能做限制，但客户端需要每次发消息前都要请求业务系统获取配置信息判断当前是否能发信息；所以我想问野火im中能否有这样的支持，对点到点的消息进行次数限制的配置或接口

**Comment by heavyrain2012** [comment]
im服务没有这个限制，需要你们业务添加。可以在应用打开后同步一次状态，然后后面计数放到客户端计数，当用户发送一条后，就把本地计数减一，再同步状态到业务服务
