### ISSUE TITLE
怎么发送提示类型的消息给用户

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#498]
怎么发送下图这样的提示信息，目前用contentType
=90类型来发消息可以实现效果，但发送方消息列表也会多出一条发送的提示消息，不希望发送方展示该消息
![971f1c9946f9316ec8906f326c5cbd0](https://user-images.githubusercontent.com/20660920/180709866-ac856638-3143-4f12-a6c7-2e4153bd33b2.jpg)

**Comment by imndx** [comment]
目前没有直接支持，可以参考下下面的思路：

1. 实现一种新的自定义消息，除了```type```之外，其他的可以和```type```为```90```的```TipNotificationContent```一致
2. 客户端收到该自定义消息之后，通过```direction```判断是发送，还是收到。如果是发送的话，将该条消息直接删除
3. 如果客户端也可能直接发送该自定义消息的话，那么可以在发送成功之后，将该消息删除
