### ISSUE TITLE
文档打不开 

### ISSUE THREAD

**Issue by phpdever** [wildfirechat/server#5]
地址：http://docs.wildfirechat.cn/

![WX20190506-130752](https://user-images.githubusercontent.com/17875582/57207400-10762580-7000-11e9-8c29-cece34884f87.png)

**Comment by heavyrain2012** [comment]
文档放置在github page上的，有些资源在国外，所以比较慢。在QQ群里有pdf版本的文档可以参考。我们稍后也会想办法加上CDN加速

**Comment by heavyrain2012** [comment]
QQ群文件保存有pdf版本的文档，请从哪里下载

**Comment by imndx** [comment]
还可以试下这个：wfc.im
