### ISSUE TITLE
On Voice/Video call, callerId should represent the person who initiate the call. But it has the other person callerId every time.

### ISSUE THREAD

**Issue by mhamidg** [wildfirechat/server#503]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是毕现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
用的是那个音视频SDK？能截图看一下问题吗？

**Comment by mhamidg** [comment]
I am using iOS and Android applications. In applications, the session
object received from the server has the callerId of the destination user. I
am using this repo for iOS https://github.com/wildfirechat/ios-chat and for
android also from wildfirechat repos.

**Comment by heavyrain2012** [comment]
callId的规则是：发起人ID + ｜ + 时间戳

**Comment by mhamidg** [comment]
It should be, but somehow everytime call initiated from any side. The
destination userId is set as callId + timestamp. Can you please have a look?

**Comment by mhamidg** [comment]
Hi Team, any progress on this issue? As we are stuck with this.

**Comment by heavyrain2012** [comment]
不好意思，还是没有弄明白到底是什么问题，请更详细说明你们的问题，最好有截图说明。

**Comment by mhamidg** [comment]
For example in mobile application:
A Calling B -> the CallerId will have B's userId
A Receive Call from B -> the CallerId will have B's userId

In the call session object, there is no reference for userId, who initiated the call. After call connected/disconnected, there is no reference that call was dialed or received. (No reference of Who initiated the call)

**Comment by heavyrain2012** [comment]
请更新 https://github.com/wildfirechat/ios-chat/commit/ea37c2937a9e34d8fceb373ab9302e44e3f8be1f 测试。如果还是有问题，请录制测试视频

**Comment by mhamidg** [comment]
Thanks,

**Comment by mhamidg** [comment]
I have tested this feature on iOS its working. But this is not implemented on Android version. Can you fix this CallerId feature on Android as well?

**Comment by imndx** [comment]
请更新 https://github.com/wildfirechat/android-chat/commit/d4b1f8392ec63a6d09a5028d21e65d08acaec026 测试

**Comment by mhamidg** [comment]
Thanks. I will look into it.
