### ISSUE TITLE
添加新的配置项

### ISSUE THREAD

**Issue by forStones** [wildfirechat/server#504]
因为我们SDK现在的功能是用户进入聊天室之后，自动拉取5分钟之前的消息，
现在我们需要一个配置参数，用来拉取固定的消息条数，而不是5分钟之前的所有消息。
![1660294298551](https://user-images.githubusercontent.com/45985079/184320162-da625772-838e-4b27-9cd9-cee817f3fd87.png)

**Comment by heavyrain2012** [comment]
没有办法加拉取消息条数的配置，跟专业版差别太大，现在加了5分钟的配置，可以把时间配置为0秒，这样就不会拉取之前的消息了
