### ISSUE TITLE
HttpHostConnectException: Connect to localhost:18080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by jiegege10** [wildfirechat/server#505]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/25316728/185892112-c5088faa-aebd-453d-bd74-a7d8872bf400.png">

**Comment by heavyrain2012** [comment]
您好，下次提issue请按照格式提，提供更多的信息。

从上面日志可以看出是某个服务请求IM服务server api端口，请求地址是127.0.0.1：18080，请确认IM服务是否部署在本机，IM服务是否正常运行

**Comment by jiegege10** [comment]
服务器上面，我只启动了一个app_server ，正常启动。然后app那边登录，服务端报这个错误了。

**Comment by heavyrain2012** [comment]
必须要有appserver和im服务才行，登陆时appserver需要调用im服务，请部署im服务再验证
