### ISSUE TITLE
能正常发送文本消息，但是不能发送语音、图片和文件

### ISSUE THREAD

**Issue by jiegege10** [wildfirechat/server#506]
是还需要配置什么吗？media.server.use_qiniu 0 默认是内置存储。后面改成use_qiniu 1 ，七牛云的配置也都配了，也都不行发送语音图片。用的版本是目前最新的

**Comment by heavyrain2012** [comment]
请按照 https://docs.wildfirechat.cn/server/oss.html 上面关于七牛的说明来配置

**Comment by jiegege10** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/25316728/186296459-c90f69d3-fc86-41aa-9640-de335db50a21.png">
![image](https://user-images.githubusercontent.com/25316728/186296570-ddd612d9-24e8-458b-bc9f-522af7f0ef76.png)
也是对着上面来的，不知道哪里错了，七牛云也没有强制https。

七牛云 AccessKey/SecretKey也是没错的

**Comment by jiegege10** [comment]
![image](https://user-images.githubusercontent.com/25316728/186296840-3d07199f-aa32-4eb3-aa0a-185c182562d8.png)

**Comment by jiegege10** [comment]
![image](https://user-images.githubusercontent.com/25316728/186296875-08c9b28b-5362-4d54-8422-40afb3dc383a.png)

**Comment by heavyrain2012** [comment]
好的，请抓一下客户端日志，把客户端日志发送给邮件 support@wildfirechat.cn 我们从客户端看一下情况

**Comment by heavyrain2012** [comment]
看日志有这么一句话： token:VoIhRqT2rQPWHHwO/XYhaXEAIjOUtiDQ, type:0
说明用的还是内置的，不是七牛，请问配置完成之后，有没有重启IM服务

**Comment by jiegege10** [comment]
感谢感谢，是没重启

**Comment by jiegege10** [comment]
对了，在请问下， media.server.use_qiniu 0 是直接存放在服务器上面吗？我设置为0 的时候
