### ISSUE TITLE
拦截某个用户的信息并自动回复自定义内容

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#508]
有没有办法拦截某个用户的信息并自动回复自定义内容，比如服务端拦截机器人账号收到的消息，并回复指定内容

**Comment by heavyrain2012** [comment]
“某个用户”如果是个机器人就比较简单，机器人属性中有个callback地址，当有人给机器人发消息时，如果这个地址存在就会把消息转发到这个地址。
如果是个普通用户，就麻烦一些，需要设置消息转发地址，这样会把所有消息都转发给特定地址，然后过滤消息

**Comment by 615203360** [comment]
这个callback地址是指t_robot表里的callback字段配置吗，意思是要改动机器人服务robot_server项目的代码吗

**Comment by heavyrain2012** [comment]
这个callback地址是指t_robot表里的callback字段配置吗
IM服务内有机器人的信息，其中就有一个callback属性，是转发机器人消息的目的地，机器人信息存储在t_robot表中，可以通过server api来修改，如果直接修改数据库需要重启。

意思是要改动机器人服务robot_server项目的代码吗
不是的，robot_server是接受转发过来的消息然后再进行回复的。机器人用户信息的callback地址就是设置为robot_server的地址，这样才能把机器人的消息转发到robot_server去

**Comment by 615203360** [comment]
“IM服务内有机器人的信息，其中就有一个callback属性”，这个具体是指哪里，好懵啊

**Comment by heavyrain2012** [comment]
![截屏2022-08-26 11 36 04](https://user-images.githubusercontent.com/34463389/186812254-50086cf3-b6ba-4d0f-bb49-9e368db8925b.png)

**Comment by 615203360** [comment]
是指把自己回调地址改成我们自己的地址吗，那这样不是就没有robot_server封装好的功能了么，我想在拥有robot_server的功能前提下拦截机器人账号收到的消息做自定义处理

**Comment by heavyrain2012** [comment]
那就是需要你们自己再转一下，可以在robot_server把消息转到你的业务服务，或者先发到业务服务再转发到robot_server

**Comment by 615203360** [comment]
好的，明白了，多谢
