### ISSUE TITLE
【需求】后台创建群聊接口支持配置是否显示群昵称

### ISSUE THREAD

**Issue by hhahali** [wildfirechat/server#509]
后台创建群聊接口支持配置是否显示群昵称

**Comment by heavyrain2012** [comment]
不能单独指定是否显示群昵称。事实上是每个用户每个群都有个设置：是否显示群昵称，这个值只在客户端上显示群消息时使用，它的意义你们可以来反转。这样可以改变全局的状态。

**Comment by li-ld** [comment]
> 不能单独指定是否显示群昵称。事实上是每个用户每个群都有个设置：是否显示群昵称，这个值只在客户端上显示群消息时使用，它的意义你们可以来反转。这样可以改变全局的状态。

能不能后台接口支持一下?

**Comment by hhahali** [comment]
> 不能单独指定是否显示群昵称。事实上是每个用户每个群都有个设置：是否显示群昵称，这个值只在客户端上显示群消息时使用，它的意义你们可以来反转。这样可以改变全局的状态。

客户端创的群可以按照客户端的来，后台admin的接口能不能支持一下？

**Comment by heavyrain2012** [comment]
这个设置是用户在群里的设置，不是群的设置，所以如果你们要设置，就需要调用接口，为群里的每个用户修改一下这个属性。有一种可能是你们自己来在群扩展个字段来，然后客户端根据扩展字段来处理

**Comment by heavyrain2012** [comment]
设置是否显示群昵称是修改用户设置，_scope是5，_key是群id，value是是否不显示群昵称，如果要是修改，需要为群里每个用户修改
t_user_setting 
| id    | _uid     | _scope | _key     | _value | _dt           |
+-------+----------+--------+----------+--------+---------------+
|  1673 | 3W4939bb |      5 | tTt5t566 | 0      | 1566945389751 |
