### ISSUE TITLE
如何根据时间范围查询到消息的总量数据

### ISSUE THREAD

**Issue by bulletqi** [wildfirechat/server#510]
通过数据库查询如何通过时间范围查询消息总量的数据

**Comment by heavyrain2012** [comment]
消息表是按照月份分表的，文档上的常见问题有说明分表规则，每个消息都是时间字段，根据时间字段就可以查询到您想要的数据了，具体sql语句还需要您自己来写了

**Comment by bulletqi** [comment]
OK，了解了，感谢
