### ISSUE TITLE
[需求]  新增一个客户端SDK 增加批量删除消息的API

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/server#511]
1.根据发送人+时间范围 进行批量删除本地消息的API；
   时间范围维度：
        开始时间-结束时间范围内全部删除；
        时间节点之前全部删除；
        时间节点之后全部删除；
2.根据messageUid 进行批量删除本地消息的API；（服务端返回的messageUid 是否可以删除本地消息？）
        删除数量可能会比较大，API可以给一个在不影响应用性能情况下的最大删除数量的阈值，我们这边根据最大数量阈值来进 
        行遍历删除

**Comment by heavyrain2012** [comment]
已经实现，请更新SDK验证
