### ISSUE TITLE
ChannelServiceApi 没有撤回公众号消息相关api

### ISSUE THREAD

**Issue by Acier** [wildfirechat/server#514]
ChannelServiceApi 没有撤回公众号消息相关api,麻烦能否加入这个功能

**Comment by heavyrain2012** [comment]
这个功能不太好加，其实和发送一条消息通知客户端删除的效率差不多。最好的办法就是客户端上做一些策略。比如进入会话时，获取消息，过滤掉无用的消息再删掉，这样最省资源
