### ISSUE TITLE
[需求] 新增一个客户端SDK 批量删除消息的API

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/server#515]
根据会话id+发送人+时间范围 进行批量删除本地消息的API；
时间范围维度：
开始时间-结束时间范围内全部删除；
时间节点之前全部删除；
时间节点之后全部删除；

**Comment by heavyrain2012** [comment]
这个功能用现有接口就能实现，因为个人在会话内的消息数是比较有限的，获取消息的接口可以指定某个人发的消息，都读取出来然后按照时间删除就行
