### ISSUE TITLE
[需求] 增加一个服务端删除消息缓存的API

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/server#517]
根据目标用户、会话id、时间范围 进行批量删除该用户发送的消息在服务端缓存消息的API；

会话id：
为空的情况，删除目标用户发送的所有缓存消息；
不为空的情况，删除改会话id中目标用户发送的缓存消息；

时间范围维度：
开始时间-结束时间范围内全部删除；
时间节点之前全部删除；
时间节点之后全部删除；

**Comment by heavyrain2012** [comment]
已经添加，请更新验证
