### ISSUE TITLE
Audio and video problems

### ISSUE THREAD

**Issue by sadakhatalikhan** [wildfirechat/server#518]
Dear Team,

We need your expertise to under below issue. Audio and video calls are not stable. 
**Sometime audio, video calls are working and sometime not.** 

we're able to send the text messages but the problem is only with audio and video calls sometime it is working and sometime not.

We are unable to trace anything from the logs. Need your assistance to fix this problem.

**Comment by heavyrain2012** [comment]
需要部署turn服务，然后在客户端进行配置https://docs.wildfirechat.cn/webrtc/

**Comment by sadakhatalikhan** [comment]
Dear,

Thanks for the quick response.

We have already deployed trun service, even though we are facing the same error. (sometime it is working and sometime not).

**Comment by heavyrain2012** [comment]
可能是turn服务没有部署正确，请用这个链接检查https://docs.wildfirechat.cn/webrtc/trickle-ice/ ，检查结果是 ![turn](https://docs.wildfirechat.cn/webrtc/turn_check.jpeg) ，有relay的candidate而且ip地址为turn服务的公网ip地址。

**Comment by sadakhatalikhan** [comment]
Hello @heavyrain2012,

Trying to validate the trun service from this url https://docs.wildfirechat.cn/webrtc/trickle-ice/ please check below screenshot.

![image](https://user-images.githubusercontent.com/45699025/189582510-231f2dbf-e143-4c03-a84b-166348da91e2.png)

**### Getting error log :** please guide me what is issue with this.

![image](https://user-images.githubusercontent.com/45699025/189582913-7e1f0358-102d-44c1-80c7-c7c0e9f97652.png)

**Comment by heavyrain2012** [comment]
正常不应该有错误才对，turn服务不是我们开发和维护的，所以请你们自己上网查一下怎么部署和如何处理这种错误吧
