### ISSUE TITLE
Add to black list not working with firerobot user

### ISSUE THREAD

**Issue by sadakhatalikhan** [wildfirechat/server#520]
Dear Team,

please help us with below issue.

A normal user receiving the messages even after the adding the fireRobot into black list. Kindly let us know what will the issue. 
please find the attached screenshot FYR.

![fireRobotBlacklistIssue](https://user-images.githubusercontent.com/45699025/189645313-6708642f-8b18-4b3a-8a27-2faf3efc7c3d.jpeg)

**Comment by heavyrain2012** [comment]
机器人一般都是用来通知的，所以你们可以把UI处理一下，去掉黑名单的设置。请参考 https://github.com/wildfirechat/ios-chat/commit/4d6d2acf025a63e5afd24ba831336ad88dd2989f
