### ISSUE TITLE
【功能需求】当聊天过程中，出现转账、钱财、汇款，理财，就立刻灰字提醒对方

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#521]
## 功能需求
当聊天过程中，出现转账、钱财、汇款，理财，就立刻灰字提醒对方。

可否实现此功能

**Comment by imndx** [comment]
可以看下这个服务[野火反诈骗服务](https://github.com/wildfirechat/anti-fraud)

**Comment by heavyrain2012** [comment]
> 可以看下这个服务[野火反诈骗服务](https://github.com/wildfirechat/anti-fraud)

反诈服务是需要把这些词添加到敏感词中，可能敏感词会消息发送失败，替换或者吞掉（IM服务配置敏感词的策略），不一定能满足需要。另外一种办法是消息转发功能，所有消息都转到指定服务，过滤这些关键字，出现后发送提示消息到会话中

**Comment by hellomcp** [comment]
> 可以看下这个服务[野火反诈骗服务](https://github.com/wildfirechat/anti-fraud)

这个服务目前可以满足我们的需求，感谢
