### ISSUE TITLE
[需求] 希望提供一个服务端可以根据消息id集合，查询这些消息已读、未读的状态的接口

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/server#522]
[需求] 希望提供一个服务端可以根据消息id集合，查询这些消息已读、未读的状态的接口

**Comment by heavyrain2012** [comment]
t_user_setting里记录了用户所有的状态，包括会话的阅读时间，_scope为7是会话阅读时间，key为会话，value是最后阅读的消息，根据此数据就可以知道消息是否已经阅读
