### ISSUE TITLE
[需求] 是否可以增加一个类似企业微信一样的，一周小结的功能

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/server#523]
[需求] 是否可以增加一个类似企业微信一样的，一周小结的功能

**Comment by heavyrain2012** [comment]
这个功能不能算是IM的核心功能，你们可以自己来开发。开发一个服务来记录客户端提交的数据，客户端在某些操作提供数据给服务，比如进入会话，离开会话，打开应用，关闭/后台应用等，然后服务定时给特定用户发送统计消息
