### ISSUE TITLE
批量同步其他系统数据到野火

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#524]
现在要把别的im系统的用户和聊天数据迁移到野火系统来，有没有什么好的方案，请指点下

**Comment by heavyrain2012** [comment]
用户信息是比较容易的，遍历现有系统的用户，然后再倒入到新的系统中就可以了。但聊天数据迁移比较难一些，没有办法服务器端迁移，只能想办法客户端迁移，需要现有系统的客户端SDK支持批量读取消息功能，然后再批量写入野火IM的客户端

**Comment by heavyrain2012** [comment]
能问一下现有IM是那个供应商的吗？如果我们比较熟悉也好给你们一些具体建议

**Comment by 615203360** [comment]
现在有im是融云的

**Comment by heavyrain2012** [comment]
我记得原来他们IM服务没有用户信息托管，用户信息都是存储在应用服务的，需要从应用服务到处用户信息，另外还有迁移群组，还有用户关系，需要把这3部分都倒入到野火IM种

**Comment by 615203360** [comment]
好的，多谢了
