### ISSUE TITLE
Server API创建用户

### ISSUE THREAD

**Issue by zhaoshengbin** [wildfirechat/server#526]
请问Server API创建用户无法给密码那这个创建用户的作用是什么呢？  有没有办法在创建用户时同时设置密码呢？

**Comment by imndx** [comment]
你好

im-server 数据库里面的```_password_md5```和```_salt```字段是历史遗留，现在已经没有用了，im-server 本身没有密码的概念，连接的时候，用的是```userId```和```token```。

其实，im-server 本身并不需要用户信息，现在提供创建用户等接口，将用户信息托管到 im-server，是了方便客户端，让客户端不用从第三方服务去获取用户信息（当然，现在客户端也支持从第三方服务获取用户信息）。

在 im-server 创建用户的作用也就是让客户端能直接从 im-server 获取到用户信息。

账号和密码是 app-server（也可以是你们自己的应用服务） 的概念，客户端通过账号和密码登录 app-server，然后 app-server 向 im-server 请求```token```等，并将```userId```和```token```返回给客户端，之后，客户端通过```userId```和```token```连接 im-server。

目前，app-server 的账号密码登录功能是有个前提的，就是通过手机号验证码登录成功之后，设置了密码才能采用账号密码登录；如果，想首次就支持用户名、密码登录，你们可以修改一下 app-server 的代码，或者在 app-server 提前创建用户，并设置密码。

app-server 的用户和 im-server 的用户是通过手机号对应起来的。

**Comment by imndx** [comment]
另外，建议看下野火im的架构说明：https://docs.wildfirechat.cn/architecture/

**Comment by zhaoshengbin** [comment]
好的  谢谢
