### ISSUE TITLE
与外部IM 接口调用通过什么实现

### ISSUE THREAD

**Issue by neversuspend** [wildfirechat/server#527]
比如我有skype，想把信息转发到野火里面

或者野火，转发消息到skype

接口调用是通过什么实现

谢谢

**Comment by imndx** [comment]
下面是个大概的思路

需要开发一个转发服务，这个服务充当野火IM 和 skype 之间的转接桥，主要作用是：

    1. 将从野火 IM 来的消息转发到 skype
    2. 将从skype 来的消息，转发到野火


### 将野火 IM 的消息转发到转发服务
这一步实现起来比较简单，野火 IM-Server 里面，有个消息转发相关的配置，正确配置即可，如下：
```
##消息转发地址
##注意回调是单线程回调，接收服务必须在同一内网，且异步处理快速返回，否则会有延迟问题！！
#message.forward.url http://localhost:8888/im_event/message
##需要转发的消息类型，当有多个时以英文逗号分割。如果转发所有消息，请注释掉配置或者设置为空
#message.forward.types 1,2,3
```

### 将 skype 消息转发到野火 IM
这一步可以通过[机器人](https://docs.wildfirechat.cn/server/robot_api/) 来实现

请参考上述思路，可以在这个 issue 下继续讨论

**Comment by heavyrain2012** [comment]
> 下面是个大概的思路
> 
> 需要开发一个转发服务，这个服务充当野火IM 和 skype 之间的转接桥，主要作用是：
> 
> ```
> 1. 将从野火 IM 来的消息转发到 skype
> 2. 将从skype 来的消息，转发到野火
> ```
> 
> ### 将野火 IM 的消息转发到转发服务
> 这一步实现起来比较简单，野火 IM-Server 里面，有个消息转发相关的配置，正确配置即可，如下：
> 
> ```
> ##消息转发地址
> ##注意回调是单线程回调，接收服务必须在同一内网，且异步处理快速返回，否则会有延迟问题！！
> #message.forward.url http://localhost:8888/im_event/message
> ##需要转发的消息类型，当有多个时以英文逗号分割。如果转发所有消息，请注释掉配置或者设置为空
> #message.forward.types 1,2,3
> ```
> 
> ### 将 skype 消息转发到野火 IM
> 这一步可以通过[机器人](https://docs.wildfirechat.cn/server/robot_api/) 来实现
> 
> 请参考上述思路，可以在这个 issue 下继续讨论

### 将 skype 消息转发到野火 IM 

这一步要用server api，不能用机器人api，因为机器人api只能以自己的身份发送消息，可能需要在野火IM中创建对应的skype应用，然后用这个用户发送消息，就需要用server api了

**Comment by neversuspend** [comment]
> ##消息转发地址
> ##注意回调是单线程回调，接收服务必须在同一内网，且异步处理快速返回，否则会有延迟问题！！
> #message.forward.url http://localhost:8888/im_event/message
> ##需要转发的消息类型，当有多个时以英文逗号分割。如果转发所有消息，请注释掉配置或者设置为空
> #message.forward.types 1,2,3

修改了im-server/config文件夹下面的wildfirechat.conf文件

message.forward.url http://www.myhost.com/im_event/message
message.forward.types 1,2,3

手机上两个测试号彼此发了消息，http://www.myhost.com/im_event/message 没有收到请求，不知道是怎么回事，重启了im-server也没有用，谢谢大家帮忙看看
