### ISSUE TITLE
如何主动给好友发送文件

### ISSUE THREAD

**Issue by jackercoco** [wildfirechat/server#528]
有对应的API吗？

**Comment by imndx** [comment]
发送文件和发送普通消息没有本质的区别，发送消息的api[看这儿](https://docs.wildfirechat.cn/server/admin_api/message_api.html)

消息负载怎么设置，看[这儿](https://docs.wildfirechat.cn/server/admin_api/models.html#MessagePayload)

**Comment by jackercoco** [comment]
根据文档，我想发文件的话，常量值MESSAGE_CONTENT_TYPE_FILE = 5，那type就是5，那文件流怎么发出去呢，放在MessagePayload这个类的那个参数中

**Comment by heavyrain2012** [comment]
媒体类消息（比如图片/语音/文件/视频，或者其他自定义包含文件的消息）没有办法直接发送，都是需要先上传到对象存储服务，然后再放入到MessagePayload这个对象的remoteUrl属性中，发送payload。

在IM服务和协议栈传输的都是messagepayload对象，在客户端会把messagepayload转会为对应的消息，因此通过server api发送的payload必须跟客户端的消息encode/decode的payload一致。比如图片消息，server api发送payload必须跟客户端图片消息encode的payload抑制（唯一的区别就是客户端有个二进制熟悉，server api对应使用base64编码过的二进制数据）

**Comment by jackercoco** [comment]
按你说的，用SDK的方式文件发过去了，接收者也收到了，但是没有显示对应的文件图标和大小

**Comment by heavyrain2012** [comment]
让客户端查一下吧，看一下server api发送的消息的payload跟客户端生成的payload有什么区别

**Comment by jackercoco** [comment]
![图片](https://user-images.githubusercontent.com/83407222/192970502-0e14877f-adb2-43c2-a412-7aea1917ab2e.png)
size和name我用SDK怎么传放哪里

**Comment by imndx** [comment]
通过```server api```发送消息时，```payload```的格式要和客户端对应消息```encode```出来的结果对应上。

针对文件消息，名字和大小分别放到```searchableContent```和```content```字段，下面是web 端文件消息的```encode```方法
```
    encode() {
        let payload = super.encode();
        payload.searchableContent = this.name;
        payload.content = this.size + '';
        return payload;
    }
```
