### ISSUE TITLE
消息发送前由服务器判断是否发送

### ISSUE THREAD

**Issue by ruliuyan** [wildfirechat/server#529]
新增一种消息回调服务器类型：
如果消息回调配置成此类型，那么消息在发送前先回调到服务器，允许服务器根据业务判断此消息是否应继续发送。

**Comment by heavyrain2012** [comment]
请检查一下IM服务配置文件，里面有个审核服务的配置，设置审核服务地址配置后，所有消息都会转到这个地址，这时就可以做你们的业务来判断是否发送，如果想要不允许发送返回403就可以了

**Comment by ruliuyan** [comment]
感谢答复，我这边测试一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/im-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月22日(星期四) 晚上8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/im-server] 消息发送前由服务器判断是否发送 (Issue #529)





 
请检查一下IM服务配置文件，里面有个审核服务的配置，设置审核服务地址配置后，所有消息都会转到这个地址，这时就可以做你们的业务来判断是否发送，如果想要不允许发送返回403就可以了
