### ISSUE TITLE
数据库改成使用mysql后启动服务报异常

### ISSUE THREAD

**Issue by pullwindyuan** [wildfirechat/server#53]
### OS version (0.24`)
配置成使用mysql
##是否使用内置DB。0使用mysql；1使用h2db
embed.db 0

出现如下错误提示：
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

**Comment by pullwindyuan** [comment]
OS为win10

**Comment by heavyrain2012** [comment]
这提示是有客户端请求，但数据库中没有该端的session信息。正常的现象

**Comment by pullwindyuan** [comment]
我后来把MySQL里session相关字段的长度限制加大了就不出这个问题了

**Comment by wydewy** [comment]
> 我后来把MySQL里session相关字段的长度限制加大了就不出这个问题了

加大哪个字段
