### ISSUE TITLE
如何更改隐私配置的默认值

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#531]
想把“陌生人查看10条朋友圈”的配置和消息通知的配置调整成默认开启的状态，目前app端只能更改配置，不知道初始值在哪里配置，如下图
![0c0f5507b67504928d87fcffe35c428](https://user-images.githubusercontent.com/20660920/192426342-d0dd7f85-702e-4073-8a0a-9315be76800f.jpg)

**Comment by heavyrain2012** [comment]
这几个初始值是没有办法修改的，但我看都是默认开的啊

**Comment by 615203360** [comment]
可是我们这边app端开发人员说sdk默认是关闭的状态，能不能在帮忙确认下

**Comment by heavyrain2012** [comment]
你可以用我们发布的demo测试看看，https://docs.wildfirechat.cn/demo/

**Comment by 615203360** [comment]
![5e8ecffe0c2ba27440030edda265665](https://user-images.githubusercontent.com/20660920/193239880-540c0c94-656e-43ce-96d0-165dc620c2a0.jpg)
我试了demo的，demo上是打开的，但是我们这边前端开发人员反应说sdk中默认给的是空字符串，如果是开启对应的状态应该是1，这个你们帮忙看看sdk中是否是这样的吧

**Comment by heavyrain2012** [comment]
空应该看成0，确认一下，0是不是打开，1是关闭？
