### ISSUE TITLE
如何主动获取某个用户的未读消息？

### ISSUE THREAD

**Issue by jackercoco** [wildfirechat/server#532]
如何主动获取某个用户的未读消息？

**Comment by jackercoco** [comment]
如何主动获取某个用户的未读消息，未读数量，哪个人发的，有对应的SDK吗？

**Comment by heavyrain2012** [comment]
服务器端没有对应数据

**Comment by jackercoco** [comment]
有没有类似的获取用户未读消息api，或者有没有合适的方案自己实现

**Comment by imndx** [comment]
你是想客户端获取，还是服务端通过 server api 获取？

**Comment by jackercoco** [comment]
服务端通过 server api 获取

**Comment by heavyrain2012** [comment]
能说一下你们想要做的业务吗？看看是不是有别的办法能达到目的

**Comment by jackercoco** [comment]
我们在另一个后台管理页面 展示了好友列表，需要在这个后台页面展示实时的未读消息数量，野火IM是通过iframe嵌套展示，点击发起聊天才进入野火IM

**Comment by heavyrain2012** [comment]
只能一个办法了，应用在后台时上报他的未读数，上报到推送服务，推送服务当收到推送时就把未读数加一，从推送服务获取用户的未读数
