### ISSUE TITLE
需要部署哪些服务

### ISSUE THREAD

**Issue by YXyjt** [wildfirechat/server#533]
只要聊天和音视频通话功能  后台需要部署哪些服务

**Comment by heavyrain2012** [comment]
1. 应用服务，负责处理登录还有部分应用层业务。
2. IM服务，就是当前项目，处理IM的所有业务。
3. 推送服务，对接系统厂商，负责手机不在线时的推送业务。
4. Turn服务，用来中转音视频通话，这个服务可以选用coturn，可以从网上查找安装方法。
