### ISSUE TITLE
iOS接入im后，重新登录我方用户，会话列表会消失

### ISSUE THREAD

**Issue by a95241815** [wildfirechat/server#534]
条件：ios端，接入野火im后
预期结果：用户退出登录后再重新登录，进入聊天窗口，可以加载到上次登录时的会话列表
实际结果：与他人聊天后，消息列表窗口有多条记录，退出登录，再次登录，会话列表会丢失
[https://lazy-pet.oss-cn-shenzhen.aliyuncs.com/uploads/1.png](url)

**Comment by heavyrain2012** [comment]
登录的接口有2个参数，全部传false应该就不会在丢失会话列表了

**Comment by a95241815** [comment]
/**
 断开连接

 @param disablePush   是否停止推送，clearSession为YES时无意义。如果为true，session会变成disable状态，token会失效，必须重新获取token才能登陆。
 @param clearSession 是否清除Session信息，如果清除本地历史消息将全部清除，且token失效无法再次登陆，必须重新获取token才能进行登陆。
 */
- (void)disconnect:(BOOL)disablePush clearSession:(BOOL)clearSession;

请问是这两个参数的设置吗，目前设置是：
[[WFCCNetworkService sharedInstance] disconnect:YES clearSession:NO];

**Comment by heavyrain2012** [comment]
是的，都用NO就好了
