### ISSUE TITLE
批量发送文件创建消息时，本地开发没问题，发布线上后报错

### ISSUE THREAD

**Issue by qinchaomeishenmeshi** [wildfirechat/server#535]
通过a页面实现批量发送文件，野火IM使用iframe嵌套的形式，在a页面获取文件的oss路径和发送人及接收人的uid后，在野火homePage页面接收参数并使用循环的方式调用batchSendFiles方法实现批量发送文件
`batchSendFiles(file, targetUid) {
            let batchFile = {
                type: "batch",
                fileUrl: file.fileUrl,
                fileSize: file.fileSize,
                fileName: file.fileName
            };

            let batchConversation = new Conversation(0, targetUid, 0);

            store.sendFile(batchConversation, batchFile);

        },`

本地没有问题，线上环境报错
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/76268951/192956616-50db85e4-ae3b-429f-a41a-958479049b82.png">
如何解决

**Comment by qinchaomeishenmeshi** [comment]
是否有更好的批量发送文件的方式

**Comment by imndx** [comment]
你好，没太看懂你的批量发送是如何实现的，采用循环的方式实现批量发送就可以

```Cannot access 'u' before initialization```一般是由于在变量定义之前，就使用导致的。
