### ISSUE TITLE
User offline notification not receiving in case of killing the process for voice and video call

### ISSUE THREAD

**Issue by sadakhatalikhan** [wildfirechat/server#537]
Hello Team, 
Please help us to resolve below issue. 

**### Issue**
We're Making a voice and video call to an offline user and then we kill the process or hang in the background for a long time, in this scenario the user does not receive the offline notification. 

In case of chat message this scenario is working, but we have an issue only with voice or video call. 

We are using **_moquette-broker-0.39.jar_**

**Comment by heavyrain2012** [comment]
是android客户端还是iOS客户端？

**Comment by sadakhatalikhan** [comment]
if is an IOS client

**Comment by sadakhatalikhan** [comment]
if is an IOS client

**Comment by sadakhatalikhan** [comment]
it is an IOS client

**Comment by heavyrain2012** [comment]
请用最新的iOS demo测试一下，这个问题应该已经解决了，更新一下音视频sdk应该就好了

**Comment by sadakhatalikhan** [comment]
Thanks for the response, can you please also update for Android client.

**Comment by BillWang0408** [comment]
> 是android客户端还是iOS客户端？

安卓也有同样的问题：
给离线用户（杀死进程或长时间挂在后台）拨打语音视频通话，用户未收到离线通知
给离线用户（杀死进程）发送文字消息，用户未收到离线推送
软件长时间挂在后台，无法接收到消息推送

**Comment by heavyrain2012** [comment]
需要部署和对接推送服务 https://github.com/wildfirechat/push_server

**Comment by sadakhatalikhan** [comment]
Hello heavyrain2012

Thanks for the quick response. 

we have already deployed push service and it is up and running in our production environment. 
you mean you're going to provide changes for android to cover above scenario.

**Comment by heavyrain2012** [comment]
那就是推送对接的问题，离线用户（杀死进程或长时间挂在后台）是不能连接IM服务和接收消息的，需要走苹果推送和android推送。关于推送的处理，请仔细阅读推送服务项目的说明
