### ISSUE TITLE
你好，怎么和我已有的用户系统结合，因为我们已经有用户以及登录了，只缺im能力，关于用户这块的结合不太明白，可以解答一下吗？

### ISSUE THREAD

**Issue by 2554178315** [wildfirechat/server#538]
你好，怎么和我已有的用户系统结合，因为我们已经有用户以及登录了，只缺im能力，关于用户这块的结合不太明白，可以解答一下吗？

**Comment by heavyrain2012** [comment]
IM服务不需要登录，SDK只需要一个token来进行连接和认证，可以在你们登录的服务来获取token，获取之后放到登录成功的响应中返回个客户端。可以参考应用服务中的登录流程，文档也可以参考 https://docs.wildfirechat.cn/base_knowledge/connect.html

用户托管有2种方案，一种 是把你们先有用户同步到野火IM中，这种方法的优点是客户端不用修改，缺点是需要服务端做同步，还有可能客户端IM相关页面的用户信息跟其他部分用户信息不同步的问题。另外一种方法是客户端来实现datasource接口，野火UI通过这个接口获取到用户信息，所有开发也仅限于客户端。
