### ISSUE TITLE
请求接口错误  nodejs.RequestError: connect ECONNREFUSED 127.0.0.1:18080, POST http://localhost:18080/admin/user/get_token

### ISSUE THREAD

**Issue by 2554178315** [wildfirechat/server#540]
nodejs.RequestError: connect ECONNREFUSED 127.0.0.1:18080, POST http://localhost:18080/admin/user/get_token

**Comment by heavyrain2012** [comment]
IM服务有没有正常启动？一般要用nohup命令运行，防止窗口关闭后自动结束。如果要是IM服务一直正常启动的，请提供IM服务的日志，可以发送给support@wildfirechat.cn
