### ISSUE TITLE
【建议】想建一个非官方的野火IM交流群可以吗？没有人交流实在是太难受了

### ISSUE THREAD

**Issue by aaronShao1** [wildfirechat/server#541]
想建一个非官方的野火IM交流群可以吗？没有人交流实在是太难受了

**Comment by heavyrain2012** [comment]
其实我们之前建过微信群，持续了小半年，但没有任何效果，群里基本都是吹水聊天的，没有任何高质量的回答，做解答的还是我们的人员。如果想交流，可以去 https://bbs.wildfirechat.cn 发帖子询问，回答的都是我们技术人员，专业又及时。
