### ISSUE TITLE
账号在其他设备登录弹出提示

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#543]
当账号在其他设备登录时希望旧设备弹出提示，有什么解决方案吗

**Comment by heavyrain2012** [comment]
把下面这个开关打开再重启IM服务试试


##客户端是否支持kickoff事件。当客户端被其他端登录踢出时，如果此开关为false时，客户端协议栈上报secret_mismatch。如果此开关为ture时，客户端协议栈上报kicked_off。
##客户端被踢时上报kicked_off是在2021.9.15之后才加上的。如果客户端协议栈全部为此日期之后的版本才可以打开此开关。
server.client_support_kickoff_event false
