### ISSUE TITLE
将野火 IM 的消息转发到转发服务未成功

### ISSUE THREAD

**Issue by neversuspend** [wildfirechat/server#547]
> ##消息转发地址
> ##注意回调是单线程回调，接收服务必须在同一内网，且异步处理快速返回，否则会有延迟问题！！
> #message.forward.url http://localhost:8888/im_event/message
> ##需要转发的消息类型，当有多个时以英文逗号分割。如果转发所有消息，请注释掉配置或者设置为空
> #message.forward.types 1,2,3

修改了im-server/config文件夹下面的wildfirechat.conf文件

message.forward.url http://www.myhost.com/im_event/message
message.forward.types 1,2,3

手机上两个测试号彼此发了消息，http://www.myhost.com/im_event/message 没有收到请求，不知道是怎么回事，重启了im-server也没有用，谢谢大家帮忙看看

**Comment by heavyrain2012** [comment]
发的是什么消息内容，把下面这行注释掉再重启试试呢
message.forward.types 1,2,3

**Comment by neversuspend** [comment]
发的是文字 1234 之类的

> #message.forward.types 1,2,3

已经注释掉了也重启了，还是不行

**Comment by heavyrain2012** [comment]
IM服务日志贴一下

**Comment by neversuspend** [comment]
wildfirechat_error.log 如下，不知道为什么时间不太对，我是先清空日志，再发了测试消息的

> 2022-10-12 08:41:31,765 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=8a8fd7dd-5667-4463-93a7-8269d3c8a0ae1663575144043, cause=null, errorMessage=Connection reset by peer
> 2022-10-12 08:41:31,765 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> 2022-10-12 08:41:31,765 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.read(IOUtil.java:192)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 2022-10-12 08:41:31,769 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - java.lang.Thread.run(Thread.java:748)
> 2022-10-12 08:42:27,312 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=98295e13-fce9-4fc0-b189-b16f8dbcbfa21663574606113, cause=null, errorMessage=Connection reset by peer
> 2022-10-12 08:42:27,312 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> 2022-10-12 08:42:27,312 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.read(IOUtil.java:192)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - java.lang.Thread.run(Thread.java:748)

**Comment by neversuspend** [comment]
wildfirechat_warn.log 如下

> 2022-10-12 08:41:31,765 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=8a8fd7dd-5667-4463-93a7-8269d3c8a0ae1663575144043, cause=null, errorMessage=Connection reset by peer
> 2022-10-12 08:41:31,765 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> 2022-10-12 08:41:31,765 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.read(IOUtil.java:192)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
> 2022-10-12 08:41:31,766 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
> 2022-10-12 08:41:31,767 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 2022-10-12 08:41:31,768 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 2022-10-12 08:41:31,769 ERROR [nioEventLoopGroup-3-1] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - java.lang.Thread.run(Thread.java:748)
> 2022-10-12 08:42:27,312 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=98295e13-fce9-4fc0-b189-b16f8dbcbfa21663574606113, cause=null, errorMessage=Connection reset by peer
> 2022-10-12 08:42:27,312 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> 2022-10-12 08:42:27,312 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.IOUtil.read(IOUtil.java:192)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
> 2022-10-12 08:42:27,313 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
> 2022-10-12 08:42:27,314 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 2022-10-12 08:42:27,315 ERROR [nioEventLoopGroup-3-3] netty.NettyMQTTHandler (NettyMQTTHandler.java:116) - java.lang.Thread.run(Thread.java:748)

**Comment by heavyrain2012** [comment]
时间是UTC时间，所以比北京时间小8小时。需要看 wildfirechat.log 的日志，可以只看发送消息后相关的几行，不用全贴上

**Comment by neversuspend** [comment]
wildfirechat.log 、wildfirechat_warn.log、wildfirechat_error.log 我发消息前都清空了，上面也是发消息后的消息

wildfirechat.log一直没有新内容，是空的

**Comment by heavyrain2012** [comment]
是不是log4j的日志配置成异步写了，config目录有个log4j2.xml 有个immediatelyFlush 属性 改成true

**Comment by neversuspend** [comment]
<img width="978" alt="60a7d54429d9ccf3a6fc0b72e99c578" src="https://user-images.githubusercontent.com/7157425/195303902-fd1cce7b-ea2e-40d0-b132-2e11c21bbef9.png">

好像原来就是true

**Comment by neversuspend** [comment]
![6806827a482bfa47b2436aadb262c1b](https://user-images.githubusercontent.com/7157425/195306888-4677700f-6d18-4f14-aab1-5618e5f6953c.jpg)

奇怪了，看日志好像POST了，怎么访问的服务器那儿没有日志打印呢，我浏览器访问都是有日志

**Comment by neversuspend** [comment]
"POST /m/wildfire/test HTTP/1.1" 400 5 "-" "okhttp/3.13.1"

应该是okhttp post出现了问题，返回400了

**Comment by imndx** [comment]
> ![6806827a482bfa47b2436aadb262c1b](https://user-images.githubusercontent.com/7157425/195306888-4677700f-6d18-4f14-aab1-5618e5f6953c.jpg)
> 
> 奇怪了，看日志好像POST了，怎么访问的服务器那儿没有日志打印呢，我浏览器访问都是有日志

消息转发是```POST```请求，浏览器访问是```GET```请求，

可能是你的服务对应接口是```GET```接口，而不是```POST```，故返回了 400

**Comment by heavyrain2012** [comment]
应用服务有个接收转发消息的示例代码，在应用服务的 IMCallbackController.java 中，请参考

**Comment by neversuspend** [comment]
谢谢大家的帮助，解决了！

我服务器端是php的yii2框架，关闭csrf验证就可以了
public $enableCsrfValidation = false;
