### ISSUE TITLE
【需求】可否为群聊中的群组提供更多的权限，比如删除群里的会话

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#550]
## 需求描述
群主拥有最高的权限，包括清理群里所有的聊天

我们希望群主可以管理群里的聊天会话，包括清理不合适，不文明的聊天记录等。

## 具体场景
群成员A发送了一条不文明消息，群主看到后，有权对此消息进行清理，清理后，此消息会从各个群成员的客户端手机上消失。

**Comment by heavyrain2012** [comment]
目前有撤回功能，群主可以撤回任意时间的消息，撤回是不是就可以满足需求。另外专业版IM服务还有删除的api，如果是专业版也可以调用api删除消息
