### ISSUE TITLE
目前群聊里面的群名只有群主能修改 ,可以改成大家都可以修改的吗？

### ISSUE THREAD

**Issue by wy8539** [wildfirechat/server#551]

**Comment by heavyrain2012** [comment]
请参考这里：https://docs.wildfirechat.cn/blogs/群的一些细节问题.html 
现在demo中群的类型默认是2，新建群改成类型为0，这样普通成员也就可以修改群名和头像了

**Comment by wy8539** [comment]
明白，谢谢了
