### ISSUE TITLE
视频能加一个复制功能吗？

### ISSUE THREAD

**Issue by wy8539** [wildfirechat/server#552]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

#### 检索已有问题
除了可以检索已有issue外，还可以去野火论坛查找已有问题，论坛地址为 https://bbs.wildfirechat.cn

#### star 我们
给我们点个star，可以及时接收到我们回复信息，另外也是对我们支持人员辛苦工作的认可，激励我们更好更快地为大家服务。

**Comment by heavyrain2012** [comment]
能详细说一下你们需要的是那个客户端，怎么样操作来复制？

**Comment by wy8539** [comment]
PC端，电脑的微信上是可以右键复制视频的，希望你们的也可以复制视频

**Comment by heavyrain2012** [comment]
野火实现与微信稍有不同，微信是自动下载文件，然后可以拷贝文件地址。野火是在线播放的，所以没有自动保存到本地，可以右键选择下载菜单，下载到本地后可以打开文件目录来查看文件
