### ISSUE TITLE
修改t_user敏感信息

### ISSUE THREAD

**Issue by wo5557511** [wildfirechat/server#558]
如果野火的tUser表把用户名和手机号之类的隐私数据都加密了,这边对野火的功能影响大吗

**Comment by heavyrain2012** [comment]
IM服务配置中有个属性 user.hide_properties 可以打开，这样可以让电话号码属性不被同步到客户端。

可以把用户名和手机号码都加密，比如md5加密，然后所有使用到用户名和手机号码的地方都做一下md5加密，比如使用手机号码搜索用户，可以把要搜索的电话号码md5加密再去服务器搜索。做这个加密最大的难度是把所有使用用户名和手机号码的地方都找到，比如客户端通过用户名和手机号码搜索，比如server api通过用户名和手机号码搜索用户等。
