### ISSUE TITLE
目前视频通话质量Android SDK最高只支持到720P， 能否支持更高视频质量，1080p， 2K，4K。

### ISSUE THREAD

**Issue by Alex4400** [wildfirechat/server#562]
目前视频通话质量Android SDK最高只支持到720P， 能否支持更高视频质量，1080p， 2K，4K，暂不考虑带宽影响。
![2222](https://user-images.githubusercontent.com/116698630/197925001-ee01ff7a-5f54-4b03-a376-3bc79967fa8d.png)

**Comment by heavyrain2012** [comment]
已添加，请更新最新SDK验证
