### ISSUE TITLE
视频会议中，能否加一个设置用户焦点的API或功能，实现固定某一成员视频画面（全屏），不受新加入用户影响。

### ISSUE THREAD

**Issue by Alex4400** [wildfirechat/server#563]
现状：
    目前主持人画面显示的是其它用户的视频画面；能否固定住某个成员画面，使其最大化，不受新加入成员影响，实现会议中每个成员的视频画面一致。

**Comment by heavyrain2012** [comment]
这个功能可以二次开发完成，在会议信息中添加一个焦点用户的字段，然后显示时判断如果会议信息中这个字段存在就设置这个为焦点用户，否则可以用户手动选择。

我们稍后会加上这个功能

**Comment by heavyrain2012** [comment]
已添加此功能，请更新版本验证
