### ISSUE TITLE
视频会议大屏适配

### ISSUE THREAD

**Issue by Alex4400** [wildfirechat/server#564]
在举行视频会议时，视频通话界面在大屏上显示混乱，统一叠加在左边。能否参考腾讯会议，直接全屏显示某一成员画面，其它画面全部放在第二个tab页。
目前大屏上显示类似下图：
![大屏bug](https://user-images.githubusercontent.com/116698630/198251591-0aafc96c-487e-4f9a-8e60-0e404dd0f7f1.png)

**Comment by heavyrain2012** [comment]
那个客户端？是最新版本吗？

**Comment by imndx** [comment]
已适配
