### ISSUE TITLE
关于群聊解散后群员会话入口的展示问题

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#565]
现在有以下需求：
1.群主在app解散群聊，希望群成员保留会话入口（目前群主解散会自动删除会话入口），并在进入会话入口后展示“群已解散”的提示信息
2.在服务端接口中解散群聊，希望所有成员保留会话入口，同样进入会话后展示“群已解散”的提示信息

**Comment by heavyrain2012** [comment]
社区版IM服务没有办法控制群组解散时会话的删除问题。

**Comment by 615203360** [comment]
我们是专业版的，希望你们可以帮忙提供一个方案，谢谢

**Comment by heavyrain2012** [comment]
看一下专业版IM服务配置文件里是不是有下面这个配置，关掉重启后，等2个小时测试是不是会话就不会删除了
```
## 群解散时，客户端上的群消息是否被清空，默认为true
group.clear_message_when_dismiss true
```

**Comment by 615203360** [comment]
可以了，谢谢
