### ISSUE TITLE
UserSetting缓存数据丢失导致未读角标数量与消息免打扰等功能异常

### ISSUE THREAD

**Issue by heyn18** [wildfirechat/server#566]
问题代码如下：
1. io.moquette.persistence.MemoryMessagesStore#loadPersistedUserSettings
2. io.moquette.persistence.MemoryMessagesStore#removeGroupUserSettings
3. io.moquette.persistence.MemoryMessagesStore#getUserSettings以下代码片段：
        Collection<WFCMessage.UserSettingEntry> entries = userSettingMap.get(userId);
        if (entries == null || entries.size() == 0) {
            entries = loadPersistedUserSettings(userId, userSettingMap);
        }
代码的线程安全分析：
1. A线程执行loadPersistedUserSettings方法，从数据库加载t_user_setting某一用户的全部数据，并且一条条循环放到缓存中
2. B线程执行removeGroupUserSettings方法，把线程A中同一用户的UserSetting缓存删除掉，此时线程A继续执行加载数据到缓存的操作，导致线程A之前加载到缓存中的数据全部丢失
3.  此后的所有线程，在执行getUserSettings方法时，从缓存中取到的UserSetting缓存数量大于0，就以缓存中不完整的数据为准，导致功能异常

复现步骤（非必现，需要多尝试几次）：
1. 同时登录PC端与APP端
2. 创建两个群
3. 在PC端与APP端同时解散两个群（最后一步触发群解散的按钮一定要同时点击）
备注：客户端收到解散群的通知后，会马上发起 一次scope为7的PutUserSetting，这是多余的操作，明明群已经解散不存在了

**Comment by heavyrain2012** [comment]
请更新验证
