### ISSUE TITLE
关于野火推送的问题

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#567]
场景：野火im多端登录的情况下（任意平台登录任意多个客户端）
问题1:野火中触发推送消息的话是否也能默认推送到多端
问题2：如果只想给多端中的某一端推消息，其他端不推，有什么好的方法吗

**Comment by heavyrain2012** [comment]
场景：野火im多端登录的情况下（任意平台登录任意多个客户端）
问题1:野火中触发推送消息的话是否也能默认推送到多端
默认应该是推送到所有不在线的移动端吧？现在是什么情况？
问题2：如果只想给多端中的某一端推消息，其他端不推，有什么好的方法吗
这个给某个端推送的逻辑是什么，你们可以在推送服务来实现这个推送逻辑

**Comment by 615203360** [comment]
目前在官网上看到pushData这个字段可以做透传，那问题2就可以通过这个字段传递信息来自定义推送逻辑了，但是又发现一个问题，app端人员说在消息类型为11时，会占用这个字段，想问下现在怎么做能既不覆盖pushData,又能传递自己的值

**Comment by heavyrain2012** [comment]
我们没有发现消息类型11占用这个字段，请提供一下相关信息

**Comment by 615203360** [comment]
![6838134021548275d6fb39a875d8c2c](https://user-images.githubusercontent.com/20660920/202941323-7582704a-ef08-46a5-a00a-58f1bd6c950d.png)
上图是安卓端截给我的消息类型11代码出处

**Comment by heavyrain2012** [comment]
你们研发理解有误，这个消息是组合消息，需要把所有包含的消息的内容都打包，然后放到消息Payload的binaryContent中，消息Payload的pushData是没有占用的

**Comment by 615203360** [comment]
好的，多谢了
