### ISSUE TITLE
关于批量删除用户的问题

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#568]
之前在表里初始化了几十万的用户，现在想把这些用户批量删除掉，请问下可以直接delete t_user表的数据吗，可以的话还需要删除其他表数据吗，还有就是消息是保存在mongodb的，如果用户被delete掉的话，消息没删有影响吗

**Comment by heavyrain2012** [comment]
可以删除t_user表里的用户信息

**Comment by 615203360** [comment]
用户消息呢，如果用户被删除了，mongodb里的消息没删除会有影响吗

**Comment by heavyrain2012** [comment]
消息就是无用了，可以删除

**Comment by heavyrain2012** [comment]
如果有用户继续存在，那么就需要保留这部分用户的消息，特别是t_user_messages表，因为用户需要根据时间线来同步消息，如果时间线被破坏了，那么同步可能就会出问题

**Comment by 615203360** [comment]
好的，明白了，多谢
