### ISSUE TITLE
服务端已开启配置客户端依然不支持kickoff事件

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#569]
服务端已经将server.client_support_kickoff_event配置为true，但客户端依然不支持kickoff事件；
场景是服务端调用UserAdmin.kickoffUserClient接口，然后安卓端返回的状态还是-6，ios端暂未测试
我们项目是22年3月启动的，所以sdk时间应该也是没问题的
![061a1d8f1c0df03f1b1a0389d5351b8](https://user-images.githubusercontent.com/20660920/204242254-c4af6c85-c59a-4c7c-8ba1-1a688f913f61.png)

**Comment by heavyrain2012** [comment]
UserAdmin.kickoffUserClient 这个接口的clientId有没有传入？

**Comment by 615203360** [comment]
有传clientId的，而且对应的app端也确实被踢出了，只不过返回状态值并不是-7，是-6

**Comment by heavyrain2012** [comment]
有可能是之前的版本有bug，更新到最新版本试试呢

**Comment by 615203360** [comment]
能不能再帮忙看看有没什么办法，我们项目已经改动了很多地方，现在不可能去更新版本了，工作量太大

**Comment by 615203360** [comment]
升级到最新版支持kickoff了
