### ISSUE TITLE
群聊推送不显示会话内容

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#571]
![89ef0e17187a6225726769836848606](https://user-images.githubusercontent.com/20660920/204721436-fbb51169-152c-48e7-a33d-991118cb8b12.jpg)
如图，群聊会话推送全部都是“@了你”，而没有显示会话内容，我们测试的内容如下：

{
    "path": "/push/ios", 
    "ip": "10.233.65.0", 
    "param": {
        "cntType": 1, 
        "convType": 1, 
        "deviceToken": "909bee81821a54f2fa788ab04f360d3c521406566cbd4bb0b6bbcb146b075d45", 
        "hiddenDetail": false, 
        "language": "zh-Hans-CN", 
        "line": 0, 
        "mentionedType": 0, 
        "messageId": 325149554804523140, 
        "packageName": "com.wanfu.wetok", 
        "pushContent": "哈哈哈", 
        "pushData": "", 
        "pushMessageType": 0, 
        "pushType": 0, 
        "sender": "fatwetok1121", 
        "senderName": "用户1102", 
        "serverTime": 1669779389704, 
        "target": "xrgqmws2k", 
        "targetName": "这是群聊", 
        "unReceivedMsg": 6, 
        "userId": "fatwetok1720", 
        "voipDeviceToken": "F1028879D15873275B81B50473C4AA17D3070215A0D04E8E290B7205323238F3"
    }
}

**Comment by heavyrain2012** [comment]
这个提示语是在推送服务设置的，可以修改推送服务代码处理

**Comment by 615203360** [comment]
好的，明白了，多谢
