### ISSUE TITLE
专业版可以支持阿里云OSS，但上传的地址不是以文件名结尾的，可以以本身的文件名结尾吗

### ISSUE THREAD

**Issue by neversuspend** [wildfirechat/server#572]
专业版可以支持阿里云OSS，但上传的地址不是以文件名结尾的，可以以本身的文件名结尾吗

谢谢！

**Comment by heavyrain2012** [comment]
不能，因为上传文件有可能重复冲突等，只能用生成的这种格式避免冲突。如果要是确认对象信息需要结合消息内容来看

**Comment by neversuspend** [comment]
是不是可以通过上传路径加上 随机码+文件名的形式

这样既保证了唯一性，有保证了最后是文件名，比如   /34ebjkjdsagha/filename.txt

**Comment by heavyrain2012** [comment]
这个对我们有些难度，因为现在支持的对象存储太多，也不是每个都支持，协议栈也都需要修改，工作量有点儿大，如果你们需要审查对象存储中的内容，可以开发系统结合着消息来看
