### ISSUE TITLE
关于服务端查询用户历史聊天记录的问题

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#573]
想在服务端查询用户之间的历史聊天记录，并根据记录判断两用户之前是否有相互聊天过

**Comment by heavyrain2012** [comment]
可以的，可以根据t_user_messages_x表里的记录，找到某个人的所有所有消息记录，消息记录中有会话信息。这个表是根据用户id做hash然后对128取模分表的

**Comment by 615203360** [comment]
好的，多谢

**Comment by 615203360** [comment]
好的，多谢
