### ISSUE TITLE
多端登录时消息只发给指定的某一端

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#574]
多端登录时消息能只发给指定的某一端吗，比如发送给指定clientId的用户端

**Comment by heavyrain2012** [comment]
这个是没有办法做到的，因为一个用户一个时间线，所有客户端共同使用这个时间线，没有办法按照设备区分。有一种办法是你们在消息中添加更多的信息，客户端收到后根据这些信息判断是那一端的消息

**Comment by 615203360** [comment]
好的明白了，谢谢
