### ISSUE TITLE
t_user_message表怎么判断接收还是发送

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#575]
![1670309493984](https://user-images.githubusercontent.com/20660920/205841830-5a8cb504-30f6-4f94-9ddf-cf043df56c31.jpg)
如上图，用户接收和发送消息的_target都是一样,现在想知道怎么区分接收和发送

**Comment by 615203360** [comment]
![image](https://user-images.githubusercontent.com/20660920/205847810-b1e2f924-7f28-4d50-91f6-fe0f0b1d6db9.png)
这个是t_message表对应的消息数据，这个表是有区分接收方和发送方的，但是这个表是根据消息id值来存放的，所以也没法作为直接的判断因素

**Comment by heavyrain2012** [comment]
> ![1670309493984](https://user-images.githubusercontent.com/20660920/205841830-5a8cb504-30f6-4f94-9ddf-cf043df56c31.jpg)
> 如上图，用户接收和发送消息的_target都是一样,现在想知道怎么区分接收和发送

这个表里有个，directing是方向，fasle是接收，true是发送

**Comment by 615203360** [comment]
请您看下我的截图，里面接收和发送对应的两条记录的directing都是false啊

**Comment by heavyrain2012** [comment]
确实是我理解错了，这个directing是定向消息的意思，不是方向。现在没有办法只从这个表中知道消息的方向，可以多查询一次或者跟消息表联表查询

**Comment by 615203360** [comment]
没办法联表啊，我是根据用户id查询t_user_message表的，但是具体对应到t_message是哪张表，是通过hash算法决定的，没法直接关联，我现在的需求是判断用户a是否给用户b发过消息，只能先根据用户a找到对应的t_user_message表，但t_user_message表数据很可能对应了多个t_message表的数据

**Comment by 615203360** [comment]
我的需求其实很简单，就是想判断某个用户是否给另一个用户发过消息

**Comment by heavyrain2012** [comment]
那就查t_messages表吧，这个能查出来一个用户是不是给另外一个用户发过消息。这个表是按照月份分表的，需要多查几次

**Comment by 615203360** [comment]
那需要查36次啊，头大

**Comment by heavyrain2012** [comment]
没有好办法，只能一个一个地查
