### ISSUE TITLE
怎么关闭添加好友的推送

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#576]
想问下怎么取消添加好友的推送，或者在推送服务中怎么过滤掉添加好友的推送消息

**Comment by heavyrain2012** [comment]
推送到推送服务的数据中有个消息类型，请求添加好友有个对应的值，把那个忽略掉就好了

**Comment by heavyrain2012** [comment]
这个推送应该很需要才对，为什么要去掉？

**Comment by 615203360** [comment]
我们现在是多端登录，所以场景比较复杂，有的端需要收到推送，有的不需要，目前推送服务中添加好友逻辑走的代码如下图：
![1670375737138](https://user-images.githubusercontent.com/20660920/206063840-a8b6a584-bb27-4add-9cba-e00618ee0fc4.jpg)

**Comment by 615203360** [comment]
好的，找到对应解决办法了，谢谢
