### ISSUE TITLE
IM用户状态问题

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/server#577]
1.服务端有强制用户下线API吗？
2.服务端的对账号设置禁用以后，为什么还能收到推送？
3.IM用户删除是物理删除吗？

**Comment by heavyrain2012** [comment]
1.服务端有强制用户下线API吗？
SDK和API有接口可以强制把用户下线，也可以禁用用户，禁用用户会把用户强制下线

2.服务端的对账号设置禁用以后，为什么还能收到推送？
这个是服务器的bug，禁用后应该不再推送，我们稍后修复

3.IM用户删除是物理删除吗？
实际上不是的，会保留这个用户id，然后把这个用户的所有信息包括消息、群组、设置、用户信息（只保留用户id）等全部删除
