### ISSUE TITLE
关于朋友圈评论非好友隐藏的问题

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#580]
目前朋友圈评论所有人都可以看到，想请教下怎么才能够实现非好友用户之间隐藏评论的展示
![index](https://user-images.githubusercontent.com/20660920/211228797-cbcc2040-c015-41dc-9466-8eb237be87a1.png)

**Comment by heavyrain2012** [comment]
请微信联系一下 wildfirechat
