### ISSUE TITLE
安卓SDK中MomentClient.getInstance().getFeedMessages取不到值

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#581]
安卓SDK中MomentClient.getInstance().getFeedMessages取不到值，ios端可以取到值
如下图所示：false应该是取到所有的值
![b49f2b89f5fc539cee766da526bf311](https://user-images.githubusercontent.com/20660920/211264182-e7cb7275-7750-4dd9-bc3a-ae98c542df06.png)

**Comment by heavyrain2012** [comment]
这个消息是本地接收的，请确认更换账号之后收到过评论或者点赞

**Comment by 615203360** [comment]
- 和更换账号没有关系，安卓端isNewMsg为true时有返回消息，false时没返回

**Comment by heavyrain2012** [comment]
isNewMsg为true时返回未读消息，为false时返回所有信息。请检查一下调用接口时有没有异常日志

**Comment by heavyrain2012** [comment]
android朋友圈SDK的问题，请更新后验证
