### ISSUE TITLE
朋友圈取消点赞能取消推送消息

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#582]
朋友圈取消点赞能取消推送消息吗，目前推送效果如下图：
![47604a967067c9ac3834dd83dafbaa5](https://user-images.githubusercontent.com/20660920/212868792-48679a3e-0347-44ae-b5e5-ac3f257174a2.png)

**Comment by 615203360** [comment]
补充下情况描述，现在ios端app未打开情况下就能收到取消点赞的推送消息；安卓端必须app运行在后台才能收到取消点赞的推送消息；请问下这个又是怎么控制的

**Comment by heavyrain2012** [comment]
微信是什么样？是不是撤回不应该推送？

**Comment by 615203360** [comment]
您误会了，不是说不应该推送；是我们的情况比较特殊，现在多个app是共用一个野火号，一个app被的点赞会被推送到另一个app上，想说怎么可以判断这个点赞的类型来进行过滤，或者干脆不推送

**Comment by heavyrain2012** [comment]
我们测试了微信是不推送的，关于朋友圈的消息的line都是2，可以不推送line为2的推送

**Comment by 615203360** [comment]
好的，多谢，我们试试看

**Comment by 615203360** [comment]
你好，我这边测试了，看到的日志中line是1，想确定下朋友圈的line到底是1还是2
![1674110237064](https://user-images.githubusercontent.com/20660920/213372677-92f62c91-2f62-485e-bc5d-34fd95786dc7.jpg)

**Comment by heavyrain2012** [comment]
不好意思我们这边没有仔细看，朋友圈通知消息的line是1
