### ISSUE TITLE
后台删除公众号带来的逻辑问题

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#584]
#### 操作说明
野火公众号的功能，当在频道管理系统和野火开放平台上把频道删除后，从数据库上看，t_application 和 wx_account 两张表的数据已成功被删除。
但是 粉丝表 wx_user 和 IM数据库的 t_channel  两张表的数据依然存在。
客户端搜索已经被删除的公众号，依然有结果，并且可以成功关注

请问这是bug，还是逻辑设计如此？

**Comment by heavyrain2012** [comment]
频道管理系统只能管理频道，不能创建或者删除频道。创建或者删除频道只能server api的权限才可以。设计上应该是开放平台删除频道时调用IM服务删除频道，当频道被删除后，state状态的值应该是64（被删除状态，关于状态的信息可以参考文档），而且server api可以获取到，state为64；客户端应该是搜索不到的。

请确认 数据库中频道的state是多少，server api获取的state是多少，还有客户端能否搜索到？

**Comment by hellomcp** [comment]
从管理平台上删除的公众号，在t_channel表里的状态确实变成了64。
但是这个时候，客户端如果取消关注被删除的公众号，会返回错误码，253，提示对象不存在

**Comment by heavyrain2012** [comment]
删除公众号后，所有的用户应该都取消了订阅才对，你可以检查一下用户的频道列表，应该就没有了，这个时候应该没有“取消关注”的按钮才对。

请确认
1，删除公众号后，用户的频道列表是否有这个被删除的公众号？
2，删除公众号后，用户是在哪里“取消关注”的？在这个界面有没有判断自己是否关注？
