### ISSUE TITLE
野火开放平台中，新建频道的回调地址有什么作用，具体该填什么值？

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#585]
![image](https://user-images.githubusercontent.com/8003424/215724049-2a2f8fe1-bacd-4033-b71d-3fd741cba3b0.png)

野火开放平台中，新建频道的回调地址有什么作用，具体该填什么值？

**Comment by heavyrain2012** [comment]
当有人关注/取消关注频道，或者给频道发送消息时，IM服务会把相关信息callback到这个地址。请把频道回调地址设置为提示的地址，这样频道服务就能收到回调了
