### ISSUE TITLE
如何通过接口判断用户是否关注某个公众号

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#586]
## 如何通过接口判断用户是否关注某个公众号
我们目前的做法是通过查询频道管理平台的粉丝表(wx_user)，来判断用户是否关注某个公众号。

但是碰到一个问题，用户在app上关注了某个公众号后，频道管理平台的粉丝列表，似乎不会立即同步，而是需要手动刷新粉丝列表，才会把新粉丝同步进来。

这样就导致，用户关注某个公众号后，在没有同步粉丝的情况下，通过数据库查询到的结果是没有关注。

有没有接口，可以直接通过调用接口，实时获取用户关注公众号的状态。

**Comment by heavyrain2012** [comment]
在IM服务中，当用户关注/取消关注时，会有个回调到他的回调地址。请检查是否正确设置了回调地址，如果正确设置了回调地址，当有用户变动订阅关系时，频道服务会做对应的更新。另外可以添加定时任务，以一定的周期全量同步用户信息，这个你们自己来加吧。另外我们稍后还会在IM服务提供一个api供频道服务检查用户是否订阅

**Comment by heavyrain2012** [comment]
另外我们稍后还会在IM服务提供一个api供频道服务检查用户是否订阅 

已添加
