### ISSUE TITLE
频道功能目前还不能使用，是吗？

### ISSUE THREAD

**Issue by pullwindyuan** [wildfirechat/server#59]
下载你们提供的演示android版本，创建频道提示创建错误。然后我看了server里的代码，好像确实没看到创建频道相关的代码，还在完善中吗，还是说我打开的方式不对？因为看文档里又确实正式列出了这个功能。

**Comment by heavyrain2012** [comment]
目前还不成熟，请暂时别用

**Comment by pullwindyuan** [comment]
谢谢

**Comment by heavyrain2012** [comment]
频道可以使用了，有问题请及时反馈给我们
