### ISSUE TITLE
解封后用户登录会话是删除状态

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#593]
在服务端用   UserAdmin.updateUserBlockStatus接口进行解封后，客户端第一次登录，t_user_session表中会话记录的_deleted值是1，要重新再登录一次才正常
![67baccc28c1643397cc8c1937dd9c62](https://user-images.githubusercontent.com/20660920/224889869-b2c56039-4e72-4637-b5f6-91e96d65015f.png)

**Comment by heavyrain2012** [comment]
已经解决，请更新最新版本验证

**Comment by 615203360** [comment]
请问这个是什么时候解决的，我们昨天刚向你们同事要了最新的im服务端

**Comment by heavyrain2012** [comment]
一个小时前刚解决的，请再要一下最新的版本吧

**Comment by 615203360** [comment]
已解决
