### ISSUE TITLE
【关于自定义消息】用户收到机器人发送的自定义消息，这个消息我不希望用户看到，或者体验到

### ISSUE THREAD

**Issue by wangdongru** [wildfirechat/server#596]
【关于自定义消息】用户收到机器人发送的自定义消息，这个消息我不希望用户看到，或者体验到，我这里只想推送一个用户看不到的消息，比如：我给用户推送了一个播放动画的一个自定义消息，这个消息本身是不可见的，他是一个动作，用户端只需要播放就可以了，让server 变成一个服务端主动给客户端推送消息的这么一个工具。
其实别的方案也可以，比如自己搞个app长连接，但是既然接入了servie 这个工具，我希望可以使用这个server 来推送自己的自定义不可见用户不可察觉的消息，若是我这个问题有问题，麻烦给指正，或者有什么其他的解决方案，我这里不知道的辛苦帮忙传授一下，谢谢。

**Comment by heavyrain2012** [comment]
自定义消息有个属性persistFlag，这个属性决定该消息是否存储和显示，可以把这个属性设置为不存储，这样就不会存储和显示了，请参考 https://docs.wildfirechat.cn/base_knowledge/message_content.html#消息类型
