### ISSUE TITLE
朋友圈删除后他人看不到评论回复记录

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#597]
现在情况是：A发朋友圈，B评论，A回复B，然后B能在朋友圈消息记录中看到该回复；此时若A删除该条朋友圈，则B再次打开朋友圈消息记录就看不到刚才的已回复消息了。
微信中是收到回复消息，就算对方删除了朋友圈，该消息记录还是会存在的，现在想问怎么能达到这种效果

**Comment by heavyrain2012** [comment]
是删除朋友圈还是删除评论？我们测试的删除朋友圈，消息是不影响的，如果删除评论，则会把通知消息给撤回。请确认

**Comment by 615203360** [comment]
抱歉，是我问题提错了，确切的问题是他人删除朋友圈，希望我的朋友圈消息中能有标志能判断到对方是否删除了朋友圈，然后提供一个友好的详情页展示（目前详情页是空白页）

**Comment by heavyrain2012** [comment]
SDK有个接口是获取单个entry，如果返回253就说明entry不存在

**Comment by 615203360** [comment]
请问下具体是哪个接口

**Comment by heavyrain2012** [comment]
getFeed

**Comment by 615203360** [comment]
前端反馈现在情况是这个getFeed根本就没有回调

**Comment by heavyrain2012** [comment]
前端是android还是iOS？换另外一端测试看看呢？

**Comment by 615203360** [comment]
安卓是完全没回调，ios回调值是-1

**Comment by heavyrain2012** [comment]
查出来了，2个客户端这块儿都有问题，已经解决了，请联系我们更新朋友圈SDK
