### ISSUE TITLE
会话删除不掉 删除群或者会话，重新安装之后 又重新出现。

### ISSUE THREAD

**Issue by shenguanjun** [wildfirechat/server#60]
我是用的mysql数据库  我数据库手动删除好友和群组 安卓客户端的会话列表还在，请问我怎么清理一下客户端的会话列表，手动删除的话，重新安装之后 还会继续出现

**Comment by heavyrain2012** [comment]
客户端和服务器之间有着复杂的数据同步机制，如果是手动删除数据库里的好友和群组是无法更新到客户端的。需要客户端去删除好友和解散群组。另外客户端会话列表是根据消息生成的，我们有历史消息功能，新安装后收都消息就会出现会话

**Comment by heavyrain2012** [comment]
http://docs.wildfirechat.cn/faq/general.html#消息无法删除问题
