### ISSUE TITLE
我这边设置允许陌生人聊天，然后a给b发消息，可以发到消息，数据库里也有，但是b拉取不到会话和消息

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#600]

**Comment by 1295801348** [comment]
a和b是陌生人

**Comment by heavyrain2012** [comment]
发的是文本消息吗？反过来b给a发送消息，a能收到吗？

**Comment by 1295801348** [comment]
> 发的是文本消息吗？反过来b给a发送消息，a能收到吗？

是文本消息，b不能收到，也一样拉不到会话，前端使用的是flutter，代码如下

![image](https://user-images.githubusercontent.com/57829159/228753852-be3f296d-2e1c-410b-b9d1-b807ba5d653d.png)

**Comment by heavyrain2012** [comment]
用flutter的demo连你们的部署的IM服务，发送消息能够互通吗

**Comment by 1295801348** [comment]
> 用flutter的demo连你们的部署的IM服务，发送消息能够互通吗

好友间发送消息是互通的，flutter sdk版本 1个月左右git拉的

**Comment by heavyrain2012** [comment]
> > 发的是文本消息吗？反过来b给a发送消息，a能收到吗？
> 
> 是文本消息，b不能收到，也一样拉不到会话，前端使用的是flutter，代码如下
> 
> ![image](https://user-images.githubusercontent.com/57829159/228753852-be3f296d-2e1c-410b-b9d1-b807ba5d653d.png)

这个代码不对，会话的target不一定都是用户id，也有情况是群组id，你可以看一下野火文档中的基础知识，也可以看一下野火的demo代码

**Comment by heavyrain2012** [comment]
> > 用flutter的demo连你们的部署的IM服务，发送消息能够互通吗
> 
> 好友间发送消息是互通的，flutter sdk版本 1个月左右git拉的

用最新的demo测试看看吧，测试时看一下日志，接收端有没有收到消息

**Comment by 1295801348** [comment]
> > > 用flutter的demo连你们的部署的IM服务，发送消息能够互通吗
> > 
> > 
> > 好友间发送消息是互通的，flutter sdk版本 1个月左右git拉的
> 
> 用最新的demo测试看看吧，测试时看一下日志，接收端有没有收到消息

好的谢谢你
