### ISSUE TITLE
做解散群聊的操作之前能在群信息中添加_extra中的数据吗？为什么都操作成功了而在最后获取_extra字段数据为空字符串

### ISSUE THREAD

**Issue by xqy81** [wildfirechat/server#601]
我想请教一个问题，就是我是使用javaSDK的  当我在调用GroupAdmin.dismissGroup方法之前想在群的拓展信息_extra中加入一些数据去完成一些业务的一些操作，所以调用了GroupAdmin.modifyGroupInfo方法 type=2  但是最终前端收到的信息显示_extra为空的字符串。请问这个是不合法的操作吗？我需要如果改进？
![22221111](https://user-images.githubusercontent.com/126557573/228755261-f2fbb046-2bc9-4189-bf7b-f202b2391e8d.png)

**Comment by heavyrain2012** [comment]
群在解散后在服务器端会被删除，所以如果修改了extra再解散群，客户端没有机会同步到最后的群信息了
