### ISSUE TITLE
pc端登录app端不提示

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#602]
原先pc端登录状态会在app端中展示，现在app端获取不到关于pc端登录的状态了，不确定跟之前升级了im是否有关系，想问下现在这个问题要从哪里入手检查

**Comment by heavyrain2012** [comment]
```
## 是否支持多端登陆，为true时支持任意平台任意多个客户端同时登录；为false时每个平台只支持一个端登录，但不同平台可以同时登录。
## Android/iOS为移动平台，windows/mac/linux为pc平台，web为web平台，小程序为小程序平台，iPad和Android Pad为Pad平台。
server.multi_endpoint false

## 多平台连接状态通知（仅当multi_endpoint为false时有效），true时移动端可以收到pc或web端或Pad端登陆的通知。
server.multi_platform_notification true
```

看一下IM服务的配置文件这，这两个配置是不是这个值

**Comment by 615203360** [comment]
server.multi_endpoint true

**Comment by 615203360** [comment]
server.multi_endpoint true
server.multi_platform_notification true
我们的配置是这样的，因为我们有个需求比较特殊，1个野火账号能同时使用在我们的多个app产品中，所以这个配置必须是true；想问下在true情况下有办法做到pc端登录，app端能收到提示吗

**Comment by heavyrain2012** [comment]
没有办法，如果多端登录是不能进行提示的
