### ISSUE TITLE
通过Server API 设置用户好友关系时，用户关系变动回调返回的value有误

### ISSUE THREAD

**Issue by shenjingfs** [wildfirechat/server#604]
应该是这里直接返回了设置请求里的status
https://github.com/wildfirechat/im-server/blob/c89259e892ac4c25e55e9db67744c48144b2c87b/broker/src/main/java/io/moquette/persistence/MemoryMessagesStore.java#L3213

Server API里设置用户好友关系
<html>
<body>

status | int | 是 | 双方关系，0为好友，1为陌生人
-- | -- | -- | --

</body>
</html> 

用户关系变动回调里
<html>
<body>

value | string | 是 | type为0时，“0”是非好友；“1”是好友。type为1时值为昵称。type2时，“0”非黑名单，“1”拉黑
-- | -- | -- | --

</body>
</html>

之前看到由于历史原因，数据库里 “0”是好友；“1”不是好友，这和回调是相反的

**Comment by heavyrain2012** [comment]
这里确实回调是错误的，已经修改请检查
