### ISSUE TITLE
window 10环境下wildfirechat.bat执行不力

### ISSUE THREAD

**Issue by mscolin** [wildfirechat/server#605]

**Comment by mscolin** [comment]
D:\distribution\bin 的目录

2023/04/14  10:15    <DIR>          .
2023/04/14  10:15    <DIR>          ..
2023/04/13  08:36               480 stop.sh
2023/04/13  08:36             3,774 wildfirechat.bat
2023/04/13  08:36             3,614 wildfirechat.sh
               3 个文件          7,868 字节
               2 个目录 315,868,090,368 可用字节

D:\distribution\bin>wildfirechat.bat
系统找不到指定的路径。
'HOME' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'gotHome' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。
'T_HOME' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
't' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
't' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。
系统找不到指定的路径。
用法：java [options] <主类> [args...]
           （执行类）
   或  java [options] -jar <jar 文件> [args...]
           （执行 jar 文件）
   或  java [options] -m <模块>[/<主类>] [args...]
       java [options] --module <模块>[/<主类>] [args...]
           （执行模块中的主类）
   或  java [options] <源文件> [args]
           （执行单个源文件程序）

 将主类、源文件、-jar <jar 文件>、-m 或
 --module <模块>/<主类> 后的参数作为参数
 传递到主类。

 其中，选项包括：

**Comment by heavyrain2012** [comment]
脚本中有中文导致的失败，把中文去掉就好了，请参考提交 https://github.com/wildfirechat/im-server/commit/c159ff90e359ea2c0eace8aa0dc120382789c601
