### ISSUE TITLE
怎么调用sdk方法发送视频消息

### ISSUE THREAD

**Issue by BarryYang1** [wildfirechat/server#607]
`
MessagePayload payload = new MessagePayload();
payload.setMediaType(MessageMediaType.VIDEO);//值是3
payload.setType(ContentTypeConst.Video);//值是6
payload.setPersistFlag(PersistFlag.Persist_And_Count);//值是3
payload.setContent("{d:3,duration:3}");//这里是我获取的视频时长
payload.setRemoteMediaUrl("这个是我把视频上传到oss的地址");
payload.setSearchableContent("[视频]");

MessageAdmin.multicastMessage(“admin”, "接受的用户", 0, payload);
`
这里发送是成功的，但是在手机端看不到视频，手机端开发说是没拿到缩略图，我这里方法是不是有问题

**Comment by heavyrain2012** [comment]
上面代码中，payload没有填写缩略图，请跟移动端确认缩略图的字段，并填入，这样客户端才能收到缩略图
