### ISSUE TITLE
撤回消息能设置文案吗

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#609]
撤回消息能设置文案吗，如下图，希望能展示自定义的文案
![index](https://user-images.githubusercontent.com/20660920/234151116-320d1b2f-9804-4496-9246-1df791205ae1.png)

**Comment by imndx** [comment]
可以修改的，撤回消息对应的是`RecallMessageContent`，你找到，看一眼里面的`formatNotification`，就知道怎么改了
