### ISSUE TITLE
请问 android 端 SDK层 会议中 弱网时 或者 连接断开 回调什么函数 ？

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/server#610]
会议中回调目前提供 didChangeState(AVEngineKit.CallState callState)
 通话状态
 Idle,   无通话状态
 Outgoing, 呼出中
 Incoming, 呼入中
 Connecting, 建立中
 Connected;  通话中
didParticipantConnected() 适用于 用户音视频接通的回调 ？ 

请问什么回调能满足 会议中（参会成员） 弱网时 或者 连接断开  回调什么函数 ？

**Comment by imndx** [comment]
网络不好时，会有丢包回调`didMediaLostPacket`
断开的回调是：`didParticipantLeft`
