### ISSUE TITLE
源码怎么大部分都没有注释呢。。

### ISSUE THREAD

**Issue by xmo-code** [wildfirechat/server#612]

**Comment by heavyrain2012** [comment]
有这几个原因，一个是命名良好的代码实际上比注释更容易理解，我们的代码都是简单易懂的，没有必要写注释了；另外就是需要投入资源的问题，我们团队开发任务太重，没有额外的资源分配到整理注释的任务上

**Comment by heavyrain2012** [comment]
实际上我们推荐的是使用野火IM，可以通过Server api来对接IM服务，熟悉掌握server api也就可以了，不建议修改IM服务源码，如果有需求可以给我们提

**Comment by xmo-code** [comment]
好的，谢谢
