### ISSUE TITLE
推送服务中收不到包名信息

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#614]
自从上次升级野火后，现在新用户登录后t_user_session表中就没存_package_name这个字段值了，导致了推送无法推。
上次升级的im版本如下图
![image](https://github.com/wildfirechat/im-server/assets/20660920/4f0ec02b-6f08-4923-a3dc-0e3e2dba8004)

**Comment by 615203360** [comment]
补充下问题：
之前的t_user_session数据如图
![image](https://github.com/wildfirechat/im-server/assets/20660920/466a5320-470f-4951-9214-5860fc2734ba)

现在的t_user_session数据如图
![image](https://github.com/wildfirechat/im-server/assets/20660920/f4145a9c-deb2-48e0-8ec3-decb4afa8e03)

**Comment by 615203360** [comment]
补充：因为我们推送服务中需要根据包名来区分推送给哪个app，所以现在没包名，就没法推了

**Comment by 615203360** [comment]
补充：对应推送服务的代码，入参对象中packageName字段空
![image](https://github.com/wildfirechat/im-server/assets/20660920/5cca68bd-c645-4854-b56a-04706d574629)
![image](https://github.com/wildfirechat/im-server/assets/20660920/8983bffe-61e4-45b8-a3f7-24c4fc57cbb4)

**Comment by heavyrain2012** [comment]
这个问题已经确认，是我们IM服务引入的问题，已经解决，请邮件联系我们要最新的版本

**Comment by 615203360** [comment]
请问下是指im服务端要升级最新，还是指app端sdk要升级最新

**Comment by heavyrain2012** [comment]
IM服务的问题，只升级IM服务就能解决问题
