### ISSUE TITLE
im-server专业版部署时报错 /bin/sh: ./bin/wildfirechat.sh: Permission denied

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#617]
![image](https://github.com/wildfirechat/im-server/assets/57829159/a88a8e41-6120-4f4a-b11c-280bc3c74b15)

sudo docker run -it --name im-server-professionalEdition -v $PATH_TO_CONFIG:/opt/im-server/config -v $PATH_TO_LOGS:/opt/im-server/logs -v $PATH_TO_H2DB:/opt/im-server/h2db -v $PATH_TO_MEDIA:/opt/im-server/media -e JVM_XMX=256M -e JVM_XMS=256M -p 80:80 -p 1883:1883 -p 8083:8083 -p 8084:8084 -p 18080:18080 im-server

![image](https://github.com/wildfirechat/im-server/assets/57829159/8dfca4da-38ec-4962-b22c-c8bd62f05ddc)
wildfirechat 文件夹里面的wildfirechat.sh 权限已经配 chmod u+x 了

**Comment by heavyrain2012** [comment]
你把错误信息贴一下

**Comment by 1295801348** [comment]
/bin/sh: ./bin/wildfirechat.sh: Permission denied
错误信息就是这个

**Comment by 1295801348** [comment]
![image](https://github.com/wildfirechat/im-server/assets/57829159/b3f7ba6b-3c4e-4c33-b48b-1ca251be2481)
![image](https://github.com/wildfirechat/im-server/assets/57829159/87006767-d7ed-41c0-9cec-7f619aa05f0b)
docker-compose -f docker-compose-im-server-pr.yml up -d

**Comment by heavyrain2012** [comment]
Dockerfile改一下，在sed语句后面加上一个chmod，然后在编译Image重新运行试试
```
RUN sed -i 's/#JAVA_OPTS="$JAVA_OPTS -Xmx128M"/JAVA_OPTS="$JAVA_OPTS -Xmx$JVM_XMX"/g' /opt/im-server/bin/wildfirechat.sh
RUN sed -i 's/#JAVA_OPTS="$JAVA_OPTS -Xms128M"/JAVA_OPTS="$JAVA_OPTS -Xms$JVM_XMS"/g' /opt/im-server/bin/wildfirechat.sh

RUN chmod a+x /opt/im-server/bin/wildfirechat.sh

```
