### ISSUE TITLE
怎么提升语音消息-音质

### ISSUE THREAD

**Issue by huazaihuola** [wildfirechat/server#619]
问题：
目前语音的格式是amr 音质，质量很小，但是音质有点差，想怎么才能提升音质。

**Comment by heavyrain2012** [comment]
是语音消息？还是语音通话？是哪个端发出来的？

**Comment by huazaihuola** [comment]
> 

比如 A用户->用户B 发送消息，B用户播放，有音损。后来我给我的自己的机器人发送消息，并异步回调监听，发现内容是一个amr 音频，所以想问一下，前端发送的语音在哪里控制，怎么提升两人发送语音消息的音质。

**Comment by huazaihuola** [comment]
@heavyrain2012

**Comment by heavyrain2012** [comment]
录音是客户端UI层录制的，所有录音和转码的代码都是开源的，让你们对应的客户端找到代码自己修改就行
