### ISSUE TITLE
为啥没有申请好友的接口，只有设置好友的？

### ISSUE THREAD

**Issue by xielinkin100** [wildfirechat/server#62]
看代码和官方开发手册
http://docs.wildfirechat.cn/server/admin_api/user_relation.html

http://domain/admin/friend/status

只有这个，设置好友关系的接口。

而不是客户端那边的逻辑，发起申请，申请通过。

查看客户端代码，好像是从协议栈走的这块服务。

**Comment by heavyrain2012** [comment]
server api要尽量保持简单，如果需要2个成好友关系就调用serverapi直接设置为好友关系。
如果你们业务中需要实现好友请求功能，可以给客户端发送一个自定义消息，客户端收到后后台发送一个好友请求
