### ISSUE TITLE
问下消息过期时间字段是用来做什么的，过期了会如何？

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#622]
![image](https://github.com/wildfirechat/im-server/assets/57829159/2cf73e18-14ac-4e2f-b2e8-e78eb85f31d0)

**Comment by heavyrain2012** [comment]
这是用在某些特殊场景，消息如果过了多久没有收到就无意义了，就不需要客户端再接收了，就可以设置过期时间
