### ISSUE TITLE
im-server 专业版一直弹这个是什么意思

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#625]
![image](https://github.com/wildfirechat/im-server/assets/57829159/a59d3bf2-0541-4560-8ce0-51f6d7e4e38f)

**Comment by heavyrain2012** [comment]
这个是有连接到端口没有发送任何数据再断开。有2种可能，一种可能是被网络扫描引起，另外一种可能是IM服务前面有nginx或者其他负载均衡，这个组件在对IM服务进行探活。这个日志可以忽略不管

**Comment by 1295801348** [comment]
好的
