### ISSUE TITLE
发送视频消息，对视频长度，大小有限制吗，我这边发送视频大于7分钟就发不出去了

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#627]

**Comment by imndx** [comment]
视频消息是媒体消息的一种，使用社区版 im-server 时，客户端使用协议栈进行文件上传，会将文件内容全部拷贝到内存，进行加密处理，故限制上传大小不能超过 100M。

针对社区版 im-server：
1. 配置 im-server 使用七牛云存储，社区版 im-server 支持内置文件存储和七牛云存储
2. 对超过100M 的文件，先在应用层进行上传，得到远程链接之后，再构建媒体消息，然后发送

针对专业版 im-server：
1. 配置 im-server 使用**非内置文件存储**即可，专业版 im-server 支持内置文件存储、七牛、阿里、华为、腾讯、野火专业存储等
2. 没了

**Comment by 1295801348** [comment]
好的谢谢你
