### ISSUE TITLE
野火专业版 上传文件的限制大小能不能搞个开关，让我们决定大小限制是多少，我们只打算使用野火内置文件存储

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#628]

**Comment by imndx** [comment]
内置文件存储，最大支持上传 100M；如果需要支持更大的媒体文件的话，需要切换到其他对象存储。

要在最大支持范围内做限制的话，可以在应用层实现，在发送媒体消息之前，检查下媒体文件大小。

另外，内置文件存储不是产品级的，仅仅为了方便大家测试，一般只建议开发、测试时使用，不建议在生产环境使用。
