### ISSUE TITLE
im-server nginx 集群模式问题

### ISSUE THREAD

**Issue by 1295801348** [wildfirechat/server#629]
（1）im-server nginx 集群模式问题下，im-app的im.admin_url 填的一定是授权域名吗？
（2）im-server的配置 server.ip 可以填授权域名吗？

**Comment by 1295801348** [comment]
（3）server.ip 如果写节点域名，那么授权域名需要转发到哪个端口

**Comment by heavyrain2012** [comment]
只有专业版IM服务才可以支持集群模式。在专业版集群部署时，其他服务调用IM服务的管理端口（比如应用服务）可以调用到任意一个节点的18080端口，也可以在集群前对18080端口做负载均衡随机到任意节点的18080端口就行，对请求地址没有要求，不一定要用手去域名，建议用内网ip地址。问题2和3请参考专业版IM服务包内的README.md 上面有多种部署方式，软件包内还有个nginx目录，里面有nginx的示例说明

**Comment by 1295801348** [comment]
好的
