### ISSUE TITLE
建议增加用户自定义自己的账号能否被搜索

### ISSUE THREAD

**Issue by qiuDar** [wildfirechat/server#630]
配置文件中有两个全局配置
##禁止搜索用户
friend.disable_search false

##禁止按照昵称搜索用户。
friend.disable_nick_name_search false

但是这两个配置是全局的，建议增加用户自定义自己能否被其他用户搜索，类似“QQ设置>权限设置>防骚扰”，以及“微信设置>朋友权限>添加我的方式”中的功能。用户可以选允许搜索（默认），不允许电话号码搜索，不允许所有搜索这几个选项，只有精准搜索才有效

**Comment by heavyrain2012** [comment]
此功能已经添加，请更新最新的IM服务，然后客户端也需要更新到最新
