### ISSUE TITLE
ios端无法打开自己发送的视频

### ISSUE THREAD

**Issue by makesiengesi** [wildfirechat/server#631]
#### 操作说明
在聊天界面，如果iOS用户发送了视频，iOS用户是无法打开视频进行播放，

#### 表现现象

你们的代码里面有给 AVPlayerItem 添加 status 等观察者，每次进行打开都是这个status的 AVPlayerStatusFailed错误
error是：Error Domain=AVFoundationErrorDomain Code=-11850 "操作已停止" UserInfo={NSLocalizedFailureReason=服务器配置不正确。, NSLocalizedDescription=操作已停止, NSUnderlyingError=0x281123960 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}

#### 预期结果
你认为正确的表现应该是什么样的。
视频最开始播放的时候，会请求一个Range【0-1】的 bytes range request。如果返回http code = 200 就会报这个11850错误。如果返回206，才可以正常播放。我们希望视频播放的时候 http code 是 206，让视频正常播放

#### 补充条件
目前在所有iOS设备上测试的是必现 ，2023年6月28日

**Comment by heavyrain2012** [comment]
这是因为IM服务内置的文件存储是测试基本的，我们建议使用商业水平的对象存储，比如七牛云，如果是专业版IM服务，还可以使用私有化部署的minio，阿里云和腾讯云
