### ISSUE TITLE
im-server部署失败了

### ISSUE THREAD

**Issue by 2748669816** [wildfirechat/server#635]
![L5IQSWPJ 38I$1Y @SO2GE8](https://github.com/wildfirechat/im-server/assets/73819017/3824bcf9-efae-459a-b083-63c73a5abdd6)
我在im-server部署过程中出现了图上的问题，我不知道什么地方出错了

**Comment by heavyrain2012** [comment]
IM服务的config目录下有个配置文件 wildfirechat.conf，把server.ip配置为有限的外网IP再试试
