### ISSUE TITLE
获取群组内未读消息数经常失败。

### ISSUE THREAD

**Issue by yuanld5** [wildfirechat/server#636]
## 提issue小提示
有很多群组聊天的时候，经常发生群组内未读数不正确的问题。

#### 操作说明
研究过野火的SDK，获取消息列表和最后读取的时间戳是两个请求，获取正确的未读数量需要两个请求全部能够成功，在网络不稳定或者重新启动应用的时候，经常出现消息获取成功但timestamp获取不到的现象，能否修改下SDK，获取消息列表的同时也把timestamp获取下来，保证事务的完整性。

#### 表现现象
群组内未读消息数量不正确。

#### 预期结果
所有客户端的群组未读消息数量一致。

**Comment by heavyrain2012** [comment]
请用最新的sdk进行验证，如果最新sdk也有问题，请详细给出问题现象描述和复现问题的方法
