### ISSUE TITLE
请用最新的sdk进行验证，如果最新sdk也有问题，请详细给出问题现象描述和复现问题的方法

### ISSUE THREAD

**Issue by yuanld5** [wildfirechat/server#637]
请用最新的sdk进行验证，如果最新sdk也有问题，请详细给出问题现象描述和复现问题的方法

_Originally posted by @heavyrain2012 in https://github.com/wildfirechat/im-server/issues/636#issuecomment-1619730242_
            
十分感谢回复，我们也算野火IM的重度用户了，这种情况比较难直接复现，跟网络环境和程序的执行情况都有关系。如果群组比较多，我们的测试人员总能发现个别群组未读数量不一致的情况。

**Comment by heavyrain2012** [comment]
您给的信息让我们无法入手，至少要把问题详细描述清楚，我们还是弄不清楚问题是什么样的，请补充描述更详细的信息，如果有图片对比或者视频更好

**Comment by heavyrain2012** [comment]
还有你们使用的是什么时候的版本也需要提供一下，在协议栈日志中搜索 setAuth，可以看到协议栈编译日期

**Comment by yuanld5** [comment]
有多个组的情况下，经常有个别组的消息虽然拉下去了，但是未读数不完全正确。现象就是能看到最后一条消息摘要，但显示的未读数不正确，偶发频发。

**Comment by yuanld5** [comment]
应该是好了很多，谢谢。
