### ISSUE TITLE
搜索用户返回的type数据错误

### ISSUE THREAD

**Issue by sunzhonghui** [wildfirechat/server#638]
#### 操作说明

PC端或者手机端，搜索用户

#### 表现现象

![1688701235512](https://github.com/wildfirechat/im-server/assets/17609963/d43331ad-59ad-4fbc-9972-b4b36fdcda32)
![image](https://github.com/wildfirechat/im-server/assets/17609963/f5093db1-053d-492e-9563-38d171d5f80e)
查询返回用户类型（type）错误，机器人也返回 0 

#### 预期结果

你认为正确的表现应该是什么样的。
应该返回正确的类型，机器人返回1 ，用户返回 0 

#### star 我们
已经star

**Comment by heavyrain2012** [comment]
客户端协议栈也没有处理，等我们更新

**Comment by heavyrain2012** [comment]
已经更新请验证
