### ISSUE TITLE
Can I get the GPS info of the client?

### ISSUE THREAD

**Issue by ChenTsuei** [wildfirechat/server#64]
This project is so promising. And I'm developing a chatbot based on this.

But I'm wondering if I can get the GPS info of the client?

**Comment by heavyrain2012** [comment]
多谢您的支持！
我们支持自定义消息，你可以在客户端获取地理位置信息后通过自定义消息发送出去。可以发送给一个机器人，使用机器人服务接收位置信息

**Comment by ChenTsuei** [comment]
Thanks for your reply. I think the further discussion should be under wildfirechat/android-chat.
