### ISSUE TITLE
a b 正在手机通话，c 给 a 发送野火音视频通话请求，a接了，a c野火音视频通话异常

### ISSUE THREAD

**Issue by Voorb** [wildfirechat/server#640]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
a b 正在手机通话
c 给 a 野火发送音视频通话请求，a 接了
结果：
a 和 b 可以正常手机通话
(注意：当a是安卓手机，手机通话并且接听野火音视频时)
Android : a 能听到 c 的声音，c 听不到 a 的声音
(注意：当a、c是苹果手机，手机通话并且接听野火音视频时)
iOS : a c 接通后，双方听不到对方的声音

#### 预期结果
A与B手机通话时，C通过野火对A发起音视频通话时应无法发起
提示文案显示：
C显示：对方忙线中
A显示：忙线未接听
当A与B在野火进行音视频通话时，B的手机收到系统通话，当B接听了系统通话时
A和B文案显示为：通话中断

#### 补充条件
必现

#### demo对比结果
demo也存在此问题

**Comment by heavyrain2012** [comment]
iOS音视频sdk的已经修改，免费版更新最新版本即可，收费版请联系我们更新。
android的没有办法在sdk内部加，因为有些商店不允许监听通话状态。你们可以按需在UI层处理，当收到音视频通话邀请时，检查如果在通话中时可以挂掉

**Comment by Voorb** [comment]
谢谢，我用demo测试了下
当A与B在野火进行音视频通话时，B的手机收到系统通话，当B接听了系统通话时
A和B文案显示为：通话中断
缺少了这种情况的处理，通话状态不够用，估计得新增状态：通话中断

**Comment by heavyrain2012** [comment]
已修改，在SDK中添加了通话中断和对方通话中断2个状态，然后UI层也做了对应的提示。请升级音视频SDK然后再同步UI层提示

**Comment by Voorb** [comment]
好的，另外请问下：安卓端和电脑端在SDK中也同步添加了通话中断和对方通话中断2个状态吗

**Comment by heavyrain2012** [comment]
已经添加
