### ISSUE TITLE
希望可以增加一个服务端获取用户会话列表的api

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/server#643]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明

希望可以增加一个服务端获取用户会话列表的api，不然服务端去MongoDB去操作数据库获取，太耗CPU了。

**Comment by heavyrain2012** [comment]
事实上野火没有在服务器端存储会话列表，服务器上只存储了消息。客户端收到消息后根据消息来自动生成会话列表。如果你们想要会话列表，可以使用消息转发功能，把消息转发到你们业务服务，业务服务记录下来会话列表
