### ISSUE TITLE
客户端设置ID大小写敏感，导致有撞号风险

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/server#645]
#### 操作说明
A用户修改野火ID为 Zhangsan
B用户修改野火IID为 zhangsan

#### 表现现象
B客户端可以修改成功

#### 预期结果
虽然功能上没有问题，但是这样会导致一个服务器上可以冒充、撞号。建议改成大小写不敏感，或者在二开的时候可配置

#### 补充条件
微信设置微信号是大小写不敏感的，就是Zhangsan存在，那么zhangsan就设置不了

**Comment by heavyrain2012** [comment]
可以对_name设置大消息不敏感，sql语句为 ALTER TABLE `t_user` MODIFY COLUMN `_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
