### ISSUE TITLE
消息解析问题MessagePayload{contentType: 406

### ISSUE THREAD

**Issue by 1771893348** [wildfirechat/server#646]
## 提issue小提示
消息解析问题MessagePayload{contentType: 406
#### 操作说明
应该是多人视频呼叫的消息提醒，注册CallStartMessageContent这一个解析不了这个消息，应该怎么解析

**Comment by imndx** [comment]
406 是多人音视频通话，添加新的参与者的通知消息，可以参考下客户端的`AddParticipantsMessageContent`进行解析

**Comment by heavyrain2012** [comment]
是flutter端吗，现在flutter端是缺少这个消息的，我们稍后会添加这个消息

**Comment by heavyrain2012** [comment]
已添加，请检查 https://github.com/wildfirechat/wfc_flutter_plugins/commit/137891eef7f0b1b68575148b402fa2b9c3eb28ca
