### ISSUE TITLE
如何通过API修改已发送的消息内容

### ISSUE THREAD

**Issue by qiuDar** [wildfirechat/server#649]
应用场景：
想制作类似QQ红包微信红包之类的消息，目前通过自定义消息内容实现“红包”消息，但是想在用户领取红包之后将“红包”消息内容变更，使之在聊天对话框中的样式变更，比如文字变成已领取。

如何通过API去修改已发送的消息内容，或者有没有什么其他方案实现这种红包消息

**Comment by heavyrain2012** [comment]
专业版IM服务有修改消息内容的功能，修改后的内容会自动同步到客户端，可以通过server api来修改消息

**Comment by qiuDar** [comment]
> 专业版IM服务有修改消息内容的功能，修改后的内容会自动同步到客户端，可以通过server api来修改消息

没有在文档中Server API部分找到修改消息的方法

**Comment by imndx** [comment]
客户端可以使用`updateRemoteMessageContent`更新自己发送的消息
用 java 版本的 server sdk 是`MessageAdmin.updateMessageContent`

**Comment by heavyrain2012** [comment]
客户端只能改自己发的消息，而且还需要在IM服务的配置文件中指定哪些类型的消息可以修改。如果是红包这种场景，需要用server api修改，正好在红包服务处理拆红包后用server api修改

**Comment by qiuDar** [comment]
好的我知道怎么弄了

**Comment by nanxiangquan** [comment]
server api修改消息，只有接收方同步到到了修改之后的消息，发送方没有接收到修改的消息。请问一下，这种情况如何处理？
