### ISSUE TITLE
单聊修改消息

### ISSUE THREAD

**Issue by nanxiangquan** [wildfirechat/server#651]
单聊情况下，发送方发送了一条消息，然后通过server-api接口修改这条消息，只有接收方同步到了修改之后的消息，发送方没有同步到修改后的消息。请问一下，这种情况如何处理？

**Comment by heavyrain2012** [comment]
IM服务是专业版吗？调用的是那个接口？

**Comment by heavyrain2012** [comment]
我这边测试没有发现问题啊，如果你那边还有问题，请微信联系 wildfirechat
