### ISSUE TITLE
群发消息没法取消推送

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#653]
专业版中调用MessageAdmin.multicastMessage接口群发消息时，就算PushContent传null值依然会推送消息

**Comment by heavyrain2012** [comment]
内置的消息类型不依赖于pushContent，只有自定义消息才依赖。如果想要群发消息不推送，有2种方法，一是用自定义消息，不设置pushContent，二是在推送服务处理，推送服务如果检查是不需要推送的，就不推送
