### ISSUE TITLE
全局禁言用户

### ISSUE THREAD

**Issue by qiuDar** [wildfirechat/server#654]
能否出一个对指定用户全局禁言的接口，目的是禁止用户私聊或者所有群聊都不允许发送消息，但是还能接收别人或者管理员发送过来的消息。这个功能的场景是当用户违规被风控时禁言用户，并通过管理员发送消息通知给用户禁言的原因。当然还需要能解除全局禁言。

**Comment by heavyrain2012** [comment]
有这个接口 https://docs.wildfirechat.cn/server/admin_api/user_api.html#更新用户状态  SDK也有这个方法，在UserAdmin对象内

**Comment by qiuDar** [comment]
> 有这个接口 [https://docs.wildfirechat.cn/server/admin_api/user_api.html#更新用户状态](https://docs.wildfirechat.cn/server/admin_api/user_api.html#%E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7%E7%8A%B6%E6%80%81) SDK也有这个方法，在UserAdmin对象内

多谢了，测试过确实符合需求
