### ISSUE TITLE
项目启动后有一条flywaydb日志反复打印

### ISSUE THREAD

**Issue by lxd7788** [wildfirechat/server#655]
org.flywaydb.core.internal.logging.slf4j.Slf4jLog.warn(Slf4jLog.java:53) - DB: Integer display width is deprecated and will be removed in a future release. (SQL State: HY000 - Error Code: 1681)
数据使用的是mysql8
除了修改日志级别，还有其他方案吗

**Comment by heavyrain2012** [comment]
这个在启动成功以后，应该不会再打印了吧
