### ISSUE TITLE
PersistFlag的Not_Persist类型问题

### ISSUE THREAD

**Issue by fkkky** [wildfirechat/server#656]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
我在使用MessageAdmin.sendMessage接口时，修改MessagePayload中的PersistFlag为Not_Persist时仍然入库了

#### 表现现象
从官方文档上来看，Not_Persist应该是不需要入库的，但是实际结果却仍然入库t_sensitive_messages表了
![image](https://github.com/wildfirechat/im-server/assets/110454073/5f644d12-f48d-43e3-b7f5-a839965f8105)

#### 预期结果
如果文档描述问题正确的话，在DatabaseStore的persistSensitiveMessage方法内是否应该加上这个判断
![image](https://github.com/wildfirechat/im-server/assets/110454073/a78398e8-4035-4704-bf22-a8510da4f334)

#### 补充条件
必现

#### demo对比结果
加上之后就不会进行入库了
![image](https://github.com/wildfirechat/im-server/assets/110454073/e055f86b-db3d-4a5c-9286-19e96e1a0c97)

**Comment by imndx** [comment]
`Not_Persist`是表示客户端不入库，服务端是入库的
