### ISSUE TITLE
im_server 由免费版切换成付费版之后, admin 消息列表中的撤回功能, 报错

### ISSUE THREAD

**Issue by Kennyfengff** [wildfirechat/server#657]
admin请求参数 如下图
![image](https://github.com/wildfirechat/im-server/assets/148446550/acc64420-95fa-48b1-8694-c95aa462c85c)
![image](https://github.com/wildfirechat/im-server/assets/148446550/674ed87e-375d-46b0-8d83-ecece60a1c72)
![image](https://github.com/wildfirechat/im-server/assets/148446550/a5a76efa-5b4b-431e-a9b3-d9a6a2d95f30)
admin 报错日志见txt
[log.txt](https://github.com/wildfirechat/im-server/files/13041257/log.txt)

**Comment by imndx** [comment]
请更新[server sdk](https://github.com/wildfirechat/app-server/blob/master/src/lib/)

**Comment by Kennyfengff** [comment]
已解决当前问题, 多谢
