### ISSUE TITLE
群组聊天详情页，A用户发消息被群主/管理员撤回后，A用户的页面该条消息被撤回了

### ISSUE THREAD

**Issue by Kennyfengff** [wildfirechat/server#659]
![image](https://github.com/wildfirechat/im-server/assets/148446550/55bd6690-990a-4b2f-8c0d-524f4f2663ce)

**Comment by heavyrain2012** [comment]
不对吧，如果被撤回了，所有人看到的都应该是被撤回状态吧，如果让发送者还以为没有被撤回，这是不符合逻辑的啊

**Comment by Kennyfengff** [comment]
这个是我们业务要求的,  能有办法兼容吗?

**Comment by heavyrain2012** [comment]
有个办法是发送者的撤回消息中，应该有被撤回的内容，可以在显示的时候处理显示被撤回的消息内容，在UI层进行处理。
但我个人觉得这样不符合逻辑啊，如果没有对业务很重要，建议不要改
