### ISSUE TITLE
群发消息撤回可以设置消息不推送吗

### ISSUE THREAD

**Issue by 615203360** [wildfirechat/server#661]
群发消息撤回有办法设置撤回消息为不推送吗，我用的是这个方法MessageAdmin.recallMultiCastMessage

**Comment by heavyrain2012** [comment]
有个办法是消息的pushData中添加一个字端，这样推送服务收到后解析出来不进行推送就行。注意这个pushData有可能客户端也会定义来传输数据，建议用json，这样避免解析错误
