### ISSUE TITLE
希望朋友圈可以增加一个获取朋友新发的消息数量功能

### ISSUE THREAD

**Issue by hex-creator** [wildfirechat/server#662]
希望朋友圈可以增加一个获取朋友新发的消息数量的接口，同时有新发消息的通知回调

**Comment by heavyrain2012** [comment]
朋友圈是松散关系，如果统计所有未读/新发的数据，是代价特别大而且无用的。像回复和提醒消息是有的

**Comment by heavyrain2012** [comment]
朋友圈中判断是否有新消息就行，当需要显示有红点时，请求一下数据，然后再跟本地记录最后阅读时间对比，就知道有没有新的未读的
