### ISSUE TITLE
用户搜索条件需求

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/server#664]
你好，我们当前有一个需求需要把搜索用户改成 uid 或 name 进行搜索用户添加好友，当前的sdk并不支持这个方式，请求是否可以把两个搜索方式加上。
描述：我们当前使用的是你们的t_user表进行用户托管，然后看到这个表的_uid和_name两个字段都是唯一索引，已经符合了我们的需求。所以我们把_uid的生成策略变成了数字（类似QQ号码），name也是唯一值可以当作登录用户名（类似微信号）。我们已经实现了使用_uid或_name进行登录验证，现在的需求就是需要添加好友时也可以使用这两个字段进行搜索。

**Comment by heavyrain2012** [comment]
已经支持，请更新服务器和客户端SDK验证
