### ISSUE TITLE
希望增加一个用户所在聊天室id列表的api

### ISSUE THREAD

**Issue by Togeth3r** [wildfirechat/server#665]
感觉聊天室用在直播间很合适，就一直在直播间用着。
最近有个场景需求，因为app端和小程序端是能同时登录的，同时进入直播间。
现在要做一个不可以同时进入直播间的功能，或者一端进入直播间后将其余进入直播间的客户端全退出来，感觉有这么一个api挺好的。

**Comment by imndx** [comment]
目前客户端有临时方案可实现：
用`UserSetting`实现，`UserSetting`跨端支持，并且是实时的。

大概实现步骤是这样子的：
1. 定义一个新的`UserSettingScope`，比如：`currentChatRoomSetting = 1002`
2. 定义`UserSetting`的`key`和`value` ，比如：`key =  currentChatRoom`，`value = ${当前 chatRoomId} + ${当前时间戳}`
3. 进入聊天之前，先调用`getUserSetting`，获取当前聊天室相关设置，并检查，以判断是否允许进入新的聊天室
4. 进入聊天之后，每分钟调用`setUserSetting`刷新时间戳，目的是防止杀进程等异常退出聊天室，导致聊天室设置有值，但不知道是否是合法的，每分钟刷新时间戳之后，就可以根据时间戳判断是否合法，2 分钟之前的聊天室设置，就认为是不合法的，表示当前并没有其他端在聊天。

**Comment by heavyrain2012** [comment]
最新提交做了2处修改，一个是添加了一个server api，可以获取一个用户在那个聊天室中。另外一个修改是添加了一个配置，当一个端在聊天室中时，如果另外一个端加入聊天室是把之前的踢掉还是返回错误。这2个修改应该能帮你们解决这个问题

**Comment by Togeth3r** [comment]
非常感谢，相信野火团队能取得更大的成就，蒸蒸日上。
