### ISSUE TITLE
有没有办法获取历史记录不获取用户加入和退出这种

### ISSUE THREAD

**Issue by bocaiJs** [wildfirechat/server#667]
现在有个需求是展示历史记录的时候不显示用户加入和退出的记录
有没有办法获取的时候不返回这些数据呢

**Comment by bocaiJs** [comment]
文档里有这么个问题 ，但是现在打不开了
https://docs.wildfirechat.cn/faq/gneral.md#15.%20%E6%88%91%E4%B8%8D%E6%83%B3%E6%94%B6%E5%88%B0%E6%9F%90%E4%BA%BA%E9%80%80%E5%87%BA%E7%BE%A4%E7%BB%84%E6%B6%88%E6%81%AF%E8%AF%A5%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%EF%BC%9F%EF%BC%88%E8%AE%A9%E6%9F%90%E4%BA%9B%E6%B6%88%E6%81%AF%E4%B8%8D%E6%98%BE%E7%A4%BA%E8%AF%A5%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%EF%BC%9F%EF%BC%89

**Comment by bocaiJs** [comment]
<img width="942" alt="image" src="https://github.com/wildfirechat/im-server/assets/19830233/ba9012a7-469e-435f-b37f-3815d2264f6c">

**Comment by heavyrain2012** [comment]
> 文档里有这么个问题 ，但是现在打不开了 https://docs.wildfirechat.cn/faq/gneral.md#15.%20%E6%88%91%E4%B8%8D%E6%83%B3%E6%94%B6%E5%88%B0%E6%9F%90%E4%BA%BA%E9%80%80%E5%87%BA%E7%BE%A4%E7%BB%84%E6%B6%88%E6%81%AF%E8%AF%A5%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%EF%BC%9F%EF%BC%88%E8%AE%A9%E6%9F%90%E4%BA%9B%E6%B6%88%E6%81%AF%E4%B8%8D%E6%98%BE%E7%A4%BA%E8%AF%A5%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%EF%BC%9F%EF%BC%89

@bocaiJs 您好，这个链接从哪里找到的？

**Comment by heavyrain2012** [comment]
https://docs.wildfirechat.cn/blogs/如何不显示退群和踢人消息.html    这个链接可能能解决您的问题
