### ISSUE TITLE
获取加入之前的群历史获取不到

### ISSUE THREAD

**Issue by bocaiJs** [wildfirechat/server#669]
<img width="822" alt="image" src="https://github.com/wildfirechat/im-server/assets/19830233/f52c6294-7183-4c2f-97ac-fa09d8fb5246">
<img width="1501" alt="image" src="https://github.com/wildfirechat/im-server/assets/19830233/80e795b0-c5f0-487e-9784-53705624bc81">

imserver上配置了允许拉取群消息
新建的群也允许成员拉取群消息
但是 前端获取的时候获取不到成员加入之前的群记录
请问要怎么解决呢

**Comment by heavyrain2012** [comment]
还有一个配置，是否允许拉取远程消息，那个开关也需要打开

**Comment by bocaiJs** [comment]
> 还有一个配置，是否允许拉取远程消息，那个开关也需要打开



> 还有一个配置，是否允许拉取远程消息，那个开关也需要打开

##是否开启拉取远程历史消息。如果为1，客户端在会话内如果本地消息读取完了，可以下拉继续加载在服务器上的该会话的消息；如果为0则不能。
message.remote_history_message 1
 是这个嘛？开启了的

**Comment by heavyrain2012** [comment]
这个问题最新版本应该已经解决。请更新验证。如果还有问题，请再打开issue
