### ISSUE TITLE
群组推送和频道推送的标题

### ISSUE THREAD

**Issue by fightroad** [wildfirechat/server#670]
群组推送和频道推送 。能否把标题改成想用的群组名和频道名  现在推送的标题 群组是发消息的人名  频道是频道主的名。

**Comment by heavyrain2012** [comment]
IM服务向推送服务发送的请求里，有target和targetName，如果是频道就是频道id和频道名称，这个信息可以满足你们的需求

**Comment by heavyrain2012** [comment]
我看了推送服务那边的代码，有部分推送用了targetName，有部分没有用，请问你是在那个推送上发现的问题

**Comment by fightroad** [comment]
> 我看了推送服务那边的代码，有部分推送用了targetName，有部分没有用，请问你是在那个推送上发现的问题

我是在个推上

**Comment by fightroad** [comment]
> > 我看了推送服务那边的代码，有部分推送用了targetName，有部分没有用，请问你是在那个推送上发现的问题
> 
> 我是在个推上

![1700789847622](https://github.com/wildfirechat/im-server/assets/39027157/f79d77db-1226-4797-aa1f-3d049a1515ff)
im推推送服务的时候pushMessageType  没能区分出是频道还是群组 还是单聊的  所以都走到标题显示发送者。

**Comment by fightroad** [comment]
> > > 我看了推送服务那边的代码，有部分推送用了targetName，有部分没有用，请问你是在那个推送上发现的问题
> > 
> > 
> > 我是在个推上
> 
> ![1700789847622](https://user-images.githubusercontent.com/39027157/285333103-f79d77db-1226-4797-aa1f-3d049a1515ff.png) im推推送服务的时候pushMessageType 没能区分出是频道还是群组 还是单聊的 所以都走到标题显示发送者。

看到推送服务有个convType  会话类型。应该是这个区分。

**Comment by fightroad** [comment]
改推送服务实现
