### ISSUE TITLE
断开连接 清空seeion表里的devicetoken

### ISSUE THREAD

**Issue by fightroad** [wildfirechat/server#672]
现在执行断开连接方法后并没有清空sesstion 表token字段。导致app退出登陆后 如果没有登陆其他账号的情况下。给刚退出的账号发离线消息，该手机还能够收到厂商推送过来的离线消息。（这样感觉不合理） 不清楚im-server离线消息是怎样的处理逻辑。感觉判断token‘字段推送感觉有问题。app通过任务栏非正常结束进程，也会出现一样的情况，可以接收到厂商推过来的离线消息。

**Comment by heavyrain2012** [comment]
disconnect的参数有2个，有个disablePush参数，当disablePush为true时，应该收不到推送
