### ISSUE TITLE
限制用户发送消息的频率

### ISSUE THREAD

**Issue by doralines** [wildfirechat/server#673]
我们购买了专业版 现在也在投入使用了
现在发现一个痛点，就是刷屏，许多用户会在社交群聊中刷屏 造成其他用户不好的体验，你们这边可以新增这个功能吗？
比如一个用户X秒内只能发XX条消息 超过这个限制 就暂时会发送失败并返回对应失败状态码 并且 回调给服务器，服务器可以针对他们临时禁言 之类的处理。

**Comment by heavyrain2012** [comment]
IM服务大部分逻辑中是没有区分具体业务的，所以在IM服务加这个逻辑是比较难的。针对你的这个需求，可以在客户端加上，当调用发送时记录一下发送频率，如果频率太多提示用户
