### ISSUE TITLE
连接状态频繁的切换同步中

### ISSUE THREAD

**Issue by doralines** [wildfirechat/server#676]
之前反馈过好像是因为超级群组的问题，现在我们就两个超级群组，几百个人的，用户反馈，会频繁的处于同步中、连接成功的状态，效果极其不好，这块你们能优化一下吗？

**Comment by doralines** [comment]
也不知道是不是超级群组的原因，感觉你们超级群组用不得啊，我们就几个超级群组 1000多人的，3台集群都有些扛不住...很多时候消息都是一堆一堆的来，就像是1秒刷新1次一样，服务器的cpu也是很多时候突然从10一下涨到60几，类似于 调用serverApi 退出群组，服务端返回timeout，但是前端仍然推送了退出群组，这样用户反复操作，会显示多次退出群组。

**Comment by doralines** [comment]
现在我们大概是3台8C16G的服务器 部署了集群，CPU使用率都不高，但是出入的流量会很大，并且3个4个超级群组，很多时候消息都是一堆一堆的来，就像是1秒刷新1次一样，并且高峰期还会有 调用serverApi 退出群组，服务端返回timeout，但是前端仍然推送了退出群组，这样用户反复操作，会显示多次退出群组。我们三台服务器中都只是部署了一个im服务器，没有其他东西。
JVM内存参数 设置如下
JAVA_OPTS="$JAVA_OPTS -Xmx6G"
JAVA_OPTS="$JAVA_OPTS -Xms2G"

能否帮我分析并优化一下当前部署？
![image](https://github.com/wildfirechat/im-server/assets/150234314/996861d8-b688-4e61-9251-9d5a652ea031)

**Comment by heavyrain2012** [comment]
这个网络流量有没有分内外网，可以看一下内网流量是多少，外网流量是多少？内网流量有数据写入到数据库的流量，还有节点之间共享数据的流量，还有服务之间RPC的流量，内网流量大是正常的，主要看外网流量有多大。

另外你们消息的分发量有多大，比如群有多大，每秒钟群内多少条消息，如果看到是一堆一堆的来消息，可能会是很大的量，确认一下消息分发的情况。

还有可以把IM服务高峰期间的日志发一份给 support@wildfirechat.cn 我们分析一下有没有接口使用错误

还有监控可以给我们更多一些，比如磁盘的，还有数据库的，看看系统的瓶颈在哪里

**Comment by doralines** [comment]
我们现在就4个还是5个超级群里面有1400多的用户量，每秒大概就几条消息吧。三台服务器感觉绰绰有余了。可是还是就消息一堆一堆的 不流畅的感觉。

**Comment by doralines** [comment]
主要看12.8号的记录  可以看到很多超频 error Execute too long
[wildfirechat.zip](https://github.com/wildfirechat/im-server/files/13610861/wildfirechat.zip)

**Comment by heavyrain2012** [comment]
能加微信了解一下情况吗，微信号： wildfirechat
