### ISSUE TITLE
 IM server偶尔会导致服务器持续高负载

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/server#677]
IM server偶尔会导致服务器持续高负载，
一般是几个小时，之后负载会降下来，
之后间隔一段时间会断开连接，
重启之后又恢复正常

**Comment by heavyrain2012** [comment]
这个无法判断是什么原因，有可能是较大的业务压力导致任务排队处理，可以考虑升级配置观察一下，或者切换到专业版IM服务

**Comment by heavyrain2012** [comment]
https://mp.weixin.qq.com/s/k_BpDtMw1-LVO_q1khApAA 可能是这个原因
