### ISSUE TITLE
用户收到的消息，获取时丢失@信息

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/server#678]
获取消息列表的消息时，文字消息的mentionedType 与 mentionedTargets 获取不到

**Comment by zeroskylian** [comment]
使用场景是通过获取被@的人员id， 获取人员信息，将其在文字中高亮出来

**Comment by heavyrain2012** [comment]
收到的消息关于@的信息都是空的，只有消息的状态变成一种特殊的未读状态（@和@all），这个就是这样设计的。如果你想加上这些信息，可以把人员信息放到extra字段中
