### ISSUE TITLE
建议添加自动删除会话消息的功能

### ISSUE THREAD

**Issue by qiuDar** [wildfirechat/server#679]
![cbbc36d4bc64c77b18038dbe3303849](https://github.com/wildfirechat/im-server/assets/10934817/89fbf29f-5822-4671-a20a-9db30f77949b)
类似tg上的，用户可以对每个会话设置一个自动删除消息的功能

**Comment by heavyrain2012** [comment]
请更新最新的客户端，发送消息时，有个参数expireDuration，单位是秒。删除时间并不是精确的，客户端协议栈在应用每次启动的时候会清理一遍过期的消息，所以体验上会有超过指定时间的可能.
