### ISSUE TITLE
离线消息的功能配置

### ISSUE THREAD

**Issue by doralines** [wildfirechat/server#681]
专业版配置中有一个离线消息数量的配置
但是在实际使用中发现，如果长时间不登录使用，一旦群消息过多，单聊消息就会被挤掉，需要去查看历史消息才能看到。
这样用户很容易错过重要的消息
所以我想问问 是否可以根据 单聊和群聊单独设置存储离线消息的数量？这样的话才一些场景下就会方便很多了。

**Comment by doralines** [comment]
这个功能有在评估吗，对我们还是比较重要的。

**Comment by heavyrain2012** [comment]
这个问题是我们设计的问题，所有的消息都在同一个时间线上，没有按照类型来区分，所以只能指定拉取更多的消息数量来减少这个问题的影响。

**Comment by doralines** [comment]
> 这个问题是我们设计的问题，所有的消息都在同一个时间线上，没有按照类型来区分，所以只能指定拉取更多的消息数量来减少这个问题的影响。

那这个还有其办法解决吗？就算之前用户的离线消息丢失了也没关系，保证后续是可以按照上述实现就可以，或者是定制化一下只保留单聊离线消息和一些群组的变更通知消息

**Comment by doralines** [comment]
或者是 现在我先这样处理，你们看可以吗
就是在用户获取token并连接成功后，先不跳转页面，我先遍历所有的单聊会话，然后每个拉取一下历史消息，这个时候这些历史消息是默认已读的还是会显示对应的未读数量？

**Comment by heavyrain2012** [comment]
也是可以的
