### ISSUE TITLE
建议在转发创建群判断传入的uid是否是好友

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/server#682]
### 步骤
转发消息
![image](https://github.com/wildfirechat/im-server/assets/11338629/1371f9ed-a5ba-4cac-a8a8-49e5c0e5774f)
创建群
![image](https://github.com/wildfirechat/im-server/assets/11338629/3eb9682c-ef81-4851-85f0-ec9cc956ee2c)
选人
![image](https://github.com/wildfirechat/im-server/assets/11338629/1e0dde0d-6fde-428f-bdb8-74a19371b771)
此时如果前端造uid数据，可以拉大群发消息，存在安全隐患

### 预期结果
因为拉人进群是要加好友的，所以这里应该增加对于创建群拉入的uid是否是好友的后端判断，避免前端造数据攻击

**Comment by heavyrain2012** [comment]
我们加了个配置文件，是否允许陌生人拉人入群，可以关掉，这样就只能建群或者加入只加好友，请邮件联系我们更新IM服务
