### ISSUE TITLE
minio文件下载

### ISSUE THREAD

**Issue by AllMyPrecious** [wildfirechat/server#685]
在使用wf-minio的时候，bucket设置为R/W后，外部通过URL可以直接下载图片，会不太安全，请问怎么可以规避这个问题。

**Comment by heavyrain2012** [comment]
请参考 https://docs.wildfirechat.cn/blogs/文件存储的安全性问题.html

**Comment by AllMyPrecious** [comment]
谢谢，我建议可以wf-minio的readme上附上这个链接。
![image](https://github.com/wildfirechat/im-server/assets/44085110/2e9785ca-ee41-4419-ad68-a6d56a985273)
