### ISSUE TITLE
群内单独禁言某成员，该成员无法添加新成员进群，提示网络错误

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/server#688]
#### 操作说明

操作：
群聊加群方式为“不限制加入”，我作为群成员被禁言。
我点击右上角群图标——进入会话详情；
点击群成员列表“+”——选择任意好友——点击右上角“完成”

现象：提示“网路错误”，添加失败，100%

预期：
成员被禁言后，仍然可以成功添加新成员进群

####对比
当设置全员禁言时，成员可以添加新成员进群

**Comment by heavyrain2012** [comment]
成员禁言后，不应该能够添加新成员。因为如果要是允许的话，那么新添加的用户是没有被禁言的，是可以发言的，这样就可以绕过禁言，用新加进来的小号说话

**Comment by heavyrain2012** [comment]
错误不应该提示网络错误，返回的错误码应该是没有权限(248)，这时候修改一下提示改成没有权限就好了

**Comment by FelicityCiao** [comment]
> 错误不应该提示网络错误，返回的错误码应该是没有权限(248)，这时候修改一下提示改成没有权限就好了

👌，修改错误提示

**Comment by FelicityCiao** [comment]
> 成员禁言后，不应该能够添加新成员。因为如果要是允许的话，那么新添加的用户是没有被禁言的，是可以发言的，这样就可以绕过禁言，用新加进来的小号说话

讨论了一下，认为禁言和添加新成员两个功能应该解耦比较好，如果需要对被禁言者限制其他功能做风控，我们可以打开开关即可。
