### ISSUE TITLE
web试用如何登录

### ISSUE THREAD

**Issue by githubyong** [wildfirechat/server#689]
## web试用
参考文档部署好了im-server(192.168.1.8)，app-server (192.168.1.8)，在 运行了web客户端项目(192.168.1.4) 使用手机端扫码登录提示 网络错误

#### 操作说明
客户端打开http://192.168.1.4:8013/#/ 能显示二维码图片，使用手机端的野火IM扫码，点击登录电脑 提示网络错误

#### 表现现象
网络错误

#### 预期结果
电脑端可正常登录

**Comment by imndx** [comment]
web SDK 是需要付费的，详见[收费项目](https://docs.wildfirechat.cn/price/)，直接运行起来的话，是无法连接到自行部署的 IM-Server 的，如果尚未申请试用的话，请看[试用说明](https://docs.wildfirechat.cn/trial/)

如果已经申请试用，并部署了专业版 im-server，并替换了 web sdk 的话，可以选择验证码登录，默认验证码是 66666（五个 6）
