### ISSUE TITLE
SDK缺少邮箱查询的方法

### ISSUE THREAD

**Issue by hellomcp** [wildfirechat/server#692]
SDK 1.2.2 版本，没有根据邮箱查询用户信息的方法。

当我们开发邮箱注册的时候，无法根据邮箱查询用户信息

**Comment by heavyrain2012** [comment]
已经添加，提交分支：https://github.com/wildfirechat/im-server/commit/c4421fc9edb6575e52125ef4d977ce3d1a8dfaae ，如果是专业版请邮件联系我们更新
