### ISSUE TITLE
若群主账号注销，群内顺位群主并不是群管理员

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/server#693]
## 提issue小提示
暂时在iOS端可以找到账号注销入口，Android未找到，用iOS操作举例

#### 操作说明
iOS账号A新建群会话，群内有联系人B和C，群管理-管理员-添加B为管理员
A进入设置-退出-注销账号

#### 表现现象
群内C变成了群主，可以选择解散群，B没有顺位成为群主

#### 预期结果
B应该比C有群主顺位优先级，B成为新的群主更合理。

**Comment by heavyrain2012** [comment]
我们稍后处理一下

**Comment by heavyrain2012** [comment]
已经添加，请更新验证

**Comment by FelicityCiao** [comment]
> 已经添加，请更新验证
请问具体更新在哪？

**Comment by heavyrain2012** [comment]
在IM服务做的修改。如果是社区版，请下载最新代码编译后更新验证；如果是专业版IM服务请联系我们更新
