### ISSUE TITLE
关于敏感词过滤处理问题

### ISSUE THREAD

**Issue by Kennyfengff** [wildfirechat/server#694]
已经设置了 sensitive.filter.type 1  但是似乎未生效, t_sensitive_messages表一直是空的,没有任何敏感词数据记录进来,这个有什么排查方向吗?

**Comment by imndx** [comment]
`t_sensitiveword`表里面，有配置上敏感词了吗？

**Comment by Kennyfengff** [comment]
t_sensitiveword表里面已经配置了敏感词

**Comment by heavyrain2012** [comment]
服务器是什么版本，可以用api/version看一下

**Comment by heavyrain2012** [comment]
> t_sensitiveword表里面已经配置了敏感词

这个配置是怎么测试的，是通过API吗，还是直接修改的数据库，如果修改的数据库需要重启一下IM服务

**Comment by Kennyfengff** [comment]
我们用的是免费版的, 很久之前的版本了, 是通过api调用的 ,  有没有排查的思路?? 加日志啥的都行

**Comment by heavyrain2012** [comment]
可以临时部署一个最新版本，用最新版本测试一下看看是不是有效的，如果最新版本是有效的，可以考虑升级到最新版本
