### ISSUE TITLE
无法配置七牛

### ISSUE THREAD

**Issue by laopaoer-wallet** [wildfirechat/server#698]
配置好七牛之后，就提示
![image](https://github.com/wildfirechat/im-server/assets/75466368/8f00bec6-3465-4aea-8b7d-83d3e48e1c7e)

wildfirechat.conf

![image](https://github.com/wildfirechat/im-server/assets/75466368/83628f48-9091-4a1e-90f2-41920d6bb472)

**Comment by laopaoer-wallet** [comment]
配置错误了，处理好了！

**Comment by heavyrain2012** [comment]
好的
