### ISSUE TITLE
第一次会话不提醒

### ISSUE THREAD

**Issue by zq-miracle** [wildfirechat/server#70]
添加好友 同意之后  对方的消息没有出现在会话栏  在联系人点开好友之后才显示会话
（我用的安卓 这个问题不确定是移动端问题还是服务端问题）

**Comment by heavyrain2012** [comment]
@imndx 你试试android有没有问题，我在iOS上没有发现问题

**Comment by tagMatrix4** [comment]
安卓的情况是这样的。
A.	[安卓]新注册用户无法收到服务器发送来的信息
首次发现时间：2019-07-29
问题回现：
im-server-ver-0.25,   // 登录、注册、转发消息服务器版本
app-server-ver-0.25,  // app 长连接版本
mysql/memory,   // 使用数据库 或者 使用内存
remote/local machine， // 远程机器 或者 本地机器

异常场景：
	登录后进入到第一个界面时，正常应该显示信息，但是进入之后可能还处于正在连接服务器的状态。

1、	仅在账号首次登录时出现，同时im服务器会提示发送成功。如果退出登录则正常
2、	但是退出后再次登录，服务器会抛出http异常，代号404
3、

**Comment by imndx** [comment]
无法复现
