### ISSUE TITLE
创建频道接口，callback参数问题。

### ISSUE THREAD

**Issue by zhangyongquanpt** [wildfirechat/server#701]
经过测试，创建频道的callback配上回调地址后，
如果auto=1，回调地址会被追加message后缀，跟callback参数不一致。改成message后缀后能收到消息，但是owner收不到消息
如果auth=0,owner能收到消息，但是回调地址就失效了，没有被调用

如何配置才能让owner和回调地址同时收到用户发送的消息。

**Comment by heavyrain2012** [comment]
最近一个提交添加了一个配置项，可以实现你的要求，请更新验证

**Comment by heavyrain2012** [comment]
如果需要同时收到消息，auto需要为0

**Comment by zhangyongquanpt** [comment]
> 最近一个提交添加了一个配置项，可以实现你的要求，请更新验证

@heavyrain2012 文档在哪儿看，没找到文档

**Comment by heavyrain2012** [comment]
文档没有这么细节，你把IM服务更新到最新，然后auto改成0就可以了
