### ISSUE TITLE
能否提供获取群聊大小的方法，方便备份时选择

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/server#706]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明

能否提供获取群聊大小的方法，方便备份时选择

#### 表现现象

我们现在备份消息，但是用户不知道备份大小，我们目前是把消息写入本地文件，然后拿这个文件大小给到用户，但是用户选择会话备份时，不能知道每个会话会产生的聊天记录大小（可以不包括文件、图片、视频等大小）；希望能研究一下，提供获取每个会话信息预计的大小，

#### 预期结果
能获取每个会话信息预计的大小

**Comment by heavyrain2012** [comment]
你们都有哪些客户端？我们可以优先加上这些客户端的接口供你们使用

**Comment by guodonghuang** [comment]
iOS，Android，Windows和Mac（electron）

**Comment by heavyrain2012** [comment]
消息备份分成2部分，一部分是消息本身，另外一部分是媒体类消息下载的或者发送的资源。在今天刚提交的代码中，有按照会话类型和line获取消息总数的接口，可以得到要备份消息的数量。 资源部分需要看你们对象存储会不会定时清理，如果不清理，可以不备份相关资源，如果会清理，需要像微信一备份，每个平台的位置都不一样，可以发送消息然后把消息读出来，看看路径在哪里

可以先看看android和ios是否满足需求，如果满足需求再邮件联系我们要新版本的pc sdk。

**Comment by guodonghuang** [comment]
需求是：获取每个会话中消息的存储大小，不是消息数量，大小用来展示给用户，可以知道上传时的流量状况

**Comment by heavyrain2012** [comment]
消息存储在协议栈中的sqlite中，每条消息一行，没有办法知道消息的大小，只能知道条数。

**Comment by guodonghuang** [comment]
好的，了解；
