### ISSUE TITLE
升级完Release version 1.2.6，服务端远程删除消息，会给部分用户推送一条“消息已删除”的本地不存储类型的消息

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/server#707]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明

升级完Release version 1.2.6，服务端远程删除消息，会给部分用户推送一条“消息已删除”的本地不存储类型的消息

#### 表现现象
服务端远程删除消息，会给部分用户推送一条“消息已删除”的本地不存储类型的消息

#### 预期结果
删除消息不推送提示

#### 补充条件
升级Release version 1.2.6  之前  是没有删除通知的

**Comment by heavyrain2012** [comment]
需要有这个消息，因为客户端那边可能已经收到了被删除之前的消息，需要收到这个不存储的消息来代替本地已经收到的消息

**Comment by guodonghuang** [comment]
是不是这个消息发送时配置了OfflinePushInfo，导致通知栏收到了该离线通知，实际上通知栏是不需要通知的，所以，希望服务端发送这个消息时候不要配置离线通知

**Comment by heavyrain2012** [comment]
比如用户A先给你发了一条hello消息，你不在线，推送就会显示在你的手机上，然后再调用接口删除这个消息，如果不重新推送一条消息覆盖之前的hello的推送，那么虽然消息删除了，但你还是能看到推送的内容。

如果你不想推送，可以在推送服务把推送删除的请求忽略掉，或者做其他更好的处理

**Comment by guodonghuang** [comment]
好的多谢
