### ISSUE TITLE
minio对象存储要使用域名+SSL访问，IM配置等相关咨询

### ISSUE THREAD

**Issue by shuiji2018** [wildfirechat/server#708]
如果minio对象存储要使用域名+SSL访问，IM配置这里server_port和server_ssl_port都需要是么，而且不能一样，证书在哪配呢，配在nginx么，下面domain中的http可以写https么

**Comment by heavyrain2012** [comment]
在 https://github.com/wildfirechat/WF-minio 项目说明中的“ 配置https” 部分有说明，需要部署nginx来做代理，需要同时支持http和https，然后im服务配置文件中，server_port填写http的端口，server_ssl_port填https的端口。domain中用https

**Comment by shuiji2018** [comment]
好的，谢谢
