### ISSUE TITLE
获取授权URL接口getAuthorizedMediaUrl，传进去是9443端口的，为啥返回的是9000的，IM中的http配置的是9000，https配置的是9443，domain中配置的是9443

### ISSUE THREAD

**Issue by shuiji2018** [wildfirechat/server#709]
获取授权URL接口getAuthorizedMediaUrl，传进去是9443端口的，为啥返回的是9000的，IM中的http配置的是9000，https配置的是9443，domain中配置的是9443

**Comment by heavyrain2012** [comment]
问题查出来了，原来默认端口为80/443，因此签名时就没有考虑端口。我们最新版本已经解决，可以联系我们更新验证，也可以把minio的端口配置为80/443
