### ISSUE TITLE
群消息判断是否已读，新加入成员对历史消息已读但没有返回数据。

### ISSUE THREAD

**Issue by captain-miao** [wildfirechat/server#710]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1. 新建一个群，设置可以查看历史消息。
2. 发送消息：消息1
3. 新加入成员：用户A
4. 用户A拉取了历史消息
5. 已读数据里面，没有「用户A」的阅读消息时间

#### 表现现象
客户端的现象：
群的历史消息被新入群的用户已读了(目前发新消息的情况下)，但未读标记没有更新为已读。
``` java 
    /**
     * 获取会话的已读情况
     *
     * @param conversation 会话，目前支持单聊和群聊
     * @return key-value, 分别表示userId和该用户已经读到了那个时间节点，可用该值和消息的server进行比较，比消息的serverTime大时，表示消息已读
     */
    public Map<String, Long> getConversationRead(Conversation conversation) {
        if (!checkRemoteService()) {
            return null;
        }

        try {
            return mClient.getConversationRead(conversation.type.getValue(), conversation.target, conversation.line);
        } catch (RemoteException e) {
            e.printStackTrace();
            return null;
        }
    }
```

#### 预期结果
接口应该返回新加入用户已读数据。

Map<String, Long> convReadEntities = ChatManager.Instance().getConversationRead(conversation);
//  用户读取消息时间

群消息设置为，可以查看历史消息。

//这个对于新加入群的成员，对于历史消息没有返回新用户数据。

#### 补充条件
必现的。

#### demo对比结果
一致。

**Comment by heavyrain2012** [comment]
这个问题跟阅读状态的实现机制有关，没有办法处理群成员加入之前的消息。可以在Ui显示时处理，把加入之前所有的消息都为已读，或者屏蔽掉加入之前的用户

**Comment by captain-miao** [comment]
了解了🫡
