### ISSUE TITLE
群消息置顶

### ISSUE THREAD

**Issue by Qiuser** [wildfirechat/server#711]
能否新增一个群聊消息置顶的功能，只有群主或者管理员可以置顶消息，类似tg的Pinned message，可以置顶多条消息
![image](https://github.com/user-attachments/assets/c99993c1-92ff-46ea-b187-58d10977c5ba)

**Comment by heavyrain2012** [comment]
这个功能你们在业务服务二开就好了，可以参考群公告，置顶的数据存储在业务服务，当进入群时拉取一下，自定义一个通知消息，收到消息也拉取一下
