### ISSUE TITLE
如何在更新消息时不产生消息通知

### ISSUE THREAD

**Issue by Qiuser** [wildfirechat/server#712]
http://domain/robot/message/update
http://domain:18080/admin/message/update
这两个接口在更新消息时，都会产生消息通知，如何在更新消息时不发送消息通知。
这两个接口都提供了一个distribute参数，但是试了没什么用，不管是1还是0都会有消息推送。

**Comment by heavyrain2012** [comment]
distribute参数的意思是要不要重新分法给用户。当为false时，更新接口只更新了消息内容，如果消息已经同步到了客户端则没有影响，如果还没有同步下来，则会同步到更新后的消息。当为true时，会通知客户端再次更新。

最新版本的IM服务发送推送内容PushMessage给推送服务，多了一个参数：republish，当消息为撤回/删除/更新时，这个值为true，可以在推送服务判断是普通消息且republish为true就不推了
