### ISSUE TITLE
扫码加群能否带上邀请人信息

### ISSUE THREAD

**Issue by Qiuser** [wildfirechat/server#714]
场景：用户A分享了群二维码给用户B，用户B扫码进入该群，并提示“用户A邀请用户B加入群聊”
![image](https://github.com/user-attachments/assets/1dfb5d8b-cbc9-4103-8f95-625a629963de)

如上，一般情况下，通过群邀请的方式是能正常显示谁邀请了谁加入群聊，但如果用户是通过扫群二维码加入群聊的话，只会显示“XXX加入了群聊”。有没有什么办法能在二维码里带上邀请人的信息，比如userId，用户扫码加入群聊的时候会将这个邀请人的id带上去，这样就能知道这个用户到底是通过谁的二维码进群的。

**Comment by heavyrain2012** [comment]
https://docs.wildfirechat.cn/faq/practicality.html 问题11
