### ISSUE TITLE
已读消息不再从服务器拉取

### ISSUE THREAD

**Issue by Qiuser** [wildfirechat/server#715]
im配置里有个选项 message.receipt 已读回执的，这个功能实现方式是什么？是在数据库中标记已读吗？如果是这样的话，能否增加一个配置，拉取历史消息的时候过滤掉已读消息。

**Comment by heavyrain2012** [comment]
这个开关是已读回执的，只有专业版IM服务才有。当打开这个功能后，一个用户发送的消息就能看到被阅读情况，只有在单聊和群聊会话中有效，聊天室和频道不支持此功能。

你说的拉取历史消息是什么意思？我的理解有2种可能，一种是当更换手机时，首次登录，会同步一定量的历史消息，这个功能叫消息漫游。另外一种是当一个会话内消息已经加载完了，就有可能从远端服务器上拉取，这个叫拉取远程历史消息。请问你说的是那种？还有你们遇到了什么问题，需要这样实现？

**Comment by Qiuser** [comment]
> 这个开关是已读回执的，只有专业版IM服务才有。当打开这个功能后，一个用户发送的消息就能看到被阅读情况，只有在单聊和群聊会话中有效，聊天室和频道不支持此功能。
> 
> 你说的拉取历史消息是什么意思？我的理解有2种可能，一种是当更换手机时，首次登录，会同步一定量的历史消息，这个功能叫消息漫游。另外一种是当一个会话内消息已经加载完了，就有可能从远端服务器上拉取，这个叫拉取远程历史消息。请问你说的是那种？还有你们遇到了什么问题，需要这样实现？

是的，目前是专业版。我说的拉取历史消息其实包含你说的两种，包括首次登录同步，以及拉取远程历史消息。我们遇到的问题是，用户更换设备后首次登录同步以及拉取远端历史消息时，发现拉取到他之前已经读过的消息，对远端存储用户聊天消息感到担忧，但是因为某些原因，我们不能使用阅后即焚功能，所以希望增加个配置，客户端同步以及拉取远端消息时，已读过的消息不再拉取。

**Comment by heavyrain2012** [comment]
没有办法添加这个功能。针对客户的担忧，有个办法是关掉消息漫游和远程消息，这样是不是就能达到和微信差不多的效果，是不是能够解决用户的担忧

**Comment by Qiuser** [comment]
> 没有办法添加这个功能。针对客户的担忧，有个办法是关掉消息漫游和远程消息，这样是不是就能达到和微信差不多的效果，是不是能够解决用户的担忧

如果关掉的话，未读消息会如何处理？比如用户A一个月没上线，在这期间别人给他发的消息会不会丢失？

**Comment by heavyrain2012** [comment]
如果换设备，未接受的消息就丢了；如果不是换设备，那就没有问题
