### ISSUE TITLE
已经在APP的设置里关闭了所有添加我的方式，手机号和帐号都不允许添加了，但仍有人加我

### ISSUE THREAD

**Issue by zbm2024** [wildfirechat/server#717]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

#### 检索已有问题
除了可以检索已有issue外，还可以去野火论坛查找已有问题，论坛地址为 https://bbs.wildfirechat.cn

#### star 我们
给我们点个star，可以及时接收到我们回复信息，另外也是对我们支持人员辛苦工作的认可，激励我们更好更快地为大家服务。

**Comment by zbm2024** [comment]
我自己测试，群里已经关了允许发起临时会话，我也关闭了现有的加我方式，用别人的号确认添加不了我，但是仍然每天有好多人添加我

**Comment by heavyrain2012** [comment]
设置里的是“找到我的方式”，可以不让用户通过手机号码和昵称来搜索到用户，不影响添加好友的操作。针对您的情况，有2种可能，一种是有人分享了您的名片，或者在群里点你的头像，选择添加好友。另外一种情况，可能有能力修改客户端，找到你的ID，用程序调用接口添加好友。

为了解决这个问题，最新IM服务有个配置，是允许一个用户一天最多添加的配置，可以限制每天添加的用户。另外修改用户ID生成的规则，比如用UUID，避免被黑客穷举用户ID，再有就是监控数据库里添加好友数据，有异常用户就封禁掉

**Comment by zbm2024** [comment]
官方能否出个版本控制，我们可以设置各端低于此版本不能使用，这样我们也好控制，不然就算这样做了，还是有可能被攻击。我们现在想更新版本，但是攻击者不升级，我们还是没办法

**Comment by zbm2024** [comment]
另外 ID生成规则在哪里？

**Comment by heavyrain2012** [comment]
> 另外 ID生成规则在哪里？

你看一下IM服务配置文件中，有没有下面这个配置，如果有打开，如果没有请更新最新版本
```
id.use_uuid true
```

**Comment by heavyrain2012** [comment]
> 官方能否出个版本控制，我们可以设置各端低于此版本不能使用，这样我们也好控制，不然就算这样做了，还是有可能被攻击。我们现在想更新版本，但是攻击者不升级，我们还是没办法

我们没有办法控制，因为客户端协议栈的版本号是commitId，是个UUID的字符串，是无序的没有办法控制。

建议你们可以写一个程序，定期扫描数据，检查有疑问的用户，检查他们聊天内容进行封号，另外增加用户举报功能，举报多了也封号

你们也可以在应用层实现版本号，在一些会调用应用服务的地方，比如获取登录/群公告等接口，加上版本号，如果没有版本号，或者较旧版本号，就发送提醒消息进行升级，也可以统计未升级的用户数

**Comment by heavyrain2012** [comment]
> 官方能否出个版本控制，我们可以设置各端低于此版本不能使用，这样我们也好控制，不然就算这样做了，还是有可能被攻击。我们现在想更新版本，但是攻击者不升级，我们还是没办法

我们没有办法控制，因为客户端协议栈的版本号是commitId，是个UUID的字符串，是无序的没有办法控制。

建议你们可以写一个程序，定期扫描数据，检查有疑问的用户，检查他们聊天内容进行封号，另外增加用户举报功能，举报多了也封号

你们也可以在应用层实现版本号，在一些会调用应用服务的地方，比如获取群公告的接口，加上版本号，如果没有版本号，或者较旧版本号，就发送提醒消息进行升级，也可以统计未升级的用户数
