### ISSUE TITLE
希望能在保存聊天图片和视频时拼上用户信息

### ISSUE THREAD

**Issue by zbm2024** [wildfirechat/server#718]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
用户发送的图片和视频文件，应拼上用户信息，这样发违规图片时可以定位，知道是哪个用户发送的，也好做处理，现在能做的只能手动删除违规内容，啥也干不了

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
拼上用户的手机号或者ID都可以

#### 补充条件
必现

#### demo对比结果
请用demo对比测试，demo上是什么状态。

#### 检索已有问题
除了可以检索已有issue外，还可以去野火论坛查找已有问题，论坛地址为 https://bbs.wildfirechat.cn

#### star 我们
给我们点个star，可以及时接收到我们回复信息，另外也是对我们支持人员辛苦工作的认可，激励我们更好更快地为大家服务。

**Comment by heavyrain2012** [comment]
你们用的是社区版还是专业版？你们用的是那个对象存储？

**Comment by zbm2024** [comment]
专业版，阿里OSS
&nbsp;


海草集万事通
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月9日(星期三) 晚上6:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/im-server] 希望能在保存聊天图片和视频时拼上用户信息 (Issue #718)














 
你们用的是社区版还是专业版？你们用的是那个对象存储？

**Comment by heavyrain2012** [comment]
你看一下发送图片和视频的链接，文件名上应该有上传者的ID和时间
