### ISSUE TITLE
转发音视频通话消息会唤起音视频通话

### ISSUE THREAD

**Issue by Qiuser** [wildfirechat/server#719]
#### 操作说明
设备A转发一条音视频通话的消息给设备B，设备B会弹出音视频通话页面，设备A没有通话页面。同理，多选消息里如果有包含音视频通话消息，并且是逐条转发，也会出现上述问题，已在demo复现。

#### 预期结果
转发音视频通话消息应该跟微信一样，只是转发文本消息“[网络电话]，而不要唤起音视频通话页面”

**Comment by heavyrain2012** [comment]
音视频通话消息是个特殊的消息，除了显示字面的意思外，还担任音视频通话开始信令的功能。所以当转发时，需要去掉信令的能力，变成普通消息。

我们准备把所有端的转发消息代码处理一下，把转发的通话消息转为文本消息，这样做就去掉了信令能力。但文本和通话消息的显示是有些区别的，如果你们对这个区别比较在意，可以再自定义一个消息，让这个自定义消息显示跟通话消息一样。

iOS平台代码已经提交 https://github.com/wildfirechat/ios-chat/commit/b07904de073fea345d2cfea1656b1baf386ed574 其他平台我们稍后添加，你们也可以参考这个来实现

**Comment by imndx** [comment]
Android 端，参考这个提交：https://github.com/wildfirechat/android-chat/commit/3e20bf3dbbd69f316a1b6b3a62f4d4af9bbf5feb
