### ISSUE TITLE
消息转发后生成的链接无法显示原始文件名

### ISSUE THREAD

**Issue by neversuspend** [wildfirechat/server#720]
#### 表现现象
专业版 IM进行消息转发

转发的文件名是onelogin_log.txt

生成的remoteMediaUrl是

https://im.oss-cn-shanghai.aliyuncs.com/bnlncW13czJr-4-1731480863-XoMNk8ywUwuz.txt

将链接转发到第三方平台，用户不知道是什么文件，第三方平台无法设置文件名的

#### 预期结果
希望remoteMediaUrl 以真实文件名结尾
remoteMediaUrl 是 https://im.oss-cn-shanghai.aliyuncs.com/。。。。/onelogin_log.txt

因为有的地方转发是无法设置文件名的

如果文件名存在非法字符，可以过滤掉非法字符。

谢谢！

**Comment by heavyrain2012** [comment]
这个问题我们仔细地分析了一下，如果修改文件名的生成方式，需要改动协议栈和IM服务，而且为了兼容多个平台及多个对象存储服务，难度太大也容易出问题，因此不能直接去改。

有个办法是可以实现这个需求的，需要做一些二开的工作，在分享之前拿到链接，先调用业务服务，业务服务调用阿里云的SDK，把这个资源复制一份，得到新链接，再分享这个新链接
