### ISSUE TITLE
社区im-server，配置七牛云存储后发送图片语音报错

### ISSUE THREAD

**Issue by ligaoman0306** [wildfirechat/server#721]
按照 https://docs.wildfirechat.cn/server/oss.html 配置的七牛云存储，配置多次比对没有问题，
在发送图片或语音是失败，
im-server 报错：
2024-11-13 17:35:15,187 ERROR [pool-3-thread-1] im.Utility (Utility.java:64) - Exception: null
2024-11-13 17:35:15,188 ERROR [pool-3-thread-1] im.Utility (Utility.java:65) - 
cn.wildfirechat.proto.WFCMessage$GetUploadTokenResult$Builder.setDomain(WFCMessage.java:23459)
io.moquette.imhandler.GetMediaUploadTokenHandler.action(GetMediaUploadTokenHandler.java:82)
io.moquette.imhandler.GetMediaUploadTokenHandler.action(GetMediaUploadTokenHandler.java:23)
io.moquette.imhandler.IMHandler.lambda$doHandler$0(IMHandler.java:204)
cn.wildfirechat.server.ThreadPoolExecutorWrapper.lambda$execute$0(ThreadPoolExecutorWrapper.java:37)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

**Comment by imndx** [comment]
请确认`qiniu.bucket_xxx`，是否正确配置？

**Comment by ligaoman0306** [comment]
多谢，我修改，可用
