### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by JiaRG** [wildfirechat/server#73]
https://github.com/wildfirechat/server/blob/59356e5b5227cbe210966fde9becd107071c771f/broker/src/main/java/com/xiaoleilu/loServer/action/Action.java#L87
String构造器添加编码
`String content = new String(bytes, StandardCharsets.UTF_8)`

**Comment by heavyrain2012** [comment]
非常感谢您的提醒，代码已经提交
