### ISSUE TITLE
贵项目能不能少打点广告？要打也说明白了是广告，披上戏服很令人作呕

### ISSUE THREAD

**Issue by Zhang-Siyang** [wildfirechat/server#76]
### Expected behavior
少打广告
### Actual behavior
广告满天飞，还编上剧本了
### Steps to reproduce
打开 https://www.v2ex.com/member/imndx/topics 查看发帖列表

**Comment by heavyrain2012** [comment]
非常抱歉会打扰到您，在这里给您和其它被打扰的朋友们道个歉。感谢您的提醒，我们会约束我们的小伙伴注意言行，避免对别人造成伤害

**Comment by Zhang-Siyang** [comment]
> 非常抱歉会打扰到您，在这里给您和其它被打扰的朋友们道个歉。感谢您的提醒，我们会约束我们的小伙伴注意言行，避免对别人造成伤害

1024
