### ISSUE TITLE
请求添加一个获取所有频道接口

### ISSUE THREAD

**Issue by yuzhongrong** [wildfirechat/server#77]
业务场景：
我需要在客户端调用展现所有频道 让客户选择自己喜欢的频道 订阅 

多加个接口即可

**Comment by yuzhongrong** [comment]
不要改动太大 尽可能

**Comment by heavyrain2012** [comment]
在应用服务去处理，app调用应用服务获取频道列表（应用服务通过直接读取数据库获取到列表）。
另外我们最近对频道关注比较少，频道功能在使用过程中有没有遇到什么问题？

**Comment by AndrmanByte** [comment]
good job
