### ISSUE TITLE
使用http服务创建用户时，有概率导致密码设置失败

### ISSUE THREAD

**Issue by innershows** [wildfirechat/server#78]
### Expected behavior
   使用/admin/user/create 接口新建用户，每次能够成功设置基本信息及密码
### Actual behavior
  存在概率导致密码存储失败
### Steps to reproduce
  正常使用用户名密码注册
### Minimal yet complete reproducer code (or URL to code) or complete log file
   
![image](https://user-images.githubusercontent.com/5716938/64310414-8f8d6180-cfd2-11e9-9455-ea703acdb851.png)

### OS version (e.g. `uname -a`)
原因分析：
   io.moquette.persistence.MemoryMessageStore
```
    @Override
    public void addUserInfo(WFCMessage.User user, String password) {
        HazelcastInstance hzInstance = m_Server.getHazelcastInstance();
        IMap<String, WFCMessage.User> mUserMap = hzInstance.getMap(USERS);
        // put会分发任务给线程池执行创建用户的操作
        mUserMap.put(user.getUid(), user);
       //update会分发任务给另一个线程池执行更新密码的操作
        databaseStore.updateUserPassword(user.getUid(), password);
      // 两个线程之间存在资源争夺，导致update先执行，create后执行，从而导致更新失败
    }
```

**Comment by heavyrain2012** [comment]
创建用户改成同步执行，不再有异步问题
