### ISSUE TITLE
客户端 IOS 和 android 连接掉线问题

### ISSUE THREAD

**Issue by ccioo** [wildfirechat/server#83]
IOS 和 android  在刚开始连接IM之后，使用正常，但是等7分钟左右过会掉线，客户端无感知。
broker异常提示：
20/09/2019 18:38:05,375 [nioEventLoopGroup-3-3] INFO  ProtocolProcessor 546  - Processing connection lost event. CId=EF9EFB2E-267A-4290-8AC4-B750A550ADAE

因此需要确定是不是正常行为，是不是长链接的心跳维持交给业务方自己来维护的? 或者是使用微信mars 的姿势不对呢？

**Comment by heavyrain2012** [comment]
理论上上协议栈会自动处理心跳。你需要给我们客户端的完整日志。
