### ISSUE TITLE
An attempt by a client to checkout a Connection has timed out.

### ISSUE THREAD

**Issue by wenzhisheng** [wildfirechat/server#84]
An attempt by a client to checkout a Connection has timed out.
socket 连接netty时出现获取不到连接池，但是server客户端接口是正常获取连接池，socket连接本地却始终报错

**Comment by heavyrain2012** [comment]
请使用野火IM提供的客户端，自己开发的客户端我们无法提供技术支持

**Comment by wenzhisheng** [comment]
我们使用的是野火IM提供的全套进行二次开发，server,app_server,android,ios,pc,这些都是，因为通过官方脚步部署在linux是完全正常（可以连接消息服务的），但是本地需要调试二次开发始终连接不上socket，server和app_server这两个服务本地启动调试接口是可以的，其它接口正常通信，就socket连接总是未连接。会抛出多种错误：Communications link failure
An attempt by a client to checkout a Connection has timed out.
Connection reset
Unrecognized Windows Sockets error: 0: recv failed
The last packet sent successfully to the server was 857 milliseconds ago.

**Comment by wenzhisheng** [comment]
野火IM项目中一个注释没有，连数据库表字段也是如此，例如一个状态值代码什么也无法一看便知，这让开发者很是头痛
