### ISSUE TITLE
群管理员不能移除成员

### ISSUE THREAD

**Issue by shutingsns** [wildfirechat/server#87]

**Comment by heavyrain2012** [comment]
能补充更多信息吗，是那个端有问题，还是说有端都有问题

**Comment by shutingsns** [comment]
安卓和苹果端都不能 重启了好多次 数据清空了好多次 
用的MySQL数据库

**Comment by shutingsns** [comment]
额 刚刚点错了

**Comment by shutingsns** [comment]
服务器一直出现
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

**Comment by shutingsns** [comment]
Linux服务器

**Comment by heavyrain2012** [comment]
服务器一直出现
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

这个问题请参考 http://docs.wildfirechat.cn/faq/server.html

群管理员不能移除成员这个问题是什么状态，我这边用最新的iOS代码是可以用的，你那边下最新的代码编译以后看看，另外服务的版本是多少

**Comment by shutingsns** [comment]
服务器 是昨天下载的最新版

**Comment by shutingsns** [comment]
IOS 也是的

**Comment by heavyrain2012** [comment]
我使用demo是可以的啊，你们用我们demo试试，另外看一下客户端报的错误码，还有服务器端的日志

**Comment by shutingsns** [comment]
客户端只是显示失败，你们的demo也有失败概率，有时候需要删除两次

**Comment by heavyrain2012** [comment]
需要补充日志

**Comment by heavyrain2012** [comment]
请补充日志后再重新打开
