### ISSUE TITLE
现在又出现大批这样的情况 显示消息发送失败 但是明明已经发出去了！

### ISSUE THREAD

**Issue by shutingsns** [wildfirechat/server#91]
![image](https://user-images.githubusercontent.com/54945733/65831283-944fe780-e2ea-11e9-8836-4d3ee2ab73a5.png)

**Comment by shutingsns** [comment]
用户至今180个不到！

**Comment by shutingsns** [comment]
服务器24H的 带宽1000M 数据库4H16G 10TB内测 两台 群集的 MySQL8.0.13

**Comment by heavyrain2012** [comment]
请提供详细信息，客户端失败的错误码是多少？服务器当时的cpu和load都是多少？服务器端有没有报错，把报错日志贴给我们？

**Comment by heavyrain2012** [comment]
客户是不是国外，客户到服务器的网络是畅通的吗？

**Comment by shutingsns** [comment]
服务器没有报错，客户到服务器网络通常

**Comment by qq78878878** [comment]
> 服务器没有报错，客户到服务器网络通常

这个问题 你要把敏感词那部分判断去掉可以解决

**Comment by heavyrain2012** [comment]
看着像客户端与服务器端连接不畅，不像是敏感词的原因。
你们需要提供客户端和服务器端的日志啊，我们也是猜不出来什么原因的

**Comment by heavyrain2012** [comment]
请补充服务端和客户端日志再重新打开
