### ISSUE TITLE
关于数据库表t_user_session中的_token字段数据有几率为空

### ISSUE THREAD

**Issue by 871846173** [wildfirechat/server#95]
在做推送的过程中需要这个_token字段，在使用的过程中发现数据库表t_user_session中的_token字段数据有几率为空，这样就没办法推送到手机上，有人知道要如何解决吗，版本是最新的distribution-0.28-bundle-tar

**Comment by heavyrain2012** [comment]
token需要客户端上传，请在客户端确认是否成功获取到token（iOS在appdelegate.m文件中，Android在push那个module内）

**Comment by 871846173** [comment]
> token需要客户端上传，请在客户端确认是否成功获取到token（iOS在appdelegate.m文件中，Android在push那个module内）

那就是说客户端可以将这个devicetoken传到后台，然后根据这个devicetoken进行推送。我的问题是在有的时候这个deviceToken（数据库表t_user_session中的_token字有时候会为空），所以说感觉很难办。所以客户端需要如何写代码才能获取到呢？

**Comment by heavyrain2012** [comment]
IM服务只提供上传token并保存，然后在需要推送的时候把token传给推送服务的功能。
因此，客户端需要自己获取token，然后调用setDeviceToken方法，之后SDK上传到IM服务去。推送服务需要处理推送。（客户端获取token和推送服务都是我们提供的demo，不属于IM服务，客户需要自己调试保证其能正确运行）

这个问题，你需要确认客户端是否获取到了token，是否调用了setDeviceToken方法，如果确认客户端调用了setDeviceToken方法，但IM服务没有保存下来，请把对应时段的IM服务日志贴给我们
