### ISSUE TITLE
pc-chat在npm install中出现的问题

### ISSUE THREAD

**Issue by ZYCZ-ChenZhiChao** [wildfirechat/server#96]
依赖:
nodejs10.16.0
python2.7
Visual Studio Community 2015(C++ Runtime & Windows SDK version 8.1)
npm install -g node-gyp

在npm install时  出现
found 3 vulnerabilities (1 low, 2 high)
详细信息
 Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   video-thumbnail-generator

  Path            video-thumbnail-generator > lodash

  More info       https://npmjs.com/advisories/577

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.11

  Dependency of   video-thumbnail-generator

  Path            video-thumbnail-generator > lodash

  More info       https://npmjs.com/advisories/782

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.12

  Dependency of   video-thumbnail-generator

  Path            video-thumbnail-generator > lodash

  More info       https://npmjs.com/advisories/1065

官网建议：
Remediation
Update to version 4.17.12 or later.

问题：如何升级lodash？

**Comment by heavyrain2012** [comment]
node-gyp安装成功了吗，这个没有关系吧，就是个warning
