### ISSUE TITLE
【BUG】BrokerConstants.MESSAGE_Remote_History_Message 中的名称和config/wildfirechat.conf 中的message.remote_history_message 名字不一致，导致配置无效

### ISSUE THREAD

**Issue by Hholz** [wildfirechat/server#97]
BrokerConstants.MESSAGE_Remote_History_Message 中的名称和config/wildfirechat.conf 中的message.remote_history_message 名字不一致，导致配置无效

**Comment by Hholz** [comment]
public static final String MESSAGE_Remote_History_Message = "message.reomte_history_message"
应该是
public static final String MESSAGE_Remote_History_Message = "message.remote_history_message "

**Comment by heavyrain2012** [comment]
已经修改，多谢提醒🙏
